Repository microsoft/react-native-windows, pull requests merged in 2020-07, with the labels that each got.

#5394 Migrate 'I18nManager' to turbo module
  change/react-native-windows-2020-06-30-12-42-24-tm-im.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#5393 Migrate 'DeviceInfo' to turbo module
  change/react-native-windows-2020-06-30-12-41-13-tm-di.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#5395 Migrate 'AppState' to turbo module
  change/react-native-windows-2020-06-30-12-50-33-tm-as.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#5410 Azure Pipelines: Don't run jobs if the dependencies haven't passed
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5403 Speed up finding Google TestAdapter extension in VS folder
  .ado/variables/vs2019.yml
Labels: AutoMerge

#5290 Implement XAML version load guard
  change/react-native-windows-2020-06-21-00-49-44-xamlGuard.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/XamlLoadState.cpp
  vnext/Microsoft.ReactNative/XamlLoadState.h
Labels: Area: Developer Experience, Area: WinUI, AutoMerge

#5418 Include "nuget.exe" as Package Dependency of react-native-windows
  change/nuget-exe-2020-07-02-03-17-13-better-nuget.json
  change/react-native-windows-2020-07-02-03-17-13-better-nuget.json
  packages/nuget-exe/.gitignore
  packages/nuget-exe/just-task.js
  packages/nuget-exe/package.json
  vnext/local-cli/src/runWindows/runWindows.ts
  vnext/local-cli/src/runWindows/utils/build.ts
  vnext/package.json
Labels: AutoMerge

#5415 Fix #4810: Remove the /vnext/etc/react-native-windows.api.md file from the shipping npm package
  change/react-native-windows-2020-07-01-20-53-19-master.json
  vnext/package.json
Labels: AutoMerge

#5420 Cleanup VS Installation Related CLI Code
  change/react-native-windows-2020-07-02-07-12-55-vswhere-cleanup.json
  vnext/local-cli/src/runWindows/runWindows.ts
  vnext/local-cli/src/runWindows/utils/build.ts
  vnext/local-cli/src/runWindows/utils/deploy.ts
  vnext/local-cli/src/runWindows/utils/msbuildtools.ts
  vnext/local-cli/src/runWindows/utils/vsInstalls.ts
Labels: AutoMerge

#5402 [0.62] Only Create Github Releases for the "react-native-windows" Package (#5307)
  .ado/publish.yml
  .ado/templates/react-native-init.yml
  .ado/variables/release.yml
  change/react-native-windows-2020-06-23-01-16-44-no-master-tags.json
  package.json
  packages/scripts/promoteRelease.js
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#5400 Run Release Note Generation Script in 0.62 Branch
  .ado/publish.yml
Labels: AutoMerge, Backported to 0.62

#5429 Create a Programmatic API for react-native-platform-override
  change/@office-iss-react-native-win32-2020-07-06-10-26-04-override-api.json
  change/@rnw-scripts-create-github-releases-2020-07-06-10-26-04-override-api.json
  change/@rnw-scripts-find-repo-root-2020-07-06-10-26-04-override-api.json
  change/@rnw-scripts-format-files-2020-07-06-10-26-04-override-api.json
  change/@rnw-scripts-just-task-2020-07-06-10-26-04-override-api.json
  change/@rnw-scripts-promote-release-2020-07-06-10-26-04-override-api.json
  change/react-native-platform-override-2020-07-06-10-26-04-override-api.json
  change/react-native-windows-2020-07-06-10-26-04-override-api.json
  change/react-native-windows-codegen-2020-07-06-10-26-04-override-api.json
  change/react-native-windows-init-2020-07-06-10-26-04-override-api.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/find-repo-root/package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/just-task/just-task.js
  packages/@rnw-scripts/promote-release/package.json
  packages/E2ETest/package.json
  packages/react-native-platform-override/.vscode/launch.json
  packages/react-native-platform-override/.vscode/settings.json
  packages/react-native-platform-override/README.md
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/Api.ts
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/FileSearch.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/OverrideFactory.ts
  packages/react-native-platform-override/src/OverridePrompt.ts
  packages/react-native-platform-override/src/UpgradeStrategy.ts
  packages/react-native-platform-override/src/e2etest/Api.test.ts
  packages/react-native-platform-override/src/e2etest/OverrideFileRepositoryImpl.test.ts
  packages/react-native-platform-override/src/e2etest/Resource.ts
  packages/react-native-platform-override/src/e2etest/UpgradeStrategy.test.ts
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/.clang-format
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/README.md
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/ReactCommon/turbomodule/samples/SampleTurboCxxModule.cpp
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/ReactCommon/turbomodule/samples/SampleTurboCxxModule.h
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/ReactCommon/yoga/yoga/Yoga.cpp
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/overrides.json
  packages/react-native-platform-override/src/e2etest/collateral/sampleOverrideRepo/setUpDeveloperTools.windesktop.js
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-windows-codegen/package.json
  packages/react-native-windows-init/package.json
  vnext/ReactCopies/overrides.json
  vnext/overrides.json
  vnext/package.json
  vnext/src/overrides.json
Labels: Area: Infrastructure, Area: Release Process

#5283 Enable experimental usage of Microsoft.ReactNative.Managed as a nuget package
  .ado/publish.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/prep-and-pack-single.yml
  .ado/templates/react-native-init.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-07-02-12-40-34-master.json
  change/react-native-windows-init-2020-07-02-12-40-34-master.json
  docs/testing-nuget-packages.md
  packages/react-native-windows-init/src/Cli.ts
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.Managed/ReflectionReactPackageProvider.cs
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.SourceReferences.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
  vnext/Scripts/Microsoft.ReactNative.nuspec
  vnext/Scripts/Microsoft.ReactNative.targets
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Scripts/PublishNugetPackagesLocally.cmd
  vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
  vnext/local-cli/src/generate-windows.ts
  vnext/local-cli/src/generator-windows/index.ts
  vnext/local-cli/templates/cs/proj/MyApp.csproj
  vnext/local-cli/templates/cs/proj/MyApp.sln
  vnext/local-cli/templates/shared/proj/NuGet.Config
Labels: AutoMerge

#5433 Disable RNIntegrationTests::Logging
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5434 Normalize override manifests to unix paths
  change/@office-iss-react-native-win32-2020-07-06-17-39-31-unix-path-manifests.json
  change/react-native-platform-override-2020-07-06-17-39-31-unix-path-manifests.json
  change/react-native-windows-2020-07-06-17-39-31-unix-path-manifests.json
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/test/Override.test.ts
  packages/react-native-win32/overrides.json
  vnext/overrides.json
Labels: AutoMerge

#5435 Increase Timeout for react-native-platform-override e2etest
  change/react-native-platform-override-2020-07-06-18-11-21-more-timeout.json
  packages/react-native-platform-override/jest.e2e.config.js
  packages/react-native-platform-override/just-task.js
Labels: AutoMerge

#5431 Use `babel-plugin-inline-view-configs` to increase verification of viewmanagers
  change/react-native-windows-2020-07-06-14-00-59-inlineviewconfigs.json
  packages/playground/babel.config.js
  vnext/.gitignore
  vnext/overrides.json
  vnext/src/babel-plugin-inline-view-configs/GenerateViewConfigJs.js
  vnext/src/babel-plugin-inline-view-configs/index.js
  vnext/src/babel-plugin-inline-view-configs/package.json
Labels: AutoMerge

#5380 Add a bunch of deps we are using but not declaring
  change/@office-iss-react-native-win32-2020-06-29-10-07-11-packagedeps.json
  change/react-native-windows-2020-06-29-10-07-11-packagedeps.json
  packages/react-native-win32/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#5439 Dont try to parseJson unless redbox error starts with {
  change/react-native-windows-2020-07-07-11-46-41-lessredboxthrow.json
  vnext/Microsoft.ReactNative/RedBox.cpp
Labels: AutoMerge

#5452 Disable Override Validation for windesktop JS
  change/react-native-windows-2020-07-07-15-33-54-no-windesktop.json
  vnext/overrides.json
Labels: AutoMerge

#5457 Update Publish pipeline to report RNW Version published
  .ado/setVersionEnvVars.js
Labels: AutoMerge

#5466 run-windows cannot find built app with default init app
  change/react-native-windows-2020-07-08-13-10-31-deploy2.json
  vnext/local-cli/src/runWindows/utils/deploy.ts
Labels: AutoMerge, Request Backport to 0.62

#5469 CR feedback, project hygiene
  change/react-native-windows-2020-07-08-19-00-08-ms-rnw-staging.json
  vnext/Desktop/ABI/TestController.cpp
  vnext/Desktop/ABI/TestController.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
Labels: Area: Core DLL, AutoMerge

#5475 Pass WACK on 62
  change/react-native-windows-2020-07-09-10-31-29-wackOn62.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#5470 Add multi-window/thread support to Playground-Win32
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-Win32.rc
  packages/playground/windows/playground-win32/resource.h
Labels: Area: Islands, AutoMerge

#5486 Add ReactModuleBuilder tests
  change/react-native-windows-2020-07-09-16-24-07-ms-rnw-staging.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.ABITests/ReactModuleBuilderTests.cpp
  vnext/Desktop/ABI/TestController.cpp
  vnext/Desktop/ABI/TestController.h
  vnext/Desktop/ABI/TestController.idl
Labels: Area: Core DLL

#5487 Make IWebSocketResource methods noexcept
  change/react-native-windows-2020-07-09-01-14-31-ws-noexcept.json
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: AutoMerge

#5485 Adjust island window size for title bar/menu bar and scrollbar
  packages/playground/windows/playground-win32/Playground-Win32.cpp
Labels: Area: Developer Experience, Area: Islands, Area: Playground, AutoMerge

#5446 Automatically Pull In New Files from RNTester and IntegrationTests
  change/react-native-platform-override-2020-07-07-16-00-08-dircopy-overrides.json
  change/react-native-windows-2020-07-07-16-00-08-dircopy-overrides.json
  packages/react-native-platform-override/.eslintrc.js
  packages/react-native-platform-override/.vscode/launch.json
  packages/react-native-platform-override/README.md
  packages/react-native-platform-override/jest.debug.config.js
  packages/react-native-platform-override/src/Api.ts
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/FileRepository.ts
  packages/react-native-platform-override/src/FileSystemRepository.ts
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  packages/react-native-platform-override/src/Hash.ts
  packages/react-native-platform-override/src/Manifest.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/OverrideFactory.ts
  packages/react-native-platform-override/src/OverrideFileRepositoryImpl.ts
  packages/react-native-platform-override/src/OverridePrompt.ts
  packages/react-native-platform-override/src/Serialized.ts
  packages/react-native-platform-override/src/UpgradeStrategy.ts
  packages/react-native-platform-override/src/ValidationStrategy.ts
  packages/react-native-platform-override/src/e2etest/Api.test.ts
  packages/react-native-platform-override/src/e2etest/FileSystemRepository.test.ts
  packages/react-native-platform-override/src/e2etest/OverrideFileRepositoryImpl.test.ts
  packages/react-native-platform-override/src/e2etest/Resource.ts
  packages/react-native-platform-override/src/e2etest/UpgradeStrategy.test.ts
  packages/react-native-platform-override/src/e2etest/collateral/0.62.2/bots/.babelrc
  packages/react-native-platform-override/src/e2etest/collateral/0.62.2/bots/README.md
  packages/react-native-platform-override/src/e2etest/collateral/0.62.2/bots/code-analysis-bot.js
  packages/react-native-platform-override/src/e2etest/collateral/0.62.2/bots/dangerfile.js
  packages/react-native-platform-override/src/e2etest/collateral/0.62.2/bots/package.json
  packages/react-native-platform-override/src/e2etest/collateral/0.62.2/bots/yarn.lock
  packages/react-native-platform-override/src/scripts/generateManifest.ts
  packages/react-native-platform-override/src/test/Hash.test.ts
  packages/react-native-platform-override/src/test/Manifest.test.ts
  packages/react-native-platform-override/src/test/MockFileRepository.ts
  packages/react-native-platform-override/src/test/Override.test.ts
  packages/react-native-platform-override/src/test/OverrideFactory.test.ts
  packages/react-native-platform-override/src/test/Serialized.test.ts
  packages/react-native-platform-override/src/test/ValidationStrategy.test.ts
  vnext/overrides.json
Labels: Area: Infrastructure, Area: Release Process, AutoMerge

#5496 Try to work around Pipelines Network Flakiness Causing Test Timeouts
  change/react-native-platform-override-2020-07-09-23-08-06-less-flakey.json
  packages/react-native-platform-override/jest.e2e.config.js
  packages/react-native-platform-override/just-task.js
Labels: Area: Tests

#5458 [Desktop] Add arbitrary global flag setting functions
  change/react-native-windows-2020-07-08-00-29-11-desktop-featuregate.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop/FeatureGate.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/Shared/FeatureGate.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Platform: Desktop, Request Backport to 0.62

#5504 [0.62] run-windows cannot find built app with default init app (#5466)
  change/react-native-windows-2020-07-08-13-10-31-deploy2.json
  vnext/local-cli/runWindows/utils/deploy.js
Labels: AutoMerge

#4842 RNTester: Update Image page and remove assert
  change/react-native-windows-2020-05-08-16-52-38-image.json
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
Labels: AutoMerge

#5495 Batch Checkouts When Upgrading Overrides
  change/@office-iss-react-native-win32-2020-07-10-16-02-44-batching-queue.json
  change/@rnw-scripts-ts-config-2020-07-10-16-02-44-batching-queue.json
  change/react-native-platform-override-2020-07-10-16-02-44-batching-queue.json
  change/react-native-windows-2020-07-10-16-02-44-batching-queue.json
  packages/@rnw-scripts/ts-config/tsconfig.json
  packages/react-native-platform-override/babel.config.js
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/ActionQueue.ts
  packages/react-native-platform-override/src/Api.ts
  packages/react-native-platform-override/src/BatchingQueue.ts
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  packages/react-native-platform-override/src/Manifest.ts
  packages/react-native-platform-override/src/e2etest/Api.test.ts
  packages/react-native-win32/overrides.json
  vnext/overrides.json
  yarn.lock
Labels: AutoMerge

#5503 Move contents of ReactDirectories.props to Directory.build.props
  change/react-native-windows-2020-07-10-11-43-03-react-directories.json
  vnext/Directory.Build.props
  vnext/Microsoft.ReactNative.sln
  vnext/PropertySheets/ReactDirectories.props
Labels: AutoMerge

#5507 Add ReactDispatcher tests
  change/react-native-windows-2020-07-10-14-20-55-ms-rnw-staging.json
  vnext/Desktop.ABITests/Application.manifest
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.ABITests/ReactDispatcherTests.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
Labels: Area: Core DLL

#5500 Only install superseding/applicable dependent framework packages
  change/react-native-windows-2020-07-10-09-45-59-5482.json
  vnext/local-cli/powershell/WindowsStoreAppUtils.ps1
  vnext/local-cli/src/runWindows/utils/deploy.ts
Labels: Area: CLI

#5499 Use XamlRoot's compositor on WinUI3
  change/react-native-windows-2020-07-10-00-43-28-islandsCompositor.json
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Views/ExpressionAnimationStore.cpp
  vnext/Microsoft.ReactNative/Views/ExpressionAnimationStore.h
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.h
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
  vnext/Microsoft.ReactNative/XamlView.cpp
  vnext/Microsoft.ReactNative/XamlView.h
Labels: Area: Islands, Area: WinUI, AutoMerge

#5517 Add ReactNotificationService test
  change/react-native-windows-2020-07-13-15-28-45-ms-rnw-staging.json
  vnext/Desktop.ABITests/Application.manifest
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
Labels: Area: Core DLL

#5509 Add Validation That Patch/Derived Overrides Aren't Identical to Their Originals
  change/react-native-platform-override-2020-07-10-19-05-02-not-same.json
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/ValidationStrategy.ts
  packages/react-native-platform-override/src/test/ValidationStrategy.test.ts
Labels: Area: Release Process

#5518 Add ReactInstanceSettings tests
  change/react-native-windows-2020-07-13-19-23-54-ms-rnw-staging.json
  vnext/Desktop.ABITests/Application.manifest
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
Labels: Area: Core DLL

#5506 Move some templates to shared location
  change/react-native-windows-2020-07-10-14-13-31-master.json
  vnext/local-cli/src/generator-windows/index.ts
  vnext/local-cli/templates/cpp/src/App.xaml
  vnext/local-cli/templates/cpp/src/MainPage.xaml
  vnext/local-cli/templates/cs/assets/LockScreenLogo.scale-200.png
  vnext/local-cli/templates/cs/assets/SplashScreen.scale-200.png
  vnext/local-cli/templates/cs/assets/Square150x150Logo.scale-200.png
  vnext/local-cli/templates/cs/assets/Square44x44Logo.scale-200.png
  vnext/local-cli/templates/cs/assets/Square44x44Logo.targetsize-24_altform-unplated.png
  vnext/local-cli/templates/cs/assets/StoreLogo.png
  vnext/local-cli/templates/cs/assets/Wide310x150Logo.scale-200.png
  vnext/local-cli/templates/cs/src/Package.appxmanifest
  vnext/local-cli/templates/shared/assets/LockScreenLogo.scale-200.png
  vnext/local-cli/templates/shared/assets/SplashScreen.scale-200.png
  vnext/local-cli/templates/shared/assets/Square150x150Logo.scale-200.png
  vnext/local-cli/templates/shared/assets/Square44x44Logo.scale-200.png
  vnext/local-cli/templates/shared/assets/Square44x44Logo.targetsize-24_altform-unplated.png
  vnext/local-cli/templates/shared/assets/StoreLogo.png
  vnext/local-cli/templates/shared/assets/Wide310x150Logo.scale-200.png
  vnext/local-cli/templates/shared/src/App.xaml
  vnext/local-cli/templates/shared/src/MainPage.xaml
  vnext/local-cli/templates/shared/src/Package.appxmanifest
Labels: Area: CLI

#5516 Fix #5469: Don't rely on variables for conditonal logic AzureDevops Pipelines
  .ado/templates/react-native-init.yml
Labels: AutoMerge

#5522 Add ReactPackageProvider tests
  change/react-native-windows-2020-07-14-14-02-41-ms-rnw-staging.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.ABITests/ReactPackageProviderTests.cpp
Labels: Area: Core DLL

#5523 Add support for `Task` and `Task<T>` async methods for C# native modules
  change/react-native-windows-2020-07-14-14-48-07-master.json
  packages/microsoft-reactnative-sampleapps/index.windows.js
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Analysis/ModuleMethodAnalysisTests.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenInitializerTests.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenMethodTests.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--DoubleArgCallbackParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--DoublePromiseParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--IntParamAndDoubleArgCallbackParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--IntParamAndDoublePromiseParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--IntParamAndPromiseParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--IntParamAndSingleArgCallbackParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--PromiseParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--TwoArgsTask--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--TwoArgsTaskOfInt--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ZeroArgTask--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ZeroArgTaskOfInt--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeAnalyzer.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Serializers.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.ViewManager.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/DiagnosticDescriptors.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/Model/ReactMethod.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/Model/ReactTypes.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/ReactNativeNames.cs
  vnext/Microsoft.ReactNative.Managed/IReactPromise.cs
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.Managed/ReactPromise.cs
  vnext/Microsoft.ReactNative.Managed/ReactTaskExtensions.cs
Labels: AutoMerge

#5527 Have Desktop integration tests use DLL instead of static linking
  change/react-native-windows-2020-07-14-21-46-53-deskit-usedll.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
Labels: AutoMerge

#5526 Update artifact publish and download to the newer versions.
  .ado/publish.yml
  .ado/templates/e2e-test-job.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/publish-build-artifacts-for-nuget.yml
  .ado/templates/react-native-init.yml
Labels: AutoMerge

#5525 Add Image load debugging output
  change/react-native-windows-2020-07-14-17-18-50-imageDebug.json
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
Labels: AutoMerge

#5535 [Win32] Bump rex-win32 version
  change/@office-iss-react-native-win32-2020-07-16-08-40-50-bumprex.json
  packages/react-native-win32/package.json
  yarn.lock
Labels: AutoMerge, Request Backport to 0.62

#5385 Codesign Microsoft.ReactNative binaries and nuget package
  .ado/publish.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/prep-and-pack-single.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-07-10-16-18-38-codesign.json
  vnext/Scripts/Microsoft.ReactNative.Cxx.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.SignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.SignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.SignConfig.xml
Labels: Area: Build Infrastructure

#5544 Add RedBox objects, tests
  change/react-native-windows-2020-07-16-16-42-08-abi-safety.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.ABITests/RedBoxTests.cpp
  vnext/Desktop/ABI/TestController.cpp
  vnext/Desktop/ABI/TestController.h
  vnext/Desktop/ABI/TestController.idl
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/RedBoxErrorFrameInfo.cpp
  vnext/Microsoft.ReactNative/RedBoxErrorFrameInfo.h
  vnext/Microsoft.ReactNative/RedBoxErrorInfo.cpp
  vnext/Microsoft.ReactNative/RedBoxErrorInfo.h
Labels: Area: Core DLL

#5533 Enabling SourceLink support.
  .ado/templates/build-rnw.yml
  change/react-native-windows-2020-07-15-21-24-35-master.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/packages.config
  vnext/Directory.Build.props
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
Labels: AutoMerge

#5542 Add fix for msbuild long paths in machine setup script
  change/react-native-windows-2020-07-16-16-31-04-master.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5551 Workaround for metro monorepo asset issues
  packages/E2ETest/metro.config.js
  packages/microsoft-reactnative-sampleapps/metro.config.js
  packages/playground/just-task.js
  packages/playground/metro.config.js
  packages/playground/package.json
Labels: AutoMerge

#5554 Update rnw-dependencies.ps1 to support grouping of requirements to hndle different use cases
  change/react-native-windows-2020-07-20-09-14-24-master.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5541 Add windows adk to machine setup script
  change/react-native-windows-2020-07-20-10-14-08-master.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5555 Move e2etest pages into rntester
  .ado/templates/e2e-test-job.yml
  change/react-native-windows-2020-07-17-20-12-27-rntester-phase1-take2.json
  packages/E2ETest/app/TestApp.tsx
  packages/E2ETest/app/TestPages.ts
  packages/E2ETest/app/UnknownPage.tsx
  packages/E2ETest/app/index.ts
  packages/E2ETest/wdio/pages/BasePage.ts
  packages/E2ETest/wdio/pages/ControlStylePage.ts
  packages/E2ETest/wdio/pages/DirectManipulationPage.ts
  packages/E2ETest/wdio/pages/HomePage.ts
  packages/E2ETest/wdio/pages/ImageTestPage.ts
  packages/E2ETest/wdio/pages/LoginPage.ts
  packages/E2ETest/wdio/pages/TextInputTestPage.ts
  packages/E2ETest/wdio/pages/TransformTestPage.ts
  packages/E2ETest/wdio/test/DirectManipulation.spec.ts
  packages/E2ETest/wdio/test/Image.spec.ts
  packages/E2ETest/wdio/test/TransformTest.spec.ts
  packages/E2ETest/wdio/test/controlStyle.spec.ts
  packages/E2ETest/wdio/test/login.spec.ts
  packages/E2ETest/wdio/test/testInput.spec.ts
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRegularBorder.json
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRoundBorder.json
  packages/E2ETest/windows/ReactUWPTestApp/MainPage.xaml.cs
  vnext/overrides.json
  vnext/src/RNTester/js/RNTesterApp.windows.js
  vnext/src/RNTester/js/components/RNTesterExampleList.windows.js
  vnext/src/RNTester/js/examples-win/LegacyTests/AccessibilityTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/Consts.ts
  vnext/src/RNTester/js/examples-win/LegacyTests/ControlStyleTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/DirectManipulationTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/ImageTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/LoginTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/TextInputTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/TransformTestPage.tsx
  vnext/src/RNTester/js/examples-win/LegacyTests/TreeDumpControl.ts
  vnext/src/RNTester/js/utils/RNTesterList.windows.ts
Labels: Area: Test Infrastructure, Area: Tests

#5561 Move WinUI 3 to Preview 2
  change/react-native-windows-2020-07-21-00-03-28-preview2.json
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/packages.config
  vnext/Microsoft.ReactNative.Cxx/UI.Text.h
  vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/WinUI.props
Labels: Area: WinUI, AutoMerge

#5562 Use per-thread compositor
  change/react-native-windows-2020-07-21-01-18-27-perThreadCompositor.json
  vnext/Microsoft.ReactNative/Modules/Animated/AdditionAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/DiffClampAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/DivisionAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/FrameAnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/ModulusAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/MultiplicationAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/SubtractionAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp
  vnext/Microsoft.ReactNative/ReactRootView.cpp
  vnext/Microsoft.ReactNative/XamlView.cpp
  vnext/Microsoft.ReactNative/XamlView.h
Labels: Area: Islands, AutoMerge

#5566 Add ReactNonAbiValue test
  change/react-native-windows-2020-07-16-16-42-08-abi-safety.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.ABITests/ReactNonAbiValueTests.cpp
  vnext/Desktop/ABI/TestController.cpp
  vnext/Desktop/ABI/TestController.h
  vnext/Desktop/ABI/TestController.idl
Labels: Area: Core DLL

#5570 Add island icon to playground-win32.
  packages/playground/windows/playground-win32/Island_256.ico
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-Win32.rc
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/resource.h
Labels: Area: Islands, AutoMerge

#5574 Update V8 package version
  change/react-native-windows-2020-07-22-14-39-04-master.json
  vnext/Desktop.DLL/packages.config
  vnext/Desktop/packages.config
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/V8JSIRuntimeHolder.cpp
Labels: AutoMerge, Request Backport to 0.62

#5569 Stop placing Microsoft.ReactNative.Cxx in the Microsoft.ReactNative nuget package
  change/react-native-windows-2020-07-21-19-54-05-master.json
  vnext/Scripts/Microsoft.ReactNative.nuspec
Labels: AutoMerge

#5580 Update V8 package version (0.62)
  change/react-native-windows-2020-07-23-17-36-11-0.62-stable.json
  vnext/Desktop.DLL/packages.config
  vnext/Desktop/packages.config
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactWindowsCore/V8JSIRuntimeHolder.cpp
Labels: AutoMerge

#5583 Bump some npm package versions
  change/@office-iss-react-native-win32-2020-07-23-14-10-52-bumpdeps.json
  change/react-native-windows-2020-07-23-14-10-52-bumpdeps.json
  package.json
  packages/react-native-win32/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#5584 Add ReactContext implementation for Win32 ABI
  change/react-native-windows-2020-07-23-17-42-00-abi-safety.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.ABITests/ReactContextTests.cpp
  vnext/Desktop.ABITests/ReactModuleBuilderTests.cpp
  vnext/Desktop/ABI/TestController.cpp
  vnext/Desktop/ABI/TestController.h
  vnext/Desktop/ABI/TestController.idl
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactHost/React_Win.h
Labels: Area: Core DLL

#5586 Integrate React Native Up to The Base of 0.63
  .ado/windows-vs-pr.yml
  change/@office-iss-react-native-win32-2020-07-25-08-23-20-base-of-0.63.json
  change/react-native-windows-2020-07-25-08-23-20-base-of-0.63.json
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
  packages/react-native-win32/src/Libraries/Inspector/Inspector.win32.js
  packages/react-native-win32/src/Libraries/Inspector/InspectorOverlay.win32.js
  packages/react-native-win32/src/index.win32.js
  vnext/.flowconfig
  vnext/Chakra/ChakraExecutor.cpp
  vnext/Chakra/ChakraExecutor.h
  vnext/DeforkingPatches/ReactCommon/yoga/yoga/Yoga.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/InstanceMocks.cpp
  vnext/Desktop.UnitTests/InstanceMocks.h
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/ReactCommon.vcxproj.filters
  vnext/ReactCopies/RNTester/js/examples/Pressable/PressableExample.js
  vnext/ReactCopies/RNTester/js/examples/ScrollView/ScrollViewSimpleExample.js
  vnext/ReactCopies/RNTester/js/examples/TextInput/TextInputExample.android.js
  vnext/ReactCopies/RNTester/js/examples/Touchable/TouchableExample.js
  vnext/ReactCopies/RNTester/js/examples/TurboModule/SampleTurboModuleExample.js
  vnext/ReactCopies/RNTester/js/utils/RNTesterStatePersister.js
  vnext/Shared/Executors/WebSocketJSExecutor.cpp
  vnext/Shared/Executors/WebSocketJSExecutor.h
  vnext/Shared/OInstance.cpp
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js
  vnext/src/Libraries/Components/Picker/Picker.windows.js
  vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
  vnext/src/Libraries/Lists/VirtualizedList.windows.js
  vnext/src/Libraries/Utilities/Appearance.windows.js
  vnext/src/Libraries/Utilities/DebugEnvironment.js
  vnext/src/babel-plugin-inline-view-configs/index.js
  vnext/src/index.windows.js
  yarn.lock
Labels: AutoMerge

#5582 [0.62] Fixed external targets for apps and libs
  change/react-native-windows-2020-07-23-13-43-02-fix62targets.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
Labels: Backport to 0.62 Approved

#5600 Create release notes for first preview + stable release as a draft
  change/@rnw-scripts-create-github-releases-2020-07-28-07-39-21-draft-notes.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
Labels: AutoMerge
