Repository microsoft/react-native-windows, pull requests merged in 2020-12, with the labels that each got.

#6633 Amend doc for REACT_STRUCT.
  change/react-native-windows-1aac7b87-16f0-4567-a57a-4e0b5ec8b55b.json
  vnext/Microsoft.ReactNative.Cxx/StructInfo.h
Labels: AutoMerge

#6644 Fix getting JsiRuntime for host functions
  change/react-native-windows-34026362-bdf7-4921-9cb1-90b87780623e.json
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#6635 Factor PR validation Yaml files
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/jschecks.yml
  .ado/jobs/macos-tests.yml
  .ado/jobs/nuget-desktop.yml
  .ado/jobs/playground.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#6646 Self-signed certificate - timeout error fix
  change/@react-native-windows-cli-4be26f48-0076-4686-9fb4-6fe14a114393.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
Labels: Area: CLI

#6657 [0.64] Fix multicore build, missing dependency on Folly
  change/react-native-windows-71860b92-7530-44e6-9d99-c06cb3814d8e.json
  vnext/ReactCommon/ReactCommon.vcxproj
Labels: AutoMerge

#6654 Update V8 package version
  change/react-native-windows-91d7f4ff-c8d8-44a0-815c-937f108994e2.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#6669 Update cli telemetry defaults
  change/@react-native-windows-cli-23db3b86-8039-40ed-b29d-be96b1e8718b.json
  change/react-native-windows-init-ca9b9927-7215-44e3-ba38-ca84e3441642.json
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/react-native-windows-init/src/Cli.ts
Labels: Request Backport to 0.63, Request Backport to 0.64

#6671 [0.63] Update cli telemetry defaults
  change/@react-native-windows-cli-a3d1917f-fa0d-4a55-9567-add8fe505b93.json
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/react-native-windows-init/src/Cli.ts
Labels: Backport to 0.63 Approved

#6653 [0.63] Backporting TimingModule assert removals
  change/react-native-windows-2020-09-13-16-16-58-no-timing-aseert.json
  change/react-native-windows-2020-10-02-12-58-35-remove-other-timingmodule-assert.json
  vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
Labels: Request Backport to 0.63

#6609 Update Min WinUI 2.x Version to 2.5
  change/@react-native-windows-cli-307096cb-c34e-41fa-b990-48cc8e329590.json
  change/react-native-windows-9d1dced1-c309-4f2f-b5de-7c5eae483dec.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRegularBorder.json
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRoundBorder.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/packages.config
  packages/playground/packages.config
  packages/playground/windows/playground/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/WinUI.props
Labels: Area: Infrastructure

#6659 Fix dependency syncing for wildcard peer dependencies
  change/@rnw-scripts-integrate-rn-1b0001cc-2902-477a-ba81-ec722cdb5fed.json
  packages/@rnw-scripts/integrate-rn/src/test/upgradeDependencies.test.ts
  packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
Labels: AutoMerge

#6662 Allow unreleased RNW versions with react-native-windows-init --useDevMode
  change/@rnw-scripts-create-github-releases-71c0b2d9-e2d4-44aa-a2dd-23463d22f3a3.json
  change/@rnw-scripts-integrate-rn-264060b3-e018-4fe5-a23c-114e2b493cc5.json
  change/@rnw-scripts-promote-release-886c8d49-5a3c-4360-be9b-280c4e982782.json
  change/@rnw-scripts-take-screenshot-53b0d611-b841-40ef-8fcf-99cd5486db3b.json
  change/react-native-platform-override-d4f4757d-82bb-4069-afa7-7e34d653dd28.json
  change/react-native-windows-codegen-ec623ba9-5181-402f-aaee-a3c7a750dff5.json
  change/react-native-windows-init-5af39e72-8d77-4cea-a8ff-e96edda20a54.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/take-screenshot/package.json
  packages/react-native-platform-override/package.json
  packages/react-native-windows-codegen/package.json
  packages/react-native-windows-init/package.json
  packages/react-native-windows-init/src/Cli.ts
Labels: Area: Release Process, AutoMerge

#6655 Fix multicore build, missing dependency on Folly
  change/react-native-windows-99027820-65f4-41ab-a0b3-bc58c04b9c75.json
  vnext/ReactCommon/ReactCommon.vcxproj
Labels: AutoMerge

#6661 Ensure windows script added on init
  change/@react-native-windows-cli-a619d127-6460-494c-b622-f2104826546e.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/index.ts
Labels: Area: Infrastructure, AutoMerge

#6663 Integrate 12/2 Nightly Build
  .ado/jobs/desktop.yml
  change/@office-iss-react-native-win32-c88bc51f-e94c-466c-92b5-4a506edbe929.json
  change/@react-native-windows-cli-ab9b239d-4a7c-4bc9-b35c-d86fd0c1e503.json
  change/react-native-windows-86f4ebe9-be85-4142-8538-feccb7bfeb54.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/tester/js/components/RNTesterExampleList.js
  packages/@react-native/tester/js/examples/ActionSheetIOS/ActionSheetIOSExample.js
  packages/@react-native/tester/js/examples/AppState/AppStateExample.js
  packages/@react-native/tester/js/examples/SectionList/SectionListExample.js
  packages/@react-native/tester/overrides.json
  packages/E2ETest/metro.config.js
  packages/E2ETest/package.json
  packages/IntegrationTest/metro.config.js
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/metro.config.js
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/metro.config.js
  packages/playground/package.json
  packages/react-native-win32-tester/overrides.json
  packages/react-native-win32-tester/package.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
  packages/react-native-win32/src/Libraries/Utilities/Platform.win32.js
  packages/react-native-win32/src/index.win32.js
  vnext/.flowconfig
  vnext/PropertySheets/Bundle.props
  vnext/metro.config.js
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/View/ReactNativeViewViewConfig.windows.js
  vnext/src/Libraries/ReactNative/PaperUIManager.windows.js
  vnext/src/Libraries/Utilities/Platform.windows.js
  vnext/src/babel-plugin-codegen/GenerateViewConfigJs.js
  vnext/src/babel-plugin-codegen/package.json
  vnext/src/index.windows.js
  vnext/template/metro.config.js
  vnext/template/metro.devMode.config.js
  yarn.lock
Labels: AutoMerge

#6660 Use whitespace insensitive compare for identical override detection
  change/react-native-platform-override-aaad62eb-415d-4d87-9019-01d3e743d512.json
  packages/react-native-platform-override/src/Hash.ts
  packages/react-native-platform-override/src/ValidationStrategy.ts
  packages/react-native-platform-override/src/test/Hash.test.ts
  packages/react-native-platform-override/src/test/ValidationStrategy.test.ts
Labels: AutoMerge

#6680 Fix destruction of UIManager in UI thread
  change/react-native-windows-a206e50b-eb3d-4f1e-bb61-35d4d333e417.json
  vnext/Desktop/Modules/UIManagerModule.cpp
Labels: AutoMerge, Backport to 0.63 Approved, Request Backport to 0.64

#6420 [0.63] Autolinking fixes for C++ / C# interop
  change/@react-native-windows-cli-2020-11-03-15-34-18-autolinkingfixes63.json
  change/react-native-windows-2020-11-03-15-34-18-autolinkingfixes63.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
  packages/@react-native-windows/cli/templates/cpp/proj/MyApp.sln
  packages/@react-native-windows/cli/templates/cs/src/AutolinkedNativeModules.g.targets
  packages/@react-native-windows/cli/templates/shared/src/AutolinkedNativeModules.g.props
  packages/@react-native-windows/cli/templates/shared/src/AutolinkedNativeModules.g.targets
  packages/E2ETest/windows/ReactUWPTestApp/AutolinkedNativeModules.g.props
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/AutolinkedNativeModules.g.props
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/AutolinkedNativeModules.g.props
  packages/playground/windows/playground-win32/AutolinkedNativeModules.g.props
  packages/playground/windows/playground/AutolinkedNativeModules.g.props
  packages/playground/windows/playground/Playground.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
Labels: AutoMerge

#6693 Fix getting host objects and functions in JSI ABI
  change/react-native-windows-5e214434-8983-474c-8d79-cae036a5fc24.json
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
Labels: AutoMerge, Needed for 0.64

#6701 Fix Taps/Clicks Being Eaten in 0.63
  change/@office-iss-react-native-win32-2020-12-07-13-16-55-scrollresponder-63.json
  change/react-native-windows-2020-12-07-13-16-55-scrollresponder-63.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/Components/ScrollResponder.win32.js
  vnext/overrides.json
  vnext/src/Libraries/Components/ScrollResponder.windows.js
Labels: Area: Mouse, AutoMerge, Backport to 0.63 Approved

#6594 Use new command-line tool for appx deployment
  change/@react-native-windows-cli-f2b98d50-5bed-4a85-abfd-c8a0cabcf7ee.json
  packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Labels: Area: CLI

#6712 [0.64] Cherry pick JS ABI and UI Manager destruction fixes
  change/react-native-windows-34026362-bdf7-4921-9cb1-90b87780623e.json
  change/react-native-windows-5e214434-8983-474c-8d79-cae036a5fc24.json
  change/react-native-windows-a206e50b-eb3d-4f1e-bb61-35d4d333e417.json
  vnext/Desktop/Modules/UIManagerModule.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#6707 Cleanup .ado folder by moving scripts into separate folder
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/playground.yml
  .ado/scripts/Get-ShellScaling.ps1
  .ado/scripts/ReactUWPTestApp.reg
  .ado/scripts/SetupLocalDumps.cmd
  .ado/scripts/TestWACK.ps1
  .ado/scripts/VSComponentList.ps1
  .ado/scripts/npmAddUser.js
  .ado/scripts/setVersionEnvVars.js
  .ado/scripts/shouldSkipPRBuild.ps1
  .ado/scripts/waitForVerdaccio.js
  .ado/templates/e2e-test-job.yml
  .ado/templates/integration-test-job.yml
  .ado/templates/prepare-env.yml
  .ado/templates/react-native-init.yml
  .ado/templates/set-version-vars.yml
  .ado/windows-vs-pr.yml
Labels: Area: Infrastructure

#6719 Remove unused pipeline yaml files.
  .ado/templates/e2e-test-job.yml
  .ado/templates/integration-test-job.yml
  .ado/templates/macos-tests-job.yml
Labels: Area: Infrastructure

#6713 [0.63] Fix destruction of UIManager in UI thread (#6680)
  change/react-native-windows-b31b0d4b-c43f-464a-8b7c-a276c8be541b.json
  vnext/Shared/Modules/UIManagerModule.cpp
Labels: AutoMerge

#6730 [0.64] Win32 Polite/Aggressive Focus API (#6711)
  change/@office-iss-react-native-win32-91e06e85-4251-45c4-97a7-5a34dda4e0f2.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
  packages/react-native-win32/src/index.win32.js
Labels: AutoMerge, Request Backport to 0.64

#6704 Reader/Writer for winrt::hstring
  change/react-native-windows-0f6efe1f-8377-4920-9644-b25e46538084.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueReaderTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
Labels: Area: Native Modules, AutoMerge

#6739 Fix RedBox on topMouseLeave event.
  change/react-native-windows-92856720-40ea-4e20-ac14-b1c0178f1ba0.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: AutoMerge

#6705 Allow git and npm publish to be skipped when manually publishing bits
  .ado/publish.yml
Labels: Area: Infrastructure

#6736 Bundle in solution dir
  change/react-native-windows-a63e7858-8496-49aa-9f5a-6e48db31dd50.json
  vnext/PropertySheets/Bundle.props
Labels: Area: Bundle, Area: CLI, Area: Test Infrastructure

#6686 Fix regression where E2ETest app no longer uploads tree dump outputs
  .ado/jobs/e2e-test.yml
  docs/e2e-testing.md
  packages/E2ETest/wdio.conf.js
  packages/E2ETest/windows/ReactUWPTestApp/Package.appxmanifest
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp_TemporaryKey.pfx
  packages/E2ETest/windows/ReactUWPTestApp/TreeDumpControlViewManager.cs
  packages/E2ETest/windows/ReactUWPTestApp/copyTreeDump.cmd
Labels: Area: Test Infrastructure

#6731 [0.63] Win32 Polite/Aggressive Focus API (#6711)
  change/@office-iss-react-native-win32-16aa1605-e207-4545-b716-7ce7beb61eb7.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
  packages/react-native-win32/src/index.win32.js
Labels: AutoMerge, Request Backport to 0.63

#6746 Cherry-pick: Fix RedBox on topMouseLeave event. (#6739)
  change/react-native-windows-92856720-40ea-4e20-ac14-b1c0178f1ba0.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: AutoMerge

#6745 Fix facebook::jsi::Runtime lifetime for ABI JSI
  change/react-native-windows-a3ba06da-a261-42a2-be5d-9b023d3493f9.json
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApi.h
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative/IReactContext.idl
Labels: AutoMerge

#6734 Show HRESULT code on WebSocket errors
  change/react-native-windows-4b3bffd5-1b12-4096-abe8-77b4b8661b2e.json
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Shared/WinRTWebSocketResource.cpp
Labels: Area: Networking, AutoMerge, Request Backport to 0.62, Request Backport to 0.63, Request Backport to 0.64

#6732 Add tabIndex property for Button
  change/react-native-windows-136ae86b-5757-4cb4-8cec-a50da19528c3.json
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/src/Libraries/Components/Button.windows.js
Labels: Area: Button, Area: Keyboard, AutoMerge

#6698 Use stages to simplify conditions and dependencies between jobs
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/jschecks.yml
  .ado/jobs/macos-tests.yml
  .ado/jobs/nuget-desktop.yml
  .ado/jobs/playground.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/windows-vs-pr.yml
Labels: Area: Infrastructure

#6744 [0.62] Win32 Polite/Aggressive Focus API
  change/@office-iss-react-native-win32-2020-12-14-13-44-42-master.json
  packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
  packages/react-native-win32/src/index.win32.ts
  packages/react-native-win32/src/overrides.json
Labels: Backport to 0.62 Approved

#6753 Force node-notifier resolution to ^9.0.0, fixes #6752
  package.json
  yarn.lock
Labels: AutoMerge

#6728 Fix: Control with "AccessibilityRole" automatically get tab focus no matter the value of focusable prop
  change/react-native-windows-6b0a9e7b-b179-4854-91fa-a1752c5c89b7.json
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Labels: Needed for 0.64

#6754 Add onPressIn/onPressOut Textinput events
  change/react-native-windows-9b1e075e-6ff9-424b-99f6-d9bc58c34f86.json
  packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: TextInput, Needed for 0.64

#6774 Fix publish pipeline due to ADO not recognizing `succeeded()` from template expression
  .ado/publish.yml
Labels: AutoMerge

#6775 Make package config more strict
  change/react-native-windows-2d953fa7-7efa-42d8-8c53-2abf0a22be62.json
  packages/playground/windows/NuGet.Config
  vnext/NuGet.Config
  vnext/template/shared-app/proj/NuGet.Config
  vnext/template/shared-lib/proj/NuGet.Config
Labels: AutoMerge

#6772 Print error message when vswhere/msbuild tools are missing
  change/@react-native-windows-cli-ce9bd95b-9609-4aa9-8cc1-aac2b148ea3b.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: AutoMerge

#6771 [0.64] Print error message when vswhere/msbuild tools are missing
  change/@react-native-windows-cli-55162ecb-57f9-4f08-b45f-a6e00b71a23b.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: AutoMerge

#6770 [0.63] Print error message when vswhere/msbuild tools are missing
  change/@react-native-windows-cli-2020-12-18-04-39-09-vswhere-0.63.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: AutoMerge

#6781 [0.62] Add key events to TextWin32 and target prop to ViewWin32
  change/@office-iss-react-native-win32-358d7e11-56fa-4d83-a480-524e5e3648f3.json
  change/@office-iss-react-native-win32-edf6d20c-9de2-4bbd-8587-fa0a6ca730cd.json
  change/react-native-windows-0e666e3c-dbdc-4185-b013-b8cae8e302e8.json
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.keydownevents.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.keyupevents.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeydown.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeydowncapture.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeyup.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeyupcapture.md
  packages/react-native-win32/docs/api/react-native-win32.md
  packages/react-native-win32/docs/api/react-native-win32.sharedtextpropsandroidandwin32.md
  packages/react-native-win32/docs/api/react-native-win32.textwin32omittypes.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/src/Libraries/Components/Text/TextWin32.Props.ts
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Labels: Backport to 0.62 Approved

#6762 [0.63] Add key events to TextWin32 and target prop to ViewWin32 (#6490)
  change/@office-iss-react-native-win32-0323552c-7d62-481b-8e21-862eee63762b.json
  packages/react-native-win32/docs/api/react-native-win32.accessibilityannotationinfo.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.keydownevents.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.keyupevents.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeydown.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeydowncapture.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeyup.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onkeyupcapture.md
  packages/react-native-win32/docs/api/react-native-win32.md
  packages/react-native-win32/docs/api/react-native-win32.sharedtextpropsandroidandwin32.md
  packages/react-native-win32/docs/api/react-native-win32.textwin32omittypes.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/src/Libraries/Components/Text/TextWin32.Props.ts
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Labels: Backport to 0.63 Approved

#6784 Remove fetch depth 1 as Lage does git some history operations and will fail otherwise
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/macos-tests.yml
Labels: AutoMerge

#6791 Add retry options to the copy to increase reliability
  Directory.Build.targets
Labels: AutoMerge

#6792 Check deps when builds fail
  .gitignore
  change/@react-native-windows-cli-3b609198-fa72-476b-943b-df441c5784d6.json
  change/react-native-windows-b973e5dc-d862-4a91-8e81-e846331c5c82.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#6793 Don't do js up to date checks for design builds
  Directory.Build.props
  Directory.Build.targets
  change/react-native-windows-9edf6a5f-06e1-45a2-ac83-c0adfd7d0f8f.json
  vnext/Directory.Build.props
Labels: AutoMerge

#6768 Fix newline issues in new cli project generated files
  change/@react-native-windows-cli-fade23e0-e162-4d43-bd96-501286fed36a.json
  change/react-native-windows-7ab8f682-3987-4ca5-974d-266c5e551cc6.json
  packages/@react-native-windows/cli/src/generator-common/index.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  vnext/template/.clang-format
  vnext/template/cpp-app/src/App.cpp
  vnext/template/cpp-app/src/App.h
  vnext/template/cpp-app/src/MainPage.cpp
  vnext/template/cpp-app/src/MainPage.h
  vnext/template/cpp-app/src/ReactPackageProvider.cpp
  vnext/template/cpp-app/src/ReactPackageProvider.h
  vnext/template/cpp-lib/src/ReactNativeModule.h
  vnext/template/cpp-lib/src/ReactPackageProvider.cpp
  vnext/template/cpp-lib/src/ReactPackageProvider.h
Labels: Request Backport to 0.63, Request Backport to 0.64
