Repository microsoft/react-native-windows, pull requests merged in 2020-10, with the labels that each got.

#6145 Integrate 8/5 Nightly RN Build
  change/@office-iss-react-native-win32-2020-09-30-17-43-45-integrate-8-5.json
  change/react-native-windows-2020-09-30-17-43-45-integrate-8-5.json
  packages/E2ETest/package.json
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/babel.config.js
  packages/playground/package.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  vnext/.gitignore
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Shared/OInstance.cpp
  vnext/codegen/NativeAnimatedTurboModuleSpec.g.h
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/Button.windows.js
  vnext/src/babel-plugin-codegen/GenerateViewConfigJs.js
  vnext/src/babel-plugin-codegen/index.js
  vnext/src/babel-plugin-codegen/package.json
  yarn.lock
Labels: AutoMerge

#6144 Add some extra error handling to GitReactFileRepository
  change/react-native-platform-override-2020-09-30-17-46-03-extra-git-error-handing.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
Labels: AutoMerge

#6135 Expose getters for some instance settings on reactcontext
  change/react-native-windows-2020-09-30-09-05-50-syncplaygroundsettings.json
  packages/E2ETest/windows/ReactUWPTestApp/App.xaml.cs
  packages/IntegrationTest/windows/integrationtest/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.xaml
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/ReactApplication.idl
  vnext/Microsoft.ReactNative/ReactHost/IReactInstance.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactHost/React_Win.h
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Shared/Shared.vcxitems.filters
  vnext/template/cpp-app/src/App.cpp
  vnext/template/cs-app/src/App.xaml.cs
Labels: AutoMerge

#5174 Use HRESULT instead of catching exceptions for WebSocket APIs
  change/react-native-windows-2020-06-10-19-57-26-ws-notrow-hresult.json
  vnext/Common/unicode.cpp
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/Utils/CppWinrtLessExceptions.h
  vnext/Shared/WinRTWebSocketResource.cpp
Labels: Area: Networking, AutoMerge, Platform: Desktop, Request Backport to 0.62, Request Backport to 0.63

#6163 Integrate 8/17 Nightly RN Build
  change/@office-iss-react-native-win32-2020-10-01-15-12-39-integrate-8-17.json
  change/react-native-windows-2020-10-01-15-12-39-integrate-8-17.json
  packages/E2ETest/package.json
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/BatchedBridge/MessageQueue.win32.js
  packages/react-native-win32/src/Libraries/Inspector/InspectorOverlay.win32.js
  vnext/.flowconfig
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.h
  vnext/codegen/NativeAnimatedModuleSpec.g.h
  vnext/codegen/NativeAnimatedTurboModuleSpec.g.h
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Pressability/Pressability.windows.js
  vnext/src/babel-plugin-codegen/GenerateViewConfigJs.js
  yarn.lock
Labels: AutoMerge

#6159 Fix native modules not being re-initialized on reload
  change/react-native-windows-2020-10-02-00-03-14-HEAD.json
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
Labels: AutoMerge

#6168 Add command to diff overrides
  change/react-native-platform-override-2020-10-01-19-45-20-override-diff.json
  packages/react-native-platform-override/README.md
  packages/react-native-platform-override/src/Api.ts
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/DiffStrategy.ts
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/UpgradeStrategy.ts
  packages/react-native-platform-override/src/e2etest/Api.test.ts
  packages/react-native-platform-override/src/e2etest/DiffStrategy.test.ts
Labels: AutoMerge

#6173 Integrate 8/19 Nightly RN Build
  change/@office-iss-react-native-win32-2020-10-02-12-44-11-integrate-8-19.json
  change/@rnw-scripts-integrate-rn-2020-10-02-12-44-11-integrate-8-19.json
  change/react-native-windows-2020-10-02-12-44-11-integrate-8-19.json
  packages/@rnw-scripts/integrate-rn/src/integrateRN.ts
  packages/E2ETest/package.json
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  vnext/overrides.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#6174 Remove the other TimingModule Assertion
  change/react-native-windows-2020-10-02-12-58-35-remove-other-timingmodule-assert.json
  vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
Labels: AutoMerge

#6178 Fix resetting of playground comboboxes upon load
  packages/playground/windows/playground/MainPage.cpp
Labels: AutoMerge

#6183 Force hermes-engine 0.70
  package.json
  yarn.lock
Labels: security

#6184 Update System.Private.Uri version for C# codegen
  change/react-native-windows-2020-10-05-12-09-22-master.json
  vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
Labels: security

#6199 Update System.Private.Uri version for C# codegen for unittest
  change/react-native-windows-2020-10-06-11-02-39-master.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
Labels: security

#6190 Update Folly
  change/react-native-windows-2020-10-05-13-51-58-folly2.json
  vnext/Directory.Build.props
Labels: Area: Build Infrastructure

#6189 Update just-scipts (remove npm-registry-fetch)
  change/@office-iss-react-native-win32-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@react-native-windows-cli-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-create-github-releases-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-find-repo-root-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-format-files-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-integrate-rn-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-just-task-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-package-utils-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-promote-release-2020-10-05-15-49-35-npm-registry-fetch.json
  change/@rnw-scripts-take-screenshot-2020-10-05-15-49-35-npm-registry-fetch.json
  change/nuget-exe-2020-10-05-15-49-35-npm-registry-fetch.json
  change/react-native-platform-override-2020-10-05-15-49-35-npm-registry-fetch.json
  change/react-native-windows-2020-10-05-15-49-35-npm-registry-fetch.json
  change/react-native-windows-codegen-2020-10-05-15-49-35-npm-registry-fetch.json
  change/react-native-windows-init-2020-10-05-15-49-35-npm-registry-fetch.json
  packages/@react-native-windows/cli/package.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/find-repo-root/package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/@rnw-scripts/just-task/package.json
  packages/@rnw-scripts/package-utils/package.json
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/take-screenshot/package.json
  packages/E2ETest/package.json
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/nuget-exe/package.json
  packages/playground/package.json
  packages/react-native-platform-override/package.json
  packages/react-native-win32/package.json
  packages/react-native-windows-codegen/package.json
  packages/react-native-windows-init/package.json
  vnext/package.json
  yarn.lock
Labels: security

#6185 Remove Insecure Trees of E2ETest Dependencies
  package.json
  packages/appium-android-driver/package.json
  packages/appium-selendroid-driver/package.json
  packages/appium-tizen-driver/package.json
  yarn.lock
Labels: security

#6176 [0.63] Fix native modules not being re-initialized on reload (#6159)
  change/react-native-windows-2020-10-02-23-12-32-HEAD.json
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
Labels: AutoMerge, Backported to 0.63

#6202 Update vnext/Microsoft.ReactNative.Cxx/README.md
  change/react-native-windows-2020-10-07-07-18-23-tm-port.json
  vnext/Microsoft.ReactNative.Cxx/Crash.h
  vnext/Microsoft.ReactNative.Cxx/README.md
Labels: AutoMerge

#6169 Consolidate WebSocket modules
  change/react-native-windows-2020-10-01-20-08-10-ws-consolidate.json
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop/Modules/TimingModule.cpp
  vnext/Desktop/NativeModuleFactories.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/CreateModules.cpp
  vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
  vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.h
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/Shared/CreateModules.h
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: Area: Native Modules, Area: Networking, AutoMerge, Request Backport to 0.62, Request Backport to 0.63

#6222 Fixed missing folly headers on publish
  change/react-native-windows-2020-10-09-13-04-00-folly6212.json
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: Area: Build Infrastructure, AutoMerge

#6229 Update url to `Consts.ts` in `e2e-testing.md`
  docs/e2e-testing.md
Labels: AutoMerge

#6231 [0.62] Fixed templates so C++ apps can consume C# native modules #5851
  change/react-native-windows-2020-10-12-14-52-23-cpp-csharp.json
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
  vnext/PropertySheets/CppAppConsumeCSharpModule.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
Labels: AutoMerge

#6232 Fix project config and package deploy to support the windows code in a different location
  change/@react-native-windows-cli-2020-10-12-16-26-22-master.json
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: Request Backport to 0.63

#6252 Pr revert #6232
  change/@react-native-windows-cli-2020-10-16-09-03-48-master.json
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: AutoMerge

#6241 Update FlyoutViewManager.cpp
  change/react-native-windows-2020-10-16-09-34-05-master.json
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
Labels: AutoMerge

#6265 Improve unittest message to update LKG's
  change/react-native-windows-2020-10-19-09-20-38-master.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGenTestBase.cs
Labels: AutoMerge

#6253 Sync native module functions are wrapping the result in an array, which it shouldn't
  change/react-native-windows-2020-10-16-11-14-51-acoates-syncfuncfix.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--NoParamReturnInt--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--OneParamReturnInt--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ThreeParamReturnInt--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
  vnext/Microsoft.ReactNative.Managed.UnitTests/NoAttributeNativeModuleTest.cs
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative.Managed/ReactSyncMethodInfo.cs
Labels: Breaking Change

#6255 Add win32 as a valid platform to platformcolorexample.win32
  packages/react-native-win32-tester/src/js/examples/PlatformColor/PlatformColorExample.win32.js
Labels: Area: PlatformColor

#6264 Fix switch events
  change/react-native-windows-2020-10-19-13-20-12-fixSwitchEvents.json
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.cpp
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.h
Labels: AutoMerge

#5710 Update Chakra JSI implementation
  change/react-native-windows-2020-08-12-15-53-24-PR-FixChakraJSI.json
  vnext/JSI/Desktop/ChakraJsiRuntime_core.cpp
  vnext/JSI/Shared/ChakraApi.cpp
  vnext/JSI/Shared/ChakraApi.h
  vnext/JSI/Shared/ChakraObjectRef.cpp
  vnext/JSI/Shared/ChakraObjectRef.h
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntime.h
  vnext/JSI/Shared/JSI.Shared.vcxitems
  vnext/JSI/Shared/JSI.Shared.vcxitems.filters
  vnext/JSI/Universal/ChakraJsiRuntime_edgemode.cpp
  vnext/Microsoft.ReactNative.ComponentTests/ChakraEdgeRuntimeTests.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.sln
Labels: AutoMerge

#6256 PlatformColors "backport" to RN-win32 0.62
  change/@office-iss-react-native-win32-2020-10-16-18-56-17-PlatformColorsBackport62.json
  packages/react-native-win32/src/Libraries/StyleSheet/NativeOrDynamicColorType.win32.js
  packages/react-native-win32/src/Libraries/StyleSheet/normalizeColorObject.win32.js
  packages/react-native-win32/src/Libraries/StyleSheet/processColor.win32.js
  packages/react-native-win32/src/Libraries/StyleSheet/processColorObject.win32.js
  packages/react-native-win32/src/RNTester/js/components/PlatformColor.js
  packages/react-native-win32/src/RNTester/js/utils/RNTesterList.win32.ts
  packages/react-native-win32/src/overrides.json
Labels: Area: PlatformColor

#6284 Make native modules to use JS queue
  change/react-native-windows-2020-10-20-09-59-36-FixDefaultJSQueue.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge, Breaking Change

#6285 Fix ReactContext::EmitJSEvent arg passing
  change/react-native-windows-2020-10-20-16-28-00-FixEmitJSEvent.json
  packages/microsoft-reactnative-sampleapps/index.windows.js
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
Labels: AutoMerge, Breaking Change

#6286 Bugfix: Dimensions never fires change events
  change/react-native-windows-2020-10-20-17-25-59-dimsfix.json
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
Labels: Area: DeviceInfo

#6288 Integrate 8/25 Nightly RN Build
  change/@office-iss-react-native-win32-2020-10-21-09-19-32-integrate-8-25.json
  change/@rnw-scripts-integrate-rn-2020-10-21-09-19-32-integrate-8-25.json
  change/react-native-windows-2020-10-21-09-19-32-integrate-8-25.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/PanResponder/PanResponderExample.js
  packages/@react-native/tester/overrides.json
  packages/@react-native/tester/package.json
  packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
  packages/E2ETest/package.json
  packages/IntegrationTest/package.json
  packages/appium-android-driver/package.json
  packages/appium-selendroid-driver/package.json
  packages/appium-tizen-driver/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32-tester/overrides.json
  packages/react-native-win32-tester/package.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/Components/ToastAndroid/ToastAndroid.win32.js
  packages/react-native-win32/src/index.win32.js
  vnext/.flowconfig
  vnext/ReactCopies/IntegrationTests/IntegrationTestHarnessTest.js
  vnext/ReactCopies/IntegrationTests/LoggingTestModule.js
  vnext/ReactCopies/IntegrationTests/SimpleSnapshotTest.js
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/ToastAndroid/ToastAndroid.windows.js
  vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
  vnext/src/index.windows.js
  yarn.lock
Labels: AutoMerge

#6220 Implement focus/blur functionality on Pressable.
  change/react-native-windows-2020-10-08-15-56-54-enable_presaability_onFocus.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
  packages/playground/Samples/view.tsx
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/overrides.json
  vnext/src/Libraries/Components/Pressable/Pressable.windows.js
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Components/TextInput/TextInputState.windows.js
  vnext/src/Libraries/Components/TextInput/WindowsTextInputNativeComponent.js
Labels: Area: Keyboard

#6304 Fix failing unit tests
  change/react-native-windows-2020-10-22-11-54-02-PR-FixUnitTests.json
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#6320 Fix default tab order for ScrollView + a couple other controls
  change/react-native-windows-2020-10-23-00-31-23-taborder-fix.json
  vnext/Microsoft.ReactNative/Views/PickerViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: Keyboard, Area: ScrollView

#6322 [0.62] [Win32] Export createUIManagerModule that takes a uiQueue
  change/react-native-windows-2020-10-23-12-24-25-exportcreateUIMan.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
Labels: Platform: NetUI

#6289 Fix crash during instance destruction if there are outstanding animations
  change/react-native-windows-2020-10-21-11-22-08-animreloadfix.json
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.h
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.h
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
  vnext/Microsoft.ReactNative/Views/ReactRootControl.h
  vnext/Shared/Threading/BatchingQueueThread.cpp
  vnext/Shared/Threading/BatchingQueueThread.h
Labels: Area: Animation, AutoMerge, Request Backport to 0.63

#6323 Don't require elevating when only checking RNW dependencies
  change/react-native-windows-2020-10-23-17-54-31-rnwDepsCheckDontElevate.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#6338 [Win32] Export createUIManagerModule that takes a uiQueue
  change/react-native-windows-2020-10-26-13-35-51-createuiman.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
Labels: AutoMerge

#6333 Move UIManager to use JSI
  change/react-native-windows-2020-10-26-11-56-00-uimanjsi.json
  vnext/Microsoft.ReactNative/INativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/overrides.json
  vnext/src/Libraries/ReactNative/PaperUIManager.windows.js
Labels: AutoMerge

#6336 Fixes for crash on reload
  change/react-native-windows-2020-10-26-12-21-08-animreloadfix2.json
  vnext/Microsoft.ReactNative/INativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Labels: AutoMerge

#6348 Better error handling of Views inside Text components
  change/@office-iss-react-native-win32-2020-10-27-13-09-58-viewintexterrors.json
  change/react-native-windows-2020-10-27-13-09-58-viewintexterrors.json
  packages/@react-native-windows/tester/src/js/components/RNTesterExampleList.windows.js
  packages/react-native-win32/src/Libraries/Components/View/View.win32.js
  packages/react-native-win32/src/Libraries/Image/Image.win32.js
  vnext/.gitignore
  vnext/overrides.json
  vnext/src/Libraries/Components/View/View.windows.js
  vnext/src/Libraries/Image/Image.windows.js
Labels: Area: Text, AutoMerge

#6337 [0.63] [Win32] Export createUIManagerModule that takes a uiQueue
  change/react-native-windows-2020-10-26-13-33-16-uimanager63.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
Labels: AutoMerge, Backported to 0.63

#6344 Allow E2ETest to Work Without Back Button (And lots of cleanup)
  .ado/templates/macos-tests-job.yml
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/Consts.ts
  packages/E2ETest/.eslintrc.js
  packages/E2ETest/run_wdio.js
  packages/E2ETest/wdio.conf.js
  packages/E2ETest/wdio/pages/BasePage.ts
  packages/E2ETest/wdio/pages/HomePage.ts
  packages/E2ETest/wdio/test/DirectManipulation.spec.ts
  packages/E2ETest/wdio/test/Image.spec.ts
  packages/E2ETest/wdio/test/TransformTest.spec.ts
  packages/E2ETest/wdio/test/VisitAllPages.spec.ts
  packages/E2ETest/wdio/test/controlStyle.spec.ts
  packages/E2ETest/wdio/test/login.spec.ts
  packages/E2ETest/wdio/test/testInput.spec.ts
Labels: AutoMerge

#6349 Better Override Validation Messages When Errors Exist in Multiple Packages
  change/react-native-platform-override-2020-10-27-13-13-55-better-monorepo-validation.json
  packages/react-native-platform-override/src/Cli.ts
Labels: AutoMerge

#6340 fix casing for SampleAppCpp pfx file
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp_TemporaryKey.pfx
Labels: AutoMerge

#6356 Integrate Additional RNTester Refactoring (9/2 Nightly RN Build)
  change/@office-iss-react-native-win32-2020-10-28-15-55-28-integrate-9-2.json
  change/react-native-windows-2020-10-28-15-55-28-integrate-9-2.json
  docs/e2e-testing.md
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/RNTesterApp.windows.js
  packages/@react-native-windows/tester/src/js/RNTesterAppShared.windows.js
  packages/@react-native-windows/tester/src/js/components/RNTesterEmptyBookmarksState.windows.js
  packages/@react-native-windows/tester/src/js/components/RNTesterExampleList.windows.js
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/tester/js/RNTesterApp.android.js
  packages/@react-native/tester/js/RNTesterApp.ios.js
  packages/@react-native/tester/js/RNTesterAppShared.js
  packages/@react-native/tester/js/components/ExamplePage.js
  packages/@react-native/tester/js/components/RNTesterBlock.js
  packages/@react-native/tester/js/components/RNTesterEmptyBookmarksState.js
  packages/@react-native/tester/js/components/RNTesterExampleFilter.js
  packages/@react-native/tester/js/components/RNTesterExampleList.js
  packages/@react-native/tester/js/components/RNTesterHeader.js
  packages/@react-native/tester/js/components/RNTesterNavbar.js
  packages/@react-native/tester/js/types/RNTesterTypes.js
  packages/@react-native/tester/js/utils/RNTesterActions.js
  packages/@react-native/tester/js/utils/RNTesterAsyncStorageAbstraction.js
  packages/@react-native/tester/js/utils/RNTesterNavigationReducer.js
  packages/@react-native/tester/js/utils/RNTesterReducer.js
  packages/@react-native/tester/js/utils/URIActionMap.js
  packages/@react-native/tester/js/utils/testerStateUtils.js
  packages/@react-native/tester/js/utils/useAsyncStorageReducer.js
  packages/@react-native/tester/overrides.json
  packages/@react-native/tester/package.json
  packages/E2ETest/package.json
  packages/E2ETest/wdio/pages/BasePage.ts
  packages/E2ETest/wdio/pages/HomePage.ts
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32-tester/overrides.json
  packages/react-native-win32-tester/package.json
  packages/react-native-win32-tester/src/js/RNTesterApp.win32.js
  packages/react-native-win32-tester/src/js/components/ExamplePage.win32.js
  packages/react-native-win32-tester/src/js/components/RNTesterEmptyBookmarksState.win32.js
  packages/react-native-win32-tester/src/js/components/RNTesterExampleFilter.win32.js
  packages/react-native-win32-tester/src/js/utils/RNTesterAsyncStorageAbstraction.win32.js
  packages/react-native-win32-tester/src/js/utils/RNTesterStatePersister.win32.js
  packages/react-native-win32-tester/src/js/utils/testerStateUtils.win32.js
  packages/react-native-win32-tester/src/js/utils/useAsyncStorageReducer.win32.js
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/index.win32.js
  vnext/.flowconfig
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/index.windows.js
  yarn.lock
Labels: AutoMerge

#6366 More Permissive Retry Logic for Verdaccio
  .ado/templates/react-native-init.yml
  .ado/verdaccio/config.yaml
Labels: Area: Test Infrastructure, AutoMerge

#6365 Extend Playground Metro Config to Allow Live Reload of RNTester Changes
  packages/playground/metro.config.js
Labels: AutoMerge

#6357 Removing forked RNTester page which crashes
  packages/@react-native-windows/tester/src/js/examples-win/CustomView/CustomViewExample.windows.tsx
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/E2ETest/wdio/test/VisitAllPages.spec.ts
Labels: Area: Tests, AutoMerge

#6369 Enable Hermes Bytecode Compilation and SourceMap Creation as Part of Build
  .ado/windows-vs-pr.yml
  change/@react-native-windows-cli-2020-10-28-22-25-48-build-hermes-bytecode.json
  change/react-native-windows-2020-10-28-22-25-48-build-hermes-bytecode.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/PropertySheets/Bundle.Common.targets
  vnext/PropertySheets/Bundle.props
  vnext/PropertySheets/JSEngine.props
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#6371 Update Template Metro Config to Enable Inline Requires By Default
  change/react-native-windows-2020-10-29-09-49-44-template-inline-requires.json
  vnext/template/metro.config.js
Labels: AutoMerge

#6385 Integrate 9/17 Nightly RN Build
  change/@office-iss-react-native-win32-2020-10-29-17-44-48-integrate-9-17.json
  change/react-native-windows-2020-10-29-17-44-48-integrate-9-17.json
  package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/Alert/AlertExample.js
  packages/@react-native/tester/js/examples/Alert/AlertIOSExample.js
  packages/@react-native/tester/js/examples/KeyboardAvoidingView/KeyboardAvoidingViewExample.js
  packages/@react-native/tester/js/examples/ToastAndroid/ToastAndroidExample.android.js
  packages/@react-native/tester/overrides.json
  packages/@react-native/tester/package.json
  packages/E2ETest/package.json
  packages/E2ETest/wdio/test/VisitAllPages.spec.ts
  packages/IntegrationTest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32-tester/overrides.json
  packages/react-native-win32-tester/package.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  vnext/.flowconfig
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/Pressable/Pressable.windows.js
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js
  vnext/src/Libraries/Pressability/Pressability.windows.js
  vnext/src/Libraries/Text/Text.windows.js
  yarn.lock
Labels: AutoMerge

#6382 Fix Generator Failing to Overwrite Template Files
  change/@react-native-windows-cli-2020-10-29-15-59-32-fix-inquirer.json
  packages/@react-native-windows/cli/src/generator-common/index.ts
Labels: AutoMerge, Backport to 0.63 Approved

#6378 Eagerly initialize UIManager
  change/react-native-windows-2020-10-29-12-55-29-uimaneager.json
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#6395 Fix desktop publish
  change/react-native-windows-2020-10-30-10-59-47-master.json
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge

#6400 Update V8 and Hermes package versions
  .ado/windows-vs-pr.yml
  change/@react-native-windows-cli-2020-10-30-16-13-52-packageupdate.json
  change/react-native-windows-2020-10-30-15-54-43-packageupdate.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/Bundle.props
  vnext/PropertySheets/JSEngine.props
Labels: AutoMerge
