Repository microsoft/react-native-windows, pull requests merged in 2020-05, with the labels that each got.

#4574 Update mouseEnter/mouseLeave algorithm
  change/react-native-windows-2020-04-10-22-47-43-users-aschultz-hover.json
  packages/playground/Samples/mouse.tsx
  vnext/ReactUWP/Views/TouchEventHandler.cpp
  vnext/ReactUWP/Views/TouchEventHandler.h
Labels: AutoMerge

#4773 Delay load ChakraCore.dll
  change/react-native-windows-2020-05-01-15-34-56-master.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
Labels: AutoMerge, Backport to 0.60, Backport to 0.61, Backport to 0.62

#4767 Implement WinRTWebSocket unit tests
  change/react-native-windows-2020-05-01-15-49-42-wsrc_ut.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/InstanceMocks.h
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.h
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
  vnext/ReactWindowsCore/WinRTWebSocketResource.h
Labels: Area: Test Infrastructure, Area: Tests, AutoMerge

#4780 Delay load ChakraCore.dll (0.61)
  change/react-native-windows-2020-05-01-15-34-56-master.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
Labels: AutoMerge

#4762 Fix appPackage path in deploy.js
  change/react-native-windows-2020-04-30-12-57-06-fix-apppackage-path.json
  vnext/local-cli/runWindows/utils/deploy.js
Labels: AutoMerge, Backport to 0.62

#4788 Treat yes the same as y in template overwrite prompt
  change/react-native-windows-2020-05-05-08-23-01-promptyes.json
  vnext/local-cli/generator-common/index.js
Labels: AutoMerge, Backport to 0.62

#4794 Support --version file:<path> for running init against local changes
  change/react-native-windows-init-2020-05-05-12-50-32-cli.json
  packages/react-native-windows-init/src/Cli.ts
Labels: AutoMerge

#4803 [Trivial] Fix typo in msbuildtools.js
  change/react-native-windows-2020-05-05-22-41-31-msbuilt.json
  vnext/local-cli/runWindows/utils/msbuildtools.js
Labels: AutoMerge

#4805 Disable CxxFrameHandler4
  change/react-native-windows-2020-05-06-05-03-56-no-fh4.json
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge, Backport to 0.62

#4800 Don't bundle during intellisense
  change/react-native-windows-2020-05-05-19-47-51-dontBundleDuringIntellisense.json
  vnext/PropertySheets/Bundle.Common.targets
Labels: AutoMerge

#4790 Ensure WebSocket write lifetime
  change/react-native-windows-2020-05-04-19-05-45-OC-4133953-pwrav.json
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Labels: Area: Networking, Platform: Desktop

#4814 Ensure InitializeCore is run before app code
  change/@office-iss-react-native-win32-2020-05-06-14-34-01-fixfast.json
  change/react-native-windows-2020-05-06-14-34-01-fixfast.json
  packages/E2ETest/metro.config.js
  packages/microsoft-reactnative-sampleapps/metro.config.js
  packages/playground/metro.config.js
  packages/react-native-win32/metro-react-native-platform.js
  packages/react-native-win32/metro.config.js
  vnext/local-cli/generator-windows/templates/metro.config.js
  vnext/metro-react-native-platform.js
  vnext/metro.config.js
Labels: AutoMerge, Backport to 0.62

#4822 The react-native repo was renamed, this fixes the 0.60 branch to handle that
  change/@office-iss-react-native-win32-2020-05-07-09-53-55-renamerepo.json
  change/react-native-windows-2020-05-07-09-53-55-renamerepo.json
  change/react-native-windows-extended-2020-05-07-09-53-55-renamerepo.json
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/package.json
  packages/react-native-windows-extended/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#4818 [0.60] Ensure WebSocket write lifetime
  change/react-native-windows-2020-05-06-21-22-41-OC-4133953-pwrav-60.json
  vnext/Desktop/Modules/WebSocketModule.cpp
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/ReactWindowsCore/Modules/WebSocketModule.h
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
  vnext/ReactWindowsCore/WinRTWebSocketResource.h
Labels: Area: Networking, AutoMerge, Backport to 0.60, Platform: Desktop

#4828 Set C# langversion of templates back to 7.3 from 8.0
  change/react-native-windows-2020-05-07-17-34-52-master.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/SampleAppCS.csproj
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleLibraryCS.csproj
  vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj
Labels: AutoMerge, Breaking Change

#4829 Correct WebSocket binary message tagging
  change/react-native-windows-2020-05-07-18-29-02-enable-binaryws.json
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Labels: Area: Networking, AutoMerge, Backport to 0.60, Backport to 0.61, Backport to 0.62, Platform: Desktop

#4826 Update main README.md
  README.md
Labels: AutoMerge

#4827 Align local metro config with future CLI changes
  change/@office-iss-react-native-win32-2020-05-07-14-18-13-clifeedback.json
  change/react-native-windows-2020-05-07-14-18-13-clifeedback.json
  packages/react-native-win32/metro-react-native-platform.js
  vnext/metro-react-native-platform.js
Labels: AutoMerge

#4831 [0.62] Correct WebSocket binary message tagging
  change/react-native-windows-2020-05-07-18-50-32-enable-binaryws-62.json
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Labels: Area: Networking, AutoMerge, Platform: Desktop

#4830 [0.61] Ensure WebSocket write lifetime
  change/react-native-windows-2020-05-07-18-34-56-OC-4133953-pwrav-61.json
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
Labels: AutoMerge, Platform: Desktop

#4832 Added Microsoft.ReactNative.IntegrationTests project to Microsoft.ReactNative.sln
  change/react-native-windows-2020-05-07-19-10-10-MS.RN.IntegrationTests.json
  vnext/Microsoft.ReactNative.sln
Labels: AutoMerge

#4816 Single Targets for CLI app templates
  change/react-native-windows-2020-05-06-15-51-59-autolinking.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/local-cli/generator-windows/index.js
  vnext/local-cli/generator-windows/templates/cpp/proj-experimental/MyApp.vcxproj
  vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj
  vnext/local-cli/generator-windows/templates/cpp/src/App.cpp
  vnext/local-cli/generator-windows/templates/cpp/src/AutolinkedNativeModules.g.h
  vnext/local-cli/generator-windows/templates/cpp/src/ReactPackageProvider.cpp
  vnext/local-cli/generator-windows/templates/cpp/src/ReactPackageProvider.h
  vnext/local-cli/generator-windows/templates/cpp/src/nativeModules.g.h
  vnext/local-cli/generator-windows/templates/cpp/src/pch.h
  vnext/local-cli/generator-windows/templates/cs/proj/MyApp.csproj
  vnext/local-cli/generator-windows/templates/cs/src/App.xaml.cs
  vnext/local-cli/generator-windows/templates/cs/src/AutolinkedNativeModules.g.cs
  vnext/local-cli/generator-windows/templates/index.windows.bundle
  vnext/local-cli/runWindows/utils/VSProjectUtils.ps1
  vnext/local-cli/runWindows/utils/autolink.js
Labels: Breaking Change

#4837 Ensure Beachball Uses The Right Branch for Experimental NuGet PR Tests
  .ado/windows-vs-pr.yml
Labels: AutoMerge, Backport to 0.62

#4817 Implemented PropertyBag for ReactContext and ReactInstanceSettings
  change/react-native-windows-2020-05-06-20-33-40-MS_PropertyBag.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
  packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/pch.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/pch.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative.SharedManaged/ReactContext.cs
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactPropertyBag.cpp
  vnext/Microsoft.ReactNative/IReactPropertyBag.h
  vnext/Microsoft.ReactNative/IReactPropertyBag.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/NoExceptionAttribute.idl
  vnext/Microsoft.ReactNative/ReactHost/PropertyBag.cpp
  vnext/Microsoft.ReactNative/ReactHost/PropertyBag.h
  vnext/Microsoft.ReactNative/ReactHost/PropertyBag_internal.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Mso/crash/verifyElseCrash.h
  vnext/ReactWindows-Desktop.sln
Labels: AutoMerge, Backport to 0.62

#4824 Update vnext README.md for v0.62-stable branch only
  vnext/README.md
Labels: AutoMerge

#4840 Reenable V8 for desktop projects
  change/react-native-windows-2020-05-08-14-17-35-master.json
  packages/E2ETest/windows/ReactUWPTestApp.sln
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground.sln
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactUWP/ReactUWP.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/ReactWindowsCore/ReactWindowsCore.vcxitems
  vnext/Shared/Shared.vcxitems
  vnext/Universal.UnitTests/React.Windows.Universal.UnitTests.vcxproj
  vnext/V8Inspector/V8Inspector.vcxproj
  vnext/V8Inspector/V8Inspector.vcxproj.filters
Labels: AutoMerge, Needs: Author Feedback

#4750 Fire onLoad event when a bitmap image is opened
  change/react-native-windows-2020-04-29-15-37-41-imageonload.json
  vnext/ReactUWP/Views/Image/ReactImage.cpp
  vnext/ReactUWP/Views/Image/ReactImage.h
Labels: AutoMerge

#4870 Fixed ReactContext copy/move semantic
  change/react-native-windows-2020-05-11-11-06-42-FixReactContext.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/pch.h
Labels: AutoMerge, Backport to 0.62

#4873 Use spec file for DevSettings NativeModule
  change/react-native-windows-2020-05-11-13-26-08-devsettingsspec.json
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.cpp
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#4884 Allow storing non-WinRT types in ReactPropertyBag
  change/react-native-windows-2020-05-12-18-57-59-UnsafePropertyId.json
  vnext/Microsoft.ReactNative.Cxx/BoxedValue.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
Labels: AutoMerge, Backport to 0.62

#4877 Use DispatcherQueue instead of CoreDispatcher for Mso::DispatchQueue
  change/react-native-windows-2020-05-12-11-18-16-MS_UIQueue.json
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
  packages/playground/windows/playground-win32.sln
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/AppStateData.cpp
  vnext/Microsoft.ReactNative/Modules/AppStateData.h
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/RedBox.h
  vnext/Microsoft.ReactNative/RedBoxHandler.cpp
  vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.cpp
  vnext/Mso/dispatchQueue/dispatchQueue.h
  vnext/Mso/src/dispatchQueue/queueService.cpp
  vnext/Mso/src/dispatchQueue/queueService.h
  vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
  vnext/ReactUWP/Base/UwpReactInstance.cpp
  vnext/ReactUWP/Modules/AppearanceModule.cpp
  vnext/ReactUWP/Modules/AppearanceModule.h
  vnext/ReactUWP/ReactUWP.vcxproj.filters
Labels: AutoMerge, Backport to 0.62

#4876 RNW dependencies
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-05-11-17-22-16-rnw-dependencies.json
  docs/building-rnw.md
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge, Developer First Experience

#4893 BugFix: fix default tabindex stomping over acceptsKeyboardFocus
  change/react-native-windows-2020-05-13-12-47-43-tabfocus-fix.json
  vnext/ReactUWP/Views/ControlViewManager.cpp
  vnext/ReactUWP/Views/ViewViewManager.cpp
Labels: Backport to 0.62

#4894 Update rnw-dependencies
  change/react-native-windows-2020-05-13-14-16-07-rnw-dep-dontexit.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#4883 ViewWin32 Accessibility: labeledBy, describedBy
  change/@office-iss-react-native-win32-2020-05-12-21-44-51-accessibilityLabeledBy.json
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
  packages/react-native-win32/src/Libraries/Components/View/Tests/ViewWin32Test.tsx
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Labels: Area: Accessibility, Backport to 0.62

#4891 Remove unused life cycle event callbacks in ReactNativeHost
  change/react-native-windows-2020-05-13-12-53-42-remove-unused-lifecycle-events.json
  vnext/Microsoft.ReactNative/ReactApplicationDelegate.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.h
  vnext/Microsoft.ReactNative/ReactNativeHost.idl
Labels: AutoMerge, Backport to 0.62

#4896 Fix Playground app crash on instance load
  packages/playground/windows/playground/MainPage.cpp
Labels: AutoMerge

#4898 Move Microsoft.ReactNative pch files in a Pch subfolder
  change/react-native-windows-2020-05-13-17-33-52-Move_pch.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Pch/pch.cpp
  vnext/Microsoft.ReactNative/Pch/pch.h
Labels: AutoMerge

#4905 Install exact version of WinAppDriver
  change/react-native-windows-2020-05-14-00-25-43-rnw-dep-winappdriver.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#4910 Some projects have target instead of bin folders
  change/react-native-windows-2020-05-14-13-47-03-4881.json
  vnext/local-cli/runWindows/utils/deploy.js
Labels: Backport to 0.62

#4914 JustMyXaml.ps1
  change/react-native-windows-2020-05-15-03-01-54-justMyXaml.json
  vnext/Scripts/JustMyXaml.ps1
Labels: AutoMerge

#4895 Move playground-win32 to Microsoft.ReactNative
  packages/playground/index.js
  packages/playground/just-task.js
  packages/playground/package.json
  packages/playground/windows/.gitignore
  packages/playground/windows/playground-win32.sln
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
Labels: AutoMerge

#4911 ReactNonAbiValue for IReactPropertyBag non-ABI values
  change/react-native-windows-2020-05-14-17-22-55-NonAbiValues.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx/BoxedValue.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Cxx/ReactNonAbiValue.h
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNonAbiValueTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/pch.h
  vnext/Microsoft.ReactNative/IBoxedValue.idl
  vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Mso/motifCpp/testCheck.h
Labels: AutoMerge, Backport to 0.62

#4922 Fixed ReactContext CallJSFunction and EmitJSEvent
  change/react-native-windows-2020-05-15-21-43-34-MS_FixReactContext2.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
Labels: AutoMerge, Backport to 0.62

#4931 Ensure Override Prompts Create Integral Issue Numbers
  packages/override-tools/src/OverridePrompt.ts
Labels: AutoMerge

#4929 Add support for 0..n args in native module callbacks
  change/react-native-windows-2020-05-17-09-26-39-MS_CallbackMultiArgs.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs
  vnext/Microsoft.ReactNative.Managed.UnitTests/NoAttributeNativeModuleTest.cs
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative.SharedManaged/JSValueGenerator.cs
  vnext/Microsoft.ReactNative.SharedManaged/ReactMethodInfo.cs
Labels: AutoMerge, Backport to 0.62

#4919 Fixes for bundle loading and back handler crash using xaml islands
  change/react-native-windows-2020-05-15-12-40-09-fixbackhandler.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
  vnext/ReactUWP/Pch/pch.h
  vnext/ReactUWP/Utils/Helpers.cpp
  vnext/ReactUWP/Utils/LocalBundleReader.cpp
  vnext/include/ReactUWP/Utils/Helpers.h
Labels: AutoMerge, Backport to 0.62

#4937 Fix compile errors with Clang 10.0.0
  change/react-native-windows-2020-05-18-02-05-00-chpurrer-rnw-clang-fixes.json
  vnext/Microsoft.ReactNative.Cxx/JSValue.h
  vnext/ReactUWP/Utils/ValueUtils.cpp
Labels: AutoMerge, Backport to 0.62

#4932 Adapt ViewWin32, etc to "accessibilityState"
  change/@office-iss-react-native-win32-2020-05-17-11-50-30-no-acc-states-32.json
  change/react-native-windows-2020-05-17-11-50-30-no-acc-states-32.json
  packages/E2ETest/app/AccessibilityTestPage.tsx
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/docs/api/react-native-win32.accessibilitystate.md
  packages/react-native-win32/docs/api/react-native-win32.accessibilitystates.md
  packages/react-native-win32/docs/api/react-native-win32.basepropswin32.md
  packages/react-native-win32/docs/api/react-native-win32.buttonwin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.buttonwin32.render.md
  packages/react-native-win32/docs/api/react-native-win32.ibuttonwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.idimensions.md
  packages/react-native-win32/docs/api/react-native-win32.inativekeyboardevent.md
  packages/react-native-win32/docs/api/react-native-win32.ipersonacoinprops.md
  packages/react-native-win32/docs/api/react-native-win32.iposition.md
  packages/react-native-win32/docs/api/react-native-win32.ipressinlocation.md
  packages/react-native-win32/docs/api/react-native-win32.irespondersyntheticevent.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itouchablewin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itouchablewin32state.md
  packages/react-native-win32/docs/api/react-native-win32.itouchinfo.md
  packages/react-native-win32/docs/api/react-native-win32.iviewwin32.md
  packages/react-native-win32/docs/api/react-native-win32.iviewwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.md
  packages/react-native-win32/docs/api/react-native-win32.omittedaccessibilitypropswin32.md
  packages/react-native-win32/docs/api/react-native-win32.textwin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.textwin32.render.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.componentwillunmount.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.render.md
  packages/react-native-win32/docs/api/react-native-win32.viewwin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.viewwin32.focus.md
  packages/react-native-win32/docs/api/react-native-win32.viewwin32.md
  packages/react-native-win32/docs/api/react-native-win32.viewwin32.render.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/Components/Button/ButtonWin32.tsx
  packages/react-native-win32/src/Libraries/Components/Text/TextWin32.tsx
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
  packages/react-native-win32/src/RNTester/APIExamples/AccessibilityExampleWin32.tsx
  vnext/package.json
  yarn.lock
Labels: AutoMerge, Backport to 0.62

#4938 Publish 0.61 as "v0.61-stable" instead of "latest"
  change/@office-iss-react-native-win32-2020-05-18-08-22-44-61-no-latest.json
  change/react-native-windows-2020-05-18-08-22-44-61-no-latest.json
  packages/react-native-win32/package.json
  vnext/package.json
Labels: AutoMerge

#4939 Reduce the changes in our custom metro config
  change/@office-iss-react-native-win32-2020-05-18-09-46-04-metrofix.json
  change/react-native-windows-2020-05-18-09-46-04-metrofix.json
  packages/E2ETest/metro.config.js
  packages/microsoft-reactnative-sampleapps/metro.config.js
  packages/playground/metro.config.js
  packages/react-native-win32/metro.config.js
  packages/react-native-win32/react-native.config.js
  vnext/local-cli/generator-windows/templates/metro.config.js
  vnext/metro-react-native-platform.js
  vnext/metro.config.js
  vnext/react-native.config.js
  yarn.lock
Labels: AutoMerge, Backport to 0.62

#4930 Implement Keyboarding/Gamepad Activation for Pressability
  change/react-native-windows-2020-05-17-10-26-45-pressability-kbd.json
  vnext/src/Libraries/Pressability/Pressability.windows.js
  vnext/src/overrides.json
Labels: AutoMerge, Backport to 0.62

#4947 Update the react-native-windows-init template to use the managed library the default (instead of the shared csproj file).
  change/react-native-windows-2020-05-18-17-40-44-master.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/local-cli/generator-windows/templates/cs/proj/MyApp.sln
  vnext/local-cli/generator-windows/templates/cs/src/App.xaml.cs
Labels: Backport to 0.62

#4953 ReactNotificationService to allow communication between native modules
  change/react-native-windows-2020-05-19-13-43-33-MS_Notifications.json
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx.UnitTests/pch.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactDispatcher.h
  vnext/Microsoft.ReactNative.Cxx/ReactHandleHelper.h
  vnext/Microsoft.ReactNative.Cxx/ReactNotificationService.h
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/IReactNotificationService.cpp
  vnext/Microsoft.ReactNative/IReactNotificationService.h
  vnext/Microsoft.ReactNative/IReactNotificationService.idl
  vnext/Microsoft.ReactNative/IReactPropertyBag.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
Labels: AutoMerge, Needs: Triage :mag:, Request Backport

#4958 Work around regression in app packaging in VS 16.5-16.6
  change/react-native-windows-2020-05-20-12-14-56-certVS.json
  vnext/local-cli/runWindows/utils/Add-AppDevPackage.ps1
  vnext/local-cli/runWindows/utils/deploy.js
Labels: Backport to 0.62

#4957 Fix a crash when setting border/foreground color on TextInput (#4708)
  change/react-native-windows-2020-04-24-14-23-47-fix-textinput-brush-update.json
  vnext/ReactUWP/Utils/ResourceBrushUtils.cpp
Labels: AutoMerge

#4962 Fixed Microsoft.ReactNative build in VS 16.6.0
  change/react-native-windows-2020-05-20-21-06-50-MS_FixVS16_6_build.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#4964 Fix animation bug
  change/react-native-windows-2020-05-21-00-35-00-animation-bug.json
  vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp
Labels: Backport to 0.62

#4971 Update CI pipeline to upload msbuild binary log file
  .ado/templates/react-native-init.yml
  .gitignore
Labels: AutoMerge

#4965 Add preprocess target to M.RN and missing deploy target in playground, don't overwrite msbuild.binlog on deploy
  .gitignore
  change/react-native-windows-2020-05-21-08-23-39-preProcessTarget.json
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/playground/windows/playground/Playground.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/local-cli/runWindows/utils/msbuildtools.js
Labels: AutoMerge

#4970 Fix spacing and extra dot in copyright of the property sheets
  change/react-native-windows-2020-05-21-09-08-39-master.json
  vnext/PropertySheets/Bundle.Common.targets
  vnext/PropertySheets/Bundle.Cpp.targets
  vnext/PropertySheets/Bundle.props
  vnext/PropertySheets/Bundle.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/ReactPatches.targets
Labels: AutoMerge

#4984 Drop LazyDevSupportManager
  change/react-native-windows-2020-05-21-16-49-04-dsmwinrt.json
  vnext/Desktop/DevSupportManager.cpp
  vnext/Desktop/DevSupportManager.h
  vnext/Desktop/LazyDevSupportManager.cpp
  vnext/Desktop/LazyDevSupportManager.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
Labels: AutoMerge, Backport to 0.60, Backport to 0.61, Backport to 0.62, Platform: Desktop

#4983 App projects only builds from clean (i.e. the first time only)
  change/react-native-windows-2020-05-21-16-35-04-doubleBuild.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/local-cli/runWindows/utils/deploy.js
Labels: AutoMerge

#4980 Implemented support for native module std::weak_ptr
  change/react-native-windows-2020-05-21-13-01-25-WeakModule.json
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: AutoMerge

#4986 Fix ReactInstance error state to avoid crashes
  change/react-native-windows-2020-05-21-22-04-55-PR-FixInstanceLoading.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
Labels: AutoMerge, Backport to 0.62

#4994 Remove unneeded or undesirable eslint suppressions
  packages/E2ETest/.eslintignore
  packages/E2ETest/app/ControlStyleTestPage.tsx
  packages/E2ETest/app/DirectManipulationPage.tsx
  packages/E2ETest/app/ImageTestPage.tsx
  packages/E2ETest/app/TestApp.tsx
  packages/E2ETest/app/TextInputTestPage.tsx
  packages/E2ETest/app/TransformTestPage.tsx
  packages/E2ETest/app/UnknownPage.tsx
  packages/E2ETest/wdio.conf.js
  packages/E2ETest/wdio/pages/BasePage.ts
  packages/microsoft-reactnative-sampleapps/.eslintignore
Labels: AutoMerge

#4993 Rename override-tools to react-native-platform-override
  .gitignore
  change/@office-iss-react-native-win32-2020-05-25-08-45-02-rename-override-tools.json
  change/react-native-platform-override-2020-05-25-08-45-02-rename-override-tools.json
  change/react-native-windows-2020-05-25-08-45-02-rename-override-tools.json
  packages/override-tools/src/ReactVersion.ts
  packages/react-native-platform-override/.eslintignore
  packages/react-native-platform-override/.eslintrc.js
  packages/react-native-platform-override/.gitignore
  packages/react-native-platform-override/.vscode/launch.json
  packages/react-native-platform-override/babel.config.js
  packages/react-native-platform-override/bin.js
  packages/react-native-platform-override/jest.config.js
  packages/react-native-platform-override/just-task.js
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/ActionQueue.ts
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/CrossProcessLock.ts
  packages/react-native-platform-override/src/FileRepository.ts
  packages/react-native-platform-override/src/FileSearch.ts
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  packages/react-native-platform-override/src/Manifest.ts
  packages/react-native-platform-override/src/ManifestData.ts
  packages/react-native-platform-override/src/OverrideFileRepositoryImpl.ts
  packages/react-native-platform-override/src/OverridePrompt.ts
  packages/react-native-platform-override/src/OverrideUpgrader.ts
  packages/react-native-platform-override/src/PackageUtils.ts
  packages/react-native-platform-override/src/scripts/generateManifest.ts
  packages/react-native-platform-override/src/scripts/hashFile.ts
  packages/react-native-platform-override/src/scripts/testLocks.ts
  packages/react-native-platform-override/src/test/Manifest.test.ts
  packages/react-native-platform-override/src/test/ManifestData.test.ts
  packages/react-native-platform-override/src/test/MockFileRepository.ts
  packages/react-native-platform-override/tsconfig.json
  packages/react-native-win32/package.json
  vnext/.gitignore
  vnext/package.json
Labels: AutoMerge

#5006 Create Microsoft.ReactNative.ComponentTests.vcxproj
  change/react-native-windows-2020-05-25-15-09-09-pull_request.json
  vnext/Microsoft.ReactNative.ComponentTests/DynamicReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
  vnext/Microsoft.ReactNative.ComponentTests/PropertySheet.props
  vnext/Microsoft.ReactNative.ComponentTests/main.cpp
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/pch/pch.cpp
  vnext/Microsoft.ReactNative.ComponentTests/pch/pch.h
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#4979 Allow developers to independently set hostname and port.
  change/react-native-windows-2020-05-21-13-07-11-independent_hostname_and_port.json
  packages/microsoft-reactnative-sampleapps/codegen/NativeMyModuleSpec.g.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/include/ReactUWP/IReactInstance.h
Labels: AutoMerge

#5007 Add UIDispatcher property to ReactInstanceSettings and IReactContext
  change/react-native-windows-2020-05-25-15-56-21-PR-UIDispatcherProperty.json
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground/MainPage.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/ReactInstanceSettingsTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/NativeModulesProvider.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.cpp
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
  vnext/Mso/dispatchQueue/dispatchQueue.h
  vnext/Mso/src/dispatchQueue/queueService.cpp
  vnext/Mso/src/dispatchQueue/queueService.h
  vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
Labels: AutoMerge

#4982 Fix loading SampleAppCpp in VS 16.6.0
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
Labels: AutoMerge, Backport to 0.62

#5009 Create JSI implementation for IJSValueReader and IJSValueWriter
  change/react-native-windows-2020-05-26-13-47-12-pull_request.json
  vnext/Microsoft.ReactNative/JsiReader.cpp
  vnext/Microsoft.ReactNative/JsiReader.h
  vnext/Microsoft.ReactNative/JsiWriter.cpp
  vnext/Microsoft.ReactNative/JsiWriter.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#5027 Obtain Google Test Adapter path dynamically
  .ado/variables/vs2019.yml
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5030 Remove unused ABI definitions
  change/react-native-windows-2020-05-27-15-53-06-PR-CleanupABI.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative/IBackgroundEventListener.idl
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/ILifecycleEventListener.idl
  vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
  vnext/Microsoft.ReactNative/LifecycleState.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/NoExceptionAttribute.idl
  vnext/Microsoft.ReactNative/ReactInstance.cpp
  vnext/Microsoft.ReactNative/ReactInstance.h
  vnext/Microsoft.ReactNative/ReactInstance.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.h
Labels: AutoMerge

#5032 Build ChakraRuntime in ComponentTests with one test case
  change/react-native-windows-2020-05-28-02-27-55-pull_request.json
  vnext/Microsoft.ReactNative.ComponentTests/JsiReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/JsiReader.cpp
Labels: AutoMerge

#5037 Update shared props to have csc emit absolute paths on errors and warnings
  change/react-native-windows-2020-05-28-09-47-11-master.json
  vnext/Directory.Build.props
Labels: AutoMerge

#5045 Add support for long paths to rnw-dependencies.ps1
  change/react-native-windows-2020-05-28-13-51-33-longpaths.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Developer First Experience

#5034 Adds a XamlUIService property to IReactContext, which exposes ElementFromTag
  change/react-native-windows-2020-05-28-08-10-23-elementFromTag.json
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/XamlUIService.cpp
  vnext/Microsoft.ReactNative/XamlUIService.h
  vnext/Microsoft.ReactNative/XamlUIService.idl
Labels: AutoMerge, Backport to 0.62

#5012 Remove ReactWindowsCore projects
  .ado/templates/prepare-env.yml
  .ado/templates/react-native-init.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-05-26-19-03-03-fixcommon.json
  docs/project-structure.md
  packages/E2ETest/windows/ReactUWPTestApp.sln
  packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
  packages/playground/windows/playground-win32.sln
  packages/playground/windows/playground.sln
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop/ABI/MessageQueueShim.h
  vnext/Desktop/Modules/WebSocketModule.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/Directory.Build.targets
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/PropertySheets/ReactDirectories.props
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactUWP/Base/CoreUIManagers.cpp
  vnext/ReactWindows-Desktop.sln
  vnext/ReactWindows-Universal.sln
  vnext/ReactWindowsCore/Modules/AsyncStorageModuleWin32.cpp
  vnext/ReactWindowsCore/Pch/pch.cpp
  vnext/ReactWindowsCore/Pch/pch.h
  vnext/ReactWindowsCore/README.md
  vnext/ReactWindowsCore/ReactWindowsCore-Desktop.vcxproj
  vnext/ReactWindowsCore/ReactWindowsCore-Desktop.vcxproj.filters
  vnext/ReactWindowsCore/ReactWindowsCore.vcxitems
  vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
  vnext/ReactWindowsCore/ReactWindowsCore.vcxproj.filters
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
  vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
  vnext/ReactWindowsCore/packages.config
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Test/React.Windows.Test.vcxproj
  vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.sln
  vnext/local-cli/generator-windows/templates/cs/proj/MyApp.sln
Labels: AutoMerge, Backport to 0.62

#5042 Fixes CLI C# app not deploying
  change/react-native-windows-2020-05-28-13-03-51-issue5041.json
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
Labels: AutoMerge

#5046 Add test cases for (Dynamic|Jsi)(Reader|Writer)
  change/react-native-windows-2020-05-28-14-57-30-pull_request.json
  vnext/Microsoft.ReactNative.ComponentTests/CommonReaderTest.h
  vnext/Microsoft.ReactNative.ComponentTests/DynamicReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/JsiReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
Labels: AutoMerge

#5050 Block all ProjectImports.zip files
  change/react-native-windows-2020-05-28-23-34-14-projectImports.json
  packages/E2ETest/metro.config.js
  packages/microsoft-reactnative-sampleapps/metro.config.js
  packages/playground/metro.config.js
  vnext/local-cli/generator-windows/templates/metro.config.js
Labels: AutoMerge

#5056 Docs CI
  .github/workflows/docs.yml
  .unbroken_exclusions
  change/react-native-windows-2020-05-29-11-44-59-docsCI.json
  docs/building-rnw.md
  docs/e2e-testing.md
  packages/playground/README.md
  vnext/proposals/readme.md
Labels: AutoMerge
