Repository microsoft/react-native-windows, pull requests merged in 2020-11, with the labels that each got.

#6408 Add ReactNativeHost::FromContext method
  change/react-native-windows-2020-11-02-10-56-27-PR-ReactNativeHostFromContext.json
  packages/microsoft-reactnative-sampleapps/index.windows.js
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.cpp
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.h
  vnext/Microsoft.ReactNative/ReactNativeHost.idl
Labels: AutoMerge

#6409 Fix one more file that was moved for Nuget Packing of Win32 version or RNW
  change/react-native-windows-577ea17d-36ca-43ab-af0f-ad8fc3785587.json
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge

#6381 Update Microsoft.ReactNative Nuget Package to support layout convention
  .ado/templates/prep-and-pack-nuget.yml
  change/react-native-windows-2020-10-30-11-37-43-master.json
  vnext/Scripts/Microsoft.ReactNative.nuspec
  vnext/Scripts/Microsoft.ReactNative.targets
  vnext/Scripts/PublishNugetPackagesLocally.cmd
  vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
Labels: AutoMerge, Backport to 0.63 Approved

#6415 [main] Set `Content-Length` on the content object and not on the request.
  change/react-native-windows-31052f2c-0c3c-42b8-9716-47c62e1560ff.json
  vnext/Shared/Modules/NetworkingModule.cpp
Labels: Area: Networking, Request Backport to 0.63

#6375 Autolinking fixes for C++ / C# interop
  change/@react-native-windows-cli-2020-10-29-10-43-34-autolinkingfixes.json
  change/react-native-windows-2020-10-29-10-43-34-autolinkingfixes.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/e2etest/dependencyConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projects/BlankApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/BlankLib/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/MissingProjectFilesApp/.gitignore
  packages/@react-native-windows/cli/src/e2etest/projects/MissingProjectFilesApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/MissingProjectFilesLib/.gitignore
  packages/@react-native-windows/cli/src/e2etest/projects/MissingProjectFilesLib/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpApp/.gitignore
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpLib/.gitignore
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpLib/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppApp/.gitignore
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppLib/.gitignore
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppLib/react-native.config.js
  packages/@react-native-windows/cli/src/generator-common/index.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
  vnext/template/cpp-app/proj/MyApp.sln
  vnext/template/cpp-lib/proj/MyLib.sln
  vnext/template/cs-app/src/AutolinkedNativeModules.g.targets
  vnext/template/shared-app/src/AutolinkedNativeModules.g.props
  vnext/template/shared-app/src/AutolinkedNativeModules.g.targets
Labels: Request Backport to 0.63

#6427 [Fix PR] Update dependencies script to support new ADO images that don't have node 12
  change/react-native-windows-30ac28be-eaef-4db2-a499-f51829f1b87d.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Blocking

#6429 Don't return an error if AsyncStorage is empty
  change/react-native-windows-a9e67774-3a7f-4de3-94c2-855154ee0ce1.json
  vnext/Shared/AsyncStorage/AsyncStorageManager.cpp
Labels: AutoMerge

#6417 [0.63] Update Microsoft.ReactNative Nuget Package to support layout convention (#6381)
  .ado/templates/prep-and-pack-nuget.yml
  change/react-native-windows-3211a5cf-8ed3-47dd-bfa1-8c52882632ea.json
  vnext/Scripts/Microsoft.ReactNative.nuspec
  vnext/Scripts/Microsoft.ReactNative.targets
  vnext/Scripts/PublishNugetPackagesLocally.cmd
  vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
Labels: AutoMerge

#6421 fix(cli): Also look for .msix* extensions in CheckIfNeedInstallCertificate
  change/@react-native-windows-cli-7e62c157-c852-4a1e-b408-b1215790f7c6.json
  packages/@react-native-windows/cli/powershell/WindowsStoreAppUtils.ps1
Labels: AutoMerge

#6432 [0.62] Fix word-wrapping behavior of tooltips (#5626)
  change/react-native-windows-2020-08-03-16-13-47-tooltip.json
  vnext/ReactUWP/Views/FrameworkElementViewManager.cpp
Labels: AutoMerge

#6440 Couple of minor cleanups to prep for fabric PR
  change/react-native-windows-13d3f266-3409-4395-82e7-f7c21b7c4bb3.json
  vnext/Microsoft.ReactNative/Base/CoreUIManagers.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/ReactRootViewTagGenerator.cpp
  vnext/Microsoft.ReactNative/Modules/ReactRootViewTagGenerator.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/Views/PaperShadowNode.cpp
  vnext/Microsoft.ReactNative/Views/PaperShadowNode.h
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
  vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.cpp
  vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.h
  vnext/Microsoft.ReactNative/XamlUIService.h
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#6399 Fix Bundling With "react-native-windows-init --useDevMode"
  change/@react-native-windows-cli-59008ac8-ff8a-45af-a889-1ef869803be6.json
  change/react-native-windows-0e3c72b2-c464-4a57-a02c-e8c1f3ee5830.json
  change/react-native-windows-init-d324dc3a-e64d-44b2-9227-76b94e4a1bbd.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/index.ts
  packages/react-native-windows-init/src/Cli.ts
  vnext/template/metro.devMode.config.js
Labels: Area: CLI, Area: Infrastructure

#6414 [0.63] Set Content-Length on the content object and not on the request itself.
  change/react-native-windows-2020-11-03-18-19-29-fix-content-length.json
  vnext/Microsoft.ReactNative/Modules/NetworkingModule.cpp
Labels: Area: Networking, Backport to 0.63 Approved

#6439 Add Code for New Static Option to Land
  change/react-native-windows-e0894da0-63cd-4dd0-8f68-3824a8f6adc8.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: Area: Layout

#6449 Fix PR validation by removing legacy ImageStore generated header file
  change/react-native-windows-24e648a9-d852-4f73-acd2-072a0f126666.json
  vnext/codegen/NativeImageStoreSpec.g.h
Labels: AutoMerge, Blocking

#6450 [CLI] Make comparison of microsoft.com domain case-insensitive for telemetry purposes
  change/@react-native-windows-telemetry-ae35bf38-2b39-4a08-b826-5a527b3b8301.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
Labels: AutoMerge

#6443 [0.63] 0.63 telemetry
  change/@react-native-windows-cli-2020-11-05-19-40-34-0.63-tel.json
  change/@react-native-windows-telemetry-18092441-4faf-4502-b6f2-f37568184ca5.json
  change/@react-native-windows-telemetry-8939f9d3-227e-4c1d-a8ff-77767de329e4.json
  change/@react-native-windows-telemetry-a669eadd-47ff-43ed-a809-893ce003b71e.json
  packages/@react-native-windows/cli/README.md
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/index.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/build.ts
  packages/@react-native-windows/telemetry/.eslintrc.js
  packages/@react-native-windows/telemetry/.gitignore
  packages/@react-native-windows/telemetry/.vscode/launch.json
  packages/@react-native-windows/telemetry/CHANGELOG.json
  packages/@react-native-windows/telemetry/CHANGELOG.md
  packages/@react-native-windows/telemetry/README.md
  packages/@react-native-windows/telemetry/jest.config.js
  packages/@react-native-windows/telemetry/just-task.js
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/index.ts
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
  packages/@react-native-windows/telemetry/tsconfig.json
  packages/react-native-windows-init/README.md
  packages/react-native-windows-init/package.json
  packages/react-native-windows-init/src/Cli.ts
  yarn.lock
Labels: Area: CLI, AutoMerge, Backport to 0.63 Approved

#6472 Exclude ProjectImports in devmode too
  change/react-native-windows-2020-11-09-12-08-16-devmodeMetro.json
  vnext/template/metro.devMode.config.js
Labels: AutoMerge

#6451 Fix TextInput not rendering sometimes
  change/react-native-windows-9310cb02-467c-4f9a-9aae-0d74ea7dc001.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: Tests, Area: TextInput, AutoMerge

#6467 [0.63] Delay-create the connection to appinsights
  change/@office-iss-react-native-win32-2020-11-09-16-13-57-silenceWarn-0.63.json
  change/@react-native-windows-cli-2020-11-09-15-42-22-silenceWarn-0.63.json
  change/@react-native-windows-telemetry-2020-11-09-09-55-24-silenceWarn-0.63.json
  change/react-native-windows-2020-11-09-16-13-57-silenceWarn-0.63.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/index.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/checkRequirements.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/index.ts
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/UpgradeStrategy.ts
  packages/react-native-platform-override/src/e2etest/Resource.ts
  packages/react-native-platform-override/src/test/Override.test.ts
  packages/react-native-win32/src/RNTester/js/examples/ColorGradientWin32Example.js
  packages/react-native-windows-codegen/package.json
  packages/react-native-windows-codegen/src/generators/GenerateNM2.ts
  packages/react-native-windows-init/package.json
  packages/react-native-windows-init/src/Cli.ts
  vnext/package.json
  vnext/src/IntegrationTests/AsyncStorageTest.windesktop.js
  vnext/src/IntegrationTests/XHRTest.js
  vnext/src/Libraries/Components/Flyout/Flyout.tsx
  vnext/src/Libraries/Components/Keyboard/KeyboardExt.tsx
  vnext/src/Libraries/Components/Popup/Popup.tsx
  vnext/src/Libraries/Lists/VirtualizedList.windows.js
  vnext/src/babel-plugin-inline-view-configs/GenerateViewConfigJs.js
  yarn.lock
Labels: AutoMerge

#6454 Lerna to Lage
  .ado/windows-vs-pr.yml
  change/@office-iss-react-native-win32-b6e6b91d-6be6-4582-8236-fb188990947b.json
  change/react-native-windows-813421fe-dc52-4223-bdd2-9c306e22c541.json
  docs/building-rnw.md
  docs/monorepo.md
  lage.config.js
  package.json
  packages/E2ETest/.eslintignore
  packages/E2ETest/just-task.js
  packages/E2ETest/package.json
  packages/E2ETest/tsconfig.json
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/react-native-win32/just-task.js
  vnext/just-task.js
  yarn.lock
Labels: AutoMerge

#6457 Delay-create the connection to appinsights
  change/@react-native-windows-cli-1f2b01ad-b55e-4589-b852-101ea9e81fe5.json
  change/@react-native-windows-telemetry-2020-11-09-01-02-17-silenceWarnAI.json
  change/react-native-windows-init-c8db854d-d6e4-49a8-a3bd-c5fe0ed5427b.json
  packages/@react-native-windows/cli/src/index.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/telemetry/src/index.ts
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
  packages/react-native-windows-init/src/Cli.ts
Labels: Area: CLI

#6476 Remove Build-Time Native Code Patching
  change/react-native-windows-59c1a8ab-a48e-4162-ab06-4c9058186ad8.json
  vnext/DeforkingPatches/README.md
  vnext/Directory.Build.props
  vnext/Microsoft.ReactNative.sln
  vnext/PropertySheets/Autolink.targets
  vnext/PropertySheets/React.Cpp.props
  vnext/PropertySheets/ReactPatches.targets
  vnext/ReactCommon/.clang-format
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/Yoga.cpp
  vnext/Scripts/Tfs/Layout-Headers.ps1
  vnext/overrides.json
Labels: Area: Build Infrastructure, AutoMerge

#6491 [0.63] Backport async storage inconsistency fix
  change/react-native-windows-a9e67774-3a7f-4de3-94c2-855154ee0ce1.json
  vnext/Shared/AsyncStorage/AsyncStorageManager.cpp
Labels: Backport to 0.63 Approved

#6376 Fixing CG issues with kind-of
  package.json
  yarn.lock
Labels: AutoMerge, Backport to 0.63 Approved

#6383 Add Component Governance Detection to ADO pipelines
  .ado/publish.yml
  .ado/windows-vs-pr.yml
Labels: Backport to 0.63 Approved

#6502 Replace WinAppDriver 1.2.1 with WinAppDriver 1.1
  .ado/templates/e2e-test-job.yml
Labels: Request Backport to 0.62, Request Backport to 0.63

#6504 Added missing autolink props files for app projects
  packages/E2ETest/windows/ReactUWPTestApp/AutolinkedNativeModules.g.props
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/AutolinkedNativeModules.g.props
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/AutolinkedNativeModules.g.props
  packages/playground/windows/playground-win32/AutolinkedNativeModules.g.props
  packages/playground/windows/playground/AutolinkedNativeModules.g.props
Labels: AutoMerge

#6510 Print out sessionId if verbose
  change/@react-native-windows-cli-edfb8099-c06e-41ab-a9c1-7c2385019025.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: Area: CLI

#6500 Fix AppState Module
  change/react-native-windows-7c4ac5f2-d0b0-48e5-b96f-16f18c357387.json
  packages/IntegrationTest/tests/AppStateTests.tsx
  packages/IntegrationTest/tests/index.ts
  packages/IntegrationTest/windows/integrationtest/AutolinkedNativeModules.g.props
  vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
Labels: AutoMerge, Request Backport to 0.63

#6493 Fix managed nuget to have ref assembly marked AnyCpu
  Directory.Build.targets
  change/react-native-windows-b8dbda54-a2f3-42a1-b0bd-9c56a21014e1.json
  vnext/Directory.Build.props
  vnext/Directory.Build.targets
  vnext/Microsoft.ReactNative.Managed/JSValue.cs
Labels: AutoMerge, Request Backport to 0.63

#6521 [0.63] Replace WinAppDriver 1.2.1 with WinAppDriver 1.1 (#6502)
  .ado/templates/e2e-test-job.yml
Labels: Backport to 0.63 Approved

#6522 [0.62] Replace WinAppDriver 1.2.1 with WinAppDriver 1.1 (#6502)
  .ado/templates/e2e-test-job.yml
Labels: Backport to 0.62 Approved

#6507 [0.63] port nuget 5.8.0 fix to 0.63
  .ado/publish.yml
  .ado/templates/prepare-env.yml
  .ado/templates/react-native-init.yml
  change/@react-native-windows-cli-2020-11-12-23-06-58-nuget-0.63.json
  packages/@react-native-windows/cli/package.json
Labels: AutoMerge, Backport to 0.63 Approved

#6524 [0.63] Fix run-windows Warnings Using Node 14 (#6116)
  change/@react-native-windows-cli-2020-09-28-00-39-44-fix-node14.json
  packages/@react-native-windows/cli/package.json
  yarn.lock
Labels: Backport to 0.63 Approved

#6527 [0.62] port nuget 5.8.0 fix to 0.62
  .ado/publish.yml
  .ado/templates/prepare-env.yml
  .ado/templates/react-native-init.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-11-13-08-47-42-0.62-stable.json
  vnext/local-cli/runWindows/utils/build.js
Labels: AutoMerge, Backported to 0.62

#6529 Update Managed ref assemblies to be AnyCpu
  .ado/templates/prep-and-pack-nuget.yml
  change/react-native-windows-2020-11-13-10-57-08-master.json
  vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: Request Backport to 0.63

#6532 Improvements to telemetry logic
  change/@react-native-windows-telemetry-a022baa7-25bb-4626-9461-00b50b4d62f8.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
Labels: Request Backport to 0.63

#6534 Fix Publish pipeline due to moved callinvoker file
  change/react-native-windows-2020-11-15-20-13-18-master.json
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: Blocking

#6537 Fix publish pipeline for viewmanager.h
  change/react-native-windows-2020-11-16-08-23-41-master.json
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge, Blocking

#6466 JSDispatcher should use JSCallInvoker internally
  change/react-native-windows-5156072e-441e-4a70-86b1-690787a7549a.json
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/Consts.ts
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/DirectManipulationTestPage.tsx
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TransformTestPage.tsx
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/E2ETest/wdio/pages/DirectManipulationPage.ts
  packages/E2ETest/wdio/pages/TransformTestPage.ts
  packages/E2ETest/wdio/test/DirectManipulation.spec.ts
  packages/E2ETest/wdio/test/TransformTest.spec.ts
  packages/E2ETest/wdio/test/VisitAllPages.spec.ts
  packages/IntegrationTest/tests/LayoutTests.tsx
  packages/IntegrationTest/tests/index.ts
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/ReactHost/JSCallInvokerScheduler.cpp
  vnext/Microsoft.ReactNative/ReactHost/JSCallInvokerScheduler.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Shared/InstanceManager.cpp
  vnext/Shared/InstanceManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/OInstance.h
Labels: Area: Instance Management, AutoMerge

#6543 Mark packages published from master as private when cutting branch
  change/@rnw-scripts-promote-release-9a8b047d-00a8-4a96-875d-31968fd0a4f6.json
  packages/@rnw-scripts/promote-release/src/promoteRelease.ts
Labels: Area: Release Process, AutoMerge

#6525 [0.63] Add win32 exports required for internal usage
  change/react-native-windows-2020-11-13-08-35-00-desktopexports63.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: Backport to 0.63 Approved

#6541 Update Nuget publish to not overwrite the created anycpu version
  .ado/templates/prep-and-pack-nuget.yml
Labels: AutoMerge

#6384 [0.63] Use HRESULT instead of catching exceptions for WebSocket APIs
  change/react-native-windows-2020-10-29-17-19-15-backport-4995-0.63.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop.UnitTests/WebSocketTest.cpp
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/Modules/WebSocketModule.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Utils/CppWinrtLessExceptions.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
  vnext/Test/WebSocketServer.cpp
  vnext/Test/WebSocketServer.h
  vnext/overrides.json
  vnext/src/IntegrationTests/WebSocketBinaryTest.js
  vnext/src/IntegrationTests/websocket_integration_test_server_binary.js
Labels: AutoMerge, Backport to 0.63 Approved, Platform: Desktop

#6535 [0.63] Port telemetry improvements to 0.63
  change/@react-native-windows-telemetry-2020-11-15-22-13-32-tel1115-0.63.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
Labels: AutoMerge, Backport to 0.63 Approved

#6549 [0.63] Collect anonymized project name (#6452)
  change/@react-native-windows-cli-63a88995-cd00-4c15-8f81-7366247a68ad.json
  packages/@react-native-windows/cli/src/e2etest/projects/BarPackage/package.json
  packages/@react-native-windows/cli/src/e2etest/projects/FooPackage/package.json
  packages/@react-native-windows/cli/src/e2etest/runWindows.test.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: Backport to 0.63 Approved

#6555 [0.63] port CornerRadius fix to 0.63
  change/react-native-windows-dea2927a-a5e6-4784-a71a-14e423a40d2e.json
  vnext/Microsoft.ReactNative.Cxx/UI.Xaml.Controls.h
  vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
Labels: AutoMerge

#6548 Use MSBuild Builtin Support for NuGet Restore
  change/@react-native-windows-cli-2020-11-17-07-29-32-msbuild-restore.json
  change/react-native-windows-8e7f24ff-a496-4a51-8181-b4c8dc474a57.json
  lage.config.js
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/build.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
  packages/nuget-exe/.gitignore
  packages/nuget-exe/CHANGELOG.json
  packages/nuget-exe/CHANGELOG.md
  packages/nuget-exe/just-task.js
  packages/nuget-exe/package.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Build Infrastructure, AutoMerge

#6556 Exclude Beast WebSocket from build.
  change/react-native-windows-ba172ba1-f613-48aa-bbd1-e19f3705f66e.json
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/WebSocketTest.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactWindows-Desktop.sln
Labels: Area: Networking, AutoMerge, Platform: Desktop

#6559 Fix 2 typos
  .ado/templates/react-native-init.yml
  change/react-native-windows-0045baf0-e7aa-4b28-871d-fd6f08e80dce.json
  vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
Labels: AutoMerge

#6560 Add Yellowbox warnings for Windows Variants of Lean Core Components
  change/react-native-windows-a6aebc81-adec-4938-a41a-28b6ce245133.json
  vnext/src/index.windows.js
Labels: AutoMerge

#6562 Wait until UWP Jobs are Finished Before Desktop Packing
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#6568 [0.62] Use HRESULT instead of catching exceptions for WebSocket APIs
  change/react-native-windows-2020-11-18-17-00-25-backport-4995-0.62.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop.UnitTests/WebSocketTest.cpp
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/Modules/WebSocketModule.cpp
  vnext/ReactWindows-Desktop.sln
  vnext/ReactWindowsCore/IWebSocketResource.h
  vnext/ReactWindowsCore/Modules/AsyncStorageModuleWin32.cpp
  vnext/ReactWindowsCore/ReactWindowsCore-Desktop.vcxproj
  vnext/ReactWindowsCore/ReactWindowsCore.vcxproj
  vnext/ReactWindowsCore/WinRTWebSocketResource.cpp
  vnext/ReactWindowsCore/WinRTWebSocketResource.h
  vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
  vnext/ReactWindowsCore/packages.config
  vnext/Test/WebSocketServer.cpp
  vnext/Test/WebSocketServer.h
  vnext/include/ReactUWP/Utils/CppWinrtLessExceptions.h
  vnext/src/IntegrationTests/WebSocketBinaryTest.js
  vnext/src/IntegrationTests/websocket_integration_test_server_binary.js
  vnext/src/overrides.json
Labels: Area: Networking, AutoMerge, Backported to 0.62, Backported to 0.63, Platform: Desktop

#6573 Use lessthrow_await_adapter in WebSocketJSExecutor::ConnectAsync
  change/react-native-windows-6336eb07-86e6-461a-a24c-79311b382c98.json
  vnext/Shared/Executors/WebSocketJSExecutor.cpp
Labels: Area: Networking, AutoMerge

#6557 Update Nuget publish to not overwrite the created anycpu version
  .ado/templates/publish-build-artifacts-for-nuget.yml
  change/react-native-windows-ad5982b9-fb47-405a-9abd-6ee2b6d23e72.json
  vnext/Scripts/PublishNugetPackagesLocally.cmd
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge

#6582 Add ReactContext::ExecuteJsi method to use JSI in NativeModules
  change/react-native-windows-e6f9e1a2-9958-4c28-af55-80100258ac48.json
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.IntegrationTests/AddValues.js
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Labels: AutoMerge

#6593 Fix invalidation bug
  change/react-native-windows-3460da96-2737-4874-8f5a-a79d89eb0942.json
  vnext/Microsoft.ReactNative/Views/ViewPanel.cpp
  vnext/Microsoft.ReactNative/Views/ViewPanel.h
Labels: Area: Layout

#6592 Fix CPanel leak when a transform is applied
  change/react-native-windows-47f0ee14-4ccf-47a3-98c0-c2d982c53259.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: AutoMerge

#6600 Don't run test bundling when doing intellisense builds in VS
  change/react-native-windows-31c93351-ecbc-4fe1-9d24-98219e03f248.json
  vnext/Microsoft.ReactNative.IntegrationTests/TestBundle.targets
Labels: AutoMerge

#6595 Fix links in some docs, mark APIs as deprecated or experimental as ap…
  change/react-native-windows-e4618568-513a-4032-96fe-212df334f46d.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
  vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
  vnext/Microsoft.ReactNative/IReactNotificationService.idl
  vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
  vnext/Microsoft.ReactNative/IReactPackageProvider.idl
  vnext/Microsoft.ReactNative/IViewManager.idl
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/Microsoft.ReactNative/ReactApplication.idl
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.idl
  vnext/Microsoft.ReactNative/RedBoxHandler.idl
Labels: AutoMerge

#6585 Add error for users who try to build apps/libs via project instead of solution
  change/react-native-windows-2c7c8288-f17e-42f0-b803-1449fea26904.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
  vnext/PropertySheets/RequireSolution.targets
Labels: Request Backport to 0.62, Request Backport to 0.63

#6608 [0.63] Make ref assembly of MS.RN.Managed nuget anycpu
  .ado/publish.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/publish-build-artifacts-for-nuget.yml
  change/react-native-windows-2020-11-23-10-29-02-0.63-stable.json
  vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
  vnext/Scripts/PublishNugetPackagesLocally.cmd
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge, Backport to 0.63 Approved

#6617 Refactor ReactContext API
  change/react-native-windows-98d06b6c-abde-4e6a-9d1e-a910ca14bc4b.json
  packages/playground/windows/playground-win32.sln
  packages/playground/windows/playground/MainPage.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApi.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
Labels: AutoMerge
