Repository microsoft/react-native-windows, pull requests merged in 2020-06, with the labels that each got.

#5024 Allow Override Tooling to Use Nightly Builds
  change/react-native-platform-override-2020-05-27-09-45-07-checkout-master.json
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  yarn.lock
Labels: AutoMerge

#5071 Enable ReactNativeHost integration test
  change/react-native-windows-2020-05-30-16-12-15-PR-RNH_API.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.h
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.xaml
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/MainPage.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/MainPage.h
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/MainPage.idl
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/MainPage.xaml
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/MainPage.xaml
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/MainPage.xaml.cs
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/WebSocketJSExecutorIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketModuleIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/pch.h
  vnext/Microsoft.ReactNative.Cxx/CppWinRTIncludes.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/XamlUtils.h
  vnext/Microsoft.ReactNative.IntegrationTests/AddValues.js
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/ReactApplication.h
  vnext/Microsoft.ReactNative/ReactApplication.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.h
  vnext/Microsoft.ReactNative/ReactNativeHost.idl
  vnext/Mso/Mso.vcxitems
  vnext/Mso/Mso.vcxitems.filters
  vnext/Mso/future/futureWinRT.h
  vnext/ReactUWP/Modules/AppThemeModuleUwp.cpp
  vnext/ReactUWP/Modules/AppearanceModule.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge, Backport to 0.62

#5058 Add info about yarn api in contributing.md
  docs/contributing.md
Labels: AutoMerge

#5063 Use NPM when testing RN init workflow
  .ado/templates/react-native-init.yml
  change/react-native-windows-2020-05-29-14-39-39-initstable.json
  vnext/local-cli/generator-common/index.js
Labels: AutoMerge

#5087 Code Cleanup: Some low hanging fruit lint fixes
  change/react-native-windows-2020-06-01-16-06-42-master.json
  packages/E2ETest/app/ImageTestPage.tsx
  packages/E2ETest/run_wdio.js
  packages/E2ETest/wdio/pages/BasePage.ts
  packages/E2ETest/wdio/test/Image.spec.ts
  packages/E2ETest/wdio/test/login.spec.ts
  vnext/local-cli/runWindows/utils/build.js
  vnext/local-cli/runWindows/utils/winappdeploytool.js
  vnext/src/RNTester/js/RNTesterApp.windows.js
  vnext/src/RNTester/js/examples/View/ViewExample.windows.js
Labels: AutoMerge

#5088 Allow paremeterization of buildLogDirectory for msbuild task when using run-windows
  .ado/templates/e2e-test-job.yml
  .ado/templates/react-native-init.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-01-16-47-14-master.json
  vnext/local-cli/runWindows/runWindows.js
  vnext/local-cli/runWindows/utils/build.js
  vnext/local-cli/runWindows/utils/deploy.js
  vnext/local-cli/runWindows/utils/msbuildtools.js
Labels: AutoMerge

#5090 Minor autolinking template update prep
  change/react-native-windows-2020-06-02-09-57-42-autolink62.json
  vnext/local-cli/generator-windows/templates/cpp/proj-experimental/MyApp.vcxproj
  vnext/local-cli/generator-windows/templates/cpp/proj-experimental/MyApp.vcxproj.filters
  vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj
  vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj.filters
  vnext/local-cli/generator-windows/templates/cpp/src/App.cpp
  vnext/local-cli/generator-windows/templates/cpp/src/AutolinkedNativeModules.g.cpp
  vnext/local-cli/generator-windows/templates/cpp/src/AutolinkedNativeModules.g.h
  vnext/local-cli/generator-windows/templates/cpp/src/pch.h
Labels: Backport to 0.62, Breaking Change, Request Backport

#5092 Fix ReloadInstance crash caused by unloaded instance
  change/react-native-windows-2020-06-02-09-55-24-FixReload.json
  packages/playground/windows/playground.sln
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactHost/React_Win.h
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
  vnext/ReactUWP/Views/ViewManagerBase.cpp
  vnext/include/ReactUWP/IReactInstance.h
Labels: AutoMerge

#5100 workaround for UWP Packaging VS 16.5-16.6 regression backport to 0.61
  change/react-native-windows-2020-06-02-11-56-08-packaging-61.json
  vnext/local-cli/runWindows/utils/Add-AppDevPackage.ps1
  vnext/local-cli/runWindows/utils/deploy.js
Labels: AutoMerge

#5109 Re-enable most Desktop integration tests
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-02-20-32-51-reenabledeskits.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/WebSocketJSExecutorIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketModuleIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
Labels: AutoMerge

#5114 Extend timeout for 'Extra Checks' in PR validation
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5115 Move devmenu out of RootControl, implement more of DevSettings
  change/react-native-windows-2020-06-03-19-20-43-devmenu.json
  packages/E2ETest/windows/ReactUWPTestApp/App.xaml.cs
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
  packages/playground/windows/playground-win32.sln
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.cpp
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.h
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.h
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
  vnext/Microsoft.ReactNative/Views/ReactRootControl.h
  vnext/Microsoft.ReactNative/XamlUIService.cpp
  vnext/Microsoft.ReactNative/XamlUIService.h
  vnext/Microsoft.ReactNative/XamlUIService.idl
  vnext/include/ReactUWP/IReactInstance.h
  vnext/local-cli/generator-windows/templates/cpp/src/App.cpp
  vnext/local-cli/generator-windows/templates/cs/src/App.xaml.cs
Labels: AutoMerge

#5123 Fix SampleApp run-windows with deploy
  change/react-native-windows-2020-06-04-13-09-07-master.json
  vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
  vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Debug.pubxml
  vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Release.pubxml
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
Labels: AutoMerge

#5118 Fix compile errors for clang in NativeModules.h - IsVoidResult and ForEachMember
  change/react-native-windows-2020-06-04-08-40-37-clang_build.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: AutoMerge, Partner: Facebook, Request Backport

#5117 Expose JSDispatcher on IReactContext
  change/react-native-windows-2020-06-04-13-42-36-pull_request_jsd.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#5065 Revise Architecture of react-native-platform-override
  change/@office-iss-react-native-win32-2020-06-04-21-00-16-restrucuture-overrides.json
  change/react-native-platform-override-2020-06-03-23-11-58-restrucuture-overrides.json
  change/react-native-windows-2020-06-04-01-50-22-restrucuture-overrides.json
  packages/react-native-platform-override/.eslintrc.js
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  packages/react-native-platform-override/src/Hash.ts
  packages/react-native-platform-override/src/Manifest.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/OverrideFactory.ts
  packages/react-native-platform-override/src/OverridePrompt.ts
  packages/react-native-platform-override/src/OverrideUpgrader.ts
  packages/react-native-platform-override/src/PackageUtils.ts
  packages/react-native-platform-override/src/Serialized.ts
  packages/react-native-platform-override/src/UpgradeStrategy.ts
  packages/react-native-platform-override/src/ValidationStrategy.ts
  packages/react-native-platform-override/src/scripts/generateManifest.ts
  packages/react-native-platform-override/src/scripts/hashFile.ts
  packages/react-native-platform-override/src/test/Hash.test.ts
  packages/react-native-platform-override/src/test/Manifest.test.ts
  packages/react-native-platform-override/src/test/ManifestData.test.ts
  packages/react-native-platform-override/src/test/MockFileRepository.ts
  packages/react-native-platform-override/src/test/Override.test.ts
  packages/react-native-platform-override/src/test/OverrideFactory.test.ts
  packages/react-native-platform-override/src/test/Serialized.test.ts
  packages/react-native-platform-override/src/test/ValidationStrategy.test.ts
  packages/react-native-platform-override/tsconfig.json
  packages/react-native-win32/src/overrides.json
  vnext/src/Libraries/Image/Image.windows.js
Labels: AutoMerge

#5085 Expose turbo module registry API
  change/react-native-windows-2020-06-01-15-09-20-pull_request.json
  packages/playground/README.md
  vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/ClipboardModule.cpp
  vnext/Microsoft.ReactNative/Modules/ClipboardModule.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/ReactPackageBuilder.cpp
  vnext/Microsoft.ReactNative/ReactPackageBuilder.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
Labels: AutoMerge

#5134 Install MSBuild structured log viewer
  change/react-native-windows-2020-06-05-15-09-16-installMSBLV.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5136 DevMenu should only show up when DeveloperSupport is on
  change/react-native-windows-2020-06-05-17-10-24-devmenudevsup.json
  packages/playground/windows/playground/MainPage.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
Labels: AutoMerge

#5139 Remove legacy react::uwp::ReactInstanceSettings struct
  change/react-native-windows-2020-06-05-21-41-46-RemoveLegacySettings.json
  packages/microsoft-reactnative-sampleapps/windows/SampleApps.sln
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/include/ReactUWP/IReactInstance.h
Labels: AutoMerge

#5091 Remove Microsoft.ReactNative.SharedManaged project.
  change/react-native-windows-2020-06-02-10-13-26-master.json
  docs/breakingchanges-0.63.md
  docs/project-structure.md
  packages/playground/windows/playground.sln
  vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
  vnext/Microsoft.ReactNative.Managed/AttributedViewManager.cs
  vnext/Microsoft.ReactNative.Managed/IJSValueTreeReader.cs
  vnext/Microsoft.ReactNative.Managed/IReactPromise.cs
  vnext/Microsoft.ReactNative.Managed/JSValue.cs
  vnext/Microsoft.ReactNative.Managed/JSValueGenerator.cs
  vnext/Microsoft.ReactNative.Managed/JSValueReader.cs
  vnext/Microsoft.ReactNative.Managed/JSValueReaderGenerator.cs
  vnext/Microsoft.ReactNative.Managed/JSValueTreeReader.cs
  vnext/Microsoft.ReactNative.Managed/JSValueTreeWriter.cs
  vnext/Microsoft.ReactNative.Managed/JSValueWriter.cs
  vnext/Microsoft.ReactNative.Managed/JSValueWriterGenerator.cs
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.Managed/OneOf.cs
  vnext/Microsoft.ReactNative.Managed/Properties/AssemblyInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactAttributes.cs
  vnext/Microsoft.ReactNative.Managed/ReactCallback.cs
  vnext/Microsoft.ReactNative.Managed/ReactConstantInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactConstantProvider.cs
  vnext/Microsoft.ReactNative.Managed/ReactConstantProviderInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactContext.cs
  vnext/Microsoft.ReactNative.Managed/ReactContextGenerator.cs
  vnext/Microsoft.ReactNative.Managed/ReactEnumerableExtensions.cs
  vnext/Microsoft.ReactNative.Managed/ReactEventInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactException.cs
  vnext/Microsoft.ReactNative.Managed/ReactFunctionInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactInitializerInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactMethodInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactModuleInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReactPackageBuilderExtensions.cs
  vnext/Microsoft.ReactNative.Managed/ReactPackageProvider.cs
  vnext/Microsoft.ReactNative.Managed/ReactPromise.cs
  vnext/Microsoft.ReactNative.Managed/ReactSyncMethodInfo.cs
  vnext/Microsoft.ReactNative.Managed/ReflectionReactPackageProvider.cs
  vnext/Microsoft.ReactNative.Managed/ViewManagerAttributes.cs
  vnext/Microsoft.ReactNative.Managed/ViewManagerEvent.cs
  vnext/Microsoft.ReactNative.SharedManaged/JSValueGenerator.cs
  vnext/Microsoft.ReactNative.SharedManaged/JSValueReader.cs
  vnext/Microsoft.ReactNative.SharedManaged/Microsoft.ReactNative.SharedManaged.projitems
  vnext/Microsoft.ReactNative.SharedManaged/Microsoft.ReactNative.SharedManaged.shproj
  vnext/Microsoft.ReactNative.sln
  vnext/ReactWindows-Universal.sln
Labels: AutoMerge, Breaking Change

#5133 Cherry pick API changes for 0.62
  change/react-native-windows-2020-05-21-13-01-25-WeakModule.json
  change/react-native-windows-2020-05-21-22-04-55-PR-FixInstanceLoading.json
  change/react-native-windows-2020-05-25-15-56-21-PR-UIDispatcherProperty.json
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Cxx.UnitTests/pch.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactDispatcher.h
  vnext/Microsoft.ReactNative.Cxx/ReactHandleHelper.h
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/ReactInstanceSettingsTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/NativeModulesProvider.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.cpp
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
  vnext/Mso/dispatchQueue/dispatchQueue.h
  vnext/Mso/src/dispatchQueue/queueService.cpp
  vnext/Mso/src/dispatchQueue/queueService.h
  vnext/Mso/src/dispatchQueue/uiScheduler_winrt.cpp
  vnext/ReactUWP/Base/UwpReactInstance.cpp
  vnext/ReactWindows-Desktop.sln
Labels: AutoMerge

#5138 Add Integration tests to CI
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-05-20-16-51-FixIntegrationTest.json
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactPropertyBagTests.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
Labels: AutoMerge

#5140 Fix difference in layout algorithm between windows and other platforms
  change/react-native-windows-2020-06-06-07-10-00-uselegacystretch.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/ReactUWP/Modules/NativeUIManager.cpp
  vnext/ReactUWP/Modules/NativeUIManager.h
Labels: AutoMerge, Breaking Change, Partner: Facebook

#5137 Native Animations shouldn't crash on RS3-RS4
  change/react-native-windows-2020-06-05-17-57-31-animationLowerThanRS5.json
  vnext/ReactUWP/Modules/Animated/PropsAnimatedNode.cpp
Labels: AutoMerge

#5152 Add support for Alert module with Xaml Islands
  change/react-native-windows-2020-06-08-13-02-44-alert.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
  vnext/Microsoft.ReactNative/Modules/AlertModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/ReactUWP/Base/CoreNativeModules.cpp
  vnext/ReactUWP/Modules/AlertModuleUwp.cpp
  vnext/ReactUWP/Modules/AlertModuleUwp.h
  vnext/src/RNTester/js/utils/RNTesterList.windows.ts
Labels: Area: Alert, Area: Tests, AutoMerge, Partner: Facebook

#5155 Fail on PowerShell exceptinos
  change/react-native-windows-2020-06-08-21-53-49-5153.json
  vnext/local-cli/runWindows/utils/commandWithProgress.js
Labels: AutoMerge

#5162 Call turbo module in IntegrationTests
  change/react-native-windows-2020-06-09-15-04-44-pull_request.json
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
Labels: AutoMerge

#5164 We shouldn't ever need to install RN globally
  .ado/templates/prepare-env.yml
Labels: AutoMerge

#5166 [0.62] Bump beachball from 1.31.0 to 1.31.1 (#4988)
  yarn.lock
Labels: Area: Infrastructure, Area: Release Process, AutoMerge

#5167 [0.61] Bump beachball from 1.31.0 to 1.31.1 (#4988)
  yarn.lock
Labels: AutoMerge

#5186 Fix file lock issue with MSBuild's `/bl` flag and the metro bundler
  change/react-native-windows-2020-06-11-17-03-06-master.json
  vnext/metro.config.js
Labels: AutoMerge

#5084 [0.62] Attempt to fix Publish pipeline in 0.62
  change/react-native-windows-2020-06-01-14-41-24-0.62-stable.json
  vnext/ReactWindows-Universal.sln
Labels: Backport Approved, Partner: Office

#5108 Add focusRef to TouchableWin32
  change/@office-iss-react-native-win32-2020-06-02-17-23-28-FocusableTouchables.json
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.focus.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/src/Libraries/Components/Touchable/Tests/TouchableWin32Test.tsx
  packages/react-native-win32/src/Libraries/Components/Touchable/TouchableWin32.tsx
Labels: Request Backport

#5184 Add Microsoft.ReactNative.Cxx to the nuget package
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-11-13-06-37-msrncxxnuget.json
  vnext/Scripts/Microsoft.ReactNative.nuspec
  vnext/Scripts/ReactWin32.nuspec
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: Backport Approved, Partner: Office

#5171 Implement SyncMethod and Constant for TurboModule
  change/react-native-windows-2020-06-10-15-33-28-pull_request.json
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#5175 Implement Logbox module
  change/react-native-windows-2020-06-10-20-32-34-logbox.json
  packages/playground/Samples/rntester.tsx
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp
  vnext/Microsoft.ReactNative/Modules/LogBoxModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/ReactNativeHost.h
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/ReactUWP/Modules/NativeUIManager.cpp
  vnext/ReactWindows-Desktop.sln
Labels: Area: Developer Experience, AutoMerge

#5196 [0.62] Add Microsoft.ReactNative.Cxx to the nuget package
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-11-13-06-37-msrncxxnuget.json
  vnext/Scripts/Microsoft.ReactNative.nuspec
  vnext/Scripts/ReactWin32.nuspec
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge, Backport Approved, Partner: Office

#5193 [0.62] Cherry pick PR #5071 for CallJsFunction queuing
  change/react-native-windows-2020-06-12-10-45-34-PR-BackportCallJSQueue.json
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Labels: AutoMerge, Backported to 0.62

#5199 [0.61] Cherry-pick PR #4893 for tab-focus bug #4703
  change/react-native-windows-2020-05-13-12-47-43-tabfocus-fix.json
  vnext/ReactUWP/Views/ControlViewManager.cpp
  vnext/ReactUWP/Views/ViewViewManager.cpp
Labels: Area: Focus

#5185 [0.60] Disable V8 globally; turn it on only for Desktop builds
  .ado/publish.yml
  .ado/templates/build-rnw.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-11-15-48-25-0.60-stable.json
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#5200 Upgrade to Boost 1.72
  change/react-native-windows-2020-06-12-19-54-19-boost-1.72.json
  packages/E2ETest/packages.config
  packages/microsoft-reactnative-sampleapps/packages.config
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.x64.def
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.x86.def
  vnext/Desktop.Test.DLL/packages.config
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/Desktop/packages.config
  vnext/Folly/Folly.vcxproj
  vnext/Folly/packages.config
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/IntegrationTests/packages.config
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/packages.config
  vnext/ReactUWP/packages.config
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
  vnext/Test/React.Windows.Test.vcxproj
  vnext/Test/WebSocketServer.cpp
  vnext/Test/WebSocketServer.h
  vnext/Test/packages.config
Labels: AutoMerge

#5205 Prevent Switches from Erroneously Becoming Disabled
  change/react-native-windows-2020-06-14-00-14-17-fix-switch-disabling.json
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRegularBorder.json
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/ControlStyleRoundBorder.json
  vnext/ReactUWP/Views/SwitchViewManager.cpp
Labels: Backport Approved

#5213 Use default brush for borders
  change/react-native-windows-2020-06-15-12-36-45-border-black.json
  vnext/ReactUWP/Utils/ResourceBrushUtils.cpp
  vnext/ReactUWP/Views/ViewPanel.cpp
  vnext/include/ReactUWP/Utils/PropertyUtils.h
  vnext/include/ReactUWP/Utils/ResourceBrushUtils.h
Labels: Area: Borders and Brushes, Breaking Change

#5061 Use midgard-yarn for faster install times
  .ado/templates/yarn-install.yml
Labels: AutoMerge

#5216 Rename "master" packages to "canary"
  .ado/templates/react-native-init.yml
  change/@office-iss-react-native-win32-2020-06-15-14-59-13-master-to-canary.json
  change/react-native-windows-2020-06-15-14-59-13-master-to-canary.json
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/package.json
  vnext/package.json
Labels: Area: Release Process, AutoMerge

#5215 [0.62] Prevent Switches from Erroneously Becoming Disabled (#5205)
  change/react-native-windows-2020-06-14-00-14-17-fix-switch-disabling.json
  vnext/ReactUWP/Views/SwitchViewManager.cpp
Labels: Area: Switch, AutoMerge

#5226 Don't `eslint` nor `flow check` the target folder
  change/react-native-windows-2020-06-15-18-01-44-master.json
  vnext/.eslintignore
  vnext/.flowconfig
Labels: AutoMerge

#5231 Unify DevSupportManager and WebSocketJSExecutor
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-16-08-59-55-unifydev.json
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj.filters
  vnext/Desktop.IntegrationTests/WebSocketJSExecutorIntegrationTest.cpp
  vnext/Desktop.UnitTests/WebSocketJSExecutorTest.cpp
  vnext/Desktop/Executors/WebSocketJSExecutor.cpp
  vnext/Desktop/Executors/WebSocketJSExecutor.h
  vnext/Desktop/Executors/WebSocketJSExecutorFactory.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/ReactWindowsCore/DevSupportManager.cpp
  vnext/ReactWindowsCore/DevSupportManager.h
  vnext/ReactWindowsCore/Executors/WebSocketJSExecutor.cpp
  vnext/ReactWindowsCore/Executors/WebSocketJSExecutor.h
  vnext/ReactWindowsCore/Executors/WebSocketJSExecutorFactory.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: Request Backport to 0.62

#5221 Implement REACT_METHOD + Callback/TwoCallbacks for turbo module
  change/react-native-windows-2020-06-15-17-03-11-pull_request.json
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#5234 [0.62] Unify DevSupportManager and WebSocketJSExecutor
  .ado/templates/react-native-init.yml
  .ado/windows-vs-pr.yml
  change/@office-iss-react-native-win32-2020-06-16-10-57-52-0.62-stable.json
  change/react-native-windows-2020-06-16-08-59-55-unifydev.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/src/Libraries/core/setUpDeveloperTools.win32.js
  packages/react-native-win32/src/overrides.json
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj.filters
  vnext/Desktop.IntegrationTests/WebSocketJSExecutorIntegrationTest.cpp
  vnext/Desktop.UnitTests/WebSocketJSExecutorTest.cpp
  vnext/Desktop/DevSupportManager.cpp
  vnext/Desktop/DevSupportManager.h
  vnext/Desktop/Executors/WebSocketJSExecutor.cpp
  vnext/Desktop/Executors/WebSocketJSExecutor.h
  vnext/Desktop/Executors/WebSocketJSExecutorFactory.cpp
  vnext/Desktop/LazyDevSupportManager.cpp
  vnext/Desktop/LazyDevSupportManager.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/ReactUWP/ReactUWP.vcxproj
  vnext/ReactWindowsCore/DevSupportManager.cpp
  vnext/ReactWindowsCore/DevSupportManager.h
  vnext/ReactWindowsCore/Executors/WebSocketJSExecutor.cpp
  vnext/ReactWindowsCore/Executors/WebSocketJSExecutor.h
  vnext/ReactWindowsCore/Executors/WebSocketJSExecutorFactory.cpp
  vnext/local-cli/generator-common/index.js
Labels: Backported to 0.62, Platform: NetUI

#5229 Create Scripts for the Release Process
  .ado/publish.yml
  .ado/templates/react-native-init.yml
  .ado/variables/release.yml
  .ado/windows-vs-pr.yml
  change/@office-iss-react-native-win32-2020-06-16-00-10-39-release-scripts.json
  change/react-native-windows-2020-06-16-00-10-39-release-scripts.json
  packages/react-native-win32/package.json
  packages/scripts/package.json
  packages/scripts/promoteRelease.js
  vnext/package.json
  yarn.lock
Labels: Area: Infrastructure, Area: Release Process

#5178 Add more required workloads for VS for rnw-dependencies
  change/react-native-windows-2020-06-11-02-43-42-rnwdep0611.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5237 Run NativeModules 2.0 in JS thread
  change/react-native-windows-2020-06-16-14-33-30-PR-NativeModule_JSQueue.json
  vnext/Microsoft.ReactNative/NativeModulesProvider.cpp
  vnext/Microsoft.ReactNative/NativeModulesProvider.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: Area: Native Modules, AutoMerge

#5258 [0.61] Disable V8 globally; turn it on only for Desktop builds
  .ado/publish.yml
  .ado/templates/build-rnw.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-16-16-10-02-0.61-stable.json
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#5259 Update C++/WinRT to version 2.0.200615.7
  change/react-native-windows-2020-06-16-16-14-45-CppWinRT_2.0.200615.7.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/packages.config
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/packages.config
  packages/playground/packages.config
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/packages.config
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/packages.config
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/module.g.cpp
  vnext/Desktop/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/packages.config
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/packages.config
  vnext/ReactUWP/packages.config
  vnext/local-cli/generator-windows/index.js
Labels: AutoMerge

#5264 Apply compatible casing on SampleTurboModule members
  change/react-native-windows-2020-06-16-22-18-15-pull_request.json
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
Labels: AutoMerge

#5257 [0.60] Drop LazyDevSupportManager (#4984)
  change/react-native-windows-2020-05-21-16-49-04-dsmwinrt.json
  vnext/Desktop/DevSupportManager.cpp
  vnext/Desktop/DevSupportManager.h
  vnext/Desktop/LazyDevSupportManager.cpp
  vnext/Desktop/LazyDevSupportManager.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/Sandbox/DevSupportManagerSandbox.cpp
Labels: AutoMerge

#5266 Optimize TurboModulesProvider to not performing unnecessary (Value*, size_t) <--> Array conversions
  change/react-native-windows-2020-06-16-23-39-51-pull_request_2.json
  vnext/Microsoft.ReactNative.ComponentTests/CommonReaderTest.h
  vnext/Microsoft.ReactNative.ComponentTests/JsiArgumentReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
  vnext/Microsoft.ReactNative/JsiReader.cpp
  vnext/Microsoft.ReactNative/JsiReader.h
  vnext/Microsoft.ReactNative/JsiWriter.cpp
  vnext/Microsoft.ReactNative/JsiWriter.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#5262 Reenable WebSocket tests in PR
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5256 [0.61] Drop LazyDevSupportManager (#4984)
  change/react-native-windows-2020-05-21-16-49-04-dsmwinrt.json
  vnext/Desktop/DevSupportManager.cpp
  vnext/Desktop/DevSupportManager.h
  vnext/Desktop/LazyDevSupportManager.cpp
  vnext/Desktop/LazyDevSupportManager.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
Labels: AutoMerge

#5274 Fix building vcxproj files outside of solution
  change/react-native-windows-2020-06-17-19-10-13-master.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
Labels: AutoMerge

#5276 Update react-native-windows-init to support 'linking' the react-native-windows package for development
  change/react-native-windows-init-2020-06-17-19-17-04-master.json
  packages/react-native-windows-init/src/Cli.ts
Labels: AutoMerge

#5227 Add folly.natvis to the nuget package
  change/react-native-windows-2020-06-17-17-03-15-folly-natvis.json
  vnext/Scripts/ReactWin32.nuspec
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge

#5277 [react-native-win32] Enable fast refresh support
  change/@office-iss-react-native-win32-2020-06-18-09-44-30-fastrefreshwin32.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/core/setUpDeveloperTools.win32.js
  packages/react-native-win32/src/overrides.json
  yarn.lock
Labels: Platform: NetUI

#5279 Re-enable Desktop integration tests in Debug
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5129 [0.62] Backport External Lib Props/Targets
  change/react-native-windows-2020-06-05-10-34-46-62libtargets.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
Labels: AutoMerge, Backport to 0.62 Approved

#5281 Complete BundleUrl should be provided to JSExecutor ...
  change/react-native-windows-2020-06-18-14-13-48-bundleurl.json
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#5282 turbo modules should be replaceable
  change/react-native-windows-2020-06-18-14-40-19-tm-fix.json
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#5289 Disable RNTesterIntegrationTests::WebSocket
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5260 Make WinUI3 a property, add support for C# apps
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-06-16-23-31-17-winui3_noconfig.json
  packages/playground/windows/playground.sln
  packages/playground/windows/playground/Playground.vcxproj
  vnext/Folly/Folly.vcxproj
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.Managed/AttributedViewManager.cs
  vnext/Microsoft.ReactNative.Managed/JSValueReader.cs
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.Managed/ReactContext.cs
  vnext/Microsoft.ReactNative.Managed/ReactContextGenerator.cs
  vnext/Microsoft.ReactNative.Managed/ViewManagerEvent.cs
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/PropertySheet.props
  vnext/Microsoft.ReactNative/ReactNative.V8JSI.Windows.WinUI3.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
  vnext/PropertySheets/WinUI.props
  vnext/PropertySheets/WinUI3.props
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/local-cli/generator-windows/index.js
  vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj
  vnext/local-cli/generator-windows/templates/cs/src/App.xaml.cs
  vnext/local-cli/generator-windows/templates/cs/src/MainPage.xaml.cs
Labels: AutoMerge, Breaking Change

#5295 Fix warnings of signed/unsigned comparison mismatches on x86 builds
  change/react-native-windows-2020-06-22-08-35-37-master.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/JSValueTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NoAttributeNativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNonAbiValueTests.cpp
  vnext/Mso.UnitTests/errorCode/maybeTest.cpp
  vnext/Mso.UnitTests/future/arrayViewTest.cpp
  vnext/Mso.UnitTests/future/futureFuncTest.cpp
  vnext/Mso.UnitTests/future/futureTestEx.cpp
  vnext/Mso.UnitTests/future/promiseGroupTest.cpp
  vnext/Mso.UnitTests/future/promiseTest.cpp
  vnext/Mso.UnitTests/future/whenAllTest.cpp
Labels: AutoMerge

#5297 Prevent --useWinUI3 and --experimentalNugetDependency from being used at the same time in react-native-windows-init
  change/react-native-windows-init-2020-06-22-09-35-38-master.json
  packages/react-native-windows-init/src/Cli.ts
Labels: AutoMerge

#5291 Fix JSValueReaderGenerator runtime error for read-only properties
  change/react-native-windows-2020-06-21-16-56-44-FixCSNullRef.json
  vnext/Microsoft.ReactNative.Managed/JSValueReaderGenerator.cs
Labels: AutoMerge, Request Backport to 0.61, Request Backport to 0.62

#5318 Split out UnitTests for managed code
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#5320 Slightly reduce the number of TS files in react-native-win32
  change/@office-iss-react-native-win32-2020-06-23-13-40-56-norntesterts.json
  packages/playground/Samples/rntester.tsx
  packages/playground/index.js
  packages/react-native-win32/just-task.js
  packages/react-native-win32/package.json
  packages/react-native-win32/src/RNTester.ts
  packages/react-native-win32/src/overrides.json
Labels: AutoMerge

#5323 Fix issue running react-native-windows-init with yarn
  change/react-native-windows-init-2020-06-23-18-14-45-yarninit.json
  packages/react-native-windows-init/src/Cli.ts
Labels: Area: CLI, AutoMerge

#5327 Fix remote debugging with web debugging in Playground.
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.h
  packages/playground/windows/playground/Package.appxmanifest
Labels: Area: Debug Infrastructure

#5330 Fix run-windows NuGet Errors in CI By Using Deterministic Binary and Update to netcore 3.1 from 2.2
  change/react-native-windows-2020-06-24-08-27-10-fix-nuget.json
  docs/managedCodeGen.md
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.CodeGen/Microsoft.ReactNative.Managed.CodeGen.csproj
  vnext/Microsoft.ReactNative.Managed.CodeGen/OlderNetCoreVersionWorkarounds.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Debug.pubxml
  vnext/Microsoft.ReactNative.Managed.CodeGen/Properties/PublishProfiles/DeployAsTool-Release.pubxml
  vnext/local-cli/runWindows/utils/build.js
Labels: AutoMerge, Request Backport to 0.62

#5321 Add script to automatically create release notes from Beachball changes
  .ado/publish.yml
  packages/scripts/createGithubReleases.js
  packages/scripts/findRepoRoot.js
  packages/scripts/package.json
  packages/scripts/promoteRelease.js
Labels: AutoMerge, Request Backport to 0.61, Request Backport to 0.62

#5307 Only Create Github Releases for Preview/Latest Releases of the "react-native-windows" Package
  .ado/publish.yml
  .ado/templates/react-native-init.yml
  .ado/variables/release.yml
  change/react-native-windows-2020-06-23-01-16-44-no-master-tags.json
  package.json
  packages/scripts/promoteRelease.js
  vnext/package.json
  yarn.lock
Labels: AutoMerge, Request Backport to 0.60, Request Backport to 0.61, Request Backport to 0.62

#5347 Ensure lib-commonjs is packaged into react-native-platform-override
  change/react-native-platform-override-2020-06-25-20-31-44-platform-override-lib.json
  packages/react-native-platform-override/package.json
Labels: AutoMerge

#5344 Unify storage for sourceBundleHost/Port and debugHost
  .ado/templates/yarn-install.yml
  change/react-native-windows-2020-06-25-13-28-13-sourceBundleSettings.json
  vnext/IntegrationTests/TestRunner.cpp
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/ReactWindowsCore/DevServerHelper.h
  vnext/ReactWindowsCore/DevSettings.h
  vnext/ReactWindowsCore/DevSupportManager.cpp
  vnext/ReactWindowsCore/DevSupportManager.h
  vnext/ReactWindowsCore/IDevSupportManager.h
  vnext/Shared/OInstance.cpp
Labels: Area: Debug Infrastructure, AutoMerge

#5331 Dont crash when bundler asks to reload, when no reload callback was provided
  change/react-native-windows-2020-06-24-10-33-33-deld.json
  vnext/Desktop/DevSupportManager.cpp
  vnext/Desktop/DevSupportManager.h
  vnext/ReactWindowsCore/DevSupportManager.cpp
Labels: AutoMerge

#5354 Update midgard-yarn to later version and give it a private yarn cache
  .ado/templates/yarn-install.yml
Labels: AutoMerge

#5355 Improve msbuild logging for universal and desktop build
  .ado/templates/build-rnw.yml
Labels: AutoMerge

#5356 Add Enterprise vs2019 support to rnw-dependencies
  change/react-native-windows-2020-06-26-10-31-10-master.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5358 Fix casing typos in NuGet and MSBuild
  .ado/publish.yml
  .ado/setVersionEnvVars.js
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/react-native-init.yml
  .ado/windows-vs-pr.yml
  .github/workflows/pr.yml
  .github/workflows/publish.yml
  change/react-native-windows-2020-06-26-12-02-44-master.json
  change/react-native-windows-init-2020-06-26-12-02-44-master.json
  docs/managedCodeGen.md
  docs/react-native-windows-init.md
  packages/react-native-windows-init/src/Cli.ts
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/App.cs
  vnext/PropertySheets/ManagedCodeGen/Microsoft.ReactNative.Managed.CodeGen.targets
  vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
  vnext/local-cli/generate-windows.js
  vnext/local-cli/generator-windows/index.js
Labels: AutoMerge

#5361 Fix build errors for codegen unittest project when building in VS2019
  change/react-native-windows-2020-06-26-15-45-16-master.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
Labels: AutoMerge

#5360 Remove Include/ReactUWP files
  change/react-native-windows-2020-06-26-12-39-27-PR-RemoveIncludeReactUWP.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative/Base/CoreUIManagers.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/ReactHost/IReactInstance.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ViewManagerProvider.h
  vnext/Microsoft.ReactNative/Views/IXamlRootView.h
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
  vnext/Microsoft.ReactNative/Views/ReactRootControl.h
  vnext/include/Include.vcxitems
  vnext/include/Include.vcxitems.filters
  vnext/include/ReactUWP/InstanceFactory.h
  vnext/include/ReactUWP/ReactRootView.h
Labels: AutoMerge

#5372 Stop generating extra files in MS.RN.ComponentTests
  change/react-native-windows-2020-06-28-11-36-54-StopGeneratingTestFiles.json
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
Labels: AutoMerge

#5365 Run WACK in CI
  .ado/TestWACK.ps1
  .ado/windows-vs-pr.yml
  packages/playground/windows/playground/Package.appxmanifest
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/Playground_TemporaryKey.pfx
Labels: Area: Release Process

#5369 AppPolicyGetWindowingModel is not WACK compliant
  .ado/TestWACK.ps1
  change/react-native-windows-2020-06-26-23-27-40-AppPolicyWACK.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge, Request Backport to 0.62

#5382 Migrate "Alert" to turbo module
  change/@office-iss-react-native-win32-2020-06-29-13-50-34-tm-migrate.json
  change/react-native-windows-2020-06-29-12-14-42-tm-migrate.json
  packages/react-native-win32/src/Libraries/Alert/Alert.win32.js
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/src/Libraries/Alert/Alert.windows.js
Labels: AutoMerge

#5383 Remove delayload dependencies on some winrt apisets, to reduce warning count
  change/react-native-windows-2020-06-29-17-13-10-master.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
Labels: AutoMerge

#5366 Fix a few more casing typos
  .github/workflows/pr.yml
  change/@office-iss-react-native-win32-2020-06-26-19-29-32-master.json
  change/react-native-windows-2020-06-26-19-29-32-master.json
  change/react-native-windows-init-2020-06-26-19-29-32-master.json
  docs/react-native-windows-init.md
  packages/react-native-win32/README.md
  packages/react-native-windows-init/README.md
  vnext/.flowconfig
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Mso/debugAssertApi/debugAssertDetails.h
  vnext/Scripts/Install-WindowsSDKISO.ps1
  vnext/Shared/DevSettings.h
  vnext/local-cli/config/configUtils.js
  vnext/local-cli/config/dependencyConfig.js
  vnext/local-cli/config/projectConfig.js
  vnext/local-cli/runWindows/runWindows.js
  vnext/local-cli/runWindows/utils/autolink.js
  vnext/local-cli/runWindows/utils/commandWithProgress.js
  vnext/react-native.config.js
  vnext/src/Libraries/Components/View/ViewWindows.tsx
  vnext/src/RNTester/js/examples-win/DatePicker/DatePickerExample.windows.tsx
  vnext/src/RNTester/js/examples-win/Picker/PickerWindowsExample.tsx
  vnext/src/RNTester/js/utils/RNTesterList.windows.ts
  vnext/src/typings-index.ts
Labels: AutoMerge

#5386 Migrate 'DevSettings' to turbo module
  change/react-native-windows-2020-06-29-23-03-19-tm-devsettings.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#5388 Implement REACT_CONSTANT as getConstants sync method for turbo module
  change/react-native-windows-2020-06-29-23-55-00-tm-const.json
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#5387 Migrate 'LogBox' to turbo module
  change/react-native-windows-2020-06-29-23-23-34-tm-logbox.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#5368 Fix various compiler warnings
  change/react-native-windows-2020-06-29-13-30-32-master.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/AutolinkedNativeModules.g.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  packages/playground/windows/playground-win32/AutolinkedNativeModules.g.cpp
  packages/playground/windows/playground/AutolinkedNativeModules.g.cpp
  packages/playground/windows/playground/Playground.vcxproj
  vnext/Common/Common.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/object/objectRefCountTest.cpp
  vnext/Mso.UnitTests/object/objectWithWeakRefTest.cpp
  vnext/Mso/motifCpp/motifCppTest.h
  vnext/Mso/object/make.h
  vnext/PropertySheets/React.Cpp.props
  vnext/local-cli/generator-windows/index.js
  vnext/local-cli/runWindows/utils/autolink.js
Labels: AutoMerge
