Repository microsoft/react-native-windows, pull requests merged in 2020-09, with the labels that each got.

#5874 Fix 5870: In C# CodeGen, don't check for inheritance, but do explicit type checks
  change/react-native-windows-2020-08-31-14-37-14-pr-FixBug.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenMethodTests.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringPromiseReturnVoid--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringPromiseReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackWithReadOnlyListParamReturnVoid--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackWithReadOnlyListParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ZeroArgTaskOfReadOnlyListOfString--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeAnalyzer.cs
  vnext/Microsoft.ReactNative.sln
Labels: Area: Native Modules

#5854 [0.60] DropViews still in ShadowNode registry during UIManager dtor
  change/react-native-windows-2020-08-26-19-52-57-dropview.json
  vnext/ReactWindowsCore/Modules/UIManagerModule.cpp
  vnext/ReactWindowsCore/ShadowNodeRegistry.cpp
  vnext/ReactWindowsCore/ShadowNodeRegistry.h
Labels: AutoMerge

#5897 Integrate 6/18 Nightly RN Build
  change/@office-iss-react-native-win32-2020-09-01-06-04-23-integrate-6-18.json
  change/react-native-windows-2020-09-01-06-04-23-integrate-6-18.json
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/.flowconfig
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/Components/SafeAreaView/SafeAreaView.win32.js
  vnext/.flowconfig
  vnext/ReactCopies/RNTester/js/examples/Image/ImageExample.js
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/SafeAreaView/SafeAreaView.windows.js
  yarn.lock
Labels: AutoMerge

#5888 [Win32] [0.62] A couple of minor style changes in LogBox to avoid win32 asserts.
  change/@office-iss-react-native-win32-2020-08-31-12-43-34-logboxwin32-62.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorStackFrame.win32.js
  packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxStyle.win32.js
  packages/react-native-win32/src/RNTester.ts
  packages/react-native-win32/src/RNTester/js/utils/RNTesterList.win32.ts
  packages/react-native-win32/src/overrides.json
  yarn.lock
Labels: Platform: NetUI

#5893 Keep Templates in react-native-windows Package
  change/@react-native-windows-cli-2020-09-01-03-47-08-vnext-templates.json
  change/react-native-windows-2020-09-01-03-47-08-vnext-templates.json
  docs/react-native-windows-init.md
  packages/@react-native-windows/cli/.gitignore
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/index.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  vnext/.gitignore
  vnext/package.json
  vnext/template/_gitignore
  vnext/template/b_gitignore
  vnext/template/cpp/keys/MyApp_TemporaryKey.pfx
  vnext/template/cpp/proj/MyApp.sln
  vnext/template/cpp/proj/MyApp.vcxproj
  vnext/template/cpp/proj/MyApp.vcxproj.filters
  vnext/template/cpp/proj/packages.config
  vnext/template/cpp/src/App.cpp
  vnext/template/cpp/src/App.h
  vnext/template/cpp/src/App.idl
  vnext/template/cpp/src/AutolinkedNativeModules.g.cpp
  vnext/template/cpp/src/AutolinkedNativeModules.g.h
  vnext/template/cpp/src/AutolinkedNativeModules.g.targets
  vnext/template/cpp/src/MainPage.cpp
  vnext/template/cpp/src/MainPage.h
  vnext/template/cpp/src/MainPage.idl
  vnext/template/cpp/src/PropertySheet.props
  vnext/template/cpp/src/ReactPackageProvider.cpp
  vnext/template/cpp/src/ReactPackageProvider.h
  vnext/template/cpp/src/pch.cpp
  vnext/template/cpp/src/pch.h
  vnext/template/cs/keys/MyApp_TemporaryKey.pfx
  vnext/template/cs/proj/MyApp.csproj
  vnext/template/cs/proj/MyApp.sln
  vnext/template/cs/src/App.xaml.cs
  vnext/template/cs/src/AutolinkedNativeModules.g.cs
  vnext/template/cs/src/AutolinkedNativeModules.g.targets
  vnext/template/cs/src/MainPage.xaml.cs
  vnext/template/cs/src/Properties/AssemblyInfo.cs
  vnext/template/cs/src/Properties/Default.rd.xml
  vnext/template/cs/src/ReactPackageProvider.cs
  vnext/template/index.windows.bundle
  vnext/template/metro.config.js
  vnext/template/shared/assets/LockScreenLogo.scale-200.png
  vnext/template/shared/assets/SplashScreen.scale-200.png
  vnext/template/shared/assets/Square150x150Logo.scale-200.png
  vnext/template/shared/assets/Square44x44Logo.scale-200.png
  vnext/template/shared/assets/Square44x44Logo.targetsize-24_altform-unplated.png
  vnext/template/shared/assets/StoreLogo.png
  vnext/template/shared/assets/Wide310x150Logo.scale-200.png
  vnext/template/shared/proj/NuGet.Config
  vnext/template/shared/src/App.xaml
  vnext/template/shared/src/MainPage.xaml
  vnext/template/shared/src/Package.appxmanifest
Labels: AutoMerge

#5899 Integrate 6/25 Nightly RN Build
  change/@office-iss-react-native-win32-2020-09-01-12-38-44-integrate-6-25.json
  change/react-native-windows-2020-09-01-12-38-44-integrate-6-25.json
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/StyleSheet/StyleSheetValidation.win32.js
  vnext/ReactCopies/IntegrationTests/ReactContentSizeUpdateTest.js
  vnext/ReactCopies/IntegrationTests/SizeFlexibilityUpdateTest.js
  vnext/ReactCopies/RNTester/js/components/RNTesterExampleList.js
  vnext/ReactCopies/RNTester/js/examples/OrientationChange/OrientationChangeExample.js
  vnext/ReactCopies/RNTester/js/types/RNTesterTypes.js
  vnext/ReactCopies/RNTester/js/utils/RNTesterList.ios.js
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/StyleSheet/StyleSheetValidation.windows.js
  vnext/src/RNTester/js/components/RNTesterExampleList.windows.js
  yarn.lock
Labels: Area: Button, AutoMerge

#5902 [Win32] [0.63] A couple of minor style changes in LogBox to avoid win32 asserts
  change/@office-iss-react-native-win32-2020-09-01-13-52-33-logboxstyle63.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/package.json
  packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorStackFrame.win32.js
  packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxStyle.win32.js
  yarn.lock
Labels: AutoMerge

#5904 [0.62] Internal nuget is missing slices
  .ado/templates/prep-and-pack-nuget.yml
  .ado/windows-vs-pr.yml
Labels: Backport to 0.62 Approved, Partner: Office

#5849 Initial AccessibilityInfo implementation
  change/react-native-windows-2020-08-26-11-33-49-accessinfo.json
  packages/E2ETest/wdio/test/VisitAllPages.spec.ts
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp
  vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/just-task.js
  vnext/overrides.json
  vnext/src/RNTester/js/examples/Accessibility/AccessibilityInfoExample.js
  vnext/src/RNTester/js/utils/RNTesterList.windows.ts
Labels: AutoMerge

#5889 Deprecate AppTheme by adding yellowbox warning
  change/react-native-windows-2020-08-31-17-06-38-apptheme-warnonce.json
  vnext/etc/react-native-windows.api.md
  vnext/src/Libraries/AppTheme/AppTheme.ts
Labels: Backport to 0.63 Approved

#5918 Update V8 and Hermes package versions
  change/react-native-windows-2020-09-04-09-54-49-v8reenable.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Directory.Build.targets
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/ReactCommon.vcxproj.filters
Labels: AutoMerge

#5920 [0.63] Add ARM64 Desktop support
  .ado/publish.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-09-04-14-03-34-desktop-arm64-0.63.json
  vnext/Common/Common.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop.Test.DLL/packages.config
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/FollyWin32/FollyWin32.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Desktop/packages.config
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/NuGet.Config
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Test/React.Windows.Test.vcxproj
  vnext/Test/packages.config
Labels: AutoMerge

#5922 [0.62] Add ARM64 Desktop support
  .ado/publish.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-09-04-14-54-59-desktop-arm64-0.62.json
  packages/E2ETest/packages.config
  packages/microsoft-reactnative-sampleapps/packages.config
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  vnext/Desktop.ABITests/packages.config
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.x64.def
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.x86.def
  vnext/Desktop.Test.DLL/packages.config
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/Desktop/packages.config
  vnext/Folly/Folly.vcxproj
  vnext/Folly/packages.config
  vnext/FollyWin32/FollyWin32.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/IntegrationTests/packages.config
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Desktop/packages.config
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/NuGet.Config
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/packages.config
  vnext/ReactUWP/packages.config
  vnext/ReactWindows-Desktop.sln
  vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Scripts/ReactWin32.nuspec
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
  vnext/Test/React.Windows.Test.vcxproj
  vnext/Test/WebSocketServer.cpp
  vnext/Test/WebSocketServer.h
  vnext/Test/packages.config
Labels: AutoMerge

#5923 [0.63] Update V8 and Hermes package versions
  change/react-native-windows-2020-09-04-16-45-40-0.63-stable.json
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.xaml
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.h
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntimeArgs.h
  vnext/JSI/Shared/ScriptStore.h
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/Utils/UwpPreparedScriptStore.h
  vnext/Microsoft.ReactNative/Utils/UwpScriptStore.h
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/BaseScriptStoreImpl.h
  vnext/Shared/DevServerHelper.h
  vnext/Shared/DevSettings.h
  vnext/Shared/DevSupportManager.cpp
  vnext/Shared/DevSupportManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge, Backport to 0.62 Approved, Backport to 0.63 Approved

#5873 [0.63] Fix 5870: In C# CodeGen, don't check for inheritance, but do explicit type checks
  change/react-native-windows-2020-08-31-14-42-17-pr-Fix5870.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/CodeGenMethodTests.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringParamReturnReadOnlyList--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringPromiseReturnVoid--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ReadOnlyListOfStringPromiseReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackWithReadOnlyListParamReturnVoid--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--SingleArgCallbackWithReadOnlyListParamReturnVoid--Sync.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenMethodTests--ZeroArgTaskOfReadOnlyListOfString--Async.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeAnalyzer.cs
  vnext/Microsoft.ReactNative.sln
Labels: Area: Native Modules, Backport to 0.63 Approved

#5947 Make Chrome install optional in rnw-dependencies.ps1
  change/react-native-windows-2020-09-08-18-00-31-rnwdeps-nochrome.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#5944 [0.62] Update V8 and Hermes package versions
  change/react-native-windows-2020-09-08-15-06-41-0.62-stable.json
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.xaml
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.h
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntimeArgs.h
  vnext/JSI/Shared/ScriptStore.h
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactUWP/EndPoints/dll/react-native-uwp.x64.def
  vnext/ReactUWP/EndPoints/dll/react-native-uwp.x86.def
  vnext/ReactWindowsCore/BaseScriptStoreImpl.h
  vnext/ReactWindowsCore/DevServerHelper.h
  vnext/ReactWindowsCore/DevSettings.h
  vnext/ReactWindowsCore/DevSupportManager.cpp
  vnext/ReactWindowsCore/DevSupportManager.h
  vnext/ReactWindowsCore/IDevSupportManager.h
  vnext/ReactWindowsCore/ReactWindowsCore-Desktop.vcxproj
  vnext/ReactWindowsCore/ReactWindowsCore.vcxitems
  vnext/ReactWindowsCore/V8JSIRuntimeHolder.h
  vnext/ReactWindowsCore/packages.ReactWindowsCore-Desktop.config
  vnext/Shared/OInstance.cpp
  vnext/include/ReactUWP/Utils/UwpPreparedScriptStore.h
  vnext/include/ReactUWP/Utils/UwpScriptStore.h
Labels: AutoMerge

#5953 Fix Closing a UWP WebSocket
  change/react-native-windows-2020-09-08-23-00-18-fix-uwp-websocket-close.json
  vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
Labels: AutoMerge

#5740 Fix Text borders not rendering.
  change/react-native-windows-2020-08-14-14-25-20-master.json
  vnext/overrides.json
  vnext/src/Libraries/Text/Text.windows.js
  vnext/src/RNTester/js/examples-win/Text/TextExample.windows.tsx
Labels: Area: Borders and Brushes, Area: Text

#5946 Start Sharing Test Configuration Between Node Projects
  .vscode/extensions.json
  change/@rnw-scripts-babel-node-config-2020-09-08-17-00-10-integration-test-runner.json
  change/@rnw-scripts-jest-debug-config-2020-09-08-17-00-10-integration-test-runner.json
  change/@rnw-scripts-jest-e2e-config-2020-09-08-17-00-10-integration-test-runner.json
  change/@rnw-scripts-jest-unittest-config-2020-09-08-17-00-10-integration-test-runner.json
  change/@rnw-scripts-just-task-2020-09-08-17-00-10-integration-test-runner.json
  change/react-native-platform-override-2020-09-08-17-00-11-integration-test-runner.json
  packages/@rnw-scripts/babel-node-config/babel.config.js
  packages/@rnw-scripts/babel-node-config/package.json
  packages/@rnw-scripts/jest-debug-config/jest.debug.config.js
  packages/@rnw-scripts/jest-debug-config/package.json
  packages/@rnw-scripts/jest-e2e-config/jest.e2e.config.js
  packages/@rnw-scripts/jest-e2e-config/package.json
  packages/@rnw-scripts/jest-unittest-config/jest.unittest.config.js
  packages/@rnw-scripts/jest-unittest-config/package.json
  packages/@rnw-scripts/just-task/just-task.js
  packages/@rnw-scripts/just-task/package.json
  packages/react-native-platform-override/.vscode/launch.json
  packages/react-native-platform-override/jest.config.js
  packages/react-native-platform-override/just-task.js
  packages/react-native-platform-override/package.json
Labels: AutoMerge

#5883 Delete deprecated AppTheme code
  change/react-native-windows-2020-08-31-15-13-43-apptheme.json
  docs/api/react-native-windows.appthemetypes.md
  docs/api/react-native-windows.iappthemechangedevent.currenttheme.md
  docs/api/react-native-windows.iappthemechangedevent.md
  docs/api/react-native-windows.md
  packages/E2ETest/wdio/test/VisitAllPages.spec.ts
  vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.cpp
  vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.h
  vnext/etc/react-native-windows.api.md
  vnext/src/Libraries/AppTheme/AppTheme.ts
  vnext/src/Libraries/AppTheme/AppThemeTypes.ts
  vnext/src/RNTester/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
  vnext/src/RNTester/js/examples-win/Theming/ThemingExample.windows.tsx
  vnext/src/RNTester/js/utils/RNTesterList.windows.ts
Labels: Breaking Change

#5967 Re-enable WebSocketIntegrationTest::SendReceiveSsl
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-09-11-12-27-08-network-server-errors.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.UnitTests/packages.config
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI.Desktop.UnitTests/packages.config
  vnext/Test/WebSocketServer.cpp
  vnext/Test/WebSocketServer.h
Labels: Area: Networking, Area: Tests, AutoMerge, Platform: Desktop

#5983 fix ts warning
  change/@react-native-windows-cli-2020-09-13-13-43-52-cli_9_13.json
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: AutoMerge

#5982 Use Program Files (x86) to locate UWP SDK props/targets
  change/react-native-windows-2020-09-13-13-39-02-CppAppConsumeCSharpModule.json
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
  vnext/PropertySheets/CppAppConsumeCSharpModule.targets
Labels: AutoMerge

#5974 Port REACT_MODULE() from react-native-windows to react-native-macos (1/4)
  change/react-native-windows-2020-09-14-13-50-25-tm-files.json
  vnext/Microsoft.ReactNative.Cxx/Crash.h
  vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValue.h
  vnext/Microsoft.ReactNative.Cxx/JSValueReader.h
  vnext/Microsoft.ReactNative.Cxx/JSValueTreeReader.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValueTreeReader.h
  vnext/Microsoft.ReactNative.Cxx/JSValueTreeWriter.cpp
  vnext/Microsoft.ReactNative.Cxx/JSValueTreeWriter.h
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
  vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.cpp
  vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Cxx/README.md
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactDispatcher.h
  vnext/Microsoft.ReactNative.Cxx/ReactError.h
  vnext/Microsoft.ReactNative.Cxx/ReactHandleHelper.h
  vnext/Microsoft.ReactNative.Cxx/ReactNonAbiValue.h
  vnext/Microsoft.ReactNative.Cxx/ReactNotificationService.h
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.Cxx/StructInfo.h
Labels: AutoMerge

#5997 Update to standard github label: "enhancement"
  .github/ISSUE_TEMPLATE/community-module-support-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Area: Issue Management

#5969 Drop PPL concurrent_queue usage in WinRTWebSocketResource
  change/react-native-windows-2020-09-11-16-19-12-ws-noconcqueue.json
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: Area: Networking, AutoMerge

#5971 Enable using VS previews in run-windows
  change/@react-native-windows-cli-2020-09-11-19-25-55-previewVS.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: Area: Build Infrastructure, AutoMerge

#5993 Enable reload while editing of files in vnext/src
  change/react-native-windows-2020-09-14-14-45-14-fastrefreshplayground.json
  packages/playground/metro.config.js
  vnext/.flowconfig
  vnext/etc/react-native-windows.api.md
  vnext/overrides.json
  vnext/src/Libraries/Components/DatePicker/DatePickerProps.ts
  vnext/src/RNTester/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
  vnext/src/RNTester/js/examples-win/AsyncStorage/AsyncStorageExampleWindows.tsx
  vnext/src/RNTester/js/examples-win/CustomView/CustomViewExample.windows.tsx
  vnext/src/RNTester/js/examples-win/DatePicker/DatePickerExample.windows.tsx
  vnext/src/RNTester/js/examples-win/FastText/FastTextExample.windows.tsx
  vnext/src/RNTester/js/examples-win/Flyout/FlyoutExample.windows.tsx
  vnext/src/RNTester/js/examples-win/Glyph/GlyphExample.tsx
  vnext/src/RNTester/js/examples-win/Keyboard/KeyboardExample.tsx
  vnext/src/RNTester/js/examples-win/Picker/PickerWindowsExample.tsx
  vnext/src/RNTester/js/examples-win/Popup/PopupExample.windows.tsx
  vnext/src/RNTester/js/examples-win/Text/TextExample.windows.tsx
  vnext/src/RNTester/js/examples-win/TransferProperties/TransferPropertiesExample.tsx
  vnext/src/RNTester/js/examples/TextInput/TextInputExample.windows.js
  vnext/src/RNTester/js/utils/RNTesterList.windows.js
Labels: Area: Developer Experience, AutoMerge

#5992 Ingest a new version of Folly, add folly changes to prevent VS 16.8 from breaking the build
  change/react-native-windows-2020-09-14-12-27-48-follyUpdate.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.UnitTests/EmptyUIManagerModule.cpp
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/Folly/Folly.vcxproj.filters
  vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
  vnext/IntegrationTests/TestInstance.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
  vnext/Scripts/Tfs/Layout-Headers.ps1
  vnext/Shared/Modules/UIManagerModule.cpp
  vnext/Shared/Utils.cpp
Labels: Area: Build Infrastructure, Request Backport to 0.60, Request Backport to 0.61, Request Backport to 0.62, Request Backport to 0.63

#5999 Enable Desktop WebSocketModule binary messages
  change/react-native-windows-2020-09-15-11-33-03-ws-jstestextended.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop.UnitTests/WebSocketTest.cpp
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/Modules/WebSocketModule.cpp
  vnext/IntegrationTests/TestInstance.cpp
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
  vnext/Test/WebSocketServer.cpp
  vnext/Test/WebSocketServer.h
  vnext/overrides.json
  vnext/src/IntegrationTests/WebSocketBinaryTest.js
  vnext/src/IntegrationTests/websocket_integration_test_server_binary.js
Labels: Area: Networking, AutoMerge, Invalid Triage, Platform: Desktop, Request Backport to 0.62, Request Backport to 0.63

#6025 Reenable RNTesterIntegrationTests::Logging
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-09-16-16-20-52-deskit-reenablelogging.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
Labels: Area: Tests, AutoMerge

#6023 Port REACT_MODULE() from react-native-windows to react-native-macos (2/4)
  change/react-native-windows-2020-09-16-10-05-25-tm-files.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.Cxx/README.md
  vnext/Microsoft.ReactNative/JsiReader.cpp
  vnext/Microsoft.ReactNative/JsiReader.h
  vnext/Microsoft.ReactNative/JsiWriter.cpp
  vnext/Microsoft.ReactNative/JsiWriter.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Shared/TurboModuleRegistry.h
Labels: Invalid Triage

#6026 Fix rnw-dependencies to work in cases where the VS installer is present but no VS 2019 installation is
  change/react-native-windows-2020-09-16-22-48-43-codespacesDeps.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Build Infrastructure, Area: Developer Experience, Invalid Triage

#6029 Auto-accept git license in rnw-dependencies install script
  change/react-native-windows-2020-09-17-20-39-35-master.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#6039 Run Non-UI-Thread Core Modules on the JS Thread
  change/react-native-windows-2020-09-20-06-37-45-core-js-modules.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.cpp
  vnext/Microsoft.ReactNative/Threading/MessageQueueThreadFactory.h
Labels: AutoMerge

#6042 Upgrade react-native Typings
  change/@office-iss-react-native-win32-2020-09-21-03-02-57-63-typings.json
  change/react-native-windows-2020-09-21-03-02-57-63-typings.json
  docs/api/react-native-windows.dayofweek.md
  docs/api/react-native-windows.ipickeritemdata.md
  docs/api/react-native-windows.ipickeritemdata.textcolor.md
  packages/E2ETest/package.json
  packages/microsoft-reactnative-sampleapps/package.json
  packages/playground/package.json
  packages/react-native-win32/package.json
  vnext/etc/react-native-windows.api.md
  vnext/package.json
  vnext/src/Libraries/Components/Picker/PickerWindows.tsx
  yarn.lock
Labels: AutoMerge

#6040 Don't Elongate Frame-Based Timers
  change/react-native-windows-2020-09-20-07-06-28-too-long-timer.json
  vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
Labels: AutoMerge

#6043 Show a custom view when using integration tests
  packages/IntegrationTest/README.md
  packages/IntegrationTest/TestInstructions.tsx
  packages/IntegrationTest/index.js
  packages/IntegrationTest/index.tsx
  packages/IntegrationTest/package.json
  packages/IntegrationTest/runner/lib/BaseTest.ts
  packages/IntegrationTest/tsconfig.json
  packages/IntegrationTest/windows/integrationtest/MainPage.cpp
  yarn.lock
Labels: AutoMerge

#6044 Add integration tests to mount and measure components
  packages/IntegrationTest/tests/MountComponentTests.tsx
  packages/IntegrationTest/tests/index.ts
Labels: AutoMerge

#6034 Alert should track its xamlroot's size
  change/react-native-windows-2020-09-18-22-49-20-alertTracking.json
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
Labels: Area: Islands

#6054 Remove LocationObserverModule
  change/react-native-windows-2020-09-21-13-17-55-remove-location-observer.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/LocationObserverModule.cpp
  vnext/Microsoft.ReactNative/Modules/LocationObserverModule.h
Labels: AutoMerge

#6062 Increase timeout on JS Checks CI task
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#6045 Better Bundled Test Discovery
  packages/IntegrationTest/.eslintrc.js
  packages/IntegrationTest/package.json
  packages/IntegrationTest/runner/IntegrationTests.test.ts
  packages/IntegrationTest/runner/lib/BaseTest.ts
  packages/IntegrationTest/runner/lib/SkipTest.ts
  packages/IntegrationTest/runner/lib/TestDescription.ts
  packages/IntegrationTest/runner/lib/discoverTests.ts
  packages/IntegrationTest/tests/SampleTests.tsx
  packages/IntegrationTest/tests/lib/TestDefinition.tsx
Labels: AutoMerge

#6069 Ignore filemode for react-native-platform-override Scratch Repository
  change/react-native-platform-override-2020-09-23-03-59-58-less-diff.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
Labels: AutoMerge

#6076 Fixups from folly update
  change/react-native-windows-2020-09-23-13-32-51-fixbuild.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/IntegrationTests/TestInstance.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
Labels: AutoMerge

#6088 Add -UseBasicParsing to all powershell Invoke-WebRequest calls to avoid dependency on IE
  .ado/VSComponentList.ps1
  .ado/templates/integration-test-job.yml
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-09-24-09-10-11-master.json
  vnext/Microsoft.ReactNative/getLayoutProps.ps1
  vnext/Scripts/IntegrationTests.ps1
  vnext/Scripts/Tfs/Install-VSFeatures.ps1
  vnext/Scripts/Tfs/Start-TestServers.ps1
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge

#6092 Flyouts should dismiss when their island changes if they are light dismissable
  change/react-native-windows-2020-09-24-13-22-45-flyoutDismissIslands.json
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
Labels: Area: Flyout

#6094 Use WinRT HTTP module in Desktop
  .ado/windows-vs-pr.yml
  change/react-native-windows-2020-09-25-01-35-29-consolidate-http.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop/Modules/NetworkingModule.cpp
  vnext/Desktop/Modules/NetworkingModule.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/ReactWindows-Desktop.sln
  vnext/Shared/Modules/NetworkingModule.cpp
  vnext/Shared/Modules/NetworkingModule.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/src/IntegrationTests/XHRTest.js
Labels: Area: Networking, Area: Tests, AutoMerge, Platform: Desktop

#6115 Disable AsyncStorage test
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#6109 Rethread After Resuming Timeout Coroutine
  packages/IntegrationTest/windows/integrationtest/TestHostHarness.cpp
Labels: AutoMerge

#6114 Reduce Microsoft.ReactNative PCH By 155MB-260MB
  change/react-native-windows-2020-09-27-10-42-45-reduce-pch.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Pch/pch.h
Labels: AutoMerge

#6111 Free Up Some Memory for react-native-init CI Jobs
  .ado/templates/react-native-init.yml
Labels: AutoMerge

#6116 Fix run-windows Warnings Using Node 14
  change/@react-native-windows-cli-2020-09-28-00-39-44-fix-node14.json
  packages/@react-native-windows/cli/package.json
  yarn.lock
Labels: AutoMerge

#6112 Remove Special UI When Debugger Attached
  change/react-native-windows-2020-09-27-07-13-43-remove-debug-backbutton.json
  vnext/Microsoft.ReactNative/ReactApplication.cpp
Labels: AutoMerge

#6118 Add integration test for C# Interop
  packages/IntegrationTest/tests/InteropCSModuleTests.tsx
  packages/IntegrationTest/tests/index.ts
  packages/IntegrationTest/windows/InteropTestModuleCS/InteropTestModuleCS.csproj
  packages/IntegrationTest/windows/InteropTestModuleCS/Properties/AssemblyInfo.cs
  packages/IntegrationTest/windows/InteropTestModuleCS/ReactPackageProvider.cs
  packages/IntegrationTest/windows/InteropTestModuleCS/TestModuleCS.cs
  packages/IntegrationTest/windows/integrationtest.sln
  packages/IntegrationTest/windows/integrationtest/App.cpp
  packages/IntegrationTest/windows/integrationtest/integrationtest.vcxproj
Labels: AutoMerge

#5373 Simplify react::uwp::IReactInstance
  change/react-native-windows-2020-06-28-11-46-05-PR-SimplifyIReactInstance.json
  vnext/Microsoft.ReactNative/ReactHost/IReactInstance.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.cpp
  vnext/Microsoft.ReactNative/ReactHost/UwpReactInstanceProxy.h
  vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
  vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.h
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Labels: AutoMerge

#5461 Initial ABI-safe JSI implementation
  change/react-native-windows-2020-07-08-10-04-04-PR-JsiValue.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/JSI/Desktop/ChakraJsiRuntime_core.cpp
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntime.h
  vnext/JSI/Universal/ChakraJsiRuntime_edgemode.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiValue.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.IntegrationTests/JsiRuntimeTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/pch.h
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Microsoft.ReactNative/ReactSupport.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Microsoft.ReactNative/XamlHelper.h
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge

#6117 Add macOS Support to react-native-platform-override
  .ado/templates/e2e-test-job.yml
  .ado/templates/integration-test-job.yml
  .ado/templates/macos-tests-job.yml
  .ado/variables/macos.yml
  .ado/windows-vs-pr.yml
  change/react-native-platform-override-2020-09-28-05-28-48-macos-platform-override.json
  change/react-native-windows-2020-09-28-05-28-48-macos-platform-override.json
  packages/react-native-platform-override/README.md
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/Cli.ts
  packages/react-native-platform-override/src/CrossProcessLock.ts
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  packages/react-native-platform-override/src/Hash.ts
  packages/react-native-platform-override/src/Manifest.ts
  packages/react-native-platform-override/src/Override.ts
  packages/react-native-platform-override/src/OverridePrompt.ts
  packages/react-native-platform-override/src/PathUtils.ts
  packages/react-native-platform-override/src/e2etest/Api.test.ts
  packages/react-native-platform-override/src/e2etest/UpgradeStrategy.test.ts
  packages/react-native-platform-override/src/scripts/generateManifest.ts
  packages/react-native-platform-override/src/test/Hash.test.ts
  packages/react-native-platform-override/src/test/Manifest.test.ts
  packages/react-native-platform-override/src/test/MockFileRepository.ts
  packages/react-native-platform-override/src/test/Override.test.ts
  packages/react-native-platform-override/src/test/OverrideFactory.test.ts
  vnext/overrides.json
Labels: Area: Release Process, AutoMerge

#6127 Fix issues that cause fast refresh issues in playground app
  packages/playground/Samples/rntester.tsx
Labels: AutoMerge

#6128 Increase react-native-init CI timeout
  .ado/windows-vs-pr.yml
Labels: AutoMerge
