Repository microsoft/react-native-windows, pull requests merged in 2021-02, with the labels that each got.

#7000 Remove lerna.json from repo
  lerna.json
Labels: AutoMerge

#6987 Allow custom view managers to be able to trigger our logic to run native layout
  change/react-native-windows-083f1165-a2b7-4be3-8e8b-522983f37163.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/IViewManager.idl
Labels: Area: Layout

#6999 Change E2ETest WebDriverIO Runner To Jest
  .ado/jobs/e2e-test.yml
  change/jest-environment-winappdriver-bb3aebdc-c562-4f53-b791-a251d8e522a3.json
  change/react-native-platform-override-315fcb66-5d31-4f0d-a4de-0b972aeea498.json
  docs/e2e-testing.md
  docs/img/SetupOptions1.png
  docs/img/SetupOptions2.png
  docs/img/technicalDecision.png
  docs/img/wdioInternalDependencies.png
  packages/E2ETest/.prettierrc.json
  packages/E2ETest/jest.config.js
  packages/E2ETest/jest.setup.js
  packages/E2ETest/just-task.js
  packages/E2ETest/metro.config.js
  packages/E2ETest/package.json
  packages/E2ETest/test/Helpers.ts
  packages/E2ETest/test/LegacyControlStyleTest.test.ts
  packages/E2ETest/test/LegacyImageTest.test.ts
  packages/E2ETest/test/LegacyLoginTest.test.ts
  packages/E2ETest/test/LegacyTextBackgroundColorTest.test.ts
  packages/E2ETest/test/LegacyTextInputTest.test.ts
  packages/E2ETest/test/visitAllPages.test.ts
  packages/E2ETest/tsconfig.json
  packages/E2ETest/wdio.conf.js
  packages/jest-environment-winappdriver/.eslintrc.js
  packages/jest-environment-winappdriver/.gitignore
  packages/jest-environment-winappdriver/README.md
  packages/jest-environment-winappdriver/package.json
  packages/jest-environment-winappdriver/src/WinAppDriverEnvironment.ts
  packages/jest-environment-winappdriver/tsconfig.json
  packages/react-native-platform-override/src/e2etest/FileSystemRepository.test.ts
  packages/react-native-platform-override/src/test/OverrideFactory.test.ts
  yarn.lock
Labels: AutoMerge

#7011 Fix deep linking activation
  change/react-native-windows-93385742-18a3-4c29-b83b-1b87733bb4ce.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.h
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
  vnext/template/cpp-app/src/App.cpp
  vnext/template/cpp-app/src/App.h
  vnext/template/cs-app/src/App.xaml.cs
Labels: AutoMerge

#7004 Move `react-native-windows-codegen` to `@react-native-windows/codegen`
  .unbroken_exclusions
  change/@react-native-windows-codegen-7bc2ad5c-8c57-49f8-9227-a50f3756b196.json
  change/react-native-windows-f26d78c2-e74a-4b34-8f5e-1f6d03088a22.json
  packages/@react-native-windows/codegen/.eslintrc.js
  packages/@react-native-windows/codegen/.gitignore
  packages/@react-native-windows/codegen/.vscode/launch.json
  packages/@react-native-windows/codegen/CHANGELOG.json
  packages/@react-native-windows/codegen/CHANGELOG.md
  packages/@react-native-windows/codegen/README.md
  packages/@react-native-windows/codegen/bin.js
  packages/@react-native-windows/codegen/jest.config.js
  packages/@react-native-windows/codegen/package.json
  packages/@react-native-windows/codegen/src/Cli.ts
  packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
  packages/@react-native-windows/codegen/tsconfig.json
  packages/microsoft-reactnative-sampleapps/just-task.js
  packages/microsoft-reactnative-sampleapps/package.json
  vnext/just-task.js
  vnext/package.json
Labels: AutoMerge

#7019 Initialize ETW provider only once
  change/react-native-windows-df0a05f5-87f4-41ae-a165-0a455e0278fa.json
  vnext/Shared/tracing/tracing.cpp
Labels: AutoMerge

#7021 Consolidate duplicated clang-format files
  .clang-format
  change/react-native-windows-21105154-726e-4db2-b628-0b0cc91edc42.json
  package.json
  packages/.clang-format
  vnext/.clang-format
Labels: AutoMerge

#7022 Explicit Versions for @types/node
  change/@react-native-windows-bot-coordinator-93280c6b-ee04-432d-a636-953f1f0d5597.json
  change/@react-native-windows-cli-5c22f1da-6349-447d-97a5-3bd45f5fbb59.json
  change/@react-native-windows-find-repo-root-2900c849-30fc-4cde-9ba7-25a43b169a9a.json
  change/@react-native-windows-package-utils-88737125-03b9-476d-969d-4e9ac38d005f.json
  change/@react-native-windows-telemetry-2e427389-3882-447a-8ae7-9536cdee4f3b.json
  change/@rnw-scripts-babel-node-config-ed7daff2-0e39-43af-aa44-bc3dd915e6fa.json
  change/@rnw-scripts-create-github-releases-60d9da20-21ca-47e3-b9e2-82f8a4c2ba7d.json
  change/@rnw-scripts-format-files-fe2971dc-d71d-419c-9ce2-341242b3f3ed.json
  change/@rnw-scripts-integrate-rn-81b455ce-f0a8-4df3-9f91-78be8f90f9d8.json
  change/@rnw-scripts-just-task-aae3dd35-0360-40ef-b747-665ece66c689.json
  change/@rnw-scripts-promote-release-897e7676-fb1c-45c9-9bba-c5665509e304.json
  change/@rnw-scripts-take-screenshot-77f1a348-7b1d-4748-afdc-1de5f1823152.json
  change/jest-environment-winappdriver-65e73737-f89a-48ee-85e5-ffa4f2958de2.json
  change/react-native-platform-override-b609a92a-4f66-41d5-b415-78e06b5d421a.json
  change/react-native-windows-904125b5-b938-476d-b4c6-b492dac8285c.json
  change/react-native-windows-codegen-de7f4f20-fcba-436a-9556-35ee42bcecf5.json
  change/react-native-windows-init-d6aae379-bc7c-4396-a387-a84c9e089bfc.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/codegen/package.json
  packages/@react-native-windows/find-repo-root/package.json
  packages/@react-native-windows/package-utils/package.json
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/tester/package.json
  packages/@rnw-bots/coordinator/package.json
  packages/@rnw-scripts/babel-node-config/package.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/@rnw-scripts/just-task/package.json
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/take-screenshot/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/jest-environment-winappdriver/package.json
  packages/playground/package.json
  packages/react-native-platform-override/package.json
  packages/react-native-windows-init/package.json
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: Area: Build Infrastructure, AutoMerge

#7037 [0.62] Fixing FocusManager Export Statement
  change/@office-iss-react-native-win32-04ef7902-7cd5-462a-8d77-700b2af7c376.json
  packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
  packages/react-native-win32/src/RNTester/APIExamples/FocusManagerAPI.tsx
  packages/react-native-win32/src/RNTester/js/utils/RNTesterList.win32.ts
  packages/react-native-win32/src/overrides.json
Labels: Backported to 0.62

#7062 [0.64] Fix the Switch component
  change/react-native-windows-7534745f-9f5e-4da9-8f97-bcc1125f57ad.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: Area: Switch, Backport to 0.64 Approved

#7061 [FIX] Switch component not working.
  change/react-native-windows-d1742e8e-85f4-4dc4-a93c-5d9f3948f50e.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: Area: Switch, AutoMerge, Request Backport to 0.64

#7044 Doxysaurus tool to generate docs for C++
  .unbroken_exclusions
  change/@rnw-scripts-doxysaurus-bd740643-6485-4762-ae8c-d7e8d83c77d9.json
  change/react-native-windows-f8e967c0-8a91-47d2-a92e-d5920bf85743.json
  package.json
  packages/@rnw-scripts/doxysaurus/.eslintrc.js
  packages/@rnw-scripts/doxysaurus/.gitignore
  packages/@rnw-scripts/doxysaurus/.vscode/launch.json
  packages/@rnw-scripts/doxysaurus/bin.js
  packages/@rnw-scripts/doxysaurus/just-task.js
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/config.ts
  packages/@rnw-scripts/doxysaurus/src/doc-model.ts
  packages/@rnw-scripts/doxysaurus/src/doxygen-model.ts
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  packages/@rnw-scripts/doxysaurus/src/doxysaurus.ts
  packages/@rnw-scripts/doxysaurus/src/logger.ts
  packages/@rnw-scripts/doxysaurus/src/markdown.ts
  packages/@rnw-scripts/doxysaurus/src/renderer.ts
  packages/@rnw-scripts/doxysaurus/src/test/markdown.test.ts
  packages/@rnw-scripts/doxysaurus/src/test/string-template.ts
  packages/@rnw-scripts/doxysaurus/src/transformer.ts
  packages/@rnw-scripts/doxysaurus/templates/cpp/class.md.mustache
  packages/@rnw-scripts/doxysaurus/tsconfig.json
  vnext/.editorconfig
  vnext/Microsoft.ReactNative.Cxx/cppapi.md.mustache
  vnext/Microsoft.ReactNative.Cxx/doxysaurus.json
  vnext/doxysaurus.json
  yarn.lock
Labels: AutoMerge

#7073 Bump just-scripts from 1.3.2 to 1.3.3
  change/@office-iss-react-native-win32-147f8efd-e57e-45b7-8d21-b75ff9a18d9a.json
  change/@react-native-windows-cli-073bad92-7805-45eb-a564-66fe4c19c04f.json
  change/@react-native-windows-codegen-3c3ba1eb-3ff5-477c-a221-4186855a8c2d.json
  change/@react-native-windows-find-repo-root-b0e617b4-a125-4c4f-a87c-4613660cb888.json
  change/@react-native-windows-package-utils-2a7c89b7-b734-413f-bfed-7c1a0f064268.json
  change/@react-native-windows-telemetry-cdc2aac1-662b-4da8-90fd-75a849fda18d.json
  change/@rnw-bots-coordinator-e726a1ca-65fc-41c7-9b97-eed3b0070454.json
  change/@rnw-scripts-create-github-releases-36ba47b9-bb23-45a8-b3f7-13e44ad378aa.json
  change/@rnw-scripts-doxysaurus-0bb5a110-e53b-40a5-a058-759ca29c833d.json
  change/@rnw-scripts-format-files-4b79ce37-6eab-4701-9e0e-453d8536746c.json
  change/@rnw-scripts-integrate-rn-ba635706-84cb-418d-a0d3-3e1eab1bc794.json
  change/@rnw-scripts-just-task-b21d4a39-79cb-4f89-ae7c-f677200e7bf9.json
  change/@rnw-scripts-promote-release-85c97f1a-e620-4db9-b529-c8fd42fdbacb.json
  change/@rnw-scripts-take-screenshot-e7ae83b1-f3b5-4df4-91d3-ab37c846b6bb.json
  change/jest-environment-winappdriver-902ff49a-e262-4758-938c-6f33235d2e47.json
  change/react-native-platform-override-a93a4fc5-464b-4111-ac10-6bee76c072b4.json
  change/react-native-windows-b46edf0c-b715-4a79-ba2b-f2427136e1ec.json
  change/react-native-windows-init-444bcb68-ef22-4912-a75d-f47b5ed4e156.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/codegen/package.json
  packages/@react-native-windows/find-repo-root/package.json
  packages/@react-native-windows/package-utils/package.json
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/tester/package.json
  packages/@rnw-bots/coordinator/package.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/@rnw-scripts/just-task/package.json
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/take-screenshot/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/jest-environment-winappdriver/package.json
  packages/playground/package.json
  packages/react-native-platform-override/package.json
  packages/react-native-windows-init/package.json
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#7076 Integration Test App Not Running in CI
  .ado/jobs/integration-test.yml
Labels: AutoMerge

#7075 Rename "BuildFlags.props" to "ExperimentalFeatures.props"
  change/@react-native-windows-cli-47fde414-2467-4de2-b40b-692de82bd608.json
  change/@rnw-scripts-jest-e2e-config-a503dae5-ee1f-45d0-81c0-ec4c420798c8.json
  change/@rnw-scripts-jest-unittest-config-c0a69118-0415-4a21-ad5c-fa0678cc41c2.json
  change/@rnw-scripts-just-task-fad85a22-7268-43f5-9d30-96be951d1f44.json
  change/react-native-windows-58bfeb4d-b061-414b-a3d3-e062048b6832.json
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
  packages/@react-native-windows/cli/src/e2etest/dependencyConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projects/WithWinUI3/react-native.config.js
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@rnw-scripts/jest-e2e-config/jest.e2e.config.js
  packages/@rnw-scripts/jest-unittest-config/jest.unittest.config.js
  packages/@rnw-scripts/just-task/just-task.js
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
  vnext/template/cs-app/proj/MyApp.csproj
  vnext/template/shared-app/proj/BuildFlags.props
  vnext/template/shared-app/proj/ExperimentalFeatures.props
  vnext/template/shared-lib/proj/ExperimentalFeatures.props
Labels: AutoMerge, Request Backport to 0.64

#7079 Better dependency warning on run-windows build error
  change/@react-native-windows-cli-577379f2-2f69-4382-ae0f-f986dd33a54d.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: AutoMerge

#7013 [0.64] Allow custom view managers to be able to trigger our logic to run native layout
  change/react-native-windows-785074ae-3954-43ad-ba5e-3748ce89c855.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/IViewManager.idl
Labels: AutoMerge

#7060 Refactor autolink
  change/@react-native-windows-bot-coordinator-93280c6b-ee04-432d-a636-953f1f0d5597.json
  change/@react-native-windows-cli-c48edaa2-72ae-491f-8df9-1adb209250c1.json
  change/react-native-windows-9817c255-bfd0-4684-bee6-a9cb26adc289.json
  change/react-native-windows-codegen-de7f4f20-fcba-436a-9556-35ee42bcecf5.json
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projectConfig.utils.ts
  packages/@react-native-windows/cli/src/e2etest/projects/MissingProjectFilesApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppApp/react-native.config.js
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  vnext/template/shared-lib/proj/BuildFlags.props
  vnext/template/shared-lib/proj/ExperimentalFeatures.props
Labels: AutoMerge

#6984 Improve compile time by increasing paralelism
  change/react-native-windows-a5f6672e-a543-4e67-912f-d0b401953d2d.json
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
Labels: AutoMerge

#7059 [0.62] TextWin32 focusable property backport
  change/@office-iss-react-native-win32-2021-02-05-17-42-07-0.62-textFocusable.json
  packages/react-native-win32/docs/api/react-native-win32.accessibilityannotationinfo.md
  packages/react-native-win32/docs/api/react-native-win32.buttonwin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.buttonwin32.render.md
  packages/react-native-win32/docs/api/react-native-win32.colorstop.md
  packages/react-native-win32/docs/api/react-native-win32.focusmanager.focus.md
  packages/react-native-win32/docs/api/react-native-win32.focusmanager.md
  packages/react-native-win32/docs/api/react-native-win32.ibuttonwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.idimensions.md
  packages/react-native-win32/docs/api/react-native-win32.inativekeyboardevent.md
  packages/react-native-win32/docs/api/react-native-win32.ipersonacoinprops.md
  packages/react-native-win32/docs/api/react-native-win32.iposition.md
  packages/react-native-win32/docs/api/react-native-win32.ipressinlocation.md
  packages/react-native-win32/docs/api/react-native-win32.irespondersyntheticevent.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.focusable.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onblur.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onblurcapture.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onfocus.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onfocuscapture.md
  packages/react-native-win32/docs/api/react-native-win32.itouchablewin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itouchablewin32state.md
  packages/react-native-win32/docs/api/react-native-win32.itouchinfo.md
  packages/react-native-win32/docs/api/react-native-win32.iviewwin32.md
  packages/react-native-win32/docs/api/react-native-win32.md
  packages/react-native-win32/docs/api/react-native-win32.nativeordynamiccolortype.md
  packages/react-native-win32/docs/api/react-native-win32.platformcolor.md
  packages/react-native-win32/docs/api/react-native-win32.textwin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.textwin32.render.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32._constructor_.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.componentwillunmount.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.md
  packages/react-native-win32/docs/api/react-native-win32.touchablewin32.render.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/src/Libraries/Components/Text/Tests/TextWin32Test.tsx
  packages/react-native-win32/src/Libraries/Components/Text/TextWin32.Props.ts
  packages/react-native-win32/src/Libraries/Text/Text.win32.js
  packages/react-native-win32/src/RNTester/js/RNTesterApp.win32.tsx
  packages/react-native-win32/src/RNTester/js/utils/RNTesterList.win32.ts
  packages/react-native-win32/src/overrides.json
Labels: AutoMerge, Request Backport to 0.62

#7085 Minor doc update
  change/react-native-windows-72d98117-3a3c-4581-8a20-f710c8890699.json
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
Labels: AutoMerge

#7095 Make most autolink FS operations async
  change/@react-native-windows-cli-8b43c495-33e7-4911-a6ee-aa9451b43017.json
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge

#7100 Do not try to execute snapshots in Jest debug config
  change/@rnw-scripts-jest-debug-config-8b535a05-86da-456e-aaf3-598af0fe44e8.json
  packages/@rnw-scripts/jest-debug-config/jest.debug.config.js
Labels: AutoMerge

#7102 Fixed typo in template which breaks C# autolinking
  change/react-native-windows-7dad67fd-f462-4483-9c48-ce1cd160f497.json
  vnext/template/cs-app/src/AutolinkedNativeModules.g.cs
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64

#7105 Fix all package typos
  change/react-native-windows-8cdef933-8580-42d9-bab3-b70a988404d8.json
  docs/testing-nuget-packages.md
  packages/README.md
  packages/react-native-platform-override/CHANGELOG.json
  packages/react-native-platform-override/CHANGELOG.md
  vnext/.npmignore
  vnext/CHANGELOG.json
  vnext/CHANGELOG.md
  vnext/Shared/PackagerConnection.h
Labels: AutoMerge

#7103 [0.64] Fixed typo in template which breaks C# autolinking
  change/react-native-windows-0d853b9b-5e62-4dff-8275-f02def99492d.json
  vnext/template/cs-app/src/AutolinkedNativeModules.g.cs
Labels: AutoMerge

#7104 [0.63] Fixed typo in template which breaks C# autolinking
  change/@react-native-windows-cli-2021-02-11-09-44-26-autolinktypo63.json
  packages/@react-native-windows/cli/templates/cs/src/AutolinkedNativeModules.g.cs
Labels: AutoMerge

#7082 [0.64] Update pathval to 1.1.1 (#7036)
  yarn.lock
Labels: AutoMerge

#7056 [FIX] Cursor resetting in TextInput
  change/react-native-windows-2dead2dd-8acc-4a17-a3f2-7e3091cde5ad.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: TextInput, Backport to 0.64 Approved

#7134 Fix indentation on AutolinkedNativeModules.g.targets
  change/@react-native-windows-cli-511afd68-8e89-4c3c-b42d-d94ebb98f5d7.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge

#7133 Update WinUI 3 to Preview 4
  change/@react-native-windows-cli-d560e28e-3435-4742-9cdd-fb9c81be8183.json
  change/react-native-windows-0e74e256-80a2-43d5-8cf9-9872a209075f.json
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/playground/windows/Playground-win32 (Package)/Playground-win32 (Package).wapproj
  packages/playground/windows/playground/packages.config
  vnext/Microsoft.ReactNative/XamlView.cpp
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/WinUI.props
Labels: AutoMerge

#7092 [0.63] TextWin32 focusable property backport
  change/@office-iss-react-native-win32-2021-02-11-12-49-00-0.63-textFocusable.json
  packages/react-native-win32/docs/api/react-native-win32.focusmanager.focus.md
  packages/react-native-win32/docs/api/react-native-win32.focusmanager.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.focusable.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onblur.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onblurcapture.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onfocus.md
  packages/react-native-win32/docs/api/react-native-win32.itextwin32props.onfocuscapture.md
  packages/react-native-win32/docs/api/react-native-win32.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/Components/Text/Tests/TextWin32Test.tsx
  packages/react-native-win32/src/Libraries/Components/Text/TextWin32.Props.ts
  packages/react-native-win32/src/Libraries/Text/Text.win32.js
  packages/react-native-win32/src/RNTester/js/utils/RNTesterList.win32.js
Labels: Area: Text, Backport to 0.63 Approved

#7142 [0.63] Workaround arm64 compiler bug for internal consumption
  change/react-native-windows-2021-02-16-10-55-56-follyarm64.json
  vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
Labels: AutoMerge

#7146 Fixes autolink check error to include command to fix it
  change/@react-native-windows-cli-280a57c0-befb-4056-8cbf-0e2417f689a9.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: Area: Build Infrastructure

#7001 Integrate 1/31 Nightly RN Build
  change/@office-iss-react-native-win32-bb8330b8-bbb4-48e4-96dc-6db53c712419.json
  change/node-rnw-rpc-dc56923c-03d3-415c-995a-98a0db94419c.json
  change/react-native-windows-10cb1559-64ce-48aa-8545-7373942abac3.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32-tester/src/js/components/ListExampleShared.win32.js
  packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/NativeAccessibilityInfo.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/legacySendAccessibilityEvent.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Inspector/Inspector.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/components/ListExampleShared.js
  packages/@react-native/tester/js/examples/Accessibility/AccessibilityExample.js
  packages/@react-native/tester/js/examples/FlatList/FlatListExample.js
  packages/@react-native/tester/js/examples/MultiColumn/MultiColumnExample.js
  packages/@react-native/tester/js/examples/ScrollView/ScrollViewExample.js
  packages/@react-native/tester/js/examples/SectionList/SectionListExample.js
  packages/@react-native/tester/js/examples/TextInput/TextInputSharedExamples.js
  packages/@react-native/tester/js/types/RNTesterTypes.js
  packages/@react-native/tester/overrides.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/node-rnw-rpc/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/.flowconfig
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js
  vnext/src/Libraries/Components/AccessibilityInfo/legacySendAccessibilityEvent.windows.js
  vnext/src/Libraries/Components/RefreshControl/RefreshControl.windows.js
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Components/Touchable/TouchableHighlight.windows.js
  vnext/src/Libraries/Components/Touchable/TouchableOpacity.windows.js
  vnext/src/Libraries/ReactNative/PaperUIManager.windows.js
  vnext/src/Libraries/Text/Text.windows.js
  yarn.lock
Labels: AutoMerge

#7135 WinUI 3 DesktopBridge
  change/react-native-windows-f0d8b5ff-cae1-4de8-864b-cf88d6005137.json
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  vnext/Microsoft.ReactNative.Cxx/DesktopWindowBridge.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative/DesktopWindowMessage.cpp
  vnext/Microsoft.ReactNative/DesktopWindowMessage.h
  vnext/Microsoft.ReactNative/DesktopWindowMessage.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.cpp
  vnext/Microsoft.ReactNative/Modules/AppThemeModuleUwp.h
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/Utils/Helpers.cpp
  vnext/Microsoft.ReactNative/Utils/Helpers.h
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/Microsoft.ReactNative/XamlUIService.cpp
  vnext/Microsoft.ReactNative/XamlUIService.h
  vnext/Microsoft.ReactNative/XamlUIService.idl
Labels: AutoMerge

#7137 Add IViewManagerCreateWithProperties to allow VMs to change behavior …
  change/react-native-windows-146a8181-a6f2-4fe4-83bd-3938080c3b8f.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/GlyphViewManager.cpp
  vnext/Microsoft.ReactNative/GlyphViewManager.h
  vnext/Microsoft.ReactNative/IViewManager.idl
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Views/ActivityIndicatorViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ActivityIndicatorViewManager.h
  vnext/Microsoft.ReactNative/Views/DatePickerViewManager.cpp
  vnext/Microsoft.ReactNative/Views/DatePickerViewManager.h
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.h
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.h
  vnext/Microsoft.ReactNative/Views/PaperShadowNode.h
  vnext/Microsoft.ReactNative/Views/PickerViewManager.cpp
  vnext/Microsoft.ReactNative/Views/PickerViewManager.h
  vnext/Microsoft.ReactNative/Views/PopupViewManager.cpp
  vnext/Microsoft.ReactNative/Views/PopupViewManager.h
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.h
  vnext/Microsoft.ReactNative/Views/RefreshControlManager.cpp
  vnext/Microsoft.ReactNative/Views/RefreshControlManager.h
  vnext/Microsoft.ReactNative/Views/RootViewManager.cpp
  vnext/Microsoft.ReactNative/Views/RootViewManager.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.h
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
  vnext/Microsoft.ReactNative/Views/SliderViewManager.cpp
  vnext/Microsoft.ReactNative/Views/SliderViewManager.h
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.cpp
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.h
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.h
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ViewViewManager.h
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: Area: View Managers, AutoMerge

#7153 Fix DevMenuControl.xbf copy conflict
  change/react-native-windows-bac296d9-c8c9-452c-861e-6e9a1fa7872a.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
Labels: AutoMerge, Request Backport to 0.64

#7156 [Perf] Make DesktopWindowMessage a struct
  change/react-native-windows-c44975c5-8aed-438b-8e0e-23e8477101f8.json
  vnext/Microsoft.ReactNative.Cxx/DesktopWindowBridge.h
  vnext/Microsoft.ReactNative/DesktopWindowMessage.cpp
  vnext/Microsoft.ReactNative/DesktopWindowMessage.h
  vnext/Microsoft.ReactNative/DesktopWindowMessage.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
Labels: AutoMerge

#7159 Drop WebSocketModule integration tests
  .ado/jobs/desktop.yml
  change/react-native-windows-4905afd2-6809-40c0-bc71-3d60ca037470.json
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj.filters
  vnext/Desktop.IntegrationTests/WebSocketModuleIntegrationTest.cpp
Labels: Area: Networking, Area: Tests, AutoMerge, Platform: Desktop

#7132 [0.64] cherry pick TextWin32 focusable property
  change/@office-iss-react-native-win32-8f4adb11-4a5d-42d6-a166-bf256e702420.json
  packages/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/Components/Text/Tests/TextWin32Test.tsx
  packages/react-native-win32/src/Libraries/Components/Text/TextWin32.Props.ts
  packages/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
Labels: Area: Text, Request Backport to 0.64

#7163 [0.64] Port deployment changes (use DeployAppRecipe in CLI)
  change/@react-native-windows-cli-447231bd-7fc0-40af-8fd3-fc4cc93c6733.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Labels: AutoMerge, Request Backport to 0.64

#7165 Fix projectName issue with C# projects and deploy tool version check
  change/@react-native-windows-cli-574dfc33-3d0e-4e33-9f03-16ee0384aead.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/config/projectConfig.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: AutoMerge

#7173 Fixes missing image size in Image onLoad event
  change/react-native-windows-c597c4ed-90a3-4cbe-81a9-2a9c993edcde.json
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
Labels: AutoMerge

#7166 Fix links in markdown docs in 0.64
  docs/e2e-testing.md
  docs/managedCodeGen.md
Labels: AutoMerge, Request Backport to 0.64

#7182 Solutions with Any CPU projects get wrongly autolinked
  change/@react-native-windows-cli-da7e3b1b-b355-47f3-ac10-44a00c0fd093.json
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Labels: AutoMerge

#7157 [0.64] view manager create with properties
  change/react-native-windows-52911e44-a979-4ebf-a182-095f9e698d72.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/GlyphViewManager.cpp
  vnext/Microsoft.ReactNative/GlyphViewManager.h
  vnext/Microsoft.ReactNative/IViewManager.idl
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Views/ActivityIndicatorViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ActivityIndicatorViewManager.h
  vnext/Microsoft.ReactNative/Views/DatePickerViewManager.cpp
  vnext/Microsoft.ReactNative/Views/DatePickerViewManager.h
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.h
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.h
  vnext/Microsoft.ReactNative/Views/PaperShadowNode.h
  vnext/Microsoft.ReactNative/Views/PickerViewManager.cpp
  vnext/Microsoft.ReactNative/Views/PickerViewManager.h
  vnext/Microsoft.ReactNative/Views/PopupViewManager.cpp
  vnext/Microsoft.ReactNative/Views/PopupViewManager.h
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.h
  vnext/Microsoft.ReactNative/Views/RefreshControlManager.cpp
  vnext/Microsoft.ReactNative/Views/RefreshControlManager.h
  vnext/Microsoft.ReactNative/Views/RootViewManager.cpp
  vnext/Microsoft.ReactNative/Views/RootViewManager.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.h
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
  vnext/Microsoft.ReactNative/Views/SliderViewManager.cpp
  vnext/Microsoft.ReactNative/Views/SliderViewManager.h
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.cpp
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.h
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.h
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ViewViewManager.h
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: AutoMerge, Request Backport to 0.64

#7193 Fixes race conditions for ReactImage
  change/react-native-windows-91ae018b-5e13-44ec-8d2a-0105ccd5303b.json
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
Labels: AutoMerge

#7207 Fix DispatchEvent for events that don't have a sender
  change/react-native-windows-923d9c58-108f-4eb0-9f78-dfa4daabec03.json
  vnext/Microsoft.ReactNative/XamlUIService.cpp
Labels: AutoMerge

#7198 [Image] add svg data uri support
  change/react-native-windows-ee1c3de0-f55d-4e41-b8eb-ee207275d2de.json
  packages/playground/Samples/image.tsx
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
Labels: Area: Image

#7218 Revert "Fix DispatchEvent for events that don't have a sender"
  change/react-native-windows-a032e591-3908-4bf5-90a6-4b8972478e89.json
  vnext/Microsoft.ReactNative/XamlUIService.cpp
Labels: AutoMerge

#7216 [0.64] [Image] add svg data uri support (#7198)
  change/react-native-windows-ee1c3de0-f55d-4e41-b8eb-ee207275d2de.json
  packages/playground/Samples/image.tsx
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
Labels: Backport to 0.64 Approved

#7217 Update e2e doc with info about configuring WinAppDriver path
  change/jest-environment-winappdriver-6f4a1d63-2951-4e4a-a78d-18f76018c64e.json
  docs/e2e-testing.md
  packages/jest-environment-winappdriver/README.md
Labels: AutoMerge
