Repository microsoft/react-native-windows, pull requests merged in 2021-05, with the labels that each got.

#7706 Add a 📦 prefix to dependabot updates and clear ignored updates as we have moved past those versions
  .github/dependabot.yml
Labels: AutoMerge

#7658 Controlled TextInput doesn't work most of the time
  change/react-native-windows-9aaace3c-20a8-4c24-90b2-d777742f65ba.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
Labels: Area: TextInput, AutoMerge, Request Backport to 0.64

#7707 Fix Text.BackgroundColor overwriting foreground.
  change/react-native-windows-5f544542-d759-45c2-891d-280ea52d6dc5.json
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextBackgroundColorTestPage.tsx
  packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
  packages/e2e-test-app/test/__snapshots__/LegacyTextBackgroundColorTest.test.ts.snap
  packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: Area: Text, AutoMerge, Request Backport to 0.64

#7718 [0.63] Update V8 package version
  change/react-native-windows-2021-05-03-17-14-25-v8-91-63.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/DevSettings.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#7716 Add check to cancel publish if the last commit was itself a publish
  .ado/publish.yml
Labels: Area: Build Infrastructure

#7713 [0.64] Controlled TextInput doesn't work most of the time
  change/react-native-windows-9aaace3c-20a8-4c24-90b2-d777742f65ba.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
Labels: AutoMerge, Backport to 0.64 Approved

#7725 [0.64] Add check to cancel publish if the last commit was itself a publish (#7716)
  .ado/publish.yml
Labels: Area: Build Infrastructure, AutoMerge

#7653 [0.64] Update Microsoft.ChakraCore to 1.11.24 (#7628)
  change/react-native-windows-c71b291f-aa9a-4aef-81e2-2aeb2fce0156.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/JSI.Desktop.UnitTests/packages.config
Labels: AutoMerge

#7727 [0.64] [Perf infra] Port ETW eventing
  change/react-native-windows-df0a05f5-87f4-41ae-a165-0a455e0278fa.json
  change/react-native-windows-f33f3a80-612e-479a-8d8c-c51c611b8e29.json
  docs/tracing.md
  vnext/Scripts/Tracing/Start-Tracing.ps1
  vnext/Scripts/Tracing/Stop-Tracing.ps1
  vnext/Scripts/Tracing/rnw.wprp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/etw/build.bat
  vnext/Shared/etw/react_native_windows.h
  vnext/Shared/etw/react_native_windows.man
  vnext/Shared/etw/react_native_windows_etw_res.dll
  vnext/Shared/etw/register.bat
  vnext/Shared/tracing/tracing.cpp
Labels: Area: Performance, AutoMerge

#7732 Fix ReactContext::DispatchEvent
  change/react-native-windows-e84bc040-e439-490a-9ecc-25bbfc3bace2.json
  packages/sample-apps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp
  vnext/Microsoft.ReactNative.Cxx/ReactContext.h
  vnext/Microsoft.ReactNative/XamlUIService.cpp
Labels: AutoMerge, Breaking Change, Request Backport to 0.64

#7714 Update Button Styling for Windows
  change/react-native-windows-2237dc3b-a41e-4123-82db-f5b24fbba30b.json
  packages/playground/windows/playground/packages.config
  vnext/src/Libraries/Components/Button.windows.js
Labels: Area: Button, Area: Theming

#7736 Remove legacy UWP WebSocket module
  change/react-native-windows-4e10fef7-1a9b-4ffe-a202-cc15ab617854.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/CreateModules.cpp
  vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.cpp
  vnext/Microsoft.ReactNative/Modules/WebSocketModuleUwp.h
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/Shared/CreateModules.h
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/OInstance.cpp
Labels: Area: Networking

#7744 Move fmt project into 'Dependencies (External)' folder
  change/react-native-windows-ffcdc494-3894-4cab-959f-74454c11ec32.json
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.sln
Labels: AutoMerge

#7741 Fix warnings and improve C++ includes
  change/react-native-windows-548b5046-c186-44ea-9510-e3287ded9bd8.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso/motifCpp/assert_IgnorePlat_emptyImpl.h
  vnext/Mso/motifCpp/assert_motifApi.h
  vnext/Mso/motifCpp/gTestAdapter.h
  vnext/Mso/motifCpp/libletAwareMemLeakDetection.h
  vnext/Mso/motifCpp/motifCppTest.h
  vnext/Mso/motifCpp/motifCppTestBase.h
  vnext/Mso/motifCpp/testCheck.h
  vnext/Mso/motifCpp/testInfo.h
  vnext/Shared/PackagerConnection.cpp
  vnext/Shared/Utils/CppWinrtLessExceptions.h
Labels: AutoMerge

#7754 [0.64] Upgrade JSI.Desktop projects version of ChakraCore
  change/react-native-windows-6cf29aac-2b5c-4473-afaa-ccf94811fd9d.json
  vnext/JSI.Desktop.UnitTests/JSI.Desktop.UnitTests.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Desktop/packages.config
Labels: AutoMerge, security

#7755 Generate cgmanifest.json for downloaded source dependencies
  change/react-native-windows-3db98399-3dfa-4e81-83ff-3d300267ac38.json
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: Request Backport to 0.64

#7759 Hook up fabric view component codegen
  .gitattributes
  change/@react-native-windows-codegen-8bf5b93f-6631-4c78-9860-a9e27b71521e.json
  change/@rnw-scripts-format-files-04311b1d-6be6-4a29-a7ad-193f9d1481e8.json
  change/react-native-windows-5b852b93-ed97-49c0-a263-a649a03c12fa.json
  packages/@react-native-windows/codegen/src/Cli.ts
  packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
  vnext/Microsoft.ReactNative/Fabric/ActivityIndicatorComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/ActivityIndicatorComponentView.h
  vnext/Microsoft.ReactNative/Fabric/ComponentViewRegistry.cpp
  vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Fabric/platform/react/components/image/conversions.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/ConcreteViewShadowNode.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/ViewEventEmitter.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/ViewProps.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/core/ConcreteComponentDescriptor.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/core/propsConversions.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/graphics/Color.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/imagemanager/primitives.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/codegen/.clang-format
  vnext/codegen/react/components/rnwcore/ComponentDescriptors.h
  vnext/codegen/react/components/rnwcore/EventEmitters.h
  vnext/codegen/react/components/rnwcore/Props.cpp
  vnext/codegen/react/components/rnwcore/Props.h
  vnext/codegen/react/components/rnwcore/ShadowNodes.cpp
  vnext/codegen/react/components/rnwcore/ShadowNodes.h
  vnext/just-task.js
Labels: Area: Fabric, AutoMerge

#7742 Emit TextInput onChangeText before onSelectionChange
  change/react-native-windows-60609fec-a316-43d0-b789-deb31e09b2f7.json
  packages/e2e-test-app/test/LegacyTextInputTest.test.ts
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: AutoMerge

#7757 Use memory-mapping in BasePreparedScriptStoreImpl::tryGetPreparedScript
  change/react-native-windows-28c44905-331e-4dce-88c2-75c763d80ab7.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
  vnext/Shared/MemoryMappedBuffer.cpp
  vnext/Shared/MemoryMappedBuffer.h
Labels: Area: JSI, AutoMerge, Request Backport to 0.63, Request Backport to 0.64

#7761 [0.64] Use memory-mapping in BasePreparedScriptStoreImpl::tryGetPreparedScript
  change/react-native-windows-0d4f22fa-77fc-46a6-a094-9f66416a3416.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
  vnext/Shared/MemoryMappedBuffer.cpp
  vnext/Shared/MemoryMappedBuffer.h
Labels: Area: JSI

#7762 [0.63] Use memory-mapping in BasePreparedScriptStoreImpl::tryGetPreparedScript
  change/react-native-windows-2021-05-11-22-27-22-jsi-v8-mmap-0.63.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
  vnext/Shared/MemoryMappedBuffer.cpp
  vnext/Shared/MemoryMappedBuffer.h
Labels: Area: JSI

#7717 Optimize textTransform parent traversal.
  change/react-native-windows-04a0b9fb-d242-443b-9ec6-9cc2870bbe85.json
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
Labels: Area: Text

#7777 Fabric: Add support for Image events, blurRadius and tintColor
  change/react-native-windows-a4cdfcef-6797-4350-8fe7-23b7e482f48e.json
  vnext/Microsoft.ReactNative/Fabric/ImageComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/ImageComponentView.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: Area: Fabric

#7776 Fabric: Add support View.opacity and View.borderRadius
  change/react-native-windows-802ab7c2-4c7e-4d56-90f9-818472447a8c.json
  vnext/Microsoft.ReactNative/Fabric/ViewComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/ViewComponentView.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
  vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp
  vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.h
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.h
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: Fabric

#7786 Fix transitive dependencies for C# nuget-based apps
  change/react-native-windows-17c03193-3fbf-480e-ae5a-0fdc80198079.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
Labels: AutoMerge, Request Backport to 0.64

#7787 [0.64] Fix transitive dependencies for C# nuget-based apps #7786
  change/react-native-windows-04b9c2df-23f5-477f-a5ba-82830126ca11.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
Labels: AutoMerge

#7678 [0.64] Fix MSBuild Bundling When Path Contains Spaces
  change/react-native-windows-2f993c0c-f439-4e9d-96b3-8392c0eadee4.json
  vnext/PropertySheets/Autolink.props
  vnext/PropertySheets/Bundle.Common.targets
Labels: Area: Bundle, Backport to 0.64 Approved, Request Backport to 0.64

#7681 Use Rex With V8 JSI Runtime
  change/@office-iss-react-native-win32-3210eac8-7824-4a08-91ae-06280cf3ab01.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/BatchedBridge/MessageQueue.win32.js
Labels: AutoMerge, Platform: Desktop

#7676 Link to curated release notes in patch release notes
  change/@rnw-scripts-create-github-releases-66a4f00b-4060-4b68-af9d-db87150537ff.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
Labels: Area: Release Process, AutoMerge

#7801 [Fabric] Add support for PlatformColor
  change/react-native-windows-b9691dda-2b02-4670-a043-8ecd90525929.json
  vnext/Microsoft.ReactNative/Fabric/ActivityIndicatorComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/ImageComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/ParagraphComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/ViewComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Float.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/conversions.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/platform/cxx/react/renderer/graphics/Color.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
  vnext/Microsoft.ReactNative/Utils/ValueUtils.h
  vnext/overrides.json
Labels: Area: Fabric, AutoMerge

#7820 Fixes bug in BatchingEventEmitter
  change/react-native-windows-e5ae44de-62f6-4114-8c1d-028cf9ca9fd2.json
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
Labels: AutoMerge

#7806 Run integration-test-app against both Chakra and Hermes
  .ado/jobs/integration-test.yml
  change/@react-native-windows-cli-eabf3e2b-931a-49b0-ae14-06f7199374c1.json
  packages/@react-native-windows/cli/README.md
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
  packages/integration-test-app/tests/InteropCSModuleTests.tsx
  packages/integration-test-app/windows/.gitignore
  packages/integration-test-app/windows/ExperimentalFeatures.props
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/integration-test-app/windows/integrationtest/packages.config
Labels: AutoMerge

#7835 [0.65] Bump Lage and Beachball
  package.json
  yarn.lock
Labels: AutoMerge

#7803 [0.64] Fix regression where E2ETest app no longer uploads tree dump outputs …
  .ado/templates/e2e-test-job.yml
  docs/e2e-testing.md
  packages/E2ETest/windows/ReactUWPTestApp/Package.appxmanifest
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/E2ETest/windows/ReactUWPTestApp/TreeDumpControlViewManager.cs
  packages/E2ETest/windows/ReactUWPTestApp/copyTreeDump.cmd
Labels: Request Backport to 0.64

#7840 I18n.AllowRTL should default to true
  change/react-native-windows-802e1a1f-0feb-43da-ac1c-e81018aa3e62.json
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp
Labels: AutoMerge, Breaking Change, Request Backport to 0.65

#7794 [0.64] Fix Text.Color not working with backgroundColor
  change/react-native-windows-e7751624-0752-4e22-9095-937978ff2335.json
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/TextBackgroundColorTestPage.tsx
  packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
  packages/E2ETest/windows/ReactUWPTestApp/Assets/TreeDump/masters/TextColorBackground.json
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/E2ETest/windows/ReactUWPTestApp/TreeDumpControlViewManager.cs
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: AutoMerge, Request Backport to 0.64

#7837 Adds event coalescing to TouchEventHandler
  change/react-native-windows-7120ebe6-957e-4ec9-84db-a461cf12802b.json
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.h
Labels: Area: Performance

#7858 [0.65] [CI Break] Port #7840
  change/react-native-windows-db5b74d5-5b43-482f-9799-0130d9f4504c.json
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
Labels: AutoMerge, Request Backport to 0.65

#7860 [0.64] [CI Break] Port #7840
  change/react-native-windows-9448e377-f259-4f02-a265-9ef112855aec.json
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
Labels: AutoMerge, Request Backport to 0.64

#7863 [0.63] [CI Break] Update .net UWP package versions
  change/react-native-windows-9448e377-f259-4f02-a265-9ef112855aec.json
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
Labels: AutoMerge, Request Backport to 0.63

#7854 Use 0.65 version for winmd API docs
  .ado/templates/build-rnw.yml
Labels: AutoMerge

#7861 Add UWP sdk version diagnostics to prepare-env
  .ado/templates/prepare-env.yml
Labels: AutoMerge

#7862 [0.65] Add UWP sdk version diagnostics to prepare-env
  .ado/templates/prepare-env.yml
Labels: AutoMerge, Request Backport to 0.65

#7859 Fix JSValue memory leak in move constructor
  change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json
  vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
Labels: AutoMerge, Request Backport to 0.62, Request Backport to 0.63, Request Backport to 0.64, Request Backport to 0.65

#7865 [0.65] Patch Nightly RN Community CLI Metro Version in RNW CLI postinstall
  beachball.config.js
  change/@react-native-windows-cli-5f346856-48e3-4552-9e4e-fcb2a1c1347a.json
  package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/postinstall.ts
Labels: AutoMerge

#7874 Native build logic shouldn't delete PCH on build for all CI machines
  change/react-native-windows-51bbc131-2b1c-465c-b2a8-b06ce1e6b002.json
  vnext/Directory.Build.targets
Labels: Area: Build Infrastructure

#7875 [0.65] Fixing inspector with Hermes v0.8 (#7852)
  change/react-native-windows-226e1de5-e19b-44dc-a44a-cd8bc20fd68c.json
  packages/integration-test-app/windows/integrationtest/packages.config
  packages/playground/packages.config
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
Labels: AutoMerge, Request Backport to 0.65

#7867 [0.65] Fix JSValue memory leak in move constructor (#7859)
  change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json
  vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
Labels: AutoMerge

#7868 [0.64] Fix JSValue memory leak in move constructor (#7859)
  change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json
  vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
Labels: AutoMerge

#7889 Provide error message when an unhandled exception occurs in a native method (in Debug)
  change/react-native-windows-c8eca782-653c-40b7-9973-879c1529aa43.json
  vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
Labels: Area: Debug Infrastructure, Area: Developer Experience

#7779 Upgrade TargetPlatformVersion to 10.0.19041.0
  .ado/jobs/integration-test.yml
  .ado/variables/msbuild.yml
  .github/ISSUE_TEMPLATE/bug-report.md
  change/@react-native-windows-cli-d3732f39-4187-40f6-a856-49eeb8f2d7c1.json
  change/node-rnw-rpc-7abb3bb7-b770-48aa-a1cd-9621d8a19615.json
  change/react-native-windows-de93550a-0f64-46c7-92c9-d4a7876f591e.json
  packages/@react-native-windows/cli/src/runWindows/utils/build.ts
  packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/integration-test-app/windows/InteropTestModuleCS/InteropTestModuleCS.csproj
  packages/integration-test-app/windows/integrationtest/TestTransaction.h
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/node-rnw-rpc/windows/NodeRpc/NodeRpc.vcxproj
  packages/playground/windows/Playground-win32 (Package)/Playground-win32-packaging.proj
  packages/playground/windows/playground-win32/Application.manifest
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground/Playground.vcxproj
  packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  packages/sample-apps/windows/SampleLibraryCS/SampleLibraryCS.csproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Directory.Build.targets
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx/ReactPropertyBag.h
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/PropertySheets/Debug.props
  vnext/PropertySheets/React.Cpp.props
  vnext/PropertySheets/Release.props
  vnext/Scripts/rnw-dependencies.ps1
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
  vnext/template/cs-app/proj/MyApp.csproj
  vnext/template/cs-lib/proj/MyLib.csproj
Labels: Request Backport to 0.63, Request Backport to 0.64

#7876 [0.65] Native build logic shouldn't delete PCH on build for all CI machines (#7874)
  change/react-native-windows-51bbc131-2b1c-465c-b2a8-b06ce1e6b002.json
  vnext/Directory.Build.targets
Labels: Area: Build Infrastructure, AutoMerge

#7891 [0.64] Add error message when an exception happens in a native module (in Debug)
  change/react-native-windows-c8eca782-653c-40b7-9973-879c1529aa43.json
  vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
Labels: AutoMerge, Request Backport to 0.64

#7890 [0.65] Add error message when an exception happens in a native module (in Debug)
  change/react-native-windows-c8eca782-653c-40b7-9973-879c1529aa43.json
  vnext/Microsoft.ReactNative/IReactModuleBuilder.cpp
Labels: AutoMerge, Request Backport to 0.65

#7892 Allow propagating WinRTWebSocketResource constructor exceptions
  change/react-native-windows-fb507b4a-50b0-480f-bf49-e8ad0ca6f888.json
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: Request Backport to 0.63, Request Backport to 0.64, Request Backport to 0.65
