Repository microsoft/react-native-windows, pull requests merged in 2021-10, with the labels that each got.

#8736 [0.66] Upgrade V8 to version 9.5
  change/react-native-windows-6a7327b1-a0a5-4a1a-b32d-fac4378feb1f.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
Labels: AutoMerge, Area: JSI, Request Backport to 0.66

#8754 Switch ImageLoader to be a codegen'd turbomodule
  change/react-native-windows-90f786a3-38e1-415b-bfd8-2473d3bab6ec.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp
  vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: AutoMerge

#8289 Add theme picker to Playground win32 app
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-Win32.rc
  packages/playground/windows/playground-win32/resource.h
Labels: AutoMerge

#8500 Fixes bugs for pointerEvents prop
  change/react-native-windows-b49059c5-b0c3-467a-a1aa-fbe285cb5fff.json
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Labels: AutoMerge, Area: Borders and Brushes, Area: Pointer

#8762 Add ARM64 support to React.Windows.Desktop.Test.DLL
  change/react-native-windows-40a317ea-d9db-48a4-9ea1-b03e399ac055.json
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.ARM64.def
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge

#8763 [0.66] Add ARM64 support to React.Windows.Desktop.Test.DLL
  change/react-native-windows-583aff3c-7407-409c-9437-156e473d0a4a.json
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.ARM64.def
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge, Request Backport to 0.66

#8764 [0.65] Add ARM64 support to React.Windows.Desktop.Test.DLL
  change/react-native-windows-422057b5-8a09-4c5c-a796-7f90a7935ef9.json
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.ARM64.def
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge, Request Backport to 0.65

#8775 Use full path to powershell
  change/@react-native-windows-cli-7dc180ee-6e42-4d53-9929-daf1622c8bb2.json
  packages/@react-native-windows/cli/src/healthChecks.ts
  packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: AutoMerge

#8778 Teach integration tooling about new nightly pattern
  change/react-native-platform-override-2ceb8de7-5beb-42a6-a02a-26caa4ec3c19.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
Labels: Area: Release Process

#8765 [0.64] Add ARM64 support to React.Windows.Desktop.Test.DLL
  change/react-native-windows-f87fbf24-d6b4-4a78-9571-d7ae209a1942.json
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.ARM64.def
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/OfficeReact.Win32.nuspec
Labels: AutoMerge, Request Backport to 0.64

#9008 Allow Setting Managed Image Independently of Pool
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/jschecks.yml
  .ado/jobs/playground.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/variables/vs2019.yml
Labels: AutoMerge

#8992 Make all msbuild in PR and CI multicore builds
  .ado/jobs/playground.yml
  .ado/templates/build-rnw.yml
  change/react-native-windows-6e463863-71ac-46eb-a69c-d91fc6d7cec5.json
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
Labels: Area: Build Infrastructure

#9003 Default `run-windows` to building system architecture
  change/@react-native-windows-cli-da13474f-cd34-41ae-94d0-2fa8c9bf4d78.json
  packages/@react-native-windows/cli/README.md
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
Labels: AutoMerge, Breaking Change

#9004 Cleanup conditionals of playground yaml
  .ado/jobs/playground.yml
Labels: AutoMerge, Area: Build Infrastructure

#9006 Set default AppxBundlePlatforms
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/jschecks.yml
  .ado/jobs/macos-tests.yml
  .ado/jobs/playground.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/templates/build-rnw.yml
  .ado/templates/prepare-build-env.yml
  .ado/templates/prepare-env.yml
  .ado/templates/prepare-js-env.yml
  .ado/templates/react-native-init.yml
  .ado/templates/set-appx-platforms.yml
  change/react-native-windows-efa74d64-974d-4cb3-9a0b-129917679c3a.json
  vnext/PropertySheets/Appx.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.props
Labels: AutoMerge

#9011 doc: Fix REACT_INIT doc to require ReactContext #9010
  change/react-native-windows-ea98d545-cb81-4e40-ba3c-41c5699f9cfd.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: AutoMerge
