Repository microsoft/react-native-windows, pull requests merged in 2021-04, with the labels that each got.

#7406 Add onKeyDown/onKeyUp to Pressable.
  change/react-native-windows-c7f8bf18-e09f-40e2-b3a6-6c1b1c388391.json
  packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
  vnext/src/Libraries/Components/Pressable/Pressable.windows.js
  vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
  vnext/src/Libraries/Pressability/Pressability.windows.js
Labels: Area: Keyboard

#7503 [0.64] Updates to documentation in IDL files (#7393)
  change/react-native-windows-17601253-734e-444b-b719-89f09535cfd0.json
  change/react-native-windows-e0a73f29-3f67-499f-953d-3427552c2bad.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
  vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
  vnext/Microsoft.ReactNative/IReactNotificationService.idl
  vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
  vnext/Microsoft.ReactNative/IReactPackageProvider.idl
  vnext/Microsoft.ReactNative/IReactPropertyBag.idl
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/Microsoft.ReactNative/ReactApplication.idl
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.idl
  vnext/Microsoft.ReactNative/ReactRootView.idl
  vnext/Microsoft.ReactNative/RedBoxHandler.idl
  vnext/Microsoft.ReactNative/XamlHelper.idl
  vnext/Microsoft.ReactNative/XamlUIService.idl
Labels: AutoMerge, Request Backport to 0.64

#7514 Force xmldom to version ^0.5.0.
  package.json
  yarn.lock
Labels: Request Backport to 0.63, Request Backport to 0.64

#7515 [0.63] Force xmldom to version ^0.5.0.
  package.json
  yarn.lock
Labels: Request Backport to 0.63

#7539 Remove the *-stable branch filter from publish.yml
  .ado/publish.yml
Labels: AutoMerge

#7545 Fix onKeyDown/onKeyUp not firing after reloading JS
  change/react-native-windows-abb13165-3468-4b49-9264-0a5c3aee7d23.json
  vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp
Labels: AutoMerge

#7509 Allow swapping to System Chakra at runtime.
  change/react-native-windows-67841011-73e1-46de-8012-91bdd8f2dd4c.json
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop/JSBigStringResourceDll.cpp
  vnext/Desktop/JSI/ChakraJsiRuntime_core.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Microsoft.ReactNative.ComponentTests/JsiArgumentReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/JsiReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj.filters
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Shared/JSI/ChakraApi.cpp
  vnext/Shared/JSI/ChakraCoreRuntime.h
  vnext/Shared/JSI/ChakraJsiRuntime_edgemode.cpp
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntime.h
  vnext/Shared/JSI/ChakraRuntimeFactory.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/RuntimeOptions.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/SystemChakraRuntime.h
Labels: Area: JSI, Platform: Desktop, Request Backport to 0.63, Request Backport to 0.64

#7268 Add Functionality to setAccessibilityFocus Method
  change/react-native-windows-9b2d34d7-a5f1-4c20-b6ed-b60bbaa80fbd.json
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Labels: Area: Accessibility

#7479 [0.63] Allow swapping to System Chakra at runtime.
  change/react-native-windows-2021-03-25-16-18-03-chakramagic-63.json
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop/JSBigStringResourceDll.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/JSI/Desktop/ChakraJsiRuntime_core.cpp
  vnext/JSI/Shared/ChakraJsiRuntime_edgemode.cpp
  vnext/JSI/Shared/ChakraObjectRef.cpp
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntime.h
  vnext/JSI/Shared/ChakraRuntimeFactory.h
  vnext/JSI/Shared/JSI.Shared.vcxitems
  vnext/JSI/Shared/JSI.Shared.vcxitems.filters
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/JsiArgumentReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/JsiReaderTest.cpp
  vnext/Microsoft.ReactNative.sln
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Shared/ChakraCoreRuntime.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/RuntimeOptions.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/SystemChakraRuntime.h
Labels: Area: JSI, Platform: Desktop

#7363 Fix XAML Visibility for `display:none`
  change/react-native-windows-66f4660e-05be-46b7-8321-74ea94fb2b4b.json
  packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/e2e-test-app/test/DisplayNoneTest.test.ts
  packages/e2e-test-app/test/__snapshots__/DisplayNoneTest.test.ts.snap
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Area: Layout

#7583 Bump handlebars to 4.7.7.
  package.json
  yarn.lock
Labels: Request Backport to 0.63, Request Backport to 0.64

#7516 [0.64] Force xmldom to version ^0.5.0.
  package.json
  yarn.lock
Labels: Request Backport to 0.64

#7587 [0.63] Bump handlebars to 4.7.7.
  yarn.lock
Labels: AutoMerge

#7590 Remove unnecessary use of yarn resolution.
  package.json
  yarn.lock
Labels: AutoMerge

#7588 [0.64] Bump handlebars to 4.7.7.
  yarn.lock
Labels: AutoMerge

#7581 [0.64] Enable any platform color to be used in PlatformColor()
  change/react-native-windows-1fda6013-a5ec-4ebc-8298-dfeab73f228a.json
  vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
Labels: Area: PlatformColor, AutoMerge, Request Backport to 0.64

#7575 Calling UIManager.dispatchViewManagerCommand doesn't trigger a UI update
  change/react-native-windows-f78483b0-732a-44b0-98f4-7becc372e8e3.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Shared/BatchingMessageQueueThread.h
  vnext/Shared/Threading/BatchingQueueThread.cpp
  vnext/Shared/Threading/BatchingQueueThread.h
Labels: AutoMerge, Request Backport to 0.64

#7521 [0.64] Allow swapping to System Chakra at runtime.
  change/react-native-windows-09aa1b25-b457-4dfb-8c79-86bdb78024a4.json
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop/JSBigStringResourceDll.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/JSI/Desktop/ChakraJsiRuntime_core.cpp
  vnext/JSI/Shared/ChakraApi.cpp
  vnext/JSI/Shared/ChakraCoreRuntime.h
  vnext/JSI/Shared/ChakraJsiRuntime_edgemode.cpp
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntime.h
  vnext/JSI/Shared/ChakraRuntimeFactory.h
  vnext/JSI/Shared/JSI.Shared.vcxitems
  vnext/JSI/Shared/JSI.Shared.vcxitems.filters
  vnext/JSI/Shared/SystemChakraRuntime.h
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/JSI/Universal/JSI.Universal.vcxproj.filters
  vnext/Microsoft.ReactNative.ComponentTests/JsiArgumentReaderTest.cpp
  vnext/Microsoft.ReactNative.ComponentTests/JsiReaderTest.cpp
  vnext/Microsoft.ReactNative.sln
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Shared/OInstance.cpp
  vnext/Shared/RuntimeOptions.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: Area: JSI, AutoMerge, Platform: Desktop

#7525 Avoid running Yoga layout on subtrees with RequireNativeLayout
  change/react-native-windows-a144c525-b2f2-4576-8155-80b658231b96.json
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Views/ViewManager.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: Area: Layout, Area: Native Modules

#7603 [0.64] Calling UIManager.dispatchViewManagerCommand should trigger updates
  change/react-native-windows-f78483b0-732a-44b0-98f4-7becc372e8e3.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Shared/BatchingMessageQueueThread.h
  vnext/Shared/Threading/BatchingQueueThread.cpp
  vnext/Shared/Threading/BatchingQueueThread.h
Labels: AutoMerge

#7605 fix filter project merge
  change/react-native-windows-2852a1ac-d875-4239-88da-42a85bd02951.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
Labels: AutoMerge

#7609 DisplayNone Test Fix
  packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx
  packages/e2e-test-app/test/__snapshots__/DisplayNoneTest.test.ts.snap
Labels: Area: Test Infrastructure, Area: Tests

#7635 Replace fmt stub with real implementation
  change/node-rnw-rpc-a0f5e7c8-3d88-498b-9bf0-166a3ef2bc54.json
  change/react-native-windows-cb2ff5f8-1003-44f2-9a5c-bb1505a6bd08.json
  packages/e2e-test-app/windows/ReactUWPTestApp.sln
  packages/integration-test-app/windows/integrationtest.sln
  packages/node-rnw-rpc/windows/NodeRpc.sln
  packages/playground/windows/playground-win32-packaged.sln
  packages/playground/windows/playground-win32.sln
  packages/playground/windows/playground.sln
  packages/sample-apps/windows/SampleApps.sln
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/Bundle.Common.targets
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/fmt/.clang-format
  vnext/fmt/fmt.vcxproj
  vnext/fmt/fmt.vcxproj.filters
  vnext/fmt/packages.config
  vnext/fmt/pch.cpp
  vnext/fmt/pch.h
  vnext/package.json
  vnext/stubs/fmt/format.h
  vnext/template/cpp-app/proj/MyApp.sln
  vnext/template/cpp-lib/proj/MyLib.sln
  vnext/template/cs-app/proj/MyApp.sln
  vnext/template/cs-lib/proj/MyLib.sln
Labels: AutoMerge

#7636 [0.64] Suppress onLayout event when layout has not changed (#7470)
  change/react-native-windows-e07fd82b-045a-44b9-a416-642e23b1ff67.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: Area: FlatList, Area: Performance, AutoMerge, Backport to 0.64 Approved

#7604 Remove unused ChakraNativeModules files
  change/react-native-windows-9ccbea02-154d-4f87-a941-e9504dc389d5.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraNativeModules.cpp
  vnext/Chakra/ChakraNativeModules.h
Labels: AutoMerge

#7637 [0.64] Change TextInput cursor behavior (#7285)
  change/react-native-windows-f478c436-a66f-4944-b578-80fea3b12488.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: TextInput, AutoMerge, Backport to 0.64 Approved

#7628 Update Microsoft.ChakraCore to 1.11.24
  change/react-native-windows-ee4c1629-c862-4360-a9de-27f106f142dc.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/ReactCommon.UnitTests/packages.config
Labels: Request Backport to 0.64, security

#7652 Add missing include folder to fix CI
  change/react-native-windows-d0c003c6-f96a-494c-9336-23b946d53683.json
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#7655 Re-enabling CG checks in CI/PR
  .ado/jobs/desktop.yml
  .ado/jobs/universal.yml
Labels: Area: Test Infrastructure

#7656 [0.64] Re-enabling CG checks in PR
  .ado/windows-vs-pr.yml
Labels: Area: Test Infrastructure

#7657 Reunion prep
  change/react-native-windows-1a01dcab-b7ee-4d5c-8afd-b230de0b44ce.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
Labels: AutoMerge

#7664 Adds 'autoFocus' prop to TextInput
  change/react-native-windows-a83fe313-38da-4b46-a583-6f8346f1d41b.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: Gamepad

#7645 Remove ARM32 Support
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/templates/prep-and-pack-nuget.yml
  change/@react-native-windows-cli-03d0e6df-c0a6-434f-abd4-f698d7211932.json
  change/node-rnw-rpc-1397c7b0-090a-4daa-af94-4cd2b7311908.json
  change/react-native-windows-8659aa8e-46be-4ef9-96ce-b3d5d82bc5ad.json
  packages/@react-native-windows/cli/README.md
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/e2e-test-app/windows/ReactUWPTestApp.sln
  packages/e2e-test-app/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/integration-test-app/windows/InteropTestModuleCS/InteropTestModuleCS.csproj
  packages/integration-test-app/windows/integrationtest.sln
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/node-rnw-rpc/windows/NodeRpc.sln
  packages/node-rnw-rpc/windows/NodeRpc/NodeRpc.vcxproj
  packages/playground/windows/playground-win32-packaged.sln
  packages/playground/windows/playground-win32.sln
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground.sln
  packages/playground/windows/playground/Playground.vcxproj
  packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleApps.sln
  packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  packages/sample-apps/windows/SampleLibraryCS/SampleLibraryCS.csproj
  vnext/Common/Common.vcxproj
  vnext/Folly/Folly.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/ARM.props
  vnext/PropertySheets/Application/ARM.props
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
  vnext/PropertySheets/CppAppConsumeCSharpModule.targets
  vnext/PropertySheets/DynamicLibrary/ARM.props
  vnext/PropertySheets/JSEngine.props
  vnext/PropertySheets/StaticLibrary/ARM.props
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactWindows-Desktop.sln
  vnext/Scripts/Install-WindowsSDKISO.ps1
  vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
  vnext/Scripts/Microsoft.ReactNative.nuspec
  vnext/Scripts/StripAdditionalPlatformsFromNuspec.ps1
  vnext/fmt/fmt.vcxproj
  vnext/template/cpp-app/proj/MyApp.sln
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.sln
  vnext/template/cpp-lib/proj/MyLib.vcxproj
  vnext/template/cs-app/proj/MyApp.csproj
  vnext/template/cs-app/proj/MyApp.sln
  vnext/template/cs-lib/proj/MyLib.csproj
  vnext/template/cs-lib/proj/MyLib.sln
Labels: AutoMerge, Breaking Change

#7683 Set Fixed RootView Width in E2ETest
  packages/e2e-test-app/windows/ReactUWPTestApp/MainPage.xaml
Labels: Area: Test Infrastructure, AutoMerge

#7675 Update @octokit/rest
  change/@rnw-scripts-create-github-releases-77b86566-6968-4cb6-b44a-87e691a48ea7.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
  yarn.lock
Labels: Area: Infrastructure

#7674 Bump RN peerDependency whenever it is prerelease
  change/@rnw-scripts-integrate-rn-1b977494-5cfd-40f4-b3cd-937b35bd3e6d.json
  packages/@rnw-scripts/integrate-rn/src/test/upgradeDependencies.test.ts
  packages/@rnw-scripts/integrate-rn/src/upgradeDependencies.ts
Labels: Area: Developer Experience, Area: Release Process

#7673 Replace `inquirer` with `prompts` in CLI
  change/@react-native-windows-cli-a6564f64-f02c-409e-b890-03439085328f.json
  change/react-native-windows-init-fb6d7734-e0de-4991-960b-3839a6b8aee6.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/generator-common/index.ts
  packages/react-native-windows-init/package.json
  yarn.lock
Labels: Area: CLI

#7672 Update to latest @types/react-native
  change/@office-iss-react-native-win32-66cdc8c8-5b8e-4fa6-a5e1-8d56ed4177d9.json
  change/react-native-windows-9f1234cc-6092-4410-96b3-e5c042444d04.json
  packages/@office-iss/react-native-win32/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: Area: Developer Experience, Area: Infrastructure, AutoMerge

#7670 Remove version from ExperimentalFeatures.props links
  change/@react-native-windows-cli-21b8c27c-4f1b-459e-a14e-52a01774729b.json
  change/react-native-windows-286084fd-2a87-474f-9806-269f85faf51e.json
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
  vnext/template/shared-app/proj/ExperimentalFeatures.props
Labels: AutoMerge

#7671 [0.64] Remove version from ExperimentalFeatures.props links
  change/react-native-windows-743fdc9e-558b-4827-9385-81d7b9fb9a41.json
  vnext/template/shared-app/proj/ExperimentalFeatures.props
Labels: AutoMerge, Request Backport to 0.64

#7677 Fix MSBuild Bundling When Path Contains Spaces
  change/react-native-windows-49eeaa07-349c-4d1f-8915-608df3e8bc01.json
  vnext/PropertySheets/Autolink.props
  vnext/PropertySheets/Bundle.Common.targets
Labels: Area: Bundle, AutoMerge, Request Backport to 0.64

#7680 Integrate April 22 RN Nightly Build
  change/@office-iss-react-native-win32-242ddd8c-f5cb-418c-b3d9-4ddce764a8c5.json
  change/node-rnw-rpc-62844fd2-8b8f-4792-9b07-261de82ce080.json
  change/react-native-windows-3ec59431-d1e3-4787-aa1c-60047b7eae13.json
  package.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/EventEmitter/NativeEventEmitter.win32.js
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/FlatList/FlatListExamples.js
  packages/@react-native/tester/js/examples/SectionList/SectionListExamples.js
  packages/@react-native/tester/js/examples/TextInput/TextInputExample.ios.js
  packages/@react-native/tester/overrides.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/node-rnw-rpc/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/.flowconfig
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/Touchable/TouchableWithoutFeedback.windows.js
  vnext/src/Libraries/EventEmitter/NativeEventEmitter.windows.js
  yarn.lock
Labels: Area: Native Modules, AutoMerge

#7684 Remove Forking Due to "acceptsKeyboardFocus" Invariant Checks
  change/@office-iss-react-native-win32-5bc205b1-20a9-4f4b-8adb-032b9febbebd.json
  change/react-native-windows-75512eb9-5b0d-4789-b68e-6c0358fb8aee.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
  vnext/overrides.json
  vnext/src/Libraries/Components/View/View.windows.js
Labels: AutoMerge

#7694 Visual tests: snapshot update accounting for fix in width inconsistency.
  packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx
  packages/e2e-test-app/test/__snapshots__/DisplayNoneTest.test.ts.snap
Labels: Area: Tests, Area: Text

#7692 Remove incorrect mapping from virtual key 192
  change/react-native-windows-cb98b272-df33-4b32-b571-f8796d620d35.json
  vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
Labels: AutoMerge

#7696 Allow `lineHeight` settings less than font height
  change/react-native-windows-41786510-3be7-441f-81e2-882e46ed5bf7.json
  packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Labels: AutoMerge

#7659 SDL Compliance Completion
  change/react-native-windows-a94bcf82-c2c3-467a-b720-c0903f97cbd9.json
  vnext/Folly/Folly.vcxproj
  vnext/Folly/TEMP_UntilFollyUpdate/dynamic.cpp
  vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
Labels: Area: Infrastructure

#7663 Update PlatformColor brushes upon theme change
  change/react-native-windows-4062d121-1aa5-49ae-b74c-861571c1fcd5.json
  vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
Labels: Area: PlatformColor, AutoMerge
