Repository microsoft/react-native-windows, pull requests merged in 2021-08, with the labels that each got.

#8354 [0.65] Fix issue using react-native-debugger with react-native-windows (#8344)
  change/react-native-windows-5d74fe3c-efd2-479b-ab75-810f5f266a11.json
  vnext/Shared/Executors/WebSocketJSExecutor.cpp
  vnext/Shared/Executors/WebSocketJSExecutor.h
Labels: AutoMerge, Backport to 0.65 Approved, Request Backport to 0.65

#8346 Add some jsvalue reader helpers for more xaml types
  change/react-native-windows-bab3d697-7bb6-4b12-8af1-a9c0bfa1517e.json
  vnext/Microsoft.ReactNative.Cxx/JSValueXaml.h
Labels: AutoMerge, Needs: Author Feedback

#8327 Add root tag to ShadowNode for resolving correct XamlRoot in FlyoutViewManager
  change/react-native-windows-2c2723ef-9489-4c71-b544-b6bb24e74a32.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
  vnext/Microsoft.ReactNative/Views/PaperShadowNode.h
Labels: Area: Flyout, Area: Islands, Area: View Managers

#8364 Do not write codegen files if the contents have not changed, as this breaks incremental builds
  change/@react-native-windows-codegen-02f90f2b-4769-435b-b35c-f09ec0b1a8d7.json
  change/react-native-windows-08b90f74-4260-454b-bf87-f2eccc345bef.json
  packages/@react-native-windows/codegen/src/Cli.ts
  vnext/just-task.js
Labels: AutoMerge

#8365 Add QuirkSettings::SetEnableBackHandler to opt out of BackHandler functionality
  change/react-native-windows-9fa432a3-64da-497e-8f46-b276ea85891a.json
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/Microsoft.ReactNative/ReactRootView.cpp
Labels: Area: Gamepad

#8386 Sets the default button for the ContentDialog
  change/react-native-windows-9327e4f0-c4f9-4c6a-b2cc-25c0ecf9e89a.json
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
  vnext/Microsoft.ReactNative/Modules/AlertModule.h
  vnext/src/Libraries/Alert/Alert.windows.js
Labels: AutoMerge

#8387 Clear tintColor when prop set to null
  change/react-native-windows-6bd5ecf8-9e67-49a6-8b65-ea0d5f53e42b.json
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
Labels: AutoMerge

#8385 Rename API for changing BackHandler behavior
  change/react-native-windows-8288a621-ac24-4906-b19c-7d66308c0b23.json
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/Microsoft.ReactNative/ReactRootView.cpp
Labels: AutoMerge

#8394 Fixes various issues related to clang compile
  change/react-native-windows-c8f0f74c-1b7f-4844-9573-de482ae55063.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
  vnext/Mso/src/eventWaitHandle/eventWaitHandleImpl_win.cpp
Labels: AutoMerge

#8403 Clean-up unwanted spaces (Part 1: CI code)
  .ado/continuous.yml
  .ado/integrate-rn.yaml
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/jschecks.yml
  .ado/jobs/macos-tests.yml
  .ado/jobs/nuget-desktop.yml
  .ado/jobs/playground.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/scripts/SetupLocalDumps.cmd
  .ado/scripts/TestWACK.ps1
  .ado/scripts/VSComponentList.ps1
  .ado/scripts/setVersionEnvVars.js
  .ado/scripts/shouldSkipPRBuild.ps1
  .ado/scripts/waitForVerdaccio.js
  .ado/stages.yml
  .ado/templates/apply-published-version-vars.yml
  .ado/templates/build-rnw.yml
  .ado/templates/cleanup-certificate.yml
  .ado/templates/configure-git.yml
  .ado/templates/discover-google-test-adapter.yml
  .ado/templates/install-SDK.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/prep-and-pack-single.yml
  .ado/templates/prepare-env.yml
  .ado/templates/react-native-init.yml
  .ado/templates/run-windows-with-certificates.yml
  .ado/templates/set-experimental-feature.yml
  .ado/templates/set-version-vars.yml
  .ado/templates/setup-certificate.yml
  .ado/templates/upload-build-logs.yml
  .ado/templates/yarn-install.yml
  .ado/variables/msbuild.yml
  .ado/verdaccio/config.yaml
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#8418 Prevent crash in AnimationDriver when RN instance destroyed
  change/react-native-windows-e95ae09a-3ccc-4ae3-a539-086bd5ad1e6d.json
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.h
Labels: AutoMerge

#8426 [0.64] Component Governance fixes
  package.json
  yarn.lock
Labels: security, Request Backport to 0.64

#8439 Exclude WinMD AttributeNameAttribute
  change/react-native-windows-d47189e2-4652-42e1-bb0f-ca9d4b18768d.json
  patches/@react-native-picker+picker+1.16.5.patch
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
Labels: AutoMerge

#8408 Fixes issues with Text backgroundColor
  change/react-native-windows-57b2d9fa-1663-4577-b3bf-4e684b970508.json
  packages/@react-native-windows/tester/src/js/examples-win/Text/TextExample.windows.tsx
  packages/e2e-test-app/test/__snapshots__/TextComponentTest.test.ts.snap
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Utils/ShadowNodeTypeUtils.h
  vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
  vnext/Microsoft.ReactNative/Utils/ValueUtils.h
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.h
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: Area: Borders and Brushes, Area: Text

#8449 Fix crash in NativeUIManager when processing extra layout nodes
  change/react-native-windows-b4f125ea-015b-4c96-a89a-906de480fe68.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: AutoMerge

#8450 Support 'focusable' prop on all ControlViewManager-derived components
  change/react-native-windows-9824cf9a-62b1-400e-b905-e9fb51a82809.json
  vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
Labels: Needs: Author Feedback, Area: ScrollView

#8451 Fix crash in KeyboardEventHandler.cpp when handling undefined keyDownEvents prop
  change/react-native-windows-569ef05e-75d4-4af7-9197-8ebc3dca1c37.json
  vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
Labels: AutoMerge, Area: Keyboard

#8448 Integrate 7/14 Nightly RN Build
  change/@office-iss-react-native-win32-b021015f-de49-4b69-9d47-3f7a72355661.json
  change/@react-native-windows-virtualized-list-4a1fcc00-f8ff-4738-b87a-eb2fd957db0b.json
  change/node-rnw-rpc-324ca09d-0b6d-43af-8793-2c1245bee8f0.json
  change/react-native-windows-0fad37d1-d4e2-4aff-b2ec-3884931ee352.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
  packages/@react-native-windows/virtualized-list/.flowconfig
  packages/@react-native-windows/virtualized-list/overrides.json
  packages/@react-native-windows/virtualized-list/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/FlatList/FlatListExample.js
  packages/@react-native/tester/js/examples/Image/ImageExample.js
  packages/@react-native/tester/js/examples/ScrollView/ScrollViewIndicatorInsetsExample.ios.js
  packages/@react-native/tester/js/examples/SectionList/SectionList-scrollable.js
  packages/@react-native/tester/js/examples/SectionList/SectionListBaseExample.js
  packages/@react-native/tester/js/examples/TextInput/TextInputExample.android.js
  packages/@react-native/tester/js/utils/RNTesterList.ios.js
  packages/@react-native/tester/overrides.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/node-rnw-rpc/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/.flowconfig
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/View/ViewAccessibility.windows.js
  vnext/src/Libraries/DeprecatedPropTypes/DeprecatedViewAccessibility.windows.js
  yarn.lock
Labels: AutoMerge

#8462 Bump xmldom and tar for Component Governance
  package.json
  yarn.lock
Labels: AutoMerge, security, Request Backport to 0.65

#8468 [0.64] Update publish pipeline to use hosted agents
  .ado/publish.yml
Labels: AutoMerge, Request Backport to 0.64

#8469 [0.65] Update publish pipeline to use hosted agents
  .ado/publish.yml
Labels: AutoMerge

#8463 [0.65] Bump xmldom and tar for Component Governance
  package.json
  yarn.lock
Labels: AutoMerge, security

#8470 Set Shared WindowsTargetPlatformVersion in External Property Sheets
  change/node-rnw-rpc-a7d877a2-4952-4c54-9d0b-71c29f1a8383.json
  change/react-native-windows-b229cc41-28f9-4cc4-95f5-206ba16cd941.json
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/node-rnw-rpc/windows/NodeRpc/NodeRpc.vcxproj
  packages/playground/windows/playground/Playground.vcxproj
  packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
Labels: Area: Developer Experience

#8455 Consume Node-Api V8 JSI Runtime
  change/react-native-windows-da09186d-42a2-44a8-bcf1-e18fc6b4f13a.json
  vnext/.editorconfig
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/DevSettings.h
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64, Area: JSI, Request Backport to 0.65

#8477 [0.64] Consume Node-Api V8 JSI Runtime
  change/react-native-windows-24c06f48-422a-4110-8886-448345a95f36.json
  vnext/.editorconfig
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Desktop/packages.config
  vnext/JSI/Shared/JSI.Shared.vcxitems
  vnext/JSI/Shared/JSI.Shared.vcxitems.filters
  vnext/JSI/Shared/NapiJsiV8RuntimeHolder.cpp
  vnext/JSI/Shared/NapiJsiV8RuntimeHolder.h
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/DevSettings.h
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#8478 [0.65] Consume Node-Api V8 JSI Runtime
  change/react-native-windows-1a3ee341-b9ff-4dc7-b456-2ca73d935491.json
  vnext/.editorconfig
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/DevSettings.h
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge

#8504 Removing unused code (MemoryTracker)
  change/react-native-windows-ad1e79d9-9d7e-4a17-ab11-1b694fb65d54.json
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Desktop.ABITests/Application.manifest
  vnext/Desktop.ABITests/MemoryTrackerTests.cpp
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj.filters
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.cpp
  vnext/Desktop.IntegrationTests/ChakraRuntimeHolder.h
  vnext/Desktop/ABI/MemoryTracker.cpp
  vnext/Desktop/ABI/MemoryTracker.h
  vnext/Desktop/ABI/MemoryTracker.idl
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/module.g.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/ReactCommon.UnitTests/JsiRuntimeGenerators.cpp
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Shared/ChakraRuntimeHolder.cpp
  vnext/Shared/DevSettings.h
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntime.h
  vnext/Shared/JSI/ChakraRuntimeArgs.h
  vnext/Shared/MemoryTracker.cpp
  vnext/Shared/MemoryTracker.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge

#8494 [0.65] Pass JSValueArgWriter around instead of immediately converting to dynamic
  change/react-native-windows-f9440adc-f697-40d9-99c3-495aaf01ab8f.json
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactRootView.cpp
  vnext/Microsoft.ReactNative/ReactRootView.h
Labels: AutoMerge

#8489 [0.64] Pass JSValueArgWriter around instead of immediately converting to dynamic
  change/react-native-windows-8b2d2b45-a399-47a4-8131-3396c5f708d3.json
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactRootView.cpp
  vnext/Microsoft.ReactNative/ReactRootView.h
Labels: AutoMerge

#8514 Add doxysaurus README
  change/@rnw-scripts-doxysaurus-9ae61e30-c0cb-4152-88a4-5616fadb7730.json
  packages/@rnw-scripts/doxysaurus/README.md
Labels: AutoMerge

#8516 Add support for UIA accessibility headings
  change/react-native-windows-a8b5bad4-4783-4c5f-a6f4-c227c9b6c8d9.json
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Labels: Request Backport to 0.64, Request Backport to 0.65
