Repository microsoft/react-native-windows, pull requests merged in 2021-11, with the labels that each got.

#9036 Fix Publish pipeline
  .ado/publish.yml
Labels: AutoMerge

#9041 Fix building desktop in publish
  .ado/publish.yml
Labels: AutoMerge

#9049 MakeTurboModuleProvider<TModule> uses TModule::ModuleSpec as the spec
  change/@react-native-windows-codegen-0b9b7adf-601a-4110-a4bf-c1a97b3b611b.json
  change/react-native-windows-43ee5fe7-40a8-4b6e-8966-b04aea4bffcd.json
  packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts
  packages/@react-native-windows/codegen/src/generators/ParamTypes.ts
  packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts
  packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
  packages/sample-apps/windows/SampleLibraryCPP/MyModule.h
  packages/sample-apps/windows/SampleLibraryCPP/ReactPackageProvider.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.h
  vnext/Microsoft.ReactNative/Modules/AlertModule.h
  vnext/Microsoft.ReactNative/Modules/AppStateModule.h
  vnext/Microsoft.ReactNative/Modules/ClipboardModule.h
  vnext/Microsoft.ReactNative/Modules/DevSettingsModule.h
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.h
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.h
  vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.h
  vnext/Microsoft.ReactNative/Modules/LogBoxModule.h
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/codegen/NativeAccessibilityManagerSpec.g.h
  vnext/codegen/NativeActionSheetManagerSpec.g.h
  vnext/codegen/NativeAlertManagerSpec.g.h
  vnext/codegen/NativeAnimatedModuleSpec.g.h
  vnext/codegen/NativeAnimatedTurboModuleSpec.g.h
  vnext/codegen/NativeAppStateSpec.g.h
  vnext/codegen/NativeBlobModuleSpec.g.h
  vnext/codegen/NativeBugReportingSpec.g.h
  vnext/codegen/NativeClipboardSpec.g.h
  vnext/codegen/NativeDatePickerAndroidSpec.g.h
  vnext/codegen/NativeDevSplitBundleLoaderSpec.g.h
  vnext/codegen/NativeExceptionsManagerSpec.g.h
  vnext/codegen/NativeFileReaderModuleSpec.g.h
  vnext/codegen/NativeHeadlessJsTaskSupportSpec.g.h
  vnext/codegen/NativeImageLoaderAndroidSpec.g.h
  vnext/codegen/NativeImageLoaderIOSSpec.g.h
  vnext/codegen/NativeIntentAndroidSpec.g.h
  vnext/codegen/NativeLinkingManagerSpec.g.h
  vnext/codegen/NativeNetworkingAndroidSpec.g.h
  vnext/codegen/NativeNetworkingIOSSpec.g.h
  vnext/codegen/NativePermissionsAndroidSpec.g.h
  vnext/codegen/NativePushNotificationManagerIOSSpec.g.h
  vnext/codegen/NativeRedBoxSpec.g.h
  vnext/codegen/NativeSampleTurboModuleSpec.g.h
  vnext/codegen/NativeSegmentFetcherSpec.g.h
  vnext/codegen/NativeSettingsManagerSpec.g.h
  vnext/codegen/NativeShareModuleSpec.g.h
  vnext/codegen/NativeUIManagerSpec.g.h
  vnext/codegen/NativeWebSocketModuleSpec.g.h
Labels: Breaking Change

#9048 Automatically Use Large PCH on Machines With >7GB per Thread
  .ado/jobs/cli-init.yml
  .ado/templates/prepare-build-env.yml
  change/react-native-windows-df7a4350-83c2-46df-995f-2de1f60a9e70.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/FastBuild.targets
Labels: AutoMerge

#9062 Use beachball bump hook for version stamping
  beachball.config.js
  package.json
  yarn.lock
Labels: AutoMerge

#9061 Disable npm post/preinstall scripts
  .yarnrc.yml
  package.json
  packages/@react-native-windows/tester/package.json
  packages/e2e-test-app/package.json
  packages/playground/package.json
  patches/@react-native-picker+picker+2.1.0.patch
  yarn.lock
Labels: AutoMerge

#9035 Fixes default background for mouse events with border
  change/react-native-windows-f0084024-b791-4e76-a6ba-cdef4c805415.json
  packages/@react-native-windows/tester/src/js/examples-win/Mouse/MouseExample.windows.js
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Labels: AutoMerge

#9078 Reenable Integration Test App X64WebDebug
  .ado/jobs/integration-test.yml
Labels: Area: Tests, Area: Test Infrastructure

#9080 Add timeout to Setup Step
  .ado/jobs/setup.yml
Labels: AutoMerge

#9081 Temporarily use medium pool for low-resource jobs
  .ado/jobs/cli-init.yml
Labels: AutoMerge

#9056 Drop ChakraCore dependency
  change/react-native-windows-31cae2e4-d9d6-4999-b3be-6135db52e3f3.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraCoreDebugger.h
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Chakra/ChakraPlatform.h
  vnext/Chakra/ChakraTracing.cpp
  vnext/Chakra/ChakraValue.h
  vnext/Chakra/Utf8DebugExtensions.cpp
  vnext/Chakra/Utf8DebugExtensions.h
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/BytecodeUnitTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/JSI/ChakraJsiRuntime_core.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Shared/JSI/ChakraApi.cpp
  vnext/Shared/JSI/ChakraApi.h
  vnext/Shared/JSI/ChakraCoreRuntime.h
  vnext/Shared/JSI/ChakraJsiRuntime_edgemode.cpp
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntimeFactory.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Area: JavaScript Engine

#9077 Remove Beachball Steps from JSChecks
  .ado/integrate-rn.yaml
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/jschecks.yml
  .ado/jobs/macos-tests.yml
  .ado/jobs/nuget-desktop.yml
  .ado/jobs/playground.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/setup.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/templates/checkout-full.yml
  .ado/templates/checkout-shallow.yml
Labels: AutoMerge

#9083 Add visual tests for react-native-xaml
  .ado/scripts/SetupLocalDumps.cmd
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/examples-win/XAML/XAMLExample.tsx
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/e2e-test-app/package.json
  packages/e2e-test-app/test/XAMLTest.test.ts
  packages/e2e-test-app/test/__snapshots__/XAMLTest.test.ts.snap
  packages/e2e-test-app/windows/RNTesterApp/AutolinkedNativeModules.g.cs
  packages/e2e-test-app/windows/RNTesterApp/AutolinkedNativeModules.g.targets
  packages/e2e-test-app/windows/RNTesterApp/MainPage.xaml.cs
  packages/e2e-test-app/windows/ReactUWPTestApp.sln
  yarn.lock
Labels: AutoMerge, Area: Tests

#9085 Add e2etest:debug (`@react-native-windows/automation` option `breakOnStart`)
  change/@react-native-windows-automation-c32fc21b-3839-4bbe-b34b-0af4877b105f.json
  docs/e2e-testing.md
  packages/@react-native-windows/automation/README.md
  packages/@react-native-windows/automation/package.json
  packages/@react-native-windows/automation/src/AutomationEnvironment.ts
  packages/e2e-test-app/jest.debug.config.js
  packages/e2e-test-app/package.json
  yarn.lock
Labels: Area: Test Infrastructure

#9072 Cache NuGet Packages in CI
  .ado/jobs/desktop.yml
  .ado/jobs/playground.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/templates/msbuild-sln.yml
  .ado/templates/restore-sln.yml
  .ado/templates/run-windows-with-certificates.yml
  change/react-native-windows-383a8791-981f-4b5a-850c-13108e44f0cc.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/integration-test-app/windows/InteropTestModuleCS/InteropTestModuleCS.csproj
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
  packages/sample-apps/windows/NuGet.Config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  packages/sample-apps/windows/SampleLibraryCS/SampleLibraryCS.csproj
  packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/template/cs-app/proj/MyApp.csproj
  vnext/template/cs-lib/proj/MyLib.csproj
Labels: AutoMerge

#9089 Remove JSI.ForceSystemChakra runtime option
  change/react-native-windows-ca2dbe30-182a-42fa-8afb-2ee4b327e019.json
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Shared/OInstance.cpp
Labels: Area: JSI

#9091 [0.66] Drop ChakraCore dependency
  change/react-native-windows-fad79ca5-13cf-49fd-821b-9f808907c0e7.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraCoreDebugger.h
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Chakra/ChakraPlatform.h
  vnext/Chakra/ChakraTracing.cpp
  vnext/Chakra/ChakraValue.h
  vnext/Chakra/Utf8DebugExtensions.cpp
  vnext/Chakra/Utf8DebugExtensions.h
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/BytecodeUnitTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/JSI/ChakraJsiRuntime_core.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Shared/JSI/ChakraApi.cpp
  vnext/Shared/JSI/ChakraApi.h
  vnext/Shared/JSI/ChakraCoreRuntime.h
  vnext/Shared/JSI/ChakraJsiRuntime_edgemode.cpp
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntimeFactory.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Request Backport to 0.66

#9092 [0.65] Drop ChakraCore dependency
  change/react-native-windows-bea57326-f073-4faa-881a-beaf4abe5b3a.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraCoreDebugger.h
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Chakra/ChakraPlatform.h
  vnext/Chakra/ChakraTracing.cpp
  vnext/Chakra/ChakraValue.h
  vnext/Chakra/Utf8DebugExtensions.cpp
  vnext/Chakra/Utf8DebugExtensions.h
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/BytecodeUnitTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/JSI/ChakraJsiRuntime_core.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Shared/JSI/ChakraApi.cpp
  vnext/Shared/JSI/ChakraApi.h
  vnext/Shared/JSI/ChakraCoreRuntime.h
  vnext/Shared/JSI/ChakraJsiRuntime_edgemode.cpp
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntimeFactory.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Request Backport to 0.65

#9094 [0.64] Drop ChakraCore dependency
  change/react-native-windows-d5a2634f-26a8-4292-a059-827fb64480dc.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraCoreDebugger.h
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Chakra/ChakraPlatform.h
  vnext/Chakra/ChakraTracing.cpp
  vnext/Chakra/ChakraValue.h
  vnext/Chakra/Utf8DebugExtensions.cpp
  vnext/Chakra/Utf8DebugExtensions.h
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/BytecodeUnitTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/packages.config
  vnext/JSI/Desktop/ChakraJsiRuntime_core.cpp
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj.filters
  vnext/JSI/Shared/ChakraApi.cpp
  vnext/JSI/Shared/ChakraApi.h
  vnext/JSI/Shared/ChakraCoreRuntime.h
  vnext/JSI/Shared/ChakraJsiRuntime_edgemode.cpp
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntimeFactory.h
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Shared/OInstance.cpp
Labels: AutoMerge, Request Backport to 0.64

#9095 [0.67] Drop ChakraCore dependency
  change/react-native-windows-0daf15e9-aad9-4dab-bf83-85feb02fe179.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraCoreDebugger.h
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Chakra/ChakraPlatform.h
  vnext/Chakra/ChakraTracing.cpp
  vnext/Chakra/ChakraValue.h
  vnext/Chakra/Utf8DebugExtensions.cpp
  vnext/Chakra/Utf8DebugExtensions.h
  vnext/Desktop.DLL/DelayLoad.cpp
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj.filters
  vnext/Desktop.DLL/packages.config
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/packages.config
  vnext/Desktop.UnitTests/BytecodeUnitTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/JSI/ChakraJsiRuntime_core.cpp
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.sln
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Scripts/Microsoft.ChakraCore.ARM64.nuspec
  vnext/Scripts/Microsoft.ChakraCore.ARM64.targets
  vnext/Shared/JSI/ChakraApi.cpp
  vnext/Shared/JSI/ChakraApi.h
  vnext/Shared/JSI/ChakraCoreRuntime.h
  vnext/Shared/JSI/ChakraJsiRuntime_edgemode.cpp
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntimeFactory.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge

#9066 Integrate RN nightly build Oct 28.
  change/@office-iss-react-native-win32-a91701c3-ecd9-48fd-bb73-d2cd12cc2a73.json
  change/@react-native-windows-automation-channel-80e6a7f7-3ba1-492b-baa9-7a63845a18bc.json
  change/@react-native-windows-virtualized-list-78882adf-7ed7-45cf-bb9a-20403e863239.json
  change/react-native-windows-d6f3b318-273d-431a-b1ad-d9155b4c9032.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32-tester/src/js/components/RNTesterEmptyBookmarksState.win32.js
  packages/@office-iss/react-native-win32-tester/src/js/components/RNTesterExampleFilter.win32.js
  packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterStatePersister.win32.js
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/Image/Image.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Text/TextNativeComponent.win32.js
  packages/@office-iss/react-native-win32/src/index.win32.js
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/components/RNTesterEmptyBookmarksState.windows.js
  packages/@react-native-windows/virtualized-list/overrides.json
  packages/@react-native-windows/virtualized-list/package.json
  packages/@react-native-windows/virtualized-list/src/VirtualizedList.js
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/RNTesterAppShared.js
  packages/@react-native/tester/js/components/RNTPressableRow.js
  packages/@react-native/tester/js/components/RNTTestDetails.js
  packages/@react-native/tester/js/components/RNTTitleBar.js
  packages/@react-native/tester/js/components/RNTesterBlock.js
  packages/@react-native/tester/js/components/RNTesterEmptyBookmarksState.js
  packages/@react-native/tester/js/components/RNTesterExampleFilter.js
  packages/@react-native/tester/js/components/RNTesterModuleContainer.js
  packages/@react-native/tester/js/components/RNTesterModuleList.js
  packages/@react-native/tester/js/components/RNTesterTheme.js
  packages/@react-native/tester/js/components/RNTesterTitle.js
  packages/@react-native/tester/js/examples/Animated/EasingExample.js
  packages/@react-native/tester/js/examples/PanResponder/PanResponderExample.js
  packages/@react-native/tester/js/examples/PointerEvents/PointerEventsExample.js
  packages/@react-native/tester/js/examples/RTL/RTLExample.js
  packages/@react-native/tester/js/examples/Switch/SwitchExample.js
  packages/@react-native/tester/js/examples/TextInput/TextInputSharedExamples.js
  packages/@react-native/tester/js/utils/RNTesterStatePersister.js
  packages/@react-native/tester/overrides.json
  packages/@react-native/tester/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/Pressable/Pressable.windows.js
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Image/Image.windows.js
  vnext/src/Libraries/Text/Text.windows.js
  vnext/src/Libraries/Text/TextNativeComponent.windows.js
  vnext/src/index.windows.js
  yarn.lock
Labels: AutoMerge, Area: Mouse

#9100 Ensure EditorConfig formatting
  .ado/image/rnw-pool.json
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/linting.yml
  .ado/jobs/node-tests.yml
  .ado/jobs/playground.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/setup.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/templates/checkout-full.yml
  .ado/templates/checkout-shallow.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/prepare-build-env.yml
  .ado/templates/react-native-init.yml
  .ado/templates/run-windows-with-certificates.yml
  .ado/templates/set-appx-platforms.yml
  .ado/variables/shared.yml
  .ado/verdaccio/.gitignore
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#9086 Remove `shouldSkipPRBuild`
  .ado/jobs/setup.yml
  .ado/scripts/shouldSkipPRBuild.ps1
  .ado/stages.yml
Labels: AutoMerge

#9097 Add MSRN Debug NuGet Packages
  .ado/jobs/cli-init.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/prep-and-pack-single.yml
  .ado/templates/react-native-init.yml
  change/react-native-windows-2a8e9d35-0717-4fb3-9b6e-9bcc63445afb.json
  vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
  vnext/Scripts/Microsoft.ReactNative.nuspec
Labels: AutoMerge

#9116 [0.64] Fix crash loading bundle in win32
  change/react-native-windows-b73de70e-deb8-4965-b68d-d923af8e564e.json
  vnext/Shared/OInstance.cpp
Labels: Platform: Desktop

#9118 [0.66] Fix autolinking to support solution files using LF instead of CRLF
  change/@react-native-windows-cli-e4154948-d0ed-4b5e-8b9e-07f6541511da.json
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Labels: AutoMerge, Area: Developer Experience, Area: Autolinking

#9119 [0.65] Fix autolinking to support solution files using LF instead of CRLF
  change/@react-native-windows-cli-e4154948-d0ed-4b5e-8b9e-07f6541511da.json
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Labels: AutoMerge, Area: Developer Experience, Area: Autolinking

#9113 Add dependency resolution to address CVE-2021-3765 in validator
  package.json
  yarn.lock
Labels: AutoMerge

#9120 Fix crash loading bundle in win32
  change/react-native-windows-a3e7fa27-57ec-4eb0-b036-c7da150c5239.json
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9121 [0.67] Fix crash loading bundle in win32
  change/react-native-windows-63383496-65ba-4bbd-8fbe-ae1663fea35c.json
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9122 [0.66] Fix crash loading bundle in win32
  change/react-native-windows-4a6967e7-18f0-4732-878f-4858417b5dd7.json
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9123 [0.65] Fix crash loading bundle in win32
  change/react-native-windows-ac49a748-6516-4a80-8251-89f2de56b5d1.json
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9051 Removes unnecessary prop settings on VM base class
  change/react-native-windows-adf7c3ae-8861-4bc8-a2ae-3050153bf499.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Breaking Change

#9131 Remove redundant WindowsTargetPlatformVersion declarations
  change/react-native-windows-24e6fa5c-585c-4ab0-8b32-13b19646a7f3.json
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#9105 [0.65] Change AgentPool.Large to rnw-pool-8
  .ado/variables/vs2019.yml
Labels: AutoMerge

#9154 Fix C# Module Event invocation
  change/react-native-windows-e3bb9f17-25d6-48ef-883e-2bf697123812.json
  packages/sample-apps/index.windows.js
  packages/sample-apps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/sample-apps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/SyntaxHelpers.cs
Labels: AutoMerge, Request Backport to 0.65

#8253 Telemetry Refactor
  change/@react-native-windows-cli-557d7606-5df3-4353-a5c6-83182f773995.json
  change/@react-native-windows-telemetry-3f34ff95-a2f0-4909-87f4-db2fa77feaa9.json
  change/react-native-windows-init-b27fb9ca-e7a5-4701-9d47-5c1cd4bcd7c1.json
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/@react-native-windows/cli/src/e2etest/runWindows.test.ts
  packages/@react-native-windows/cli/src/index.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
  packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/CodedError.ts
  packages/@react-native-windows/telemetry/src/index.ts
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/projectUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/projects/BlankUsesReactNativeConfig/react-native.config.js
  packages/@react-native-windows/telemetry/src/test/projects/BlankUsesTypeScript/tsconfig.json
  packages/@react-native-windows/telemetry/src/test/projects/UsesPackageReference/UsesPackageReference.csproj
  packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/UsesPackagesConfig.vcxproj
  packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/packages.config
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
  packages/@react-native-windows/telemetry/src/test/sanitizeUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
  packages/@react-native-windows/telemetry/src/test/versionUtils.test.ts
  packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
  packages/@react-native-windows/telemetry/src/utils/errorUtils.ts
  packages/@react-native-windows/telemetry/src/utils/optionUtils.ts
  packages/@react-native-windows/telemetry/src/utils/projectUtils.ts
  packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
  packages/@react-native-windows/telemetry/src/utils/versionUtils.ts
  packages/react-native-windows-init/src/Cli.ts
  yarn.lock
Labels: Area: CLI, Area: Tests

#9159 [0.67] Fix C# Module Event invocation (#9154)
  change/react-native-windows-e3bb9f17-25d6-48ef-883e-2bf697123812.json
  packages/sample-apps/index.windows.js
  packages/sample-apps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/sample-apps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/SyntaxHelpers.cs
Labels: Request Backport to 0.65

#9160 [0.66] Fix C# Module Event invocation (#9154)
  change/react-native-windows-e3bb9f17-25d6-48ef-883e-2bf697123812.json
  packages/sample-apps/index.windows.js
  packages/sample-apps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/sample-apps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/SyntaxHelpers.cs
Labels: Request Backport to 0.65

#9178 Add environment variable overrides to specify telemetry setup string and proxy
  change/@react-native-windows-telemetry-2b84c3a1-6327-4e87-9833-c8a67256ca07.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
Labels: Area: Telemetry

#9039 Supports changing ToggleSwitch's color at runtime
  change/react-native-windows-b2039cc4-d9ae-41c3-8261-1f6a92ebdc98.json
  vnext/Microsoft.ReactNative/Utils/ResourceBrushUtils.cpp
  vnext/Microsoft.ReactNative/Utils/ResourceBrushUtils.h
  vnext/Microsoft.ReactNative/Views/SwitchViewManager.cpp
Labels: Area: Switch

#9193 Fix telemetry unit test timeouts
  change/@react-native-windows-telemetry-733c82bd-37df-4935-a8fd-9f0ef10dad8d.json
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/test/versionUtils.test.ts
  yarn.lock
Labels: AutoMerge, Area: Tests, Area: Telemetry

#9199 Block old telemetry events from firing
  change/@react-native-windows-telemetry-59ec6aad-e0df-4b25-9435-3e02e2d6296b.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
Labels: AutoMerge, Area: CLI, Area: Telemetry

#9202 [0.65] Make ADK dependency optional in dependency script
  .ado/jobs/universal.yml
  change/react-native-windows-6ee7207e-33bb-4654-9f55-1a007584f2a0.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge, Area: Tests, Area: Build Infrastructure

#9200 Fix telemetry path sanitization to handle our packages in the npx cache
  change/@react-native-windows-telemetry-2bc4bbb3-d817-4598-86cc-786b31a14866.json
  packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/sanitizeUtils.test.ts
  packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
Labels: AutoMerge, Area: CLI, Area: Telemetry

#9161 [0.65] Fix C# Module Event invocation (#9154)
  change/react-native-windows-e3bb9f17-25d6-48ef-883e-2bf697123812.json
  packages/sample-apps/index.windows.js
  packages/sample-apps/windows/SampleLibraryCPP/SampleModuleCPP.h
  packages/sample-apps/windows/SampleLibraryCS/SampleModuleCS.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenEventTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--MultipleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--NoArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsField.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/CodeGen/Lkg/Microsoft.ReactNative.Managed.CodeGen.UnitTests.CodeGen.CodeGenFunctionTests--SingleArgsProperty.lkg
  vnext/Microsoft.ReactNative.Managed.CodeGen/CodeGenerator.Module.cs
  vnext/Microsoft.ReactNative.Managed.CodeGen/SyntaxHelpers.cs
Labels: Request Backport to 0.65

#9207 CG: Update version of jsprim to get updated json-schema
  yarn.lock
Labels: AutoMerge, security, Request Backport to 0.64, Request Backport to 0.65, Request Backport to 0.66, Request Backport to 0.67

#9209 [0.67] CG: Update version of jsprim to get updated json-schema
  yarn.lock
Labels: AutoMerge

#9215 Update Component Governance to only run when needed
  .ado/jobs/desktop.yml
  .ado/jobs/project-reunion.yml
  .ado/jobs/universal.yml
Labels: Area: Test Infrastructure

#9210 [0.66] Backporting CG fixes
  package.json
  yarn.lock
Labels: AutoMerge

#9213 [0.64] Backporting CG fixes
  package.json
  yarn.lock
Labels: AutoMerge
