Repository microsoft/react-native-windows, pull requests merged in 2021-07, with the labels that each got.

#8146 Remove unnecessary line from GetCompositor
  change/react-native-windows-dc38be40-2c3f-4b74-8f0e-98b90d52fe01.json
  vnext/Microsoft.ReactNative/XamlView.cpp
Labels: Area: Animation, AutoMerge, Request Backport to 0.64, Request Backport to 0.65

#8155 [0.63] Backporting AccessibilityControls prop on ViewWin32
  change/@office-iss-react-native-win32-2021-07-03-12-41-38-sammy-0.63_ViewWin32Config_Backport.json
  packages/react-native-win32/docs/api/react-native-win32.basepropswin32.md
  packages/react-native-win32/etc/react-native-win32.api.md
  packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Labels: Backported to 0.63

#8154 [0.64] Backporting AccessibilityControls prop on ViewWin32
  change/@office-iss-react-native-win32-ab588088-9d63-4f25-b0da-123dfa0d64fd.json
  packages/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Labels: Backported to 0.64

#8153 [0.65] Backporting AccessibilityControls prop on ViewWin32 to 0.65
  change/@office-iss-react-native-win32-4dda44c6-b595-42d3-93cf-245cae23ce5c.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewViewConfig.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
Labels: Backported to 0.65

#8170 Add hooks to allow instance to be usable with pluggable UI platforms
  .ado/jobs/desktop.yml
  change/@office-iss-react-native-win32-e08e70eb-e50d-452b-9414-a3980e22a905.json
  change/react-native-windows-26a7dc77-a8eb-4dcf-9963-5acdcc5e06d3.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/TextInput/TextInput.win32.tsx
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
  packages/@office-iss/react-native-win32/src/Libraries/ReactNative/PaperUIManager.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/module.g.cpp
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.h
  vnext/Microsoft.ReactNative/ReactCoreInjection.idl
  vnext/Microsoft.ReactNative/ReactHost/JSCallInvokerScheduler.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/RedBox.h
  vnext/Microsoft.ReactNative/RedBoxHandler.cpp
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge

#8186 [0.64] Add hooks to allow instance to be usable with pluggable UI platforms
  .ado/windows-vs-pr.yml
  change/@office-iss-react-native-win32-8a0dc0bb-85e9-4a78-8150-f8b763fa05f4.json
  change/react-native-windows-ae1c2677-4b46-40bb-8c42-edff1da29e2c.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/Components/TextInput/TextInput.win32.tsx
  packages/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
  packages/react-native-win32/src/Libraries/ReactNative/PaperUIManager.win32.js
  packages/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/module.g.cpp
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.h
  vnext/Microsoft.ReactNative/ReactCoreInjection.idl
  vnext/Microsoft.ReactNative/ReactHost/JSCallInvokerScheduler.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/RedBox.h
  vnext/Microsoft.ReactNative/RedBoxHandler.cpp
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Scripts/Tfs/Layout-Headers.ps1
Labels: AutoMerge

#8194 [0.65] Fix e2e-test-app intermittency
  packages/@react-native-windows/tester/src/js/examples-win/DisplayNone/DisplayNoneExample.windows.tsx
  packages/e2e-test-app/test/DisplayNoneTest.test.ts
  packages/e2e-test-app/test/__snapshots__/DisplayNoneTest.test.ts.snap
Labels: AutoMerge

#8006 Adds timestamp to onKeyUp/Down events
  change/react-native-windows-8cc2d5c9-9a96-49cd-9235-6d0679ed92e4.json
  vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp
  vnext/proposals/active/keyboard-reconcile-desktop.md
Labels: AutoMerge

#8209 Allow multiple calls to alert
  change/react-native-windows-296a5268-bc99-4005-884c-1196ca4b8bac.json
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
  vnext/Microsoft.ReactNative/Modules/AlertModule.h
Labels: Area: Alert, AutoMerge

#8039 Use DispatcherTimer unless animation frame needed
  change/react-native-windows-97eb0bc5-471b-4848-bdf8-edd943238c00.json
  vnext/Microsoft.ReactNative/Modules/TimingModule.cpp
  vnext/Microsoft.ReactNative/Modules/TimingModule.h
Labels: Area: TimingModule

#8226 [0.63] Add check to cancel publish if the last commit was itself a publish (#7716)
  .ado/publish.yml
Labels: Area: Build Infrastructure

#8230 Add React.Windows.Desktop\** to published build artifacts
  .ado/publish.yml
Labels: Request Backport to 0.64, Request Backport to 0.65

#8231 [0.65] Add React.Windows.Desktop\** to published build artifacts
  .ado/publish.yml
Labels: Request Backport to 0.64, Request Backport to 0.65

#8214 [0.65] Allow multiple calls to alert
  change/react-native-windows-de1752b0-dbd2-4922-a3f9-5d34d99c5e26.json
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
  vnext/Microsoft.ReactNative/Modules/AlertModule.h
Labels: AutoMerge

#8215 [0.64] Allow multiple calls to alert
  change/react-native-windows-f6515af1-8691-48f1-899b-558df1fea435.json
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
  vnext/Microsoft.ReactNative/Modules/AlertModule.h
Labels: AutoMerge

#8223 [0.65] Revert Pre-RC CLI Workaround
  beachball.config.js
  change/@react-native-windows-cli-25139461-4fba-4c95-aa27-fdb14bab09a5.json
  package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/postinstall.ts
Labels: Area: CLI

#8222 [0.65] Integrate RN 0.65.0-rc.2
  change/@office-iss-react-native-win32-d7689351-707e-47b6-9463-948e4e5d952f.json
  change/react-native-windows-1d85d861-3541-44e6-ba11-f57293d70eb4.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/tester/js/examples/Text/TextExample.android.js
  packages/@react-native/tester/js/examples/Text/TextExample.ios.js
  packages/@react-native/tester/overrides.json
  packages/@rnw-scripts/jest-out-of-snapshot-resolver/package.json
  packages/@rnw-scripts/jest-out-of-tree-resolver/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/node-rnw-rpc/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Text/Text.windows.js
  yarn.lock
Labels: AutoMerge

#8241 Enable interactive tests on more powerfull agents
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/variables/vs2019.yml
Labels: AutoMerge

#8147 Integrate June 9 Nightly RN Build
  change/@office-iss-react-native-win32-94d1206b-0696-4766-99fd-b8d90c32d00b.json
  change/@react-native-windows-virtualized-list-ce2199f9-40e8-458c-be23-41a42eede4dc.json
  change/node-rnw-rpc-fb7c16bc-ad37-4a71-9663-69d510de4bba.json
  change/react-native-windows-7e8b6ba8-85f2-464c-bcb9-008c3749a75f.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32-tester/src/js/components/RNTesterExampleFilter.win32.js
  packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/index.win32.js
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/examples/Pressable/PressableExample.windows.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/@react-native-windows/virtualized-list/overrides.json
  packages/@react-native-windows/virtualized-list/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/assets/bottom-nav-center-box.png
  packages/@react-native/tester/js/components/ExamplePage.js
  packages/@react-native/tester/js/components/RNTesterBlock.js
  packages/@react-native/tester/js/components/RNTesterExampleFilter.js
  packages/@react-native/tester/js/components/RNTesterHeader.js
  packages/@react-native/tester/js/components/RNTesterNavbar.js
  packages/@react-native/tester/js/examples/Animated/AnimatedExample.js
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExApp.js
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExBobble.js
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExChained.js
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExScroll.js
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExSet.js
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExSlides.md
  packages/@react-native/tester/js/examples/AnimatedGratuitousApp/AnExTilt.js
  packages/@react-native/tester/js/examples/Pressable/PressableExample.js
  packages/@react-native/tester/js/examples/ScrollView/ScrollViewExample.js
  packages/@react-native/tester/js/examples/SwipeableCardExample/SwipeableCardExample.js
  packages/@react-native/tester/js/examples/Text/TextExample.android.js
  packages/@react-native/tester/js/examples/Text/TextExample.ios.js
  packages/@react-native/tester/js/utils/RNTesterList.android.js
  packages/@react-native/tester/js/utils/RNTesterList.ios.js
  packages/@react-native/tester/overrides.json
  packages/e2e-test-app/package.json
  packages/e2e-test-app/test/LegacyTextInputTest.test.ts
  packages/e2e-test-app/test/__snapshots__/TextComponentTest.test.ts.snap
  packages/integration-test-app/package.json
  packages/node-rnw-rpc/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/uimanager/UIManagerBinding.h
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/Picker/Picker.windows.js
  vnext/src/index.windows.js
  yarn.lock
Labels: AutoMerge

#8260 Fix for #8087. Disable 'unreachable code' warning for RethrowJsiError usage.
  change/react-native-windows-796dc7c7-51ba-49cf-a162-02374de38abe.json
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
Labels: Area: JSI

#8268 Drop BaseIntDir setting from CI
  .ado/jobs/playground.yml
  .ado/templates/build-rnw.yml
  .ado/templates/run-windows-with-certificates.yml
  .ado/variables/vs2019.yml
Labels: Area: Build Infrastructure

#8267 Move from windevpool to rnw-pool for universal and medium pool now suports interactive
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/universal.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/variables/vs2019.yml
  change/react-native-windows-cc6b9293-23e0-4735-b163-bc6d05190dd1.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/Scripts/Microsoft.ReactNative.Managed.nuspec
Labels: Area: Build Infrastructure

#8282 Update instructions for running a single E2E test
  docs/e2e-testing.md
Labels: Area: Test Infrastructure

#8281 Do not start packager for run-windows release builds
  change/@react-native-windows-cli-f7148586-13ff-456d-8981-5dfe310c2e37.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: Area: CLI, Area: Developer Experience, Area: Infrastructure

#7461 Re-add PlatformColorExample.win32.ts and remove 'use strict' from .d.ts files
  change/@office-iss-react-native-win32-41861b96-0c64-45c4-b5ea-c35b4df5057a.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/src/js/examples/PlatformColor/PlatformColorExample.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/StyleSheet/PlatformColorValueTypesWin32.d.ts
  packages/@office-iss/react-native-win32/src/Libraries/Utilities/FocusManager.win32.d.ts
Labels: Area: PlatformColor, AutoMerge

#7685 Remove DatePicker and PickerWindows
  change/react-native-windows-bbba972c-caf2-4885-844a-04d1845152bd.json
  packages/@react-native-windows/tester/src/js/examples-win/DatePicker/DatePickerExample.windows.tsx
  packages/@react-native-windows/tester/src/js/examples-win/Flyout/FlyoutExample.windows.tsx
  packages/@react-native-windows/tester/src/js/examples-win/Keyboard/KeyboardExample.tsx
  packages/@react-native-windows/tester/src/js/examples-win/Keyboard/KeyboardFocusExample.windows.tsx
  packages/@react-native-windows/tester/src/js/examples-win/LegacyTests/ControlStyleTestPage.tsx
  packages/@react-native-windows/tester/src/js/examples-win/Picker/PickerWindowsExample.tsx
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/e2e-test-app/test/__snapshots__/LegacyControlStyleTest.test.ts.snap
  vnext/Microsoft.ReactNative/Base/CoreUIManagers.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Views/DatePickerViewManager.cpp
  vnext/Microsoft.ReactNative/Views/DatePickerViewManager.h
  vnext/overrides.json
  vnext/src/Libraries/Components/DatePicker/DatePicker.tsx
  vnext/src/Libraries/Components/DatePicker/DatePickerProps.ts
  vnext/src/index.windows.js
  vnext/src/typings-index.ts
Labels: Breaking Change

#8320 Disable warnAsError for projectReunion in publish as well
  .ado/jobs/project-reunion.yml
  .ado/publish.yml
Labels: AutoMerge

#8344 Fix issue using react-native-debugger with react-native-windows
  change/react-native-windows-5d74fe3c-efd2-479b-ab75-810f5f266a11.json
  vnext/Shared/Executors/WebSocketJSExecutor.cpp
  vnext/Shared/Executors/WebSocketJSExecutor.h
Labels: AutoMerge
