Repository microsoft/react-native-windows, pull requests merged in 2021-03, with the labels that each got.

#7220 Fix announceForAccessibility
  change/react-native-windows-29f65fa8-43ca-4485-9da4-0168ac84cd17.json
  vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp
Labels: Area: Accessibility

#7238 Update NuGetCommand@2 with workaround for microsoft ADO
  .ado/templates/build-rnw.yml
  .ado/templates/prep-and-pack-single.yml
Labels: AutoMerge

#7222 Narrow fix for tintColor and repeat images
  change/react-native-windows-529f30ae-e99b-41c4-8da5-fd63deb8c688.json
  vnext/Microsoft.ReactNative/Views/Image/ReactImageBrush.cpp
Labels: Area: Image, AutoMerge

#7221 Ensure root views are properly unloaded
  change/react-native-windows-2021-03-01-10-44-41-fix-unloading.json
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.h
Labels: AutoMerge

#7248 runtimeExecutor discards std::thread ctor
  change/react-native-windows-7abcb8aa-50a6-40b6-9a5a-e17677e2bdba.json
  change/react-native-windows-923d9c58-108f-4eb0-9f78-dfa4daabec03.json
  packages/e2e-test-app/windows/ReactUWPTestApp/AutolinkedNativeModules.g.targets
  vnext/Microsoft.ReactNative/XamlUIService.cpp
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/runtimeexecutor/ReactCommon/RuntimeExecutor.h
  vnext/overrides.json
Labels: AutoMerge

#7228 Update WinAppDriver version requirement
  change/react-native-windows-96f79fad-22cc-49c2-a3a1-7727f3903e48.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Test Infrastructure, AutoMerge

#7259 Fixes registration name for TextInput onScroll
  change/react-native-windows-c5698690-4198-40b4-8676-9fc490f8f49d.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: AutoMerge

#7275 [0.64] Remove HostObject Jsi exceptions
  change/react-native-windows-04ac2b06-039a-423c-af36-e8d00d6866a1.json
  vnext/JSI/Shared/ChakraRuntime.cpp
Labels: AutoMerge

#7274 Remove HostObject Jsi exceptions
  change/react-native-windows-b281f453-7a97-4544-81e3-b1a1dd93ce1b.json
  vnext/Shared/JSI/ChakraRuntime.cpp
Labels: AutoMerge

#7278 Fix cursor warning when right clicking
  change/react-native-windows-97d7ac05-284f-40fe-9829-493043e1988b.json
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Labels: Area: Mouse

#7273 Fix documentation for running a single E2ETest Test
  docs/e2e-testing.md
Labels: Area: Test Infrastructure, AutoMerge

#7260 Coalesce ScrollView Messages
  change/react-native-windows-2602b5c0-d5d5-4250-a951-5a26601422b2.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.h
Labels: Area: FlatList, Area: Performance, AutoMerge

#7179 Remove ChakraExecutor (non-JSI)
  change/react-native-windows-48b2fbac-250b-4c35-89f0-7b4354d42798.json
  vnext/Chakra/Chakra.vcxitems
  vnext/Chakra/Chakra.vcxitems.filters
  vnext/Chakra/ChakraExecutor.cpp
  vnext/Chakra/ChakraExecutor.h
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/DevSettings.h
  vnext/Shared/OInstance.cpp
Labels: Area: Instance Management, Area: JavaScript Engine, AutoMerge

#7280 Remove stale Appium comment
  change/react-native-windows-66a7a026-2973-48ac-ad29-9153ea483a8b.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Test Infrastructure, AutoMerge

#7284 [0.63] Avoid exporting data as that breaks delay loading
  change/react-native-windows-2021-03-04-18-44-45-0.63-stable.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
Labels: AutoMerge

#7249 [0.64] runtimeExecutor discards std::thread ctor
  change/react-native-windows-8ca60002-6df1-4469-897a-8c8d042c448f.json
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/runtimeexecutor/ReactCommon/RuntimeExecutor.h
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64

#7250 [0.63] runtimeExecutor discards std::thread ctor
  change/react-native-windows-3c934fc7-f0b4-4edc-826d-08fde563d7ed.json
  change/react-native-windows-9cce7d7e-9829-435d-b6a2-afe52b28a8de.json
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/runtimeexecutor/ReactCommon/RuntimeExecutor.h
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64

#7287 Avoid re-registering render callbacks when coalescing single element queue
  change/react-native-windows-b4e6adb2-e454-4bfe-9455-8bc887380703.json
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.cpp
  vnext/Microsoft.ReactNative/Utils/BatchingEventEmitter.h
Labels: AutoMerge

#7298 [0.64] Fix autolinking for solutions that have 'Any CPU' projects
  change/@react-native-windows-cli-7acd994f-3013-46a4-ba8d-83ed7b864d10.json
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Labels: Area: CLI, AutoMerge, Request Backport to 0.64

#7306 Added 0.64+ to projectType flag for react-native-windows-init cli
  change/react-native-windows-init-ff672186-e7d4-4afc-a426-920010c7da26.json
  packages/react-native-windows-init/src/Cli.ts
Labels: Area: CLI, Request Backport to 0.64

#7310 [0.64] Clarify some API docs
  change/react-native-windows-319707ea-206f-44ae-a849-d12574f2b011.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactNotificationService.idl
  vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
  vnext/Microsoft.ReactNative/IViewManager.idl
Labels: AutoMerge

#7320 Fix merge
  change/react-native-windows-d67b5b95-1b98-40f6-b290-73e9b6dd7a41.json
  vnext/Microsoft.ReactNative/XamlUIService.cpp
Labels: AutoMerge

#7317 Doc improvements
  change/react-native-windows-319707ea-206f-44ae-a849-d12574f2b011.json
  change/react-native-windows-d67e55dd-0364-4967-b689-a5ea88430e62.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactNotificationService.idl
  vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
  vnext/Microsoft.ReactNative/IViewManager.idl
Labels: AutoMerge

#7307 [0.64] Fix cursor warning when right clicking (#7278)
  change/react-native-windows-97d7ac05-284f-40fe-9829-493043e1988b.json
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Labels: AutoMerge, Request Backport to 0.64

#7319 Disable warning 4103 in MemoryMappedBufferTests.cpp
  change/react-native-windows-00b73d31-195e-4e20-97d3-444d09a770eb.json
  vnext/Desktop.UnitTests/MemoryMappedBufferTests.cpp
Labels: Area: Tests, AutoMerge, Platform: Desktop

#7316 [0.63] Add NugetSecurityAnalysisWarningLevel=warn for publish.yml
  .ado/publish.yml
Labels: AutoMerge

#7315 [0.64] Add NugetSecurityAnalysisWarningLevel=warn for publish.yml
  .ado/publish.yml
Labels: AutoMerge

#7340 More doc formatting
  change/react-native-windows-a537dfa1-1200-41e7-add4-81130e198ccd.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IViewManager.idl
Labels: AutoMerge

#7335 Enable view managers to be notified about JS event handler attach/detach
  change/react-native-windows-560f15c9-e411-419e-8d58-46cdcbb247ef.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/IViewManagerCore.idl
Labels: AutoMerge

#7341 [0.64] port doc formatting fix
  change/react-native-windows-c1da70c2-1880-4789-97f4-349ddec7b248.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IViewManager.idl
Labels: AutoMerge, Backport to 0.64 Approved

#7343 [0.63] Update NuGetCommand@2 with workaround for microsoft ADO (#7238)
  .ado/templates/build-rnw.yml
  .ado/templates/prep-and-pack-single.yml
Labels: AutoMerge

#7342 [0.64] Update NuGetCommand@2 with workaround for microsoft ADO (#7238)
  .ado/templates/build-rnw.yml
  .ado/templates/prep-and-pack-single.yml
Labels: AutoMerge

#7304 Fixes case where focus commands may be ignored
  change/react-native-windows-58079bd4-79e5-455a-a510-7b6beb15e66b.json
  vnext/src/Libraries/Components/TextInput/TextInputState.windows.js
Labels: AutoMerge

#6958 Enabling codesigning via ESRP
  .ado/publish.yml
  .ado/templates/prep-and-pack-single.yml
  change/react-native-windows-c49d4321-957d-48c6-b7fb-a7187ea03568.json
  vnext/Scripts/Microsoft.ReactNative.Cxx.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.SignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.SignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.SignConfig.xml
Labels: Needs: Author Feedback, Request Backport to 0.64

#7279 Include ViewPanel.Top/Left in E2E tree dumps
  packages/e2e-test-app/test/__snapshots__/LegacyControlStyleTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/LegacyImageTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/LegacyTextBackgroundColorTest.test.ts.snap
  packages/e2e-test-app/windows/ReactUWPTestApp/MainPage.xaml.cs
Labels: Area: Layout, Area: Test Infrastructure

#7355 [0.64] Disable warning 4103 in MemoryMappedBufferTests.cpp
  change/react-native-windows-7fe6b7ea-630a-4f0e-bf79-394a1ddb0f0a.json
  vnext/Desktop.UnitTests/MemoryMappedBufferTests.cpp
Labels: AutoMerge, Platform: Desktop

#7350 [0.64] Enabling codesigning via ESRP
  .ado/publish.yml
  .ado/templates/prep-and-pack-single.yml
  change/react-native-windows-65c4a147-9e2f-47b4-9068-d66775a59aa3.json
  vnext/Scripts/Microsoft.ReactNative.Cxx.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.CodeGen.SignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.Managed.SignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.NugetSignConfig.xml
  vnext/Scripts/Microsoft.ReactNative.SignConfig.xml
Labels: AutoMerge

#7356 Raise Instance notifications in JSDispatcher thread
  change/react-native-windows-65cb61de-5d53-4917-8d6e-b50d3b506a93.json
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.js
  vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj.filters
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
  vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TestReactNativeHostHolder.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
Labels: Area: JSI, AutoMerge, Needed for 0.64

#7176 Include Hermes NuGet Package By Default
  .ado/jobs/cli-init.yml
  change/@react-native-windows-cli-94433c22-4d45-472b-9b7b-7c969bc5a44f.json
  change/react-native-windows-d6524b7e-7404-429d-b010-cdb3140323f3.json
  change/react-native-windows-init-8cd79b0d-0869-4ff5-a2cd-c6c66b9d4c1a.json
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/projectConfig.test.ts.snap
  packages/@react-native-windows/cli/src/e2etest/projectConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projectConfig.utils.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/playground/packages.config
  packages/playground/windows/ExperimentalFeatures.props
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.h
  packages/playground/windows/playground/MainPage.xaml
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/packages.config
  packages/react-native-windows-init/src/Cli.ts
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.DLL/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/Bundle.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.props
  vnext/PropertySheets/JSEngine.props
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/HermesRuntimeHolder.h
  vnext/template/shared-app/proj/ExperimentalFeatures.props
Labels: AutoMerge

#7285 Change TextInput cursor behavior
  change/react-native-windows-b3c2f4a8-d704-4a38-b837-993459d15495.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: AutoMerge

#7352 Update to newer cppwinrt, 2-3% reduction in binary size
  change/@react-native-windows-cli-592e7fc9-318f-4345-9b14-81644a198cce.json
  change/node-rnw-rpc-570cbab7-7ac0-4737-9f48-660f8f0d1f3f.json
  change/react-native-windows-54baf16d-d7fd-4199-a7ff-4a60d320c96c.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/integration-test-app/windows/integrationtest/packages.config
  packages/node-rnw-rpc/windows/NodeRpc/NodeRpc.vcxproj
  packages/node-rnw-rpc/windows/NodeRpc/packages.config
  packages/playground/packages.config
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/sample-apps/windows/SampleAppCPP/packages.config
  packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  packages/sample-apps/windows/SampleLibraryCPP/packages.config
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/packages.config
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.Test.DLL/React.Windows.Desktop.Test.DLL.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/packages.config
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/packages.config
  vnext/Directory.Build.targets
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/packages.config
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/packages.config
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/packages.config
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
Labels: Area: Infrastructure, AutoMerge

#7396 Fix codesign parameter passing
  .ado/publish.yml
Labels: AutoMerge

#7398 Fix build for codegen test on new agents
  change/react-native-windows-03e0841c-eea4-4548-912a-5ca9abe8284d.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
Labels: AutoMerge

#7399 [0.64] Fix build for codegen test on new agents
  .ado/templates/e2e-test-job.yml
  change/react-native-windows-b6e73d45-2af4-4c9c-97f3-2591a3cb6fce.json
  packages/E2ETest/wdio.conf.js
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp.csproj
  packages/E2ETest/windows/ReactUWPTestApp/ReactUWPTestApp_TemporaryKey.pfx
  packages/E2ETest/windows/ReactUWPTestApp/copyTreeDump.cmd
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/AnalysisTestBase.cs
Labels: AutoMerge, Backport to 0.64 Approved

#7397 Get constants for view manager throws
  change/react-native-windows-2a59f263-f757-4309-93ae-257a58fa468a.json
  vnext/src/Libraries/ReactNative/PaperUIManager.windows.js
Labels: AutoMerge

#7386 Minor docs update for ReactDispatcherHelper
  change/react-native-windows-a27fc5d4-c7b6-4ca9-8b02-26521cc3a3c3.json
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
Labels: AutoMerge

#7405 Improve error message for forgetting to run `Yarn change`
  .ado/windows-vs-pr.yml
Labels: AutoMerge

#7377 [0.64] Fix DevMenuControl.xbf copy conflict (#7153)
  change/react-native-windows-bac296d9-c8c9-452c-861e-6e9a1fa7872a.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
Labels: AutoMerge

#7378 [0.64] Fix deep linking activation (#7011)
  change/react-native-windows-6afc98ef-6d70-4f4d-9fcb-85784bfdfc82.json
  change/react-native-windows-93385742-18a3-4c29-b83b-1b87733bb4ce.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.cpp
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/App.h
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/App.xaml.cs
  vnext/template/cpp-app/src/App.cpp
  vnext/template/cpp-app/src/App.h
  vnext/template/cs-app/src/App.xaml.cs
Labels: AutoMerge

#7393 Updates to documentation in IDL files
  change/react-native-windows-e0a73f29-3f67-499f-953d-3427552c2bad.json
  vnext/Microsoft.ReactNative/IJSValueReader.idl
  vnext/Microsoft.ReactNative/IJSValueWriter.idl
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
  vnext/Microsoft.ReactNative/IReactModuleBuilder.idl
  vnext/Microsoft.ReactNative/IReactNonAbiValue.idl
  vnext/Microsoft.ReactNative/IReactNotificationService.idl
  vnext/Microsoft.ReactNative/IReactPackageBuilder.idl
  vnext/Microsoft.ReactNative/IReactPackageProvider.idl
  vnext/Microsoft.ReactNative/IReactPropertyBag.idl
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/Microsoft.ReactNative/QuirkSettings.idl
  vnext/Microsoft.ReactNative/ReactApplication.idl
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.idl
  vnext/Microsoft.ReactNative/ReactRootView.idl
  vnext/Microsoft.ReactNative/RedBoxHandler.idl
  vnext/Microsoft.ReactNative/XamlHelper.idl
  vnext/Microsoft.ReactNative/XamlUIService.idl
Labels: AutoMerge

#7420 Update option name due to breaking change in create-react-native-module
  .ado/templates/react-native-init.yml
Labels: AutoMerge

#7415 Make BaseWebSocketResource destructor noexcept
  change/react-native-windows-885d112a-fe20-474d-8ac2-06adf41cdf0d.json
  vnext/Desktop/BeastWebSocketResource.cpp
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64

#7421 Add retries to Folly download
  change/react-native-windows-e8fc0ecf-f569-432a-a940-79548093f13f.json
  vnext/Folly/Folly.vcxproj
Labels: AutoMerge

#7422 [0.64] Fix CI due to breaking change in create-react-native-module
  .ado/templates/react-native-init.yml
Labels: AutoMerge

#7447 [0.64] Autolinking doesn't add a project marked as a non-direct dependency
  change/@react-native-windows-cli-d0076a39-a34a-488b-990f-f2622a21750d.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge

#7458 [0.63] Backport nuget buggyness fix
  .ado/variables/vs2019.yml
Labels: Request Backport to 0.63

#7441 Fix deployment of x64 apps when they've also been already built for x86
  change/@react-native-windows-cli-e8a45edf-cfc4-4a35-9121-5f3088d8799b.json
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: Area: CLI

#7452 [0.63] Autolinking doesn't add a project marked as a non-direct dependency
  change/@react-native-windows-cli-7995510b-9839-4382-b2f4-2e6ebe444f00.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge

#7464 Fix app template to use app.json's name for main component name
  change/@react-native-windows-cli-0feca964-7b3e-404c-8e51-364f88390786.json
  change/react-native-windows-c082b40c-f14b-48a1-b788-08264f8c0382.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/template/shared-app/src/MainPage.xaml
Labels: Area: Bundle, Request Backport to 0.64

#7471 [0.64] Fix app template to use app.json's name for main component name (#7464)
  change/@react-native-windows-cli-4be2d5ca-e277-4951-82bf-da53ce53d4de.json
  change/react-native-windows-49f20f25-562a-474d-a144-4ca4afc65f68.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/template/shared-app/src/MainPage.xaml
Labels: Area: Bundle, Request Backport to 0.64

#7472 [0.63] Fix app template to use app.json's name for main component name (#7464)
  change/@react-native-windows-cli-2021-03-24-14-50-09-appjson63.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/templates/shared/src/MainPage.xaml
Labels: Area: Bundle, Request Backport to 0.64

#7470 Suppress onLayout event when layout has not changed
  change/react-native-windows-5eed73aa-6cf2-4940-9e6e-d2ae1d5b0740.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: AutoMerge

#7478 [0.64] Bump peer dependency to require non-rc version of react-native
  change/@office-iss-react-native-win32-b242d66c-aec8-416c-9627-bfbad81339b1.json
  change/react-native-windows-1e08502b-2b0f-460c-8875-7512862d716b.json
  packages/react-native-win32/package.json
  vnext/package.json
Labels: AutoMerge

#7477 [0.63] Fix AppStateModule::GetCurrentAppState from returning undefined
  change/react-native-windows-2021-03-25-11-59-48-appstatechangeFix.json
  vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
Labels: Request Backport to 0.63

#7489 Implement JSI getOwnPropertyDescriptor
  change/react-native-windows-dcbf0582-57f0-4850-9088-108360f8205f.json
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntime.h
Labels: AutoMerge

#7490 [0.64] getOwnPropertyDescriptor missing implementation
  change/react-native-windows-a1ef06ee-6340-494c-bcec-f6cf094f4c70.json
  vnext/JSI/Shared/ChakraRuntime.cpp
  vnext/JSI/Shared/ChakraRuntime.h
Labels: AutoMerge, Request Backport to 0.64

#7499 Update folly to 2021.03.29.00
  change/react-native-windows-0f876f10-0c77-4626-bfdb-331800a31965.json
  vnext/Directory.Build.props
  vnext/Folly/.clang-format
  vnext/Folly/Folly.vcxproj
  vnext/Folly/Folly.vcxproj.filters
  vnext/Folly/TEMP_UntilFollyUpdate/portability/Builtins.h
  vnext/stubs/double-conversion/double-conversion.h
  vnext/stubs/fmt/format.h
Labels: AutoMerge

#7498 [0.64] Enable apps to override WinUI and SDK version for RNW framework projects
  change/react-native-windows-c07dd628-fa24-4ff3-967e-d2ba099bd9b5.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/PropertySheets/React.Cpp.props
  vnext/PropertySheets/WinUI.props
Labels: AutoMerge, Request Backport to 0.64
