Repository microsoft/react-native-windows, pull requests merged in 2021-06, with the labels that each got.

#7896 [0.65] Allow propagating WinRTWebSocketResource constructor exceptions
  change/react-native-windows-528a6d68-44a6-40ab-8e25-63b25356b527.json
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: AutoMerge

#7897 [0.64] Allow propagating WinRTWebSocketResource constructor exceptions
  change/react-native-windows-6ba7b85f-119d-450d-a7e6-4aebe3e23210.json
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: AutoMerge

#7887 [0.64] Bump ws dependency
  change/react-native-windows-afc90ab9-a345-490e-a27c-7f2092a8773d.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge, Request Backport to 0.64, security

#7913 Specify Upload Appx Conditions for Playground Pipeline
  .ado/jobs/playground.yml
Labels: Area: Build Infrastructure

#7915 CG: Update vulnerable versions of ws to 7.4.6
  package.json
  packages/@react-native/tester/package.json
  packages/integration-test-app/package.json
  yarn.lock
Labels: Request Backport to 0.64, Request Backport to 0.65, security

#7909 Expect ChainValidationResult vector as r-value
  change/react-native-windows-07754594-cf2d-410b-86f2-c3d5dc403abb.json
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: AutoMerge

#7901 Check for missing dependencies during lint
  change/@react-native-windows-cli-304d106c-687a-4435-bf0e-cf7addb881c9.json
  change/@rnw-bots-coordinator-1895d53d-fe3c-4fd2-9576-657485164a52.json
  change/@rnw-scripts-doxysaurus-5e925906-1c02-4334-bf46-7146fd44019d.json
  change/@rnw-scripts-eslint-config-537160da-a842-4844-b538-0a5755e7e1ff.json
  change/@rnw-scripts-jest-unittest-config-a18467fd-d221-462c-8579-910eb57bba75.json
  change/@rnw-scripts-just-task-265b9cd6-a3b6-4499-a634-453069b67c08.json
  change/jest-environment-winappdriver-8a3cce7a-2858-44c8-976e-7aaa34b20499.json
  change/react-native-platform-override-94ae408c-ef9b-4258-9d08-044e664ff6b6.json
  change/react-native-windows-1637f2f8-8fa9-4107-aea6-b4cbfe9eb280.json
  change/react-native-windows-init-93db042d-176a-4c2a-9d4c-b27c80cbdc8e.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@react-native-windows/cli/depcheck.config.js
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/cli/src/healthChecks.ts
  packages/@react-native-windows/tester/package.json
  packages/@rnw-bots/coordinator/package.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/eslint-config/package.json
  packages/@rnw-scripts/just-task/just-task.js
  packages/@rnw-scripts/just-task/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/jest-environment-winappdriver/package.json
  packages/playground/package.json
  packages/react-native-platform-override/depcheck.config.js
  packages/react-native-platform-override/package.json
  packages/react-native-windows-init/depcheck.config.js
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: Area: Build Infrastructure, Area: Test Infrastructure, AutoMerge

#7908 Fix GitHub Release Generation for Previews
  change/@rnw-scripts-create-github-releases-fd7dd57a-2910-4fdf-9e9f-a2e271f970eb.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
Labels: AutoMerge

#7918 [0.63] 3 Hacks to fix breaking changes from nuget affecting 0.63 pipelines
  .ado/variables/vs2019.yml
  .ado/windows-vs-pr.yml
  Directory.Build.rsp
  change/react-native-windows-2021-06-01-21-05-37-main.json
  vnext/PropertySheets/Autolink.props
Labels: Area: Build Infrastructure, Request Backport to 0.63

#7869 [0.63] Fix JSValue memory leak in move constructor (#7859)
  change/react-native-windows-01974fdb-aa04-49a7-ad88-8715629563e1.json
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/AutolinkedNativeModules.g.props
  packages/microsoft-reactnative-sampleapps/windows/SampleAppCS/AutolinkedNativeModules.g.props
  vnext/Microsoft.ReactNative.Cxx/JSValue.cpp
Labels: AutoMerge

#7898 [0.63] Allow propagating WinRTWebSocketResource constructor exceptions
  change/react-native-windows-2021-05-29-18-05-51-ws-handlebaduri-63.json
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Desktop/Modules/WebSocketModule.cpp
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: AutoMerge

#7857 Integrate May 5th RN nightly build.
  change/@office-iss-react-native-win32-6b850bbd-5c81-40ce-a3b4-20f32276c90b.json
  change/node-rnw-rpc-10a3fe50-78b8-4037-816c-42ce19f83d10.json
  change/react-native-windows-3c3b20fa-49ce-4ac3-b6bf-57465d751424.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/index.win32.js
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/Accessibility/AccessibilityExample.js
  packages/@react-native/tester/js/examples/Modal/ModalCustomizable.js
  packages/@react-native/tester/js/examples/Snapshot/SnapshotViewIOS.ios.js
  packages/@react-native/tester/overrides.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/integration-test-app/tests/MountComponentTests.tsx
  packages/node-rnw-rpc/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/.flowconfig
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/mapbuffer/MapBufferBuilder.cpp
  vnext/codegen/react/components/rnwcore/Props.cpp
  vnext/codegen/react/components/rnwcore/Props.h
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/View/ViewAccessibility.windows.js
  vnext/src/Libraries/DeprecatedPropTypes/DeprecatedViewAccessibility.windows.js
  vnext/src/index.windows.js
  yarn.lock
Labels: AutoMerge

#7925 Update V8 package version
  change/react-native-windows-ef095eea-3e90-4fd2-8645-9930173d8334.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/V8JSIRuntimeHolder.cpp
Labels: AutoMerge

#7927 [0.64] Do not mark instance as IsProfiling when using fastrefresh
  change/react-native-windows-fbd04605-ccd9-4478-80a6-f7040fa55702.json
  vnext/Shared/DevSupportManager.cpp
  vnext/Shared/DevSupportManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/tracing/tracing.cpp
Labels: AutoMerge

#7926 [0.65] Do not mark instance as IsProfiling when using fastrefresh
  change/react-native-windows-fbd04605-ccd9-4478-80a6-f7040fa55702.json
  vnext/Shared/DevSupportManager.cpp
  vnext/Shared/DevSupportManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/tracing/tracing.cpp
  vnext/Shared/tracing/tracing.h
Labels: AutoMerge

#7941 Remove Bad Task in Playground Pipeline
  .ado/jobs/playground.yml
Labels: Area: Build Infrastructure

#7940 [0.64] Update resolutions to pass Component Governance
  package.json
  packages/IntegrationTest/package.json
  yarn.lock
Labels: AutoMerge, security

#7943 Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer
  change/react-native-windows-9566a736-184e-4f8f-bb18-95eefbad34a3.json
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
Labels: Area: JSI, AutoMerge, Request Backport to 0.63, Request Backport to 0.64, Request Backport to 0.65

#7944 Run WACK validation in PR
  .ado/jobs/playground.yml
Labels: Area: Build Infrastructure, Area: Tests, AutoMerge

#7930 [0.63] [Win32] Use text instead of images for LogBox arrows
  change/@office-iss-react-native-win32-2021-06-02-16-38-58-logboximg63win32.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorHeader.win32.js
Labels: Platform: NetUI, Request Backport to 0.63

#7946 [0.65] Upgrade to winmd2md 0.1.13
  .ado/templates/build-rnw.yml
Labels: AutoMerge

#7947 Upgrade to winmd2md 0.1.13
  .ado/templates/build-rnw.yml
Labels: AutoMerge

#7931 [0.64] [Win32] Use text instead of images for LogBox arrows
  change/@office-iss-react-native-win32-13768581-8dbc-4e34-9588-68a6e59599ec.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorHeader.win32.js
Labels: Platform: NetUI, Request Backport to 0.64

#7942 [0.63] V8 package update
  change/react-native-windows-2021-06-03-16-51-38-0.63-stable.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/V8JSIRuntimeHolder.cpp
Labels: AutoMerge

#7933 [Win32] Use text instead of images for LogBox arrows
  change/@office-iss-react-native-win32-0ada2090-15bd-444f-a739-848b783a0cde.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorHeader.win32.js
Labels: Platform: NetUI

#7958 [0.63] Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer
  change/react-native-windows-2021-06-04-13-24-10-fg-mmap-63.json
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
Labels: AutoMerge

#7957 [0.64] Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer
  change/react-native-windows-749550b6-6f9d-4baa-a66d-1bd43d055421.json
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
Labels: AutoMerge

#7949 Emit `onSubmitEditing` before clearing text
  change/react-native-windows-2021-06-04-11-17-50-textInputEventOrder.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: AutoMerge

#7956 [0.65] Add JSI.MemoryMappedScriptStore runtime option to control usage of MemoryMappedBuffer
  change/react-native-windows-b7cfbe58-72d2-4c5f-9a33-bf6e94ba0e1d.json
  vnext/Desktop.UnitTests/ScriptStoreTests.cpp
  vnext/Shared/BaseScriptStoreImpl.cpp
Labels: AutoMerge

#7961 [0.65] V8 Package Update
  change/react-native-windows-2021-06-04-13-48-46-0.65-stable.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/V8JSIRuntimeHolder.cpp
Labels: AutoMerge

#7965 CG: Add resolution for glob-parent@^5.1.2
  package.json
  yarn.lock
Labels: Request Backport to 0.64, Request Backport to 0.65, security

#7911 [0.65] Require Triage Starting 6/4
  .github/CODEOWNERS
Labels: AutoMerge

#7966 [0.65] CG: Add resolution for glob-parent@^5.1.2
  package.json
  yarn.lock
Labels: security

#7967 [0.64] CG: Add resolution for glob-parent@^5.1.2
  package.json
  yarn.lock
Labels: security

#7960 [0.64] V8 Package Update
  change/react-native-windows-99fbdd24-e0f4-4e20-8475-ec69a95664e8.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#7978 Fix activation of xaml islands app in 18362
  packages/playground/windows/playground-win32/Application.manifest
Labels: AutoMerge

#7986 Re-enable Cpp UnitTests using GoogleTestAdapter
  .ado/jobs/desktop.yml
  .ado/jobs/universal.yml
  .ado/templates/discover-google-test-adapter.yml
  .ado/variables/vs2019.yml
  change/react-native-windows-a2012f47-540f-47ef-ac49-b4d8666dbc86.json
Labels: AutoMerge

#8018 Better reporting of failures to load the bundle file
  change/react-native-windows-846102b7-d6a2-4c67-a0d1-a9f6cb4daee3.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#8017 Ensure VsTest will fail when it can't find any tests...
  .ado/jobs/desktop.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#8009 [0.64] Update ejs to pass CG
  package.json
  yarn.lock
Labels: AutoMerge, Request Backport to 0.64, security

#8023 Fix playground-win32 delay-loading Hermes
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
Labels: AutoMerge

#8007 Further ws updates to pass CG
  package.json
  packages/@react-native/tester/package.json
  yarn.lock
Labels: AutoMerge, security

#8008 [0.65] Further ws updates to pass CG
  package.json
  packages/@react-native/tester/package.json
  yarn.lock
Labels: AutoMerge, Request Backport to 0.65, security

#7932 [0.65] [Win32] Use text instead of images for LogBox arrows
  change/@office-iss-react-native-win32-b7532046-a50a-4df5-9278-c471f9ad6216.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/LogBox/UI/LogBoxInspectorHeader.win32.js
Labels: Platform: NetUI

#8026 Intermittent deadlock when reloading multiple times rapidly
  change/react-native-windows-8d2272f9-2d73-4871-a7f4-ced1c2c6f30b.json
  vnext/Shared/Threading/BatchingQueueThread.cpp
  vnext/Shared/Threading/BatchingQueueThread.h
Labels: Request Backport to 0.65

#8038 Disable arm64 unit test on desktop builds in CI
  .ado/jobs/desktop.yml
Labels: AutoMerge

#8029 [0.64] Further ws updates to pass CG
  package.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/package.json
  yarn.lock
Labels: AutoMerge, Request Backport to 0.64, security

#8035 TurboModules might be kept alive by RNH when instance is shutdown
  change/react-native-windows-b0a5a498-4f12-447c-97cd-82b3d28ccb4e.json
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.h
  packages/playground/windows/playground/MainPage.xaml
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
Labels: AutoMerge, Request Backport to 0.65

#8042 Fix crash when adding a ReactRootView while reloading a ReactHost
  change/react-native-windows-1d2d0396-a5d9-4b9c-8e80-2625d8eae80c.json
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-Win32.rc
  packages/playground/windows/playground-win32/resource.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.h
Labels: Area: Islands, Request Backport to 0.65

#8034 Avoid crash when unsupported facade is given - `react-native-paper` button fix
  change/react-native-windows-cb6f7ebc-0410-4d3e-9840-b160e5f8f554.json
  vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h
  vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/StyleAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/TransformAnimatedNode.cpp
Labels: Area: Animation

#8049 [0.65] Cherry pick various high impact fixes
  change/react-native-windows-1d2d0396-a5d9-4b9c-8e80-2625d8eae80c.json
  change/react-native-windows-503903d7-2bfe-4626-9861-291a470f0ec5.json
  change/react-native-windows-802e1a1f-0feb-43da-ac1c-e81018aa3e62.json
  change/react-native-windows-846102b7-d6a2-4c67-a0d1-a9f6cb4daee3.json
  change/react-native-windows-8d2272f9-2d73-4871-a7f4-ced1c2c6f30b.json
  change/react-native-windows-b0a5a498-4f12-447c-97cd-82b3d28ccb4e.json
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-Win32.rc
  packages/playground/windows/playground-win32/resource.h
  packages/playground/windows/playground/MainPage.cpp
  packages/playground/windows/playground/MainPage.h
  packages/playground/windows/playground/MainPage.xaml
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/ReactApplication.h
  vnext/Microsoft.ReactNative/ReactApplication.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Threading/BatchingQueueThread.cpp
  vnext/Shared/Threading/BatchingQueueThread.h
Labels: Request Backport to 0.65

#8050 [0.63] V8 package update
  change/react-native-windows-2021-06-16-18-11-51-0.63-stable.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge, Request Backport to 0.63

#8056 [0.65] Fix msbuild as more cases of *Undefined* are popping up
  change/react-native-windows-a8adb9da-d192-4a5a-a3f4-a68e4d8bc8e3.json
  vnext/Directory.Build.props
Labels: Request Backport to 0.65

#8057 [0.64] Fix msbuild as more cases of *Undefined* are popping up
  change/react-native-windows-c45458c5-46d6-4759-a42d-9c38edb2c0da.json
  vnext/Directory.Build.props
Labels: Request Backport to 0.64

#8059 [0.63] Fix msbuild as more cases of *Undefined* are popping up
  change/react-native-windows-e515567c-07b2-4a7f-ba29-966aa5512168.json
  vnext/Directory.Build.props
Labels: AutoMerge, Request Backport to 0.63

#8053 Autolink best effort
  change/@react-native-windows-cli-bb7e2de4-5a44-4dc8-9eda-d4528ae003da.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: Area: Autolinking, Area: Native Modules, AutoMerge

#8061 Reorder RNTester multicolumn example to be inside the group of flatlist examples
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
Labels: AutoMerge

#8062 make playground win32 use comctl v6
  packages/playground/windows/playground-win32/Application.manifest
Labels: AutoMerge

#8065 Update universal.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#8046 [0.63] Fix XAML Visibility for `display:none`
  change/react-native-windows-af57ea20-4d70-48cb-99f9-559acce12fa6.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Backport to 0.63 Approved

#8044 [0.64] Fix XAML Visibility for `display:none`
  change/react-native-windows-c609b529-2e4e-4b5a-8b30-1d3567f739f6.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Backport to 0.64 Approved

#8068 Have script store return nullptr on facebook::jsi::JSINativeException
  change/react-native-windows-63ea3a71-e181-4a1e-a183-141818f55403.json
  vnext/Shared/BaseScriptStoreImpl.cpp
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64, Request Backport to 0.65

#8071 Tie visitAllPages Test to RNTesterList
  packages/e2e-test-app/jest-resolver.js
  packages/e2e-test-app/jest.config.js
  packages/e2e-test-app/jest.setup.js
  packages/e2e-test-app/package.json
  packages/e2e-test-app/test/framework/Navigation.ts
  packages/e2e-test-app/test/visitAllPages.test.ts
Labels: Area: Test Infrastructure

#8084 Fix CI Testing one more time...
  .ado/jobs/desktop.yml
Labels: AutoMerge

#8089 Fix publish for Reunion
  .ado/publish.yml
  change/jest-environment-winappdriver-5494a7a8-d87b-443b-b3ec-4f6da8751e5a.json
  change/node-rnw-rpc-440ea60e-b70d-45a8-a582-ffca5545b622.json
  change/react-native-windows-59917df8-86a0-4d7b-904b-b8a138b7d92d.json
  change/react-native-windows-ddd0873a-3e92-4489-8bf4-d6e41276bfd4.json
  packages/@react-native-windows/tester/CHANGELOG.json
  packages/@react-native-windows/tester/CHANGELOG.md
  packages/@react-native-windows/tester/package.json
  packages/e2e-test-app/CHANGELOG.json
  packages/e2e-test-app/CHANGELOG.md
  packages/e2e-test-app/package.json
  packages/integration-test-app/CHANGELOG.json
  packages/integration-test-app/CHANGELOG.md
  packages/integration-test-app/package.json
  packages/jest-environment-winappdriver/CHANGELOG.json
  packages/jest-environment-winappdriver/CHANGELOG.md
  packages/jest-environment-winappdriver/package.json
  packages/node-rnw-rpc/CHANGELOG.json
  packages/node-rnw-rpc/CHANGELOG.md
  packages/node-rnw-rpc/package.json
  packages/playground/CHANGELOG.json
  packages/playground/CHANGELOG.md
  packages/playground/package.json
  packages/sample-apps/CHANGELOG.json
  packages/sample-apps/CHANGELOG.md
  packages/sample-apps/package.json
  vnext/CHANGELOG.json
  vnext/CHANGELOG.md
  vnext/package.json
Labels: AutoMerge

#8090 V8 Package Version Update
  change/react-native-windows-a48eb1a2-d8f1-4896-9025-0d370d9ded5f.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#8028 Remove rule that CG must pass for code signing
  .ado/publish.yml
  .ado/templates/component-governance.yml
Labels: Request Backport to 0.64, Request Backport to 0.65

#7982 Normalize paths provided by react-native.config.js
  change/@react-native-windows-cli-35e87e87-c745-44ad-8f4c-2b38f9b46108.json
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/config/projectConfig.ts
Labels: AutoMerge

#8096 [0.64] Remove rule that CG must pass for code signing
  .ado/publish.yml
  .ado/templates/component-governance.yml
Labels: AutoMerge

#8097 [0.65] Remove rule that CG must pass for code signing
  .ado/publish.yml
  .ado/templates/component-governance.yml
Labels: AutoMerge

#8099 Detect whether a project file is a dynamic library
  change/@react-native-windows-cli-d720ea1c-57b4-4909-9483-55a540f9e192.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
  packages/@react-native-windows/cli/src/e2etest/__snapshots__/dependencyConfig.test.ts.snap
  packages/@react-native-windows/cli/src/e2etest/dependencyConfig.test.ts
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCSharpApp/react-native.config.js
  packages/@react-native-windows/cli/src/e2etest/projects/SimpleCppApp/react-native.config.js
Labels: Area: Autolinking, Area: Native Modules

#8100 Allow native module to set JS-side QuirkSettings
  change/@office-iss-react-native-win32-5e79c3d4-72cf-454b-b113-878d1f3d5c66.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/CachingNativeQuirkSettings.js
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/NativeQuirkSettings.js
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/QuirkSettings.js
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/Quirks.js
Labels: Platform: NetUI

#7991 Deduplicate lockfile
  change/@react-native-windows-telemetry-1c876c23-73f0-4104-9f34-5a7301d31e1c.json
  packages/@react-native-windows/telemetry/src/test/sanitize.test.ts
  yarn.lock
Labels: AutoMerge

#8127 [0.63] Use V8 by default in desktop (if enabled)
  change/react-native-windows-2021-06-28-15-49-47-0.63-stable.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#8130 Security: update normalize-url to 4.5.1
  package.json
  yarn.lock
Labels: security

#8117 [0.65] Allow native module to set JS-side QuirkSettings (#8100)
  change/@office-iss-react-native-win32-5e79c3d4-72cf-454b-b113-878d1f3d5c66.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/CachingNativeQuirkSettings.js
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/NativeQuirkSettings.js
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/QuirkSettings.js
  packages/@office-iss/react-native-win32/src/Libraries/QuirkSettings/Quirks.js
Labels: Platform: NetUI

#8118 [0.64] Allow native module to set JS-side QuirkSettings (#8100)
  change/@office-iss-react-native-win32-5e79c3d4-72cf-454b-b113-878d1f3d5c66.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/QuirkSettings/CachingNativeQuirkSettings.js
  packages/react-native-win32/src/Libraries/QuirkSettings/NativeQuirkSettings.js
  packages/react-native-win32/src/Libraries/QuirkSettings/QuirkSettings.js
  packages/react-native-win32/src/Libraries/QuirkSettings/Quirks.js
Labels: Platform: NetUI

#8125 Bump rex-win32 to latest
  change/@office-iss-react-native-win32-c8620725-c50c-4b3b-9033-09bfcdc6607b.json
  packages/@office-iss/react-native-win32/package.json
Labels: AutoMerge, Platform: NetUI

#8119 [0.63] Allow native module to set JS-side QuirkSettings (#8100)
  change/@office-iss-react-native-win32-5e79c3d4-72cf-454b-b113-878d1f3d5c66.json
  packages/react-native-win32/overrides.json
  packages/react-native-win32/src/Libraries/QuirkSettings/CachingNativeQuirkSettings.js
  packages/react-native-win32/src/Libraries/QuirkSettings/NativeQuirkSettings.js
  packages/react-native-win32/src/Libraries/QuirkSettings/QuirkSettings.js
  packages/react-native-win32/src/Libraries/QuirkSettings/Quirks.js
Labels: AutoMerge, Platform: NetUI

#8139 Replace npm-registry with npm-registry-fetch
  change/react-native-windows-init-27955fd7-c4ea-43e5-8404-408071742112.json
  packages/react-native-windows-init/package.json
  packages/react-native-windows-init/src/Cli.ts
  yarn.lock
Labels: security
