Repository microsoft/react-native-windows, pull requests merged in 2021-09, with the labels that each got.

#8515 Rename `node-rnw-rpc` to `@react-native-windows/automation-channel`
  .gitignore
  change/@react-native-windows-automation-channel-525a4103-5a05-40bc-91a5-49f53f75727c.json
  change/jest-environment-winappdriver-6975ecb3-44a8-41c7-923d-4a8960cbe67f.json
  packages/@react-native-windows/automation-channel/.eslintrc.js
  packages/@react-native-windows/automation-channel/.gitignore
  packages/@react-native-windows/automation-channel/README.md
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/automation-channel/src/automationChannel.ts
  packages/@react-native-windows/automation-channel/tsconfig.json
  packages/@react-native-windows/automation-channel/windows/.gitignore
  packages/@react-native-windows/automation-channel/windows/AutomationChannel.sln
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.def
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.filters
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/CommandHandler.cpp
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/CommandHandler.h
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/CommandHandler.idl
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/CppWinrtLessExceptions.h
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/JsonRpcRequestProcessor.cpp
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/JsonRpcRequestProcessor.h
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/PropertySheet.props
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/ReactPackageProvider.cpp
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/ReactPackageProvider.h
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/ReactPackageProvider.idl
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/Server.cpp
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/Server.h
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/Server.idl
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.config
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/pch.cpp
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/pch.h
  packages/e2e-test-app/.eslintrc.js
  packages/e2e-test-app/jest.config.js
  packages/e2e-test-app/package.json
  packages/e2e-test-app/test/framework/TreeDump.ts
  packages/e2e-test-app/windows/ReactUWPTestApp.sln
  packages/e2e-test-app/windows/ReactUWPTestApp/AutolinkedNativeModules.g.cs
  packages/e2e-test-app/windows/ReactUWPTestApp/AutolinkedNativeModules.g.targets
  packages/e2e-test-app/windows/ReactUWPTestApp/MainPage.xaml.cs
  packages/integration-test-app/package.json
  packages/integration-test-app/runner/lib/IntegrationTestClient.ts
  packages/integration-test-app/windows/integrationtest.sln
  packages/integration-test-app/windows/integrationtest/AutolinkedNativeModules.g.cpp
  packages/integration-test-app/windows/integrationtest/AutolinkedNativeModules.g.targets
  packages/integration-test-app/windows/integrationtest/TestHostHarness.cpp
  packages/integration-test-app/windows/integrationtest/TestHostHarness.h
  packages/jest-environment-winappdriver/package.json
  packages/jest-environment-winappdriver/src/WinAppDriverEnvironment.ts
  packages/node-rnw-rpc/CHANGELOG.json
  packages/node-rnw-rpc/CHANGELOG.md
  packages/node-rnw-rpc/windows/NodeRpc/Handler.h
  packages/node-rnw-rpc/windows/NodeRpc/Handler.idl
Labels: AutoMerge

#8541 Fix logic to avoid launching packager
  change/@react-native-windows-cli-dc9b1092-11ab-4867-8616-1ffbef340913.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
Labels: AutoMerge

#8532 Allow Building in Visual Studio 2022
  change/react-native-windows-bbbb4380-bccd-4f8f-855f-610bd443358c.json
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.ABITests/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/packages.config
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/packages.config
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/ReactCommon.UnitTests/packages.config
Labels: AutoMerge

#8526 Fire onMouseEnter/Leave events on pointer concluded
  change/react-native-windows-63c7eafa-0398-42ec-a2db-6dc37804f31a.json
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Labels: AutoMerge

#8501 Provide ability to specify name for the runtime instance when debugging
  change/react-native-windows-7787fb2d-a0b7-496b-8f86-214d17efdc1f.json
  vnext/Chakra/ChakraInstanceArgs.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/DevSettings.h
  vnext/Shared/HermesRuntimeHolder.cpp
Labels: AutoMerge

#8540 ReactUwpTestApp -> RNTesterApp
  .ado/jobs/e2e-test.yml
  .ado/scripts/ReactUWPTestApp.reg
  .ado/templates/setup-certificate.yml
  change/jest-environment-winappdriver-5d33e3fd-3415-43dc-90a8-e27ef375c6c6.json
  docs/e2e-testing.md
  docs/img/e2e-crashdumps.png
  docs/img/e2e-syms.png
  packages/e2e-test-app/.gitignore
  packages/e2e-test-app/app.json
  packages/e2e-test-app/jest.config.js
  packages/e2e-test-app/windows/RNTesterApp/.gitignore
  packages/e2e-test-app/windows/RNTesterApp/App.xaml
  packages/e2e-test-app/windows/RNTesterApp/App.xaml.cs
  packages/e2e-test-app/windows/RNTesterApp/Assets/LockScreenLogo.scale-200.png
  packages/e2e-test-app/windows/RNTesterApp/Assets/SplashScreen.scale-200.png
  packages/e2e-test-app/windows/RNTesterApp/Assets/Square150x150Logo.scale-200.png
  packages/e2e-test-app/windows/RNTesterApp/Assets/Square44x44Logo.scale-200.png
  packages/e2e-test-app/windows/RNTesterApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  packages/e2e-test-app/windows/RNTesterApp/Assets/StoreLogo.png
  packages/e2e-test-app/windows/RNTesterApp/Assets/Wide310x150Logo.scale-200.png
  packages/e2e-test-app/windows/RNTesterApp/AutolinkedNativeModules.g.cs
  packages/e2e-test-app/windows/RNTesterApp/AutolinkedNativeModules.g.props
  packages/e2e-test-app/windows/RNTesterApp/AutolinkedNativeModules.g.targets
  packages/e2e-test-app/windows/RNTesterApp/MainPage.xaml
  packages/e2e-test-app/windows/RNTesterApp/MainPage.xaml.cs
  packages/e2e-test-app/windows/RNTesterApp/Package.appxmanifest
  packages/e2e-test-app/windows/RNTesterApp/Properties/AssemblyInfo.cs
  packages/e2e-test-app/windows/RNTesterApp/Properties/Default.rd.xml
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/ReactPackageProvider.cs
  packages/e2e-test-app/windows/ReactUWPTestApp.sln
Labels: AutoMerge

#8566 [0.65] Fix race condition when building customer projects
  change/react-native-windows-3a67ace6-bef6-4d76-b8a7-36d5c51604db.json
  vnext/Folly/Folly.vcxproj
Labels: AutoMerge, Request Backport to 0.65

#8567 [0.66] Fix race condition when building customer projects
  change/react-native-windows-dc161fbd-a211-4a9a-9fae-a6e9428ee13b.json
  vnext/Folly/Folly.vcxproj
Labels: AutoMerge, Request Backport to 0.66

#8565 Typecheck Playground Samples
  packages/playground/Samples/accessible.tsx
  packages/playground/Samples/rntester.tsx
  packages/playground/Samples/ticTacToe.tsx
  packages/playground/just-task.js
  packages/playground/tsconfig.json
Labels: AutoMerge, Area: Test Infrastructure, Area: Build Infrastructure

#8564 Create change files against main branch when cutting preview
  change/@rnw-scripts-promote-release-b733b042-b3f6-4301-b418-3bdeeff9d7f1.json
  packages/@rnw-scripts/promote-release/src/promoteRelease.ts
Labels: AutoMerge

#8563 Stop Tagging 0.63 Builds
  change/react-native-windows-288a5f41-0865-467a-83c0-2e53f5f0ede5.json
  vnext/package.json
Labels: AutoMerge

#8560 Announce when accessibilityState Changes.
  change/react-native-windows-7a05383a-8c03-4a46-a949-0b615e1ff5b5.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Area: Accessibility

#8586 [Fix CI] Restore name of the Encoded Client Key as stored in our KeyVault
  .ado/templates/setup-certificate.yml
Labels: AutoMerge

#8587 Fix autolinking to support solution files using LF instead of CRLF
  change/@react-native-windows-cli-e4154948-d0ed-4b5e-8b9e-07f6541511da.json
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Labels: AutoMerge

#8533 Bump to 0.66-based react-native-tscodegen
  change/@react-native-windows-codegen-82bc5607-bee7-4448-b42d-81eb04bbcb47.json
  packages/@react-native-windows/codegen/package.json
  patches/react-native-tscodegen+0.68.3.patch
  yarn.lock
Labels: AutoMerge

#8574 Expose launch args as high level automation option
  change/@react-native-windows-automation-82f03b0b-cdd1-4c44-b4c4-11eec17ef46b.json
  packages/@react-native-windows/automation/README.md
  packages/@react-native-windows/automation/src/AutomationEnvironment.ts
Labels: AutoMerge

#8594 [0.64] Add Functionality to setAccessibilityFocus Method
  change/react-native-windows-85928af6-903b-4435-b317-7e7fde3dfc54.json
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Labels: Request Backport to 0.64

#8575 Remove Stale changefiles
  change/jest-environment-winappdriver-5d33e3fd-3415-43dc-90a8-e27ef375c6c6.json
  change/jest-environment-winappdriver-6975ecb3-44a8-41c7-923d-4a8960cbe67f.json
  change/node-rnw-rpc-be74ebeb-f50e-4c02-9205-471b71a2124b.json
Labels: AutoMerge

#8589 Fix autolinking to respect WinUI2xVersion or WinUI3Version set in ExperimentalFeatures.props
  change/@react-native-windows-cli-adebc2a0-5e54-4cf7-8f2b-185115c14991.json
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/playground/packages.config
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground/Playground.vcxproj
Labels: AutoMerge, Area: WinUI, Area: Playground, Area: Autolinking

#8625 Health check code doesn't handle paths with spaces
  change/@react-native-windows-cli-351665bb-29ec-4fb8-93fa-fa627d7d4d18.json
  packages/@react-native-windows/cli/src/healthChecks.ts
Labels: AutoMerge, Area: Bundle

#8629 Fixed CLI options defaults
  change/@react-native-windows-cli-6c46e85a-7b25-4067-971c-737433a62ced.json
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/@react-native-windows/cli/src/e2etest/runWindows.test.ts
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: Area: CLI

#8626 Enable publishing NuGet symbol packages
  .ado/publish.yml
  .ado/templates/prep-and-pack-nuget.yml
  .ado/templates/prep-and-pack-single.yml
  change/react-native-windows-4ba0a096-3ae5-48d9-92c2-9ef0966f6f61.json
  vnext/Scripts/PublishNugetPackagesLocally.cmd
Labels: Area: Performance, Area: Developer Experience

#8604 Allow injection of custom UI thread
  change/@office-iss-react-native-win32-4fd27bb9-3004-4b9a-8a87-a52c34939d5a.json
  change/react-native-windows-f40c6052-dede-4f5c-8e57-bb43903e5e6c.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.tsx
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp
  vnext/Microsoft.ReactNative/Modules/AppearanceModule.h
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.h
  vnext/Microsoft.ReactNative/ReactCoreInjection.idl
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/RedBox.h
  vnext/Microsoft.ReactNative/RedBoxHandler.cpp
  vnext/Shared/Threading/MessageDispatchQueue.cpp
  vnext/Shared/Threading/MessageDispatchQueue.h
Labels: AutoMerge

#8635 Restore Fast Refresh Functionality
  change/react-native-windows-9991abee-8b19-4ff1-a209-7478d569bfe2.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: Area: Developer Experience

#8634 Ensures IsHitTestVisible is set on correct view
  change/react-native-windows-c815a24d-e3b1-4071-8f69-3461f31545ed.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Labels: AutoMerge, Area: Borders and Brushes, Area: Pointer

#8636 [0.66] Restore Fast Refresh Functionality
  change/react-native-windows-83a35785-ab50-466c-80bd-5e9937041fe5.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: Request Backport to 0.66, Backport to 0.66 Approved

#8454 Introduces TextVisitor to consolidate text traversal algorithms
  change/react-native-windows-f7be41bd-666d-4885-aa40-4c801dad1528.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Utils/TextTransform.h
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.h
  vnext/Microsoft.ReactNative/Views/Text/TextHighlighterVisitor.cpp
  vnext/Microsoft.ReactNative/Views/Text/TextHighlighterVisitor.h
  vnext/Microsoft.ReactNative/Views/Text/TextParentVisitor.cpp
  vnext/Microsoft.ReactNative/Views/Text/TextParentVisitor.h
  vnext/Microsoft.ReactNative/Views/Text/TextPropertyChangedParentVisitor.cpp
  vnext/Microsoft.ReactNative/Views/Text/TextPropertyChangedParentVisitor.h
  vnext/Microsoft.ReactNative/Views/Text/TextTransformParentVisitor.cpp
  vnext/Microsoft.ReactNative/Views/Text/TextTransformParentVisitor.h
  vnext/Microsoft.ReactNative/Views/Text/TextTransformVisitor.cpp
  vnext/Microsoft.ReactNative/Views/Text/TextTransformVisitor.h
  vnext/Microsoft.ReactNative/Views/Text/TextVisitor.cpp
  vnext/Microsoft.ReactNative/Views/Text/TextVisitor.h
  vnext/Microsoft.ReactNative/Views/Text/TextVisitorScope.h
  vnext/Microsoft.ReactNative/Views/Text/TextVisitors.h
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.h
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: Area: Text

#8617 Migrate NapiJsiRuntime from V8-JSI
  change/react-native-windows-1ec9d3b9-8e14-45d8-a311-d1f74ae3a7fe.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/JsiTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/Shared.vcxitems
Labels: AutoMerge, Area: JSI

#8660 Add REACT_GET_CONSTANTS to turbo module
  change/react-native-windows-e5514276-02c7-4ebb-bece-2744e53be34b.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/TurboModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
Labels: AutoMerge

#8655 Fix Bug in Native Animation Interpolation Clamping
  change/react-native-windows-6e731943-941d-4e37-8582-1a0d32e94184.json
  vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
Labels: Area: Animation

#8674 Disable broken x64 debug build of ComponentTest
  change/react-native-windows-8490e8f1-dbb7-4010-8f94-062a27aa2994.json
  vnext/Microsoft.ReactNative.sln
Labels: AutoMerge

#8667 [0.63] Migrate NapiJsiRuntime from V8-JSI
  change/react-native-windows-2021-09-20-19-03-24-napi-jsrit-63.json
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/JSI/Desktop/JSI.Desktop.vcxproj
  vnext/JSI/Shared/NapiJsiV8RuntimeHolder.cpp
  vnext/JSI/Shared/NapiJsiV8RuntimeHolder.h
  vnext/JSI/Universal/JSI.Universal.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/JsiTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
Labels: AutoMerge

#8688 Bring back Questions list item via config.yml link
  .github/ISSUE_TEMPLATE/config.yml
Labels: AutoMerge

#8687 Integrate RN nightly build Sep 16th.
  change/@office-iss-react-native-win32-cf64718d-f62c-41b1-9c7b-231deb4ce2c4.json
  change/@react-native-windows-automation-channel-4fc98c9e-9b2f-4b98-993e-03d96ac19dc6.json
  change/@react-native-windows-virtualized-list-5b34f388-b005-4495-9a85-a9ed325fd42d.json
  change/react-native-windows-d555b152-a806-4c7e-a0c1-5a9b347b7e2e.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/examples/Border/BorderExample.windows.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/@react-native-windows/virtualized-list/overrides.json
  packages/@react-native-windows/virtualized-list/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/tester/js/examples/Animated/MovingBoxExample.js
  packages/@react-native/tester/js/examples/Border/BorderExample.js
  packages/@react-native/tester/js/examples/FlatList/BaseFlatListExample.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-basic.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-contentInset.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-inverted.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-multiColumn.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-onEndReached.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-onViewableItemsChanged.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-withSeparators.js
  packages/@react-native/tester/js/examples/FlatList/FlatListExampleIndex.js
  packages/@react-native/tester/js/examples/FlatList/FlatListExamples.js
  packages/@react-native/tester/js/utils/RNTesterList.android.js
  packages/@react-native/tester/js/utils/RNTesterList.ios.js
  packages/@react-native/tester/overrides.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/overrides.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#8697 Restore CI Build
  .ado/templates/setup-certificate.yml
Labels: AutoMerge

#8572 Export AutomationElement type
  change/@react-native-windows-automation-0bb4044e-9656-4374-9679-1a1c6e2c6e3f.json
  packages/@react-native-windows/automation/.eslintrc.js
  packages/@react-native-windows/automation/src/index.ts
Labels: Needs: Author Feedback

#8573 Remove RNW peerDep from automation-commands package
  change/@react-native-windows-automation-4cbf9691-3db0-44bc-bffd-efb7b517571e.json
  change/@react-native-windows-automation-channel-db0c97a4-12dc-4aa3-9de2-31c73849512c.json
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/automation/package.json
Labels: AutoMerge

#8571 Make CLI Fail Gracefully on Dep Script Errors
  change/@react-native-windows-cli-e08e7b1e-3a52-43ef-bac5-6952ceecf5ec.json
  packages/@react-native-windows/cli/src/healthChecks.ts
Labels: AutoMerge

#8713 [0.63] Upgrade V8-JSI to 0.63.16
  change/react-native-windows-2021-09-27-19-45-59-v8jsi-0.63.16.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#8730 Check constants in generated turbo module specs
  change/@react-native-windows-codegen-6c4bbd11-6b44-4efd-a05f-f9c8dd4cee28.json
  change/react-native-windows-b42a7122-6b6e-4976-8994-ea45fecb435c.json
  packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
  packages/@react-native-windows/codegen/src/generators/ValidateConstants.ts
  packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
  vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
  vnext/Microsoft.ReactNative/Modules/AppStateModule.h
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp
  vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.h
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.cpp
  vnext/Microsoft.ReactNative/Modules/I18nManagerModule.h
  vnext/codegen/NativeAppStateSpec.g.h
  vnext/codegen/NativeBlobModuleSpec.g.h
  vnext/codegen/NativeDeviceInfoSpec.g.h
  vnext/codegen/NativeDialogManagerAndroidSpec.g.h
  vnext/codegen/NativeI18nManagerSpec.g.h
  vnext/codegen/NativeJSDevSupportSpec.g.h
  vnext/codegen/NativePlatformConstantsAndroidSpec.g.h
  vnext/codegen/NativePlatformConstantsIOSSpec.g.h
  vnext/codegen/NativePlatformConstantsWinSpec.g.h
  vnext/codegen/NativeSampleTurboModuleSpec.g.h
  vnext/codegen/NativeSettingsManagerSpec.g.h
  vnext/codegen/NativeSourceCodeSpec.g.h
  vnext/codegen/NativeStatusBarManagerAndroidSpec.g.h
  vnext/codegen/NativeStatusBarManagerIOSSpec.g.h
  vnext/codegen/NativeToastAndroidSpec.g.h
Labels: AutoMerge

#8731 [0.64] Fix issue using react-native-debugger with react-native-windows
  change/react-native-windows-5d74fe3c-efd2-479b-ab75-810f5f266a11.json
  vnext/Shared/Executors/WebSocketJSExecutor.cpp
  vnext/Shared/Executors/WebSocketJSExecutor.h
Labels: Partner: AppConsult, Backport to 0.63 Approved

#8495 Adds hook for view managers to capture pointer events
  change/react-native-windows-aaade5cd-5bf8-4e76-8a0f-ebf880e356b1.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/IViewManager.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.cpp
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.h
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.idl
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
  vnext/Microsoft.ReactNative/XamlView.h
Labels: AutoMerge, Area: Mouse

#8702 Bump the version of xmldom used by @react-native-windows/cli to 0.7.0.
  change/@react-native-windows-cli-fa19ef9a-896c-4af1-b889-400f32f2bd31.json
  package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/cli/src/config/configUtils.ts
  packages/@react-native-windows/cli/src/e2etest/autolink.test.ts
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
  yarn.lock
Labels: AutoMerge, Request Backport to 0.63, Request Backport to 0.64, Request Backport to 0.65, Request Backport to 0.66

#8735 Upgrade V8 to version 9.5
  change/react-native-windows-aa558e27-c76b-4b78-a3d5-e04cdd114b77.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
Labels: AutoMerge, Area: JSI

#8752 Enforce 0.66 Triage Requirement
  .github/CODEOWNERS
Labels: AutoMerge

#8751 Update @react-native-picker/picker
  packages/@react-native-windows/tester/package.json
  packages/e2e-test-app/package.json
  packages/playground/package.json
  patches/@react-native-picker+picker+1.16.5.patch
  patches/@react-native-picker+picker+2.1.0.patch
  yarn.lock
Labels: AutoMerge

#8738 [0.64] Upgrade V8 to version 9.5
  change/react-native-windows-59521771-6e91-4fab-8b3b-3311d3dae8b7.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
Labels: AutoMerge, Request Backport to 0.64, Area: JSI

#8737 [0.65] Upgrade V8 to version 9.5
  change/react-native-windows-2ef55695-7158-4402-9b1c-3d457cb80f3c.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
Labels: AutoMerge, Area: JSI, Request Backport to 0.65

#8739 [0.63] Upgrade V8 to version 9.5
  change/react-native-windows-2021-09-28-18-59-44-v8-9.5-63.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.ComponentTests/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge, Request Backport to 0.63, Area: JSI
