Repository microsoft/react-native-windows, pull requests merged in 2022-01, with the labels that each got.

#9337 Update when telemetry populates NPM package versions
  change/@react-native-windows-telemetry-90748cb8-547c-4e1c-ba61-57a8df530393.json
  change/react-native-windows-init-0a3d283c-7dc5-4965-9de9-97362a1466ed.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/react-native-windows-init/src/Cli.ts
Labels: Area: CLI

#9174 Add tests to validate `react-native-windows-init` options
  change/react-native-windows-init-069d8151-5f3e-4536-94e2-a4961b53cf40.json
  packages/react-native-windows-init/bin.js
  packages/react-native-windows-init/src/Cli.ts
  packages/react-native-windows-init/src/e2etest/cli.test.ts
Labels: Area: CLI, Area: Tests

#9281 Fixes crash when using `Animated.divide`
  change/react-native-windows-e28e82a4-9e7a-45c8-bb89-3010b55711b4.json
  vnext/Microsoft.ReactNative/Modules/Animated/DivisionAnimatedNode.cpp
Labels: Area: Animation

#9201 Use Window::Current compositor on XAML Islands
  change/react-native-windows-94a433f4-aa44-431d-a5a5-322479b41c9d.json
  vnext/Microsoft.ReactNative/XamlView.cpp
  vnext/Microsoft.ReactNative/XamlView.h
Labels: Area: Animation

#9254 Fixes crash when creating DiffClampAnimatedNode
  change/react-native-windows-332a5dcc-33ef-464e-b057-72cece380c6f.json
  vnext/Microsoft.ReactNative/Modules/Animated/DiffClampAnimatedNode.cpp
Labels: Area: Animation

#9231 Reduce scope of marking YogaNode dirty
  change/react-native-windows-dc6afdfd-5d3f-41ff-8cbc-3ac0ad348203.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/Views/RawTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TextViewManager.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.cpp
  vnext/Microsoft.ReactNative/Views/VirtualTextViewManager.h
Labels: Area: Animation

#9300 Integrate 12/17 Nightly Build
  change/@office-iss-react-native-win32-b1a54c2d-3b05-43f4-8041-fb7e3f47f317.json
  change/@react-native-windows-automation-channel-9e0b604e-6862-4bc0-9d36-dd90ea42aae2.json
  change/@react-native-windows-virtualized-list-d152fec9-5fd2-4e62-864c-a799fedf45c0.json
  change/react-native-windows-45c90ee8-7829-451f-bf9d-3cf3996267b4.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/Image/Image.win32.js
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/virtualized-list/.flowconfig
  packages/@react-native-windows/virtualized-list/overrides.json
  packages/@react-native-windows/virtualized-list/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/Image/ImageExample.js
  packages/@react-native/tester/js/examples/NewArchitecture/NewArchitectureExample.js
  packages/@react-native/tester/js/examples/TextInput/TextInputSharedExamples.js
  packages/@react-native/tester/js/utils/RNTesterList.ios.js
  packages/@react-native/tester/overrides.json
  packages/@react-native/tester/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/.flowconfig
  vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Fabric/FabricUIManagerModule.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Image/Image.windows.js
  vnext/src/babel-plugin-codegen/index.js
  vnext/src/babel-plugin-codegen/package.json
  yarn.lock
Labels: AutoMerge

#9344 Publish codegen spec files into win32 nuget
  change/react-native-windows-13c812ce-c9cc-409b-94eb-467c8a6ddc80.json
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Scripts/Tfs/Layout-MSRN-Headers.ps1
Labels: AutoMerge, Platform: NetUI

#9190 Fixes issue with restarting animations
  change/react-native-windows-1ea926cf-a734-42b3-84e6-d1254a7676f1.json
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.h
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h
  vnext/Microsoft.ReactNative/Modules/Animated/TrackingAnimatedNode.cpp
Labels: Area: Animation

#9385 Remove ADO NuGet feed from config for new projects
  change/@react-native-windows-cli-2ad609f4-0c3c-44d4-8e13-4ecfd456a97b.json
  change/react-native-windows-ee44eaf2-859d-439a-8bc3-589c7b0f4a19.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/template/shared-app/proj/NuGet.Config
Labels: AutoMerge, Area: Build Infrastructure, Request Backport to 0.66, Request Backport to 0.67

#9386 [0.67] Remove ADO NuGet feed from config for new projects
  change/@react-native-windows-cli-2e64e8b9-4efb-4a44-a73d-3964c5bbea3b.json
  change/react-native-windows-43c5ac53-664f-46ea-9e13-4278d5eff38f.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/template/shared-app/proj/NuGet.Config
Labels: AutoMerge, Area: Build Infrastructure

#9401 Ensure `yarn windows` and `Visual Studio` restore `packages.config` projects
  Directory.Build.targets
  change/@react-native-windows-cli-eda6a4d0-c02d-416d-a40a-503d009ed4f9.json
  change/react-native-windows-a1f98f3d-c095-4624-adf5-00f7b94b340e.json
  lage.config.js
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/build.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/e2e-test-app/.gitignore
  packages/e2e-test-app/packages.config
  packages/e2e-test-app/windows/RNTesterApp/packages.config
  vnext/Directory.Build.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.targets
Labels: AutoMerge, Area: Build Infrastructure

#9368 Removes unnecessary conditional from NativeAnimatedNodeManager
  change/react-native-windows-6aef389f-13f4-4dba-ad02-0e7eb18adf64.json
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp
Labels: Area: Animation

#9425 Playground controls disabled on boot
  packages/playground/windows/playground/MainPage.xaml
Labels: AutoMerge

#9421 Fix integration by tag of newer RN Builds
  change/react-native-platform-override-52d0e542-568b-4b4a-b83f-e67962dd6fb6.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
Labels: AutoMerge

#9374 Adds RNW version to template project files
  change/@react-native-windows-cli-778a4223-463e-4205-8a3a-d8258366137e.json
  change/@react-native-windows-telemetry-3d1207cd-9085-41c5-9331-9e2eb4228a7b.json
  change/react-native-windows-771187a6-a81a-4473-87f9-49d02f334c03.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/@react-native-windows/telemetry/src/index.ts
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
  vnext/template/cs-app/proj/MyApp.csproj
  vnext/template/cs-lib/proj/MyLib.csproj
Labels: Area: CLI

#9400 Adds "Editable" Property to TextInput with SecureTextEntry
  change/react-native-windows-553a56e5-0020-49e8-86b4-24a1659ce988.json
  packages/e2e-test-app/test/__snapshots__/LegacyControlStyleTest.test.ts.snap
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: TextInput

#9299 [0.65] Avoid capturing raw this pointer in WebSocket module
  change/react-native-windows-372c5d9f-7593-4229-9832-01e0274d1e85.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/Microsoft.ReactNative/Modules/CreateModules.cpp
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/InspectorPackagerConnection.cpp
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/Modules/WebSocketModule.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: AutoMerge, Request Backport to 0.65

#9297 [0.64] Avoid capturing raw this pointer in WebSocket module
  change/react-native-windows-c1d22fac-977e-4cd0-bc88-6c060ef768b6.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/WebSocketResourcePerformanceTests.cpp
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.cpp
  vnext/Desktop.UnitTests/WebSocketMocks.h
  vnext/Desktop.UnitTests/WebSocketModuleTest.cpp
  vnext/Desktop.UnitTests/WinRTWebSocketResourceUnitTest.cpp
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/Microsoft.ReactNative/Modules/CreateModules.cpp
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/Modules/WebSocketModule.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Shared/WinRTWebSocketResource.h
Labels: Request Backport to 0.64

#9433 Add document for Turbo Module codegen
  change/@react-native-windows-codegen-b38d03b4-1d88-4bdb-bccf-60fd1dce0bee.json
  change/@react-native-windows/fs-a94faf16-47da-4af9-9665-41b8a756267f.json
  packages/@react-native-windows/codegen/Document.md
Labels: AutoMerge

#9396 [0.65] Fix Google Test Adapter detection in CI/PR so unit tests are actually run
  .ado/jobs/desktop.yml
  .ado/jobs/universal.yml
  .ado/templates/discover-google-test-adapter.yml
  .ado/variables/vs2019.yml
Labels: AutoMerge, Area: Tests, Area: Build Infrastructure, Request Backport to 0.65

#9439 CG: Upgrade to node-fetch@^2.6.7
  change/react-native-platform-override-22df1f78-430c-43dc-9a9e-01ff161f59d6.json
  package.json
  packages/react-native-platform-override/package.json
  yarn.lock
Labels: AutoMerge, security
