Repository microsoft/react-native-windows, pull requests merged in 2022-06, with the labels that each got.

#9976 Update NuGet config files to reduce Secure Supply Chain Analysis warnings
  NuGet.Config
  change/react-native-windows-e24cec68-175e-4980-ac12-788e91464627.json
  packages/e2e-test-app/windows/NuGet.Config
  packages/integration-test-app/windows/NuGet.Config
  packages/playground/windows/NuGet.Config
  packages/sample-apps/windows/NuGet.Config
  vnext/NuGet.Config
Labels: AutoMerge, security, Area: Compliance

#10042 [0.68] Resolving CG alerts 6/1/2022
  .ado/templates/component-governance.yml
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10043 [0.67] Resolving CG alerts 6/1/2022
  .ado/templates/component-governance.yml
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10045 [0.66] Resolving CG alerts 6/1/2022
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10048 [0.69] Run more checks against stable branch PRs
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#10047 [0.64] Resolving CG alerts 6/1/2022
  package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10046 [0.65] Resolving CG alerts 6/1/2022
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10050 [0.68] Run more checks against stable branch PRs
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#10051 [0.67] Run more checks against stable branch PRs
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#10052 [0.66] Run more checks against stable branch PRs
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/playground.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#10053 [0.65] Run more checks against stable branch PRs
  .ado/jobs/cli-init.yml
  .ado/jobs/desktop.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/playground.yml
  .ado/jobs/sample-apps.yml
  .ado/jobs/universal.yml
Labels: AutoMerge

#10055 Bump Hermes package version
  change/react-native-windows-afc24edc-bdf4-45c3-8166-f645792f51ca.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/InspectorPackagerConnection.cpp
  vnext/Shared/InspectorPackagerConnection.h
Labels: AutoMerge

#10058 Fix floating point conversions in non en-US locales
  change/react-native-windows-ea378e65-3e8c-4b6e-a90b-d9b4d862ed17.json
  vnext/stubs/double-conversion/double-conversion.h
Labels: AutoMerge

#10065 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: AutoMerge, Documentation

#10061 Bump Hermes package version
  change/react-native-windows-53703444-288b-48c3-aca9-b7c42c5befae.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/InspectorPackagerConnection.cpp
Labels: AutoMerge

#10079 Do not use Blob/FileReader modules in UWP
  change/react-native-windows-d4179584-e159-44b9-b6fe-c1f4c00e8004.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Shared/OInstance.cpp
Labels: Area: Networking

#10094 [0.66] Enable Blob module with runtime option
  change/react-native-windows-a8df45ea-26f4-44f5-9b82-712c9aad497e.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Shared/OInstance.cpp
Labels: Backport: Requested

#10082 Fixed metro config when using `--useDevMode`
  change/react-native-windows-53a5b9fa-249c-4cf1-bf1f-f18b7d6be767.json
  vnext/template/metro.devMode.config.js
Labels: AutoMerge

#10102 BinSkim fixes for Desktop
  .ado/jobs/desktop.yml
  change/react-native-windows-ad1c4154-6c84-4807-a0a1-1f3c29bf4f17.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Directory.Build.props
Labels: AutoMerge, Area: Build Infrastructure

#10103 Fix use of [[maybe_unused]] attribute
  change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
Labels: AutoMerge

#10112 Fix matrix multiplication logic for transforms
  change/react-native-windows-3db31062-b08b-44b3-8158-a73f139c1714.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Area: Animation, Area: View Managers, Area: View Style Props, Backport: Requested

#10127 [0.69] Fix use of [[maybe_unused]] attribute (#10103)
  change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
Labels: AutoMerge

#10126 [0.68] Fix use of [[maybe_unused]] attribute (#10103)
  change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
Labels: AutoMerge

#10125 [0.67] Fix use of [[maybe_unused]] attribute (#10103)
  change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
Labels: AutoMerge

#10124 [0.66] Fix use of [[maybe_unused]] attribute (#10103)
  change/react-native-windows-3914f431-df32-466b-8f29-1f0db9176a75.json
  vnext/Microsoft.ReactNative.Cxx/JSValueWriter.h
Labels: AutoMerge

#10150 [0.67] Fix ExecuteJsi on instance shutdown
  .gitignore
  change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
  vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
Labels: AutoMerge

#10151 [0.68] Fix ExecuteJsi on instance shutdown
  .gitignore
  change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
  vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
Labels: AutoMerge

#10152 [0.69] Fix ExecuteJsi on instance shutdown
  .gitignore
  change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
  vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
Labels: AutoMerge

#10014 Update autolinking to not error if a dependency is misconfigured
  change/@react-native-windows-cli-c9f9301d-177d-4cda-8f4b-165434d5a5dd.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge, Backport: Requested

#10091 [0.69] Enable Blob module with runtime option
  change/react-native-windows-0521218e-04c4-4409-8cb0-62e95a3e74a2.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge, Backport: Requested

#10093 [0.67] Enable Blob module with runtime option
  change/react-native-windows-03c56ba5-1de6-4f15-968b-e1e2afb78063.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge, Backport: Requested

#10160 [0.66] Fix ExecuteJsi on instance shutdown
  .gitignore
  change/react-native-windows-f4c57fc5-105d-4b9b-bae5-77b41456c140.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactPromiseTest.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiApiContext.h
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.cpp
  vnext/Microsoft.ReactNative.Cxx/ReactPromise.h
  vnext/Microsoft.ReactNative.Cxx/TurboModuleProvider.h
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/ExecuteJsiTests.js
Labels: AutoMerge

#10176 [0.67] Stop using /fp:strict to build yoga.cpp
  change/react-native-windows-0eabcbbe-3124-42fe-b30b-356332950c73.json
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/CompactValue.h
  vnext/overrides.json
Labels: Area: Layout, Platform: NetUI

#10179 [0.69] Stop using /fp:strict to build yoga.cpp
  change/react-native-windows-93991d79-32d9-4ddb-b3e1-41652af70870.json
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/yoga/yoga/CompactValue.h
  vnext/overrides.json
Labels: Area: Layout, Platform: NetUI

#10123 Fix UTF8 Bug in vswhere Command
  change/@react-native-windows-cli-3f8700bf-ee14-4a3e-82b6-873d10aa6fc0.json
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: Area: CLI

#10192 Add partial PlatformColor support for Image's tintColor
  change/react-native-windows-ed697687-b653-4c00-a2ea-341bcc4bae8e.json
  packages/playground/Samples/image.tsx
  vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
Labels: Area: Image, Area: PlatformColor

#10187 Enable Blob module in UWP
  change/react-native-windows-9a3751a7-f0ff-4185-92d1-608aa823c32a.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/OInstance.cpp
Labels: Area: Networking

#10199 Centralize getting package identity and fix a bug getting app folder
  change/react-native-windows-f312927e-5f5d-4689-a6d1-6f9281409c06.json
  vnext/Microsoft.ReactNative.Cxx/AppModelHelpers.h
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Shared/Utils.cpp
Labels: AutoMerge

#10209 Fixes issue when alert is not only descendant of PopupRoot
  change/react-native-windows-f2020c58-e8e2-4364-a3a9-619e3cd68c88.json
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
Labels: AutoMerge

#10208 CG: Update Newtonsoft.Json to 13.0.1
  change/react-native-windows-9f3d191c-3b3f-458a-8add-28df22e2531d.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
Labels: AutoMerge, security

#10161 [0.69] Update autolinking to not error if a dependency is misconfigured
  change/@react-native-windows-cli-c9f9301d-177d-4cda-8f4b-165434d5a5dd.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge

#10163 [0.68] Update autolinking to not error if a dependency is misconfigured
  change/@react-native-windows-cli-c9f9301d-177d-4cda-8f4b-165434d5a5dd.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge
