Repository microsoft/react-native-windows, pull requests merged in 2022-03, with the labels that each got.

#9573 Use current version of Metro and Community CLI
  change/react-native-windows-f482fef1-2187-47aa-a3de-aaacc8d961d3.json
  package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#9628 Set ResolveNuGetPackages in external props
  change/react-native-windows-fe9965b7-8e26-4928-b2d8-7453a5738923.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
Labels: Area: Build Infrastructure, PackageReference

#9629 Dependencies script checks for multiple VS installs
  change/react-native-windows-ce41eed2-2de5-43a0-9d29-b100a2d39d30.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: AutoMerge, Area: Developer Experience, Area: Dependencies

#9470 Capture MSBuild properties in telemetry
  .gitignore
  change/@react-native-windows-cli-bfddb2a2-3f9f-4251-932f-84c3a4dd88d2.json
  change/react-native-windows-ce55d8f0-2ae7-4fde-b722-58bec7970aa3.json
  packages/@react-native-windows/cli/powershell/Eval-MsBuildProperties.ps1
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/OutputMSBuildProperties.targets
Labels: Area: Telemetry

#9639 [0.68] Update how RunWindows phases are reported
  change/@react-native-windows-cli-5c176e39-baa5-4bfb-818a-da9b3c8d1720.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
Labels: AutoMerge

#9640 [0.68] Capture MSBuild properties in telemetry
  .gitignore
  change/@react-native-windows-cli-bfddb2a2-3f9f-4251-932f-84c3a4dd88d2.json
  change/react-native-windows-ce55d8f0-2ae7-4fde-b722-58bec7970aa3.json
  packages/@react-native-windows/cli/powershell/Eval-MsBuildProperties.ps1
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/cli/src/runWindows/utils/telemetryHelpers.ts
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/OutputMSBuildProperties.targets
Labels: Area: Telemetry

#9603 Enables right-click by reverting #4878
  change/react-native-windows-800ca5e6-b669-4cb3-a673-19fdf2c3ced0.json
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
  vnext/src/Libraries/Pressability/Pressability.windows.js
Labels: Area: Mouse

#9642 Implement crash management
  change/react-native-windows-202e71fb-d2d3-431c-a1bd-53c82a6e6037.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp
  vnext/Microsoft.ReactNative/ReactHost/CrashManager.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/DevSettings.h
  vnext/Shared/HermesRuntimeHolder.cpp
  vnext/Shared/HermesRuntimeHolder.h
  vnext/Shared/HermesShim.cpp
  vnext/Shared/HermesShim.h
  vnext/Shared/JSI/RuntimeHolder.h
Labels: AutoMerge

#9647 Scope down usage of PackageReference
  Directory.Build.props
  Directory.Build.targets
  change/react-native-windows-60d16274-555b-4c37-aaa3-738a6f44be49.json
  vnext/Directory.Build.props
  vnext/Directory.Build.targets
Labels: AutoMerge, Area: Developer Experience, Area: Build Infrastructure, PackageReference

#9646 [0.68] Implement crash management
  change/react-native-windows-202e71fb-d2d3-431c-a1bd-53c82a6e6037.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/ReactHost/CrashManager.cpp
  vnext/Microsoft.ReactNative/ReactHost/CrashManager.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.cpp
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/DevSettings.h
  vnext/Shared/HermesRuntimeHolder.cpp
  vnext/Shared/HermesRuntimeHolder.h
  vnext/Shared/HermesShim.cpp
  vnext/Shared/HermesShim.h
  vnext/Shared/JSI/RuntimeHolder.h
Labels: AutoMerge

#9631 [0.68] Set ResolveNuGetPackages in external props
  change/react-native-windows-34090dc6-d476-438d-afee-8299ac07d43d.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props
Labels: AutoMerge

#9664 Adjust PackageReferences ProjectCapability evaluation
  Directory.Build.props
  Directory.Build.targets
  change/react-native-windows-47509427-32c9-478b-a02a-b00ba1318391.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/PropertySheets/CppEnablePackageReferences.props
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge, PackageReference

#9670 Update CppAppConsumeCSharpModules.props for VS2022
  change/react-native-windows-5c80c286-c4d1-403d-bbf4-848681cecf12.json
  vnext/PropertySheets/CppAppConsumeCSharpModule.props
Labels: AutoMerge

#9674 Pass platform and configuration to restorePackageConfigs
  change/@react-native-windows-cli-679e9a34-edc1-42e2-ae0e-2946aebd203c.json
  change/react-native-windows-47509427-32c9-478b-a02a-b00ba1318391.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Labels: AutoMerge, Area: Build Infrastructure, PackageReference

#9648 Use Canvas.Top and Left instead of custom DependencyProperties
  change/react-native-windows-1de81d27-2dc7-4a31-914e-572cdf8c1945.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp
  vnext/Microsoft.ReactNative/Views/ViewPanel.cpp
  vnext/Microsoft.ReactNative/Views/ViewPanel.h
Labels: AutoMerge, Area: Performance, Area: Layout

#9677 [0.68] Fix Sample Apps crash when loading the bundle
  packages/sample-apps/windows/SampleAppCPP/App.xaml
  packages/sample-apps/windows/SampleAppCS/App.xaml
Labels: AutoMerge

#9679 [0.67] Fix Sample Apps crash when loading the bundle
  packages/sample-apps/windows/SampleAppCPP/App.xaml
  packages/sample-apps/windows/SampleAppCS/App.xaml
Labels: AutoMerge

#9680 [0.66] Fix Sample Apps crash when loading the bundle
  packages/sample-apps/windows/SampleAppCPP/App.xaml
  packages/sample-apps/windows/SampleAppCS/App.xaml
Labels: AutoMerge

#9683 [0.68] Pass platform and configuration to restorePackageConfigs
  change/@react-native-windows-cli-1379e65b-7117-40ac-883f-a84ade49c7ca.json
  packages/@react-native-windows/cli/src/runWindows/runWindows.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
Labels: AutoMerge

#9686 Safe re-entrancy for EnsureHermesLoaded
  change/react-native-windows-317164cb-1054-481e-9319-53a5d609ce51.json
  vnext/Shared/HermesShim.cpp
Labels: AutoMerge

#9687 [0.68] Safe re-entrancy for EnsureHermesLoaded
  change/react-native-windows-084dc412-a417-4d9e-833a-113946a147ae.json
  vnext/Shared/HermesShim.cpp
Labels: AutoMerge

#9688 [0.67] Safe re-entrancy for EnsureHermesLoaded
  change/react-native-windows-d29a2bab-2467-4365-80e2-a3265a695786.json
  vnext/Shared/HermesShim.cpp
Labels: AutoMerge

#9689 [0.66] Safe re-entrancy for EnsureHermesLoaded
  change/react-native-windows-ab3ebecb-a61b-4e1f-abd4-379c7d6a81c8.json
  vnext/Shared/HermesShim.cpp
Labels: AutoMerge

#9706 Update WebView2 Package Import Following PkgRef Support
  change/react-native-windows-2bf487b3-ad01-47f4-a8ca-d446525207d1.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: Area: Build Infrastructure

#9708 [0.68] Update WebView2 Package Import Following PkgRef Support
  change/react-native-windows-2bf487b3-ad01-47f4-a8ca-d446525207d1.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: Area: Build Infrastructure

#9710 Move some libraries to delayload
  change/react-native-windows-9233768b-4345-43af-8035-08c54dbaa6af.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#9717 [0.68] Port Delayload fixes
  change/react-native-windows-fc114619-d2a7-443e-bd71-404237757294.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#9718 [0.67] Port Delayload fixes
  change/react-native-windows-bdc169c1-d4e0-4cd0-a9f0-a05e51c840ca.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
Labels: AutoMerge

#9728 Enable version checks in IDL files
  change/react-native-windows-75461af6-8aa8-4ca9-8277-9e541ff6ffc3.json
  vnext/PropertySheets/PackageVersionDefinitions.props
Labels: AutoMerge

#9729 [0.68] Enable version checks in IDL files
  change/react-native-windows-2144dfb3-3e5a-460b-9527-f29e451addb4.json
  vnext/PropertySheets/PackageVersionDefinitions.props
Labels: AutoMerge

#9736 [0.68] Guard against crashes due to cancelations and other errors from BitmapSource/SvgImageSource SetSourceAsync
  change/react-native-windows-d82b05f8-153c-45d6-9c66-71225d0144c9.json
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
Labels: AutoMerge

#9756 DevSupportManager crashes in unpackaged apps
  change/react-native-windows-c85f8920-99c5-46dc-94a4-32e2144cb016.json
  vnext/Shared/DevSupportManager.cpp
Labels: AutoMerge

#9749 [0.66] MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early
  change/react-native-windows-8a5e8b21-c7ab-4640-badb-cd9cabcd2ad7.json
  vnext/Mso/dispatchQueue/dispatchQueue.h
Labels: AutoMerge

#9750 [0.67] MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early
  change/react-native-windows-dd2c94b5-db93-43d7-8c63-9f6932774c39.json
  vnext/Mso/dispatchQueue/dispatchQueue.h
Labels: AutoMerge

#9727 Update testing-nuget-packages.md
  docs/testing-nuget-packages.md
Labels: AutoMerge

#9650 Fix publish after promotion to preview
  change/@react-native-windows-automation-719d2126-8602-405f-bf02-083385755440.json
  change/@react-native-windows-cli-f53cd8c4-c555-40b5-85ba-348c95bae135.json
  change/@react-native-windows-codegen-16743fbb-dd13-42e9-a9ec-21b6166179c0.json
  change/@react-native-windows-find-repo-root-7ad6518a-51ff-42f2-881c-e8777e309444.json
  change/@react-native-windows-fs-6dbaaa2a-cc3d-4e82-9a98-232746f0bb3b.json
  change/@react-native-windows-package-utils-83785828-1057-484f-9239-e393a7ac0276.json
  change/@react-native-windows-telemetry-38361f9a-1a50-4264-be1e-8f086bcde18a.json
  change/@rnw-scripts-create-github-releases-ee057c02-6b0e-4d99-9d92-e0817b398a4f.json
  change/@rnw-scripts-doxysaurus-6c1b7e09-b52b-47da-a558-71f2bff17f4d.json
  change/@rnw-scripts-integrate-rn-cbe4d17f-0fde-465e-aa34-0d8bb287b065.json
  change/@rnw-scripts-promote-release-66ccf6a9-41b8-4014-9dd0-4d37e9f41fa8.json
  change/@rnw-scripts-take-screenshot-2561f068-20ab-4d92-b0b2-10edc38c5e07.json
  change/react-native-platform-override-3bdbf3d0-0926-4fec-8dde-4750eef5776f.json
  change/react-native-windows-init-1c63f030-1b4c-4404-86b5-f4451373b601.json
  packages/@react-native-windows/automation/package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/codegen/package.json
  packages/@react-native-windows/find-repo-root/package.json
  packages/@react-native-windows/fs/package.json
  packages/@react-native-windows/package-utils/package.json
  packages/@react-native-windows/telemetry/package.json
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/stamp-version/package.json
  packages/@rnw-scripts/take-screenshot/package.json
  packages/integration-test-app/package.json
  packages/react-native-platform-override/package.json
  packages/react-native-windows-init/package.json
Labels: AutoMerge
