Repository microsoft/react-native-windows, pull requests merged in 2022-02, with the labels that each got.

#9445 UI Manager module is not being destroyed on the UI thread
  change/react-native-windows-8a1ddf14-de89-4434-9dc7-81bb20402521.json
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Labels: Request Backport to 0.66, Request Backport to 0.67

#9427 Allow OutputType `Library` to be autolinked for C# native modules
  change/@react-native-windows-cli-ea061697-b24d-4b3f-adc6-252bb52bd67a.json
  packages/@react-native-windows/cli/src/config/dependencyConfig.ts
Labels: Area: Native Modules, Area: Autolinking

#9442 Fix VS hang when switching Platform within IDE
  change/react-native-windows-98e7ec7d-e4f1-4295-a50e-58d8bab9a679.json
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
  vnext/Directory.Build.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.targets
Labels: Area: Build Infrastructure, Area: Playground

#9449 [0.67] UI Manager module is not being destroyed on the UI thread
  change/react-native-windows-98c19395-026b-4bf1-9a08-1dc416a5a6b2.json
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Labels: AutoMerge

#9450 [0.66] UI Manager module is not being destroyed on the UI thread
  change/react-native-windows-2c7c5197-58c8-4868-b554-c2801540c955.json
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
Labels: AutoMerge

#9367 Use raw value for CalculatedAnimationDriver
  change/react-native-windows-b50197bd-a2bb-423e-a088-a65afa8f7969.json
  vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.cpp
Labels: Area: Animation

#9370 Stop both raw value and offset animation
  change/react-native-windows-0642e501-eb2a-4df5-91d4-ba64dd5b0aaa.json
  vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
Labels: Area: Animation

#9471 [0.66] [NetUI] Add additional exports for react-native-win32.dll
  change/react-native-windows-50d42888-74d9-4ac0-ad8f-60e874390f4b.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
Labels: AutoMerge, Platform: NetUI

#9125 Add OnUnloaded Method to RNW View Managers
  change/react-native-windows-256e05dc-84c5-4236-802b-656492f31486.json
  vnext/Microsoft.ReactNative/ABIViewManager.cpp
  vnext/Microsoft.ReactNative/ABIViewManager.h
  vnext/Microsoft.ReactNative/IViewManager.idl
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
Labels: Area: Native Modules

#9461 Replace __APPLE__ with __clang__ where applicable
  change/react-native-windows-f9d6ddce-6909-439b-b4b7-0e8a541240c4.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: Backport: Request for 0.64, Backport: Request for 0.65, Backport: Request for 0.66, Backport: Request for 0.67

#9481 [0.64] Replace __APPLE__ with __clang__ where applicable
  change/react-native-windows-5af3db60-0ec1-4a05-805e-0b0193498c7a.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: Backport: Request for 0.64

#9480 [0.66] Replace __APPLE__ with __clang__ where applicable (#9461)
  change/react-native-windows-50600557-a3cd-481c-8991-01a803894add.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: Backport: Request for 0.66

#9479 [0.67] Replace __APPLE__ with __clang__ where applicable (#9461)
  change/react-native-windows-5742b31c-adda-4f16-b922-7a4b5e938474.json
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
Labels: Backport: Request for 0.67

#9173 Fixes onMouseEnter/Leave to fire when pointer down
  change/react-native-windows-cd6b59e4-a2d9-492a-b011-e534519b7714.json
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Labels: Breaking Change

#9453 React-native-windows-init reuses existing projectGUIDs by default
  change/@react-native-windows-cli-46d66f80-8f36-4e1f-aa9e-fbb83eda5a5b.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
Labels: Area: CLI, Area: Autolinking

#9498 Fix TurboModule codegen document
  change/@react-native-windows-codegen-fabf9411-e605-4506-8bec-969f10262da4.json
  packages/@react-native-windows/codegen/Document.md
Labels: AutoMerge

#9372 Normalize package reference for WinUI between C# and C++ templates
  change/@react-native-windows-telemetry-df29036f-2f1d-46bf-a917-85a8765ca3fc.json
  change/react-native-windows-a961f49b-f6c1-4f59-8ef2-09a5ebd975c8.json
  packages/@react-native-windows/telemetry/src/test/projects/UsesPackageReference/UsesPackageReference.csproj
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/playground/react-native.config.js
  packages/playground/windows/ExperimentalFeatures.props
  packages/playground/windows/Playground-win32 (Package)/Playground-win32-packaging.proj
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground/Playground.vcxproj
  packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleLibraryCPP/pch.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.SourceReferences.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
  vnext/template/cs-app/proj/MyApp.csproj
Labels: Area: Infrastructure

#9514 Version of hermes used in playground-win32 is incorrect
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
Labels: AutoMerge

#9491 Share monorepo-friendly metro config between dev packages
  change/@office-iss-react-native-win32-d26ccde7-9380-4dd5-9fda-b6eaea59efc4.json
  change/react-native-windows-2c5aeae9-a499-4edc-b091-81e574e6fcee.json
  packages/@office-iss/react-native-win32/metro.config.js
  packages/@office-iss/react-native-win32/package.json
  packages/@rnw-scripts/metro-dev-config/.eslintrc.js
  packages/@rnw-scripts/metro-dev-config/README.md
  packages/@rnw-scripts/metro-dev-config/metro.dev.config.js
  packages/@rnw-scripts/metro-dev-config/package.json
  packages/e2e-test-app/metro.config.js
  packages/e2e-test-app/package.json
  packages/integration-test-app/metro.config.js
  packages/integration-test-app/package.json
  packages/playground/metro.config.js
  packages/playground/package.json
  packages/sample-apps/metro.config.js
  packages/sample-apps/package.json
  vnext/metro.config.js
  vnext/package.json
  vnext/template/metro.devMode.config.js
  yarn.lock
Labels: AutoMerge

#9504 [0.66] [NetUI] Stop exporting data blocks from react-native-win32.dll
  change/react-native-windows-a2ac0b37-db86-4647-8a15-ca57d4b9e08a.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
  vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
  vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
Labels: Platform: NetUI

#9524 Bump Hermes version to 0.11
  change/react-native-windows-aa5ba522-5922-4c4c-8d70-dfdb18b69cca.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  vnext/PropertySheets/JSEngine.props
Labels: AutoMerge, Backport: Request for 0.67, Backport: Request for 0.68

#9526 [0.68] Bump Hermes version to 0.11
  change/react-native-windows-ed74409e-c94a-4998-8f2e-7b0ff6441ca8.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  vnext/PropertySheets/JSEngine.props
Labels: AutoMerge

#9484 Implement IHttpResource
  change/react-native-windows-7bb307e0-b40f-48f0-a356-a43c860eeefb.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop/HttpResource.cpp
  vnext/Desktop/HttpResource.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/IntegrationTests/TestRunner.h
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/CreateModules.h
  vnext/Shared/IHttpResource.h
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Modules/HttpModule.h
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/Utils/WinRTConversions.cpp
  vnext/Shared/Utils/WinRTConversions.h
  vnext/Shared/WinRTHttpResource.cpp
  vnext/Shared/WinRTHttpResource.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
  vnext/src/IntegrationTests/XHRTest.js
Labels: AutoMerge, Area: Networking

#9541 [0.67] CG fixes for node-fetch, shelljs, nanoid
  package.json
  yarn.lock
Labels: AutoMerge, security

#9542 [0.66] CG fixes for node-fetch, shelljs, nanoid
  package.json
  yarn.lock
Labels: AutoMerge, security

#9533 Re-enable WebSocket RNTester integration test
  .ado/jobs/desktop.yml
Labels: AutoMerge, Area: Tests

#9549 [0.67] fix(cli): fix cache not being used when there are no dependencies
  change/@react-native-windows-cli-3aac23ad-e95a-4369-b241-c4fea1afcb7a.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge, Area: Developer Experience, Area: Autolinking

#9548 [0.68] fix(cli): fix cache not being used when there are no dependencies
  change/@react-native-windows-cli-401a1aee-fc62-4128-b881-42b970e6102e.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge, Area: Developer Experience, Area: Autolinking

#9550 [0.66] fix(cli): fix cache not being used when there are no dependencies
  change/@react-native-windows-cli-3aac23ad-e95a-4369-b241-c4fea1afcb7a.json
  packages/@react-native-windows/cli/src/runWindows/utils/autolink.ts
Labels: AutoMerge, Area: Developer Experience, Area: Autolinking

#9544 [0.64] CG fixes for node-fetch, shelljs, and more
  package.json
  yarn.lock
Labels: AutoMerge, security

#9561 Use temporary folder to store V8 JS bytecode
  change/react-native-windows-3ac7d6df-cb97-4b78-beb3-c8224e826f10.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
Labels: AutoMerge

#9562 MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early
  change/react-native-windows-5e2cc7a5-b37d-49cc-b01b-c3669a0686c3.json
  vnext/Mso/dispatchQueue/dispatchQueue.h
Labels: AutoMerge

#9567 Crash when getting Platform.osVersion on Windows 8.1
  change/react-native-windows-25e9c3ca-7257-4815-931b-f339b9e70b3c.json
  vnext/Shared/Modules/PlatformConstantsModule.cpp
Labels: AutoMerge

#9547 Update packages.lock.json
  change/react-native-windows-c1ac328c-89ed-4734-b356-ec1435cef4a7.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
Labels: AutoMerge

#9575 Pr/binskim
  .ado/jobs/desktop.yml
Labels: AutoMerge

#9568 [0.65] CG: Update node-fetch to 2.6.7
  yarn.lock
Labels: AutoMerge

#9587 Make mac compliant
  .ado/jobs/macos-tests.yml
Labels: AutoMerge

#9566 Expose InlineSourceMap property
  change/react-native-windows-d48d7a10-2970-40aa-9ee8-b874def5fff2.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/MsoReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9589 Add wrap-reverse to flex wrap options
  change/react-native-windows-2345d670-7aa7-4de1-91e0-692025d93223.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: AutoMerge

#9591 [0.68] Expose InlineSourceMap property
  change/react-native-windows-d48d7a10-2970-40aa-9ee8-b874def5fff2.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9592 [0.67] Expose InlineSourceMap property
  change/react-native-windows-d48d7a10-2970-40aa-9ee8-b874def5fff2.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactContext.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.h
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/ReactNativeHost.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9588 Add TypeScript turbo module definition as new codegen target
  change/@react-native-windows-codegen-c2c652de-c0b5-4c7e-9655-56a42b7088a1.json
  packages/@react-native-windows/codegen/src/Cli.ts
  packages/@react-native-windows/codegen/src/generators/GenerateTypeScript.ts
Labels: AutoMerge

#9596 [0.66] Crash when getting Platform.osVersion on Windows 8.1
  change/react-native-windows-daade875-fb12-466a-977d-34ee3c6b8f76.json
  vnext/Shared/Modules/PlatformConstantsModule.cpp
Labels: AutoMerge

#9597 [0.67] Crash when getting Platform.osVersion on Windows 8.1
  change/react-native-windows-f76676c9-d827-4411-9408-671efc9dbeac.json
  vnext/Shared/Modules/PlatformConstantsModule.cpp
Labels: AutoMerge

#9593 Fix tag handling for foreign UI elements
  change/react-native-windows-0b30a99b-f579-48be-9dd3-fcbae6d5bd54.json
  vnext/Microsoft.ReactNative/Fabric/ComponentViewRegistry.cpp
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
  vnext/Microsoft.ReactNative/XamlUIService.cpp
  vnext/Microsoft.ReactNative/XamlView.h
Labels: AutoMerge

#9607 Enable credscan
  .ado/jobs/linting.yml
Labels: AutoMerge

#9606 [0.68] Enable TurboModule Promise completion from any thread (#9595)
  change/react-native-windows-d91b29f6-0fd4-4087-bc9e-ad1385fd4673.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/JsiWriter.cpp
  vnext/Microsoft.ReactNative/JsiWriter.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Labels: AutoMerge

#9608 Update packages.lock.json
  change/react-native-windows-ed9e04da-76f8-4c0e-b1d2-d44636407f01.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
Labels: AutoMerge

#9594 Move hardcoded PackageReferences from templates into targets
  change/@react-native-windows-cli-96a7ab29-267b-43ab-887b-c8c89b226442.json
  change/react-native-windows-eb95d834-f0d8-4ba8-bca5-585943544f0d.json
  packages/@react-native-windows/cli/src/e2etest/projectConfig.utils.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/PropertySheets/CppEnablePackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.CSharp.PackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.CSharp.ProjectReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.PackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
  vnext/template/cs-lib/proj/Directory.Build.props
  vnext/template/shared-lib/proj/ExperimentalFeatures.props
Labels: Area: Native Modules, Area: JavaScript Engine, Area: Build Infrastructure

#9605 [0.67] Enable TurboModule Promise completion from any thread (#9595)
  change/react-native-windows-259159fd-d65e-4319-82fe-7b4b570b6104.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/JsiWriter.cpp
  vnext/Microsoft.ReactNative/JsiWriter.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Labels: AutoMerge

#9604 [0.66] Enable TurboModule Promise completion from any thread (#9595)
  change/react-native-windows-b38f3f2f-4014-40fd-8c40-6134c3630c30.json
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/JsiWriter.cpp
  vnext/Microsoft.ReactNative/JsiWriter.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Microsoft.ReactNative/Views/ScrollViewManager.cpp
Labels: AutoMerge

#9612 [0.68] Move hardcoded PackageReferences from templates into targets
  change/@react-native-windows-cli-5ed427bb-43ff-4b44-ac15-1a92df8a90fb.json
  change/react-native-windows-c1a07f90-d4f5-4b2d-ab99-c5997e16d88a.json
  packages/@react-native-windows/cli/src/e2etest/projectConfig.utils.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/PropertySheets/CppEnablePackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.CSharp.PackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.CSharp.ProjectReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.PackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
  vnext/template/cs-lib/proj/Directory.Build.props
  vnext/template/shared-lib/proj/ExperimentalFeatures.props
Labels: AutoMerge, Area: Native Modules, Area: JavaScript Engine, Area: Build Infrastructure

#9611 Add CredScan to release
  .ado/publish.yml
Labels: AutoMerge
