Repository microsoft/react-native-windows, pull requests merged in 2022-08, with the labels that each got.

#10349 Update custom targets in Folly.vcxproj and fmt.vcxproj
  change/react-native-windows-96cc10b8-f540-456c-a1b9-2d1f8ecb536e.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/Folly/cgmanifest.json
  vnext/fmt/cgmanifest.json
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge, Area: Build Infrastructure, Area: Compliance

#10348 Require beachball change files to have a valid comment string
  packages/@rnw-scripts/beachball-config/src/beachball.config.ts
Labels: AutoMerge, Area: Infrastructure

#10351 Add import lib if the app sets the UseRNCoreApp property
  change/react-native-windows-6167fbe2-bc35-447b-a0eb-5b947cc5b538.json
  vnext/Scripts/Microsoft.ReactNative.targets
Labels: AutoMerge

#10365 Fix skew transforms for string values
  change/react-native-windows-7381bba4-15a0-458e-82c9-63951b1129c8.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Area: Animation, Area: View Style Props, Backport: Requested

#10332 Update nuget feed declarations
  NuGet.Config
  change/react-native-windows-018abdbd-de95-40a0-ad82-807c96ba29fa.json
  vnext/Desktop.ABITests/NuGet.Config
  vnext/Desktop.DLL/NuGet.Config
  vnext/Desktop.IntegrationTests/NuGet.Config
  vnext/Desktop.UnitTests/NuGet.Config
  vnext/Desktop/NuGet.Config
  vnext/NuGet.Config
  vnext/ReactCommon.UnitTests/NuGet.Config
Labels: Platform: Desktop, Area: Compliance

#10369 Update Folly to v2021.07.22.0
  change/react-native-windows-2b9efe2b-f4fe-4ba0-aab6-3b25289be552.json
  vnext/Directory.Build.props
  vnext/Folly/cgmanifest.json
Labels: AutoMerge, Area: Dependencies

#10373 Remove incorrect `typename` keyword in helpers.h function template
  change/react-native-windows-8d7cf1e8-5491-4630-bf74-b2e4f942cf70.json
  vnext/Microsoft.ReactNative/Utils/Helpers.h
Labels: AutoMerge

#10386 Update autolinking to update project paths in solution files
  change/@react-native-windows-cli-b5c97a05-d431-433f-86bb-1dffed74144b.json
  packages/@react-native-windows/cli/src/runWindows/utils/vstools.ts
Labels: Area: CLI

#10266 Use programmatic focus for UIManager.focus
  change/react-native-windows-a5041465-ffcd-4b52-b4d1-34cb0370b209.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: Area: Focus

#10355 Fixes various issues with fast text optimization
  change/react-native-windows-80ab1dcb-5a57-4983-be91-37a76beeb23d.json
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Labels: Area: Text

#10275 Fix relative include path for Views/Image
  change/react-native-windows-17c67a31-ebaf-4153-84f6-d830f7910ddb.json
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
Labels: AutoMerge

#10203 Adds gesture cancellation to pointer event handling
  change/react-native-windows-f387ef6b-5fac-48a8-86bf-42e6afbd3744.json
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.cpp
Labels: AutoMerge

#10314 Fix XamlRoot crashes in FlyoutViewManager
  change/react-native-windows-1ec41f70-0685-4d1f-8037-dbb4cfd0d22a.json
  vnext/Microsoft.ReactNative/Views/FlyoutViewManager.cpp
Labels: AutoMerge

#10408 Fix `ReactNotificationService` memory leak in `ExecuteJsi`
  change/react-native-windows-ddcc5f68-cdab-4bae-a2e7-714fdc0de029.json
  vnext/Microsoft.ReactNative.IntegrationTests/ReactNotificationServiceTests.cpp
  vnext/Microsoft.ReactNative/IReactNotificationService.cpp
  vnext/Microsoft.ReactNative/IReactNotificationService.h
Labels: AutoMerge

#10402 Fix Deploy Error for Apps that Contain Spaces in Path
  change/@react-native-windows-cli-512117e3-b225-422d-aac1-f69efa3a70cb.json
  packages/@react-native-windows/cli/src/runWindows/utils/deploy.ts
Labels: Area: CLI

#10318 Fix accessibilityValue & ensure narrator announces changes
  change/react-native-windows-6fe248a3-3b5d-4c70-9268-6bf15953e9e3.json
  packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx
  packages/playground/Samples/accessible.tsx
  vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.cpp
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
  vnext/Microsoft.ReactNative/Views/cppwinrt/DynamicAutomationPeer.idl
Labels: Area: Accessibility

#10341 Make borderRadius consistent with other RN platforms
  change/react-native-windows-efe766b4-6a8c-4b71-b043-7223168cafa4.json
  vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
  vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ControlViewManager.h
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.cpp
  vnext/Microsoft.ReactNative/Views/Image/ImageViewManager.h
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
Labels: Area: Borders and Brushes

#10436 Use LongLivedObjects for TurboModule callbacks
  change/react-native-windows-74efbb30-e443-4b2f-b4d4-482b9fa56fe5.json
  vnext/Microsoft.ReactNative.Cxx/JSI/LongLivedJsiValue.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Shared/InstanceManager.cpp
  vnext/Shared/InstanceManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/OInstance.h
Labels: AutoMerge

#10443 [0.68] Use LongLivedObjects for TurboModule callbacks (#10436)
  change/react-native-windows-74efbb30-e443-4b2f-b4d4-482b9fa56fe5.json
  vnext/Microsoft.ReactNative.Cxx/JSI/LongLivedJsiValue.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Shared/InstanceManager.cpp
  vnext/Shared/InstanceManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/OInstance.h
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge

#10441 [0.70] Use LongLivedObjects for TurboModule callbacks (#10436)
  change/react-native-windows-74efbb30-e443-4b2f-b4d4-482b9fa56fe5.json
  vnext/Microsoft.ReactNative.Cxx/JSI/LongLivedJsiValue.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TestEventService.h
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.js
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
  vnext/Shared/InstanceManager.cpp
  vnext/Shared/InstanceManager.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/OInstance.h
Labels: AutoMerge

#10472 [0.69] Allow batches to complete during load
  change/react-native-windows-cb076a1b-e4cb-40ad-a74d-f7b826107a3d.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Shared/Threading/BatchingQueueThread.cpp
Labels: AutoMerge

#10474 Add `$schema` to `cgmanifest.json`
  change/react-native-windows-fa7f3afb-6f45-432e-a939-5cfcc6c0dd51.json
  vnext/Folly/cgmanifest.json
Labels: AutoMerge

#9658 Move react tag to an attached property
  change/react-native-windows-e49f3f73-84f5-46de-b33b-75f711679a1e.json
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
  vnext/Microsoft.ReactNative/XamlUIService.cpp
  vnext/Microsoft.ReactNative/XamlUIService.h
  vnext/Microsoft.ReactNative/XamlUIService.idl
  vnext/Microsoft.ReactNative/XamlView.cpp
  vnext/Microsoft.ReactNative/XamlView.h
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.props
  vnext/PropertySheets/NewAPIDeclarations.props
Labels: Breaking Change

#10468 Add pre/post build compliance templates and address PoliCheck issues
  .ado/compliance.yml
  .ado/config/PoliCheckRules.mdb
  .ado/jobs/linting.yml
  .ado/publish.yml
  .ado/templates/run-compliance-postbuild.yml
  .ado/templates/run-compliance-prebuild.yml
  change/react-native-windows-4adb017c-a018-4673-a78a-1d87d3ba43e3.json
  change/react-native-windows-init-a2ce2e04-90ee-4f58-a390-f5899aa19a8d.json
  packages/react-native-windows-init/src/GenerateWindowsType.ts
  vnext/CHANGELOG.json
  vnext/CHANGELOG.md
  vnext/Desktop/ABI/NativeLogging.idl
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Labels: Area: Compliance
