Repository microsoft/react-native-windows, pull requests merged in 2022-07, with the labels that each got.

#10222 Use interface for ReactImage memory streams
  change/react-native-windows-b064d013-f809-4f41-8d4f-6427c428618a.json
  vnext/Microsoft.ReactNative/Modules/ImageViewManagerModule.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp
  vnext/Microsoft.ReactNative/Views/Image/ReactImage.h
Labels: AutoMerge, Area: Image

#10223 [0.67] CG updates for 6/28/22
  change/react-native-windows-3d4bf4d5-6fad-4d59-bc5e-2387ce0fdef5.json
  package.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10224 [0.66] CG updates for 6/28/22
  change/react-native-windows-78674cf9-6396-441e-bf59-d5f0cd4f2aac.json
  package.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10225 [0.65] CG updates for 6/28/22
  change/react-native-windows-b239012b-a060-41d6-9c2b-88f52bfd7e41.json
  package.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10226 [0.64] CG updates for 6/28/22
  change/react-native-windows-3f168ded-c8d2-4ad9-89db-457a4ca04fa8.json
  package.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10217 [0.68] CG updates for 6/28/22
  change/react-native-windows-45866773-3818-4b68-b400-e7a0ece48718.json
  package.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10244 Additional compiler & linker flags for binary size
  change/react-native-windows-f17abf92-78b7-416e-866a-5637f77ac23e.json
  vnext/PropertySheets/Release.props
Labels: AutoMerge

#10229 Fix Color Customization Bug During High Contrast Mode
  change/react-native-windows-a7fb9056-7818-4d19-93c6-792041ed96f1.json
  vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
Labels: Area: Accessibility

#10250 [0.68] Fix Color Customization Bug During High Contrast Mode
  change/react-native-windows-657e1817-a100-4707-8603-7b1ffc3ce060.json
  vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
Labels: Area: Accessibility

#10251 [0.69] Fix Color Customization Bug During High Contrast Mode
  change/react-native-windows-0521218e-04c4-4409-8cb0-62e95a3e74a2.json
  change/react-native-windows-93991d79-32d9-4ddb-b3e1-41652af70870.json
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/tester/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/Microsoft.ReactNative/Utils/PropertyUtils.h
Labels: Area: Accessibility

#10210 CG: Remove deprecated dependency `hermes-engine` package
  change/@office-iss-react-native-win32-b376cd2b-6570-4dbb-b305-2311dab97b09.json
  change/react-native-windows-68a2b28e-78bb-452c-bf90-3f29dcdd5f7f.json
  packages/@office-iss/react-native-win32/package.json
  vnext/package.json
Labels: security, Area: Compliance

#10216 [0.69] CG updates for 6/28/22
  change/react-native-windows-a1c5b546-123a-467b-af09-b6e523f36db9.json
  vnext/Microsoft.ReactNative.Managed.CodeGen.UnitTests/Microsoft.ReactNative.Managed.CodeGen.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10064 Map App Window Focus to RN AppState
  change/react-native-windows-4a008974-44b3-4f6c-bfb5-5aa79c2b0f79.json
  vnext/Microsoft.ReactNative/Modules/AppStateModule.cpp
  vnext/Microsoft.ReactNative/Modules/AppStateModule.h
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
Labels: AutoMerge, Area: AppState

#10267 Import WinUI package only if OverrideWinUIPackage is not set to "true"
  change/react-native-windows-1a39d1a9-7548-4b2b-956e-d684a2eace90.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
Labels: AutoMerge

#10261 Implement HTTP client timeout
  change/react-native-windows-42dec614-af90-4b29-b8c7-f266415ea240.json
  vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
Labels: Area: Networking

#10273 [0.69] Import WinUI package only if OverrideWinUIPackage is not true
  change/react-native-windows-0440ff4e-5b47-4657-acb1-939f8568d6eb.json
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
Labels: AutoMerge

#10169 [0.68] Update source of DeviceID for telemetry
  change/@react-native-windows-telemetry-731eae08-aad0-4223-98a0-59137f9c271d.json
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
  yarn.lock
Labels: AutoMerge

#9936 CoreApp API
  .ado/jobs/playground.yml
  change/react-native-windows-4b89df3c-1b2d-4dcc-8adf-ef3c9372df35.json
  packages/playground/.gitignore
  packages/playground/CoreApp/App.cpp
  packages/playground/CoreApp/Assets/LockScreenLogo.scale-200.png
  packages/playground/CoreApp/Assets/SplashScreen.scale-200.png
  packages/playground/CoreApp/Assets/Square150x150Logo.scale-200.png
  packages/playground/CoreApp/Assets/Square44x44Logo.scale-200.png
  packages/playground/CoreApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  packages/playground/CoreApp/Assets/StoreLogo.png
  packages/playground/CoreApp/Assets/Wide310x150Logo.scale-200.png
  packages/playground/CoreApp/CoreApp.sln
  packages/playground/CoreApp/CoreApp.vcxproj
  packages/playground/CoreApp/CoreApp.vcxproj.filters
  packages/playground/CoreApp/ExperimentalFeatures.props
  packages/playground/CoreApp/Package.appxmanifest
  packages/playground/CoreApp/PropertySheet.props
  packages/playground/CoreApp/app.config.json
  packages/playground/CoreApp/pch.cpp
  packages/playground/CoreApp/pch.h
  vnext/Microsoft.ReactNative.Cxx/CoreApp.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems.filters
  vnext/Microsoft.ReactNative/CoreApp.cpp
  vnext/Microsoft.ReactNative/CoreAppPage.cpp
  vnext/Microsoft.ReactNative/CoreAppPage.h
  vnext/Microsoft.ReactNative/CoreAppPage.idl
  vnext/Microsoft.ReactNative/CoreAppPage.xaml
  vnext/Microsoft.ReactNative/Fabric/ActivityIndicatorComponentView.cpp
  vnext/Microsoft.ReactNative/IReactPropertyBag.cpp
  vnext/Microsoft.ReactNative/IReactPropertyBag.h
  vnext/Microsoft.ReactNative/IReactPropertyBag.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/ReactApplication.cpp
  vnext/Microsoft.ReactNative/ReactApplication.h
  vnext/Microsoft.ReactNative/microsoft.reactnative.def
Labels: Area: Developer Experience, Area: Build Infrastructure

#10168 [0.69] Update source of DeviceID for telemetry
  change/@react-native-windows-telemetry-731eae08-aad0-4223-98a0-59137f9c271d.json
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
  yarn.lock
Labels: AutoMerge

#10288 [0.69] Fix floating point conversions in non en-US locales
  change/react-native-windows-2e859e4c-95bd-4d4c-a348-0957d6a5e79d.json
  vnext/stubs/double-conversion/double-conversion.h
Labels: AutoMerge, Area: Globalization

#10289 [0.68] Fix floating point conversions in non en-US locales
  change/react-native-windows-81fdd983-b7d9-4e03-9175-a9545a5e8599.json
  vnext/stubs/double-conversion/double-conversion.h
Labels: AutoMerge, Area: Globalization

#10281 [0.68] Implement importantForAccessibility="no-hide-accessibility"
  change/@office-iss-react-native-win32-6203522e-a1d1-4c7c-8abd-058880715a24.json
  change/react-native-windows-710a5094-3190-497d-94e5-1b58d8ec27ae.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
  vnext/src/Libraries/Components/View/View.windows.js
Labels: Area: Accessibility

#10280 [0.67] Implement importantForAccessibility="no-hide-accessibility"
  change/@office-iss-react-native-win32-66e95e8b-c77f-4122-bcbb-fcb1e6ce5077.json
  change/react-native-windows-93fc478e-4970-43db-9342-1f0e9aa42483.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/View.win32.js
  vnext/src/Libraries/Components/View/View.windows.js
Labels: Area: Accessibility

#10315 Fix doxysaurus error logging to handle Error objects
  change/@rnw-scripts-doxysaurus-13ba6601-91c6-4360-80cd-7b98e4e90bce.json
  packages/@rnw-scripts/doxysaurus/src/doxysaurus.ts
Labels: Area: Tooling

#10316 CG updates for 7/25/22
  change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  yarn.lock
Labels: security, Area: Compliance

#10317 Additional fix required for UTF-8 characters in bundle path
  change/react-native-windows-14e96a89-26af-4535-b3d9-517842df1df6.json
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#10321 Fix crash in DynamicAutomationPeer::GetContentName
  change/react-native-windows-cd8eaf8d-1ab0-463a-9f8c-3efd78aa308d.json
  vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.cpp
Labels: AutoMerge

#10328 [0.65] CG updates for 7/25/22
  change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10327 [0.66] CG updates for 7/25/22
  change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10326 [0.67] CG updates for 7/25/22
  change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10324 [0.68] CG updates for 7/25/22
  change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10320 [0.69] CG updates for 7/25/22
  change/@rnw-scripts-doxysaurus-94fae730-ad36-43ec-b3a6-33ae58cb6cab.json
  packages/@rnw-scripts/doxysaurus/package.json
  packages/@rnw-scripts/doxysaurus/src/doxygen.ts
  yarn.lock
Labels: AutoMerge, security, API: Completion
