Repository microsoft/react-native-windows, pull requests merged in 2022-04, with the labels that each got.

#9730 Adds Switch component RNTester page treedump tests
  packages/e2e-test-app/test/SwitchComponentTest.test.ts
  packages/e2e-test-app/test/__snapshots__/SwitchComponentTest.test.ts.snap
Labels: AutoMerge

#9719 Adds mouse-click events e2e tests
  packages/@react-native-windows/tester/src/js/examples-win/Mouse/MouseClickExample.windows.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/e2e-test-app/test/MouseClickTest.test.ts
Labels: AutoMerge

#9747 [0.68] Security: Update simple-git dependency to 3.3.0
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/promote-release/src/promoteRelease.ts
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  yarn.lock
Labels: AutoMerge

#9781 [0.66] Security: Update simple-git dependency to 3.3.0
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/promote-release/src/promoteRelease.ts
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  yarn.lock
Labels: AutoMerge

#9765 Eliminate a whole-bundle string copy
  change/react-native-windows-4221e184-d6c7-49d8-9c92-8ce786a85e4c.json
  vnext/Shared/DevSupportManager.cpp
Labels: AutoMerge

#9768 Enable loading the bundle from an embedded resource via resource://moduleName/resourceId
  change/react-native-windows-73626f69-9b5c-4bcc-bf4a-2bffdfab80b6.json
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/Utils/LocalBundleReader.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge

#9799 [Win32] Don't load XAML if we are checking if we are a XAML app
  change/react-native-windows-a8ae532b-cf51-4163-9351-660a49956641.json
  vnext/Microsoft.ReactNative.Cxx/XamlUtils.h
Labels: AutoMerge

#9801 Stop Telemetry background threads running after test completion
  change/@react-native-windows-telemetry-b9507482-ef51-4a3c-b217-6a53d40e0bb4.json
  packages/@react-native-windows/telemetry/package.json
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
  yarn.lock
Labels: AutoMerge

#9809 Fix error output in rnw-dependencies.ps1
  change/react-native-windows-c6313129-5ecd-4713-a7e6-f1a0996e742e.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Dependencies

#9782 [0.65] Security: Update simple-git dependency to 3.3.0
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/promote-release/src/promoteRelease.ts
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  yarn.lock
Labels: AutoMerge

#9818 Fix Sequential Mso DispatchQueue deadlock on shutdown
  change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters
  vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
  vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Labels: AutoMerge

#9783 [0.64] Security: Update simple-git dependency to 3.3.0
  packages/@rnw-scripts/create-github-releases/package.json
  packages/@rnw-scripts/create-github-releases/src/createGithubReleases.ts
  packages/@rnw-scripts/promote-release/package.json
  packages/@rnw-scripts/promote-release/src/promoteRelease.ts
  packages/react-native-platform-override/package.json
  packages/react-native-platform-override/src/GitReactFileRepository.ts
  yarn.lock
Labels: AutoMerge

#9831 Avoid loading XAML just to fill a Color struct
  change/react-native-windows-28f2445d-ffec-4dd1-a51e-0c2386980e28.json
  packages/e2e-test-app/package.json
  vnext/Microsoft.ReactNative.Cxx/CppWinRTIncludes.h
  vnext/Microsoft.ReactNative.Cxx/XamlUtils.h
  vnext/Microsoft.ReactNative/ReactRootView.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp
  yarn.lock
Labels: AutoMerge

#9842 [Perf] simplify cdebug, removes an unnecessary dynamic initializer
  change/react-native-windows-36fd6f7c-9773-4ab0-8927-b164153478dd.json
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/cdebug.cpp
  vnext/include/Shared/cdebug.h
Labels: AutoMerge

#9845 [0.68] CG: Update async to resolve CVE-2021-43138
  package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/react-native-platform-override/package.json
  yarn.lock
Labels: AutoMerge

#9848 [0.65] CG: Update async to resolve CVE-2021-43138
  package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/react-native-platform-override/package.json
  yarn.lock
Labels: AutoMerge

#9849 [0.64] CG: Update async to resolve CVE-2021-43138
  package.json
  packages/@rnw-scripts/format-files/package.json
  packages/@rnw-scripts/integrate-rn/package.json
  packages/react-native-platform-override/package.json
  yarn.lock
Labels: AutoMerge

#9825 Re-enable telemetry tests
  .ado/jobs/node-tests.yml
  change/@react-native-windows-telemetry-97ad5a9e-21cc-4617-8d2a-cee091607fd5.json
  packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
  packages/@react-native-windows/telemetry/src/test/versionUtils.test.ts
Labels: AutoMerge

#9829 Handle abrupt WebSocket connection interruption
  change/react-native-windows-11d58db5-55b8-4782-b499-1baaeb791c35.json
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Shared/Networking/IWebSocketResource.h
  vnext/Shared/Networking/WinRTWebSocketResource.cpp
Labels: AutoMerge, Area: Networking

#9867 [0.66] Fix JSI implementation for Node-API and update v8jsi to 0.65.11
  change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Labels: AutoMerge

#9864 [0.68] Fix Sequential Mso DispatchQueue deadlock on shutdown
  change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters
  vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
  vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Labels: AutoMerge

#9863 [0.67] Fix Sequential Mso DispatchQueue deadlock on shutdown
  change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters
  vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
  vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Labels: AutoMerge

#9858 [0.64] CG Fixes for 4/18/2022
  yarn.lock
Labels: AutoMerge, security

#9857 [0.65] CG Fixes for 4/18/2022
  yarn.lock
Labels: AutoMerge, security

#9853 [0.68] CG fixes for 4/18/2022
  yarn.lock
Labels: AutoMerge, security

#9871 Narrator announces changes to accessibilityState
  change/react-native-windows-07a91306-5a2e-4459-b70b-ce9761c3ac91.json
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
Labels: Area: Accessibility

#9856 [0.66] CG Fixes for 4/18/2022
  yarn.lock
Labels: AutoMerge, security

#9855 [0.67] CG Fixes for 4/18/2022
  yarn.lock
Labels: AutoMerge, security

#9862 [0.66] Fix Sequential Mso DispatchQueue deadlock on shutdown
  change/react-native-windows-994ac337-c779-45ca-aea6-48c686f2e857.json
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj
  vnext/Mso.UnitTests/Mso.UnitTests.vcxproj.filters
  vnext/Mso.UnitTests/dispatchQueue/dispatchQueueTest.cpp
  vnext/Mso/src/dispatchQueue/threadPoolScheduler_win.cpp
Labels: AutoMerge

#9872 [0.67] Fix JSI implementation for Node-API and update v8jsi to 0.65.11 (#9867)
  change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Labels: AutoMerge

#9875 [0.68] Fix JSI implementation for Node-API and update v8jsi to 0.65.11 (#9867)
  change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Labels: AutoMerge

#9883 Fix JSI implementation for Node-API and update v8jsi to 0.65.11 (#9867)
  change/react-native-windows-5399ecee-0b0c-4061-ad9c-5308081e829d.json
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Labels: AutoMerge

#9873 Telemetry updates to meet server-side requirements
  change/@react-native-windows-cli-9b90ea8d-57a8-49b1-a2c3-1dbf5dc120bc.json
  change/@react-native-windows-telemetry-576950f0-e0ad-4946-afbd-7def82c5885b.json
  packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
  packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
  packages/@react-native-windows/telemetry/src/utils/errorUtils.ts
  packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
Labels: Area: CLI, Area: Telemetry

#9886 [0.68] Telemetry updates to meet server-side requirements
  change/@react-native-windows-cli-fbe2ed4a-2420-408e-9c0a-ec10c517eb0a.json
  change/@react-native-windows-telemetry-b37e2a4f-8e7a-4dba-8658-480455e84792.json
  packages/@react-native-windows/cli/src/runWindows/utils/commandWithProgress.ts
  packages/@react-native-windows/cli/src/runWindows/utils/msbuildtools.ts
  packages/@react-native-windows/telemetry/src/telemetry.ts
  packages/@react-native-windows/telemetry/src/test/basePropUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/errorUtils.test.ts
  packages/@react-native-windows/telemetry/src/test/telemetry.test.ts
  packages/@react-native-windows/telemetry/src/utils/basePropUtils.ts
  packages/@react-native-windows/telemetry/src/utils/errorUtils.ts
  packages/@react-native-windows/telemetry/src/utils/sanitizeUtils.ts
Labels: Area: CLI, Area: Telemetry

#9888 Pr/fix glob parent
  change/@react-native-windows-codegen-848bb339-e81b-46c8-9f89-7a28efd64901.json
  packages/@react-native-windows/codegen/package.json
Labels: AutoMerge

#9880 [0.68] Handle abrupt WebSocket connection interruption
  change/react-native-windows-6ccd7390-80e0-4efd-bdd1-c5dfba7bf786.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/DesktopTestRunner.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.IntegrationTests/WebSocketIntegrationTest.cpp
  vnext/Desktop/HttpResource.cpp
  vnext/Desktop/HttpResource.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/IntegrationTests/TestRunner.h
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/CreateModules.h
  vnext/Shared/IHttpResource.h
  vnext/Shared/IWebSocketResource.h
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Modules/HttpModule.h
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/Utils/WinRTConversions.cpp
  vnext/Shared/Utils/WinRTConversions.h
  vnext/Shared/WinRTHttpResource.cpp
  vnext/Shared/WinRTHttpResource.h
  vnext/Shared/WinRTWebSocketResource.cpp
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
  vnext/src/IntegrationTests/XHRTest.js
Labels: AutoMerge

#9897 Fix links to GitHubDocs
  CONTRIBUTING.md
Labels: AutoMerge, Documentation

#9911 [0.68] Avoid crashing when running unpackaged apps
  change/react-native-windows-75d3cf97-675c-4257-b49c-bcc7bfbd0e27.json
  vnext/Shared/DevSupportManager.cpp
Labels: AutoMerge

#9912 [0.68] Built in turbomodules should not override app provided versions
  change/react-native-windows-12b8ebce-b24a-4945-aabb-3021ecb46003.json
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/ReactPackageBuilder.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
  vnext/Microsoft.ReactNative/TurboModulesProvider.h
Labels: AutoMerge

#9887 Stop exporting data blocks from react-native-win32.dll
  change/react-native-windows-4e0e762e-ea7f-458b-93c2-533b3fa3a806.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
  vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
  vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.h
Labels: Platform: NetUI

#9902 [react-native-win32] Add listitem accessibility role and accessibilityControls test example
  change/@office-iss-react-native-win32-d14f43ea-5d87-42e6-ac59-932aaee0dd9e.json
  packages/@office-iss/react-native-win32-tester/src/js/examples-win32/Accessibility/AccessibilityExampleWin32.tsx
  packages/@office-iss/react-native-win32-tester/src/js/utils/RNTesterList.win32.js
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Labels: AutoMerge, Area: Accessibility, Platform: NetUI

#9917 [0.68] Enable loading the bundle from an embedded resource via resource://moduleName/resourceId
  change/react-native-windows-73626f69-9b5c-4bcc-bf4a-2bffdfab80b6.json
  vnext/Microsoft.ReactNative/ReactInstanceSettings.idl
  vnext/Microsoft.ReactNative/Utils/LocalBundleReader.cpp
  vnext/Shared/OInstance.cpp
Labels: AutoMerge
