Repository microsoft/react-native-windows, pull requests merged in 2022-09, with the labels that each got.

#10495 Add `$schema` to `cgmanifest.json` codegen
  change/react-native-windows-1f809f69-c2e9-49d5-bea5-706b281f03ff.json
  vnext/Folly/Folly.vcxproj
  vnext/Folly/cgmanifest.json
  vnext/fmt/cgmanifest.json
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge

#10498 Fixes bug introduced by pointerEvents change
  change/react-native-windows-6319c12d-1bae-496d-a970-f863834d0d05.json
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
Labels: Backport: Requested

#10356 Avoid ReplaceView in TextInputViewManager
  change/react-native-windows-8d46a210-dc6e-4eaf-b095-1b6ffa9c3aba.json
  packages/e2e-test-app/test/__snapshots__/LegacyControlStyleTest.test.ts.snap
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: TextInput

#10558 [0.70] [RN Win32] Backport accessibility access key win32
  change/@office-iss-react-native-win32-b89a8ae7-e8bb-4ce4-ac95-b7ecf6ba88ca.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Labels: AutoMerge

#10553 ADO: Change full checkout `persistCredentials` default back to `false`
  .ado/integrate-rn.yaml
  .ado/jobs/cli-init.yml
  .ado/jobs/setup.yml
  .ado/publish.yml
  .ado/templates/checkout-full.yml
Labels: AutoMerge, security, Area: Build Infrastructure

#10592 Add Agent ES exemption file for compliance pipeline
  .ado/config/AgentES.Exemptions.json
Labels: Area: Compliance

#10534 Implement HTTP redirection
  change/react-native-windows-d5cf0017-99f3-40eb-856e-25f6e85f6fa2.json
  vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/RedirectHttpFilterUnitTest.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.h
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/IRedirectEventSource.h
  vnext/Shared/Networking/IWinRTHttpRequestFactory.h
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.h
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
Labels: AutoMerge, Area: Networking

#10596 [0.70] Implement HTTP redirection
  change/react-native-windows-26a724f0-7103-4b59-a493-7ef156733d0d.json
  vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/RedirectHttpFilterUnitTest.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.h
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/IRedirectEventSource.h
  vnext/Shared/Networking/IWinRTHttpRequestFactory.h
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.h
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
Labels: Backport: Requested

#10599 [0.69] Implement HTTP redirection
  change/react-native-windows-8774bc63-ff18-46cc-a251-a29365cb67c6.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/RedirectHttpFilterUnitTest.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Shared/Modules/BlobModule.cpp
  vnext/Shared/Modules/BlobModule.h
  vnext/Shared/Modules/FileReaderModule.cpp
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Modules/IBlobPersistor.h
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/IRedirectEventSource.h
  vnext/Shared/Networking/IWinRTHttpRequestFactory.h
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.h
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
  vnext/overrides.json
Labels: Backport: Requested

#10600 [0.68] Implement HTTP redirection
  change/react-native-windows-b2f23c96-082a-4440-8d14-1d5a0ce3d115.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  vnext/Desktop.IntegrationTests/HttpOriginPolicyIntegrationTest.cpp
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Desktop.UnitTests/OriginPolicyHttpFilterTest.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop.UnitTests/RedirectHttpFilterUnitTest.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.cpp
  vnext/Desktop.UnitTests/WinRTNetworkingMocks.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Microsoft.ReactNative/Pch/pch.h
  vnext/Shared/Modules/BlobModule.cpp
  vnext/Shared/Modules/BlobModule.h
  vnext/Shared/Modules/FileReaderModule.cpp
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Modules/IBlobPersistor.h
  vnext/Shared/Modules/WebSocketModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/IRedirectEventSource.h
  vnext/Shared/Networking/IWinRTHttpRequestFactory.h
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.h
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Test/HttpServer.cpp
  vnext/Test/HttpServer.h
  vnext/overrides.json
Labels: Backport: Requested

#10604 Fix formatting in App.xaml.cs in C# WinAppSDK project template
  change/react-native-windows-4fcaba6c-79ae-484a-a6a8-64fa08ee4c4b.json
  vnext/template/cs-app-WinAppSDK/MyApp/App.xaml.cs
Labels: AutoMerge

#10628 Consolidate JavaScript HTTP module specifications
  change/@office-iss-react-native-win32-5d4d2e75-73de-4731-96a7-622b462c7d8a.json
  change/react-native-platform-override-563b2a70-909c-4494-a291-9bf419ee59fd.json
  change/react-native-windows-1fcfe09c-4814-4557-8df4-7e9d39f6a908.json
  packages/@office-iss/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
  vnext/Shared/Modules/HttpModule.h
  vnext/overrides.json
  vnext/src/Libraries/Network/RCTNetworking.windows.js
  vnext/src/Libraries/Network/RCTNetworkingWinShared.js
Labels: Area: Networking, Platform: Desktop

#10629 [0.70] Consolidate JavaScript HTTP module specifications
  change/@office-iss-react-native-win32-adf69e32-d30a-4c8b-83dd-a24c6eb742f7.json
  change/react-native-windows-1d378eed-7c0b-48c5-81d0-5d6358317af3.json
  packages/@office-iss/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
  vnext/Shared/Modules/HttpModule.h
  vnext/overrides.json
  vnext/src/Libraries/Network/RCTNetworking.windows.js
  vnext/src/Libraries/Network/RCTNetworkingWinShared.js
Labels: AutoMerge, Backport: Requested

#10631 [0.68] Consolidate JavaScript HTTP module specifications
  change/@office-iss-react-native-win32-b997a1ed-7200-40f6-b3d2-08e758a21407.json
  change/react-native-windows-272a70cc-305e-4e6a-bd95-54e03d3a873a.json
  packages/@office-iss/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
  vnext/Shared/Modules/HttpModule.h
  vnext/overrides.json
  vnext/src/Libraries/Network/RCTNetworking.windows.js
  vnext/src/Libraries/Network/RCTNetworkingWinShared.js
Labels: AutoMerge, Backport: Requested

#10630 [0.69] Consolidate JavaScript HTTP module specifications
  change/@office-iss-react-native-win32-677fb78b-0eba-469c-9a87-693da5313ab9.json
  change/react-native-windows-28c5a499-c077-473b-af15-73804a799f33.json
  packages/@office-iss/react-native-win32/src/Libraries/Network/RCTNetworking.win32.js
  vnext/Shared/Modules/HttpModule.h
  vnext/overrides.json
  vnext/src/Libraries/Network/RCTNetworking.windows.js
  vnext/src/Libraries/Network/RCTNetworkingWinShared.js
Labels: AutoMerge, Backport: Requested

#10652 Fabric: Stop ScrollView from scrolling past content
  change/react-native-windows-5ca2f093-d86c-4bab-9a50-4b6d722eefa4.json
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
Labels: Area: Fabric

#10653 Fabric: fix zorder issues
  change/react-native-windows-f017b5c1-bf44-4a8f-b996-203d619e5329.json
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
Labels: Area: Fabric

#10659 Fabric: simplify border code, and fix some border issues
  change/react-native-windows-f017b5c1-bf44-4a8f-b996-203d619e5329.json
  vnext/Microsoft.ReactNative/CompositionSwitcher.idl
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
Labels: Area: Fabric
