Repository microsoft/react-native-windows, pull requests merged in 2022-05, with the labels that each got.

#9943 Fix issue with CLI tests failing in PRs
  .ado/templates/react-native-init.yml
  .ado/templates/run-windows-with-certificates.yml
Labels: AutoMerge, Area: CLI, Area: Metro

#9946 Upgrade to @react-native-community/cli@8.0.0-alpha.6
  .ado/templates/react-native-init.yml
  change/@office-iss-react-native-win32-8c3a049d-265c-4c97-8797-4a58274e66b7.json
  change/react-native-windows-a25b692a-2335-4dda-89f4-d3a086f93053.json
  packages/@office-iss/react-native-win32/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/metro.config.js
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#9940 Removes JSI overrides from ReactCommon
  change/react-native-windows-ddd2652f-c119-418e-bceb-717f409d9e7b.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/Playground.vcxproj.filters
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/JSCRuntime.cpp
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/jsi/decorator.h
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/jsi/jsi.h
  vnext/Shared/InspectorPackagerConnection.cpp
  vnext/Shared/InspectorPackagerConnection.h
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntime.h
  vnext/overrides.json
Labels: Area: JSI

#9953 Terminate if a Chakra JS object cannot be created
  change/react-native-windows-502521d2-2bf0-4423-8d9c-0a79dbfa01b3.json
  vnext/Chakra/ChakraValue.cpp
Labels: AutoMerge

#9935 Remove JsiEngineOverride::ChakraCore
  change/react-native-windows-9f2d0dd5-3706-43d6-bb7b-1de7c47a3925.json
  vnext/Shared/DevSettings.h
  vnext/Shared/OInstance.cpp
Labels: AutoMerge, Area: JavaScript Engine

#9959 Update comments in IReactDispatcher.idl
  change/react-native-windows-91963646-c015-49a5-87cc-d174fa06e010.json
  vnext/Microsoft.ReactNative/IReactDispatcher.idl
Labels: AutoMerge

#9972 Fix crash when enabling Yoga logging
  change/react-native-windows-9193a9f7-cac3-4657-b640-ac468b782823.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: AutoMerge

#9957 Allow >10MB HTTP downloads
  change/react-native-windows-68257dfa-e3b3-4038-b170-6bc686cb3b08.json
  vnext/Shared/Networking/WinRTHttpResource.cpp
Labels: AutoMerge, Area: Networking

#9990 Compliance: Rename template Nuget.config files to stop triggering multi-feed warnings
  change/@react-native-windows-cli-81517eff-3586-4693-8d07-0ff6bd9710b0.json
  change/react-native-windows-74880bf0-e7b0-4668-9148-3c7fbf28d4a9.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/template/cs-app-WinAppSDK/proj/NuGet_Config
  vnext/template/shared-app/proj/NuGet_Config
  vnext/template/shared-lib/proj/NuGet_Config
Labels: AutoMerge, Area: Compliance

#9965 Fix the run loop
  change/react-native-windows-b0c290d3-c8b2-4afe-82b3-2c1aa7a5741c.json
  vnext/Mso/src/dispatchQueue/looperScheduler.cpp
Labels: AutoMerge

#10007 Resolving CodeQL warnings 5/25/22
  change/react-native-windows-562754ad-2fa6-471f-b04d-5cabf2739c81.json
  vnext/Chakra/ChakraHelpers.cpp
  vnext/Chakra/ChakraPlatform.cpp
  vnext/Chakra/ChakraValue.h
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Utils/Helpers.cpp
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
  vnext/Shared/JSI/ChakraRuntime.cpp
Labels: AutoMerge, Area: Compliance

#9950 [0.69] Removes JSI overrides from ReactCommon
  change/react-native-windows-82bf98df-8dab-4d3e-acd5-043e8fdc5ea9.json
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/JsiAbiApi.h
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative/JsiApi.cpp
  vnext/Microsoft.ReactNative/JsiApi.h
  vnext/Microsoft.ReactNative/JsiApi.idl
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/JSCRuntime.cpp
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/jsi/decorator.h
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/jsi/jsi/jsi.h
  vnext/Shared/InspectorPackagerConnection.cpp
  vnext/Shared/InspectorPackagerConnection.h
  vnext/Shared/JSI/ChakraRuntime.cpp
  vnext/Shared/JSI/ChakraRuntime.h
  vnext/overrides.json
Labels: Area: JSI

#9437 Updates visual of TextInput if focusable = false
  change/react-native-windows-c363f784-3f86-470a-817a-ec93e46441c9.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: Area: TextInput

#10011 Change CG registration for folly and fmt from `other` to `git`
  change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge

#10005 [0.66] Expose LoadingState on ReactContext
  change/react-native-windows-48cb9d1d-48bd-4997-b425-b576e6f72e2f.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactContextTest.cpp
  vnext/Microsoft.ReactNative.Cxx.UnitTests/ReactModuleBuilderMock.h
  vnext/Microsoft.ReactNative.Managed.UnitTests/ReactModuleBuilderMock.cs
  vnext/Microsoft.ReactNative/IReactContext.cpp
  vnext/Microsoft.ReactNative/IReactContext.h
  vnext/Microsoft.ReactNative/IReactContext.idl
Labels: AutoMerge

#10019 [0.69] Change CG registration for folly and fmt from `other` to `git`
  change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge, security

#10020 [0.68] Change CG registration for folly and fmt from `other` to `git`
  change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge, security

#10021 [0.67] Change CG registration for folly and fmt from `other` to `git`
  change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge, security

#10022 [0.66] Change CG registration for folly and fmt from `other` to `git`
  change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge, security

#10023 [0.65] Change CG registration for folly and fmt from `other` to `git`
  change/react-native-windows-300bd2ca-501b-4462-8eff-3116a3b509a5.json
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge, security

#9995 [0.66] Support PreparedScriptStore for V8 Node-API
  change/react-native-windows-8f4cd7f3-9cd6-4681-8d63-b378c912d67d.json
  vnext/Desktop.DLL/packages.config
  vnext/Microsoft.ReactNative.Cxx.UnitTests/packages.config
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative/packages.config
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.config
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
Labels: AutoMerge

#10037 Add CodeQL .lgtm.yml configuration file
  .lgtm.yml
Labels: AutoMerge, Area: Compliance

#10039 Add PoliCheck and CredScan config files
  .ado/compliance.yml
  .ado/config/CredScanSuppressions.json
  .ado/config/PoliCheckExclusions.xml
  .ado/jobs/linting.yml
  .ado/publish.yml
Labels: AutoMerge, Area: Compliance
