Repository microsoft/react-native-windows, pull requests merged in 2022-12, with the labels that each got.

#10956 Minor build fixes to enable fabric in desktop dll
  change/react-native-windows-11b3105a-6557-4333-84b6-ebcf40ffc432.json
  vnext/Desktop/module.g.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHelpers.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/React.Cpp.props
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: Platform: NetUI

#10087 Use ProcDump to capture crash dumps in CI pipelines
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/jobs/playground.yml
  .ado/scripts/RunProcDump.ps1
  .ado/scripts/SetupLocalDumps.cmd
  .ado/templates/cleanup-certificate.yml
  .ado/templates/prepare-build-env.yml
  .ado/templates/upload-build-logs.yml
  packages/integration-test-app/windows/integrationtest/Package.appxmanifest
Labels: AutoMerge, Area: Tests, Area: Test Infrastructure, Area: Build Infrastructure

#10957 Update rnw-image* config backups and stop extra .NET installs
  .ado/image/rnw-img-node16.json
  .ado/image/rnw-img-vs2022.json
  .ado/variables/shared.yml
Labels: AutoMerge, Area: Compliance

#10429 [0.70] Add new prop alwaysShowToolTip to ViewWin32 (#10381)
  change/@office-iss-react-native-win32-7fce2b29-0c20-4c4f-b2c6-8c4e7001f7cd.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Labels: AutoMerge

#10966 [0.68] Fix V8 Node API Task Runner implementation
  change/react-native-windows-cafebabf-5714-4f76-9359-584cca01febc.json
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.cpp
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/Networking/IWebSocketResource.h
Labels: AutoMerge

#10428 [0.69] Add new prop alwaysShowToolTip to ViewWin32 (#10381)
  change/@office-iss-react-native-win32-7fce2b29-0c20-4c4f-b2c6-8c4e7001f7cd.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ReactNativeViewAttributes.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewWin32.Props.ts
Labels: AutoMerge

#10133 Adds logic to retain undo/redo history for TextInput
  change/react-native-windows-9bafa41c-fc12-4ffa-b62c-8a2820372974.json
  vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp
Labels: AutoMerge, Area: TextInput

#10983 [0.71] Implement HTTP incremental updates
  change/react-native-windows-77be59f2-bcaa-426d-9d27-b1b89d80207b.json
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
Labels: Backport: Requested

#10985 [0.69] Implement HTTP incremental updates
  .vscode/settings.json
  change/react-native-windows-68257dfa-e3b3-4038-b170-6bc686cb3b08.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExample.js
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExampleMultiPartFormData.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/Modules/FileReaderModule.cpp
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/src/IntegrationTests/BlobTest.js
Labels: AutoMerge, Backport: Requested

#10984 [0.70] Implement HTTP incremental updates
  change/react-native-windows-345bfd62-1796-4a42-9aad-c5423193bb33.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExample.js
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExampleMultiPartFormData.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
Labels: AutoMerge, Backport: Requested

#10986 [0.68] Implement HTTP incremental updates
  .vscode/settings.json
  change/react-native-windows-b9e554cb-99ed-4bb5-8219-96f0c4372b29.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExample.js
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExampleMultiPartFormData.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/Modules/FileReaderModule.cpp
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Networking/IHttpResource.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/src/IntegrationTests/websocket_integration_test_server_blob.js
Labels: AutoMerge, Backport: Requested

#10994 Remove work around for broken Utilities import in core
  change/@office-iss-react-native-win32-09122742-d6a3-4232-ad09-91d594721b50.json
  change/react-native-platform-override-9750f78b-6b48-4fa5-ab0b-31b4fa8e7f0c.json
  change/react-native-windows-d2516c3f-bb61-44bd-980e-846418091114.json
  packages/@office-iss/react-native-win32-tester/tsconfig.json
  packages/@office-iss/react-native-win32/tsconfig.json
  packages/@react-native-windows/tester/tsconfig.json
  packages/playground/tsconfig.json
  packages/react-native-platform-override/tsconfig.json
  vnext/tsconfig.json
Labels: AutoMerge

#10997 [0.70] CG Updates for 12/12/22
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10998 [0.69] CG Updates for 12/12/22
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11000 Fix raw text update clearing Text
  change/react-native-windows-dc9c358f-08b5-4a90-aca1-37f042a31a3f.json
  vnext/Microsoft.ReactNative/Views/TextViewManager.cpp
Labels: Backport: Requested

#11004 [0.67] CG Updates for 12/12/22
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11027 V8 Package Update
  change/react-native-windows-fdeebb2c-7e65-431c-bff1-efc8aeb24786.json
  packages/playground/windows/NuGet.Config
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/OInstance.cpp
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#11002 [0.68] CG Updates for 12/12/22
  yarn.lock
Labels: AutoMerge, security, Area: Compliance
