Repository microsoft/react-native-windows, pull requests merged in 2022-10, with the labels that each got.

#10672 Fabric: ImageRequest should kick off from ImageShadowNode instead of ImageComponentView
  change/react-native-windows-f017b5c1-bf44-4a8f-b996-203d619e5329.json
  vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
  vnext/Microsoft.ReactNative/Fabric/ImageManager.cpp
  vnext/Microsoft.ReactNative/Fabric/ImageRequest.cpp
  vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.cpp
  vnext/Microsoft.ReactNative/Fabric/WindowsImageManager.h
  vnext/Shared/Shared.vcxitems
  vnext/overrides.json
Labels: Area: Fabric

#10665 Explicitly measure relative to the root XAML element
  change/react-native-windows-0f54d4e2-d544-4e6b-b6bb-3f7e6eb6d3e3.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: AutoMerge

#10661 Adds QuirkSetting to use YGExperimentalFeatureWebFlexBasis
  change/react-native-windows-81766dee-43b9-4551-9a83-d2cc2e6b1f03.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.cpp
  vnext/Microsoft.ReactNative/QuirkSettings.h
  vnext/Microsoft.ReactNative/QuirkSettings.idl
Labels: AutoMerge, Needs: Author Feedback, Area: Layout, Area: Text

#10658 Refactor the onLayout event for view flattening
  change/react-native-windows-377f2770-0169-4a24-add1-e9ae515c1038.json
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Views/ShadowNodeBase.h
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp
  vnext/Microsoft.ReactNative/Views/ViewManagerBase.h
Labels: AutoMerge

#10692 Fabric: TextInput caret is incorrect size
  change/react-native-windows-4e282efb-fc79-4999-8d71-dd5b68a36f92.json
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
Labels: AutoMerge, Area: Fabric

#10695 Set User-Agent header in Origin Policy filter
  change/react-native-windows-a912b218-3e03-4b76-8b54-d9cd603a29c0.json
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Area: Networking

#10700 Set Origin HTTP header during CORS
  change/react-native-windows-8769dfac-39b4-4cfc-88ae-91a5456390a2.json
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Labels: Area: Networking

#10697 [0.70] Set User-Agent header in Origin Policy filter
  change/react-native-windows-fe91be36-714d-421e-a49f-92e619873986.json
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Backport: Requested

#10698 [0.69] Set User-Agent header in Origin Policy filter
  change/react-native-windows-d3922b8e-5a78-442a-baec-8e3453e3254c.json
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Backport: Requested

#10699 [0.68] Set User-Agent header in Origin Policy filter
  change/react-native-windows-e9126ab9-769d-4af3-9c11-c3a5043e9237.json
  vnext/Desktop.IntegrationTests/HttpResourceIntegrationTests.cpp
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
  vnext/Shared/Networking/RedirectHttpFilter.cpp
  vnext/Shared/Shared.vcxitems.filters
Labels: AutoMerge, Backport: Requested

#10703 [0.68] Set Origin HTTP header during CORS
  change/react-native-windows-b7b41b5d-bb81-4afb-9bad-df2adf65518c.json
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Labels: AutoMerge, Backport: Requested

#10701 [0.70] Set Origin HTTP header during CORS
  change/react-native-windows-449be090-5a44-4889-ab07-0d5be2bd88c3.json
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Labels: AutoMerge, Backport: Requested

#10702 [0.69] Set Origin HTTP header during CORS
  change/react-native-windows-4090a69c-674e-42d3-a643-39ec206c7c00.json
  vnext/Shared/Networking/OriginPolicyHttpFilter.cpp
Labels: AutoMerge, Backport: Requested

#10686 Always synchronize focusable and accessible props
  change/react-native-windows-9c0c9ca5-333f-4bbb-bd5a-7312b7431160.json
  packages/playground/Samples/view.tsx
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ViewViewManager.h
Labels: Area: Accessibility, Area: Focus

#10753 Fix warnings for malformed_package_json test file
  .ado/config/CredScanSuppressions.json
  .ado/templates/component-governance.yml
Labels: AutoMerge, Area: Compliance

#10752 Integration 8/26/22
  change/@office-iss-react-native-win32-2dea3ad5-977b-4636-904e-2c352c31c503.json
  change/@react-native-windows-automation-channel-cbdb4f9a-0579-4024-87fb-49ca84462ad5.json
  change/@react-native-windows-virtualized-list-043e7a3b-a1c9-4008-8b7c-c8a607f50d1c.json
  change/react-native-windows-f68da6af-2da2-4fe0-b718-6bc1435802a3.json
  packages/@office-iss/react-native-win32-tester/overrides.json
  packages/@office-iss/react-native-win32-tester/package.json
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@office-iss/react-native-win32/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/DatePicker/DatePickerIOS.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Components/View/ViewPropTypes.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/Inspector/Inspector.win32.js
  packages/@office-iss/react-native-win32/src/Libraries/StyleSheet/StyleSheet.win32.js
  packages/@react-native-windows/automation-channel/package.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/package.json
  packages/@react-native-windows/tester/src/js/examples-win/Flyout/FlyoutExample.windows.tsx
  packages/@react-native-windows/tester/src/js/examples/TextInput/TextInputExample.windows.js
  packages/@react-native-windows/virtualized-list/.flowconfig
  packages/@react-native-windows/virtualized-list/overrides.json
  packages/@react-native-windows/virtualized-list/package.json
  packages/@react-native/repo-config/overrides.json
  packages/@react-native/repo-config/package.json
  packages/@react-native/tester/js/examples/Accessibility/AccessibilityExample.js
  packages/@react-native/tester/js/examples/Experimental/W3CPointerEventPlatformTests/PointerEventAttributesNoHoverPointers.js
  packages/@react-native/tester/js/examples/Experimental/W3CPointerEventsExample.js
  packages/@react-native/tester/js/examples/FlatList/FlatList-basic.js
  packages/@react-native/tester/js/examples/RTL/RTLExample.js
  packages/@react-native/tester/js/examples/TextInput/TextInputExample.android.js
  packages/@react-native/tester/js/examples/TextInput/TextInputExample.ios.js
  packages/@react-native/tester/overrides.json
  packages/@rnw-scripts/metro-dev-config/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/.flowconfig
  vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputState.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputState.h
  vnext/ReactCopies/IntegrationTests/AppEventsTest.js
  vnext/codegen/NativeAccessibilityManagerSpec.g.h
  vnext/overrides.json
  vnext/package.json
  vnext/src/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js
  vnext/src/Libraries/Components/Button.windows.js
  vnext/src/Libraries/Components/DatePicker/DatePickerIOS.windows.js
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Components/View/ViewPropTypes.windows.js
  vnext/src/Libraries/StyleSheet/processTransform.windows.js
  yarn.lock
Labels: Area: Fabric

#10766 V8 package update
  change/react-native-windows-55aaf03d-9022-46b4-acd4-8d2637c6f49b.json
  packages/playground/windows/NuGet.Config
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/packages.config
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#10780 [0.68] react-native-win32 is using RN types from 0.66 instead of 0.68
  change/@office-iss-react-native-win32-44f9b4f8-73e4-4bb2-9492-2f976a4d89b7.json
  change/react-native-windows-31b4a10a-3a4a-4fec-a304-10161fae6aea.json
  packages/@office-iss/react-native-win32/package.json
  packages/e2e-test-app/package.json
  packages/integration-test-app/package.json
  packages/playground/package.json
  packages/sample-apps/package.json
  vnext/package.json
  yarn.lock
Labels: AutoMerge

#10770 [0.70] V8 package update
  change/react-native-windows-55aaf03d-9022-46b4-acd4-8d2637c6f49b.json
  packages/playground/windows/NuGet.Config
  packages/playground/windows/playground-win32/Playground-Win32.cpp
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/Playground.vcxproj
  packages/playground/windows/playground/packages.config
  vnext/Desktop.ABITests/React.Windows.Desktop.ABITests.vcxproj
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.Cxx.UnitTests/Microsoft.ReactNative.Cxx.UnitTests.vcxproj
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.cpp
  vnext/Microsoft.ReactNative.Cxx/JSI/NodeApiJsiRuntime.h
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.ProjectReferences.props
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/ReactCommon.UnitTests.vcxproj
  vnext/Shared/JSI/NapiJsiV8RuntimeHolder.h
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#10747 Fix `yarn install` run in VS project builds
  Directory.Build.props
  Directory.Build.targets
  change/react-native-windows-2835f765-8b00-4402-9c42-32f427689baf.json
  vnext/Microsoft.ReactNative.sln
Labels: AutoMerge

#10771 Update WindowsAppSDK versions to latest
  change/@react-native-windows-cli-e884393e-295e-43ea-b50c-dce70f71a176.json
  change/react-native-windows-90e2cc65-5baa-4b5c-9bf9-0cdfe54e132a.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/ExperimentalFeatures.props
  vnext/Microsoft.ReactNative.WindowsAppSDK/Microsoft.ReactNative.WindowsAppSDK.csproj
  vnext/PropertySheets/WinUI.props
  vnext/template/cs-app-WinAppSDK/proj/MyApp.csproj
Labels: Platform: WinAppSDK

#10793 Allow customers to specify $(CppWinRTVersion)
  change/react-native-windows-79f6563d-c38d-419d-b66a-00820b069c31.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
Labels: AutoMerge, Area: Dependencies
