Repository microsoft/react-native-windows, pull requests merged in 2022-11, with the labels that each got.

#10815 Remove Microsoft.ReactNative.Managed.IntegrationTests from ARM64 build
  change/react-native-windows-8a89df6e-f669-46dc-9ada-d645db4f038d.json
  vnext/Microsoft.ReactNative.Managed.IntegrationTests/Microsoft.ReactNative.Managed.IntegrationTests.csproj
  vnext/Microsoft.ReactNative.sln
Labels: AutoMerge

#10820 [0.69] Allow customers to specify $(CppWinRTVersion)
  change/react-native-windows-79f6563d-c38d-419d-b66a-00820b069c31.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
Labels: AutoMerge

#10821 [0.70] Allow customers to specify $(CppWinRTVersion)
  change/react-native-windows-79f6563d-c38d-419d-b66a-00820b069c31.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
Labels: AutoMerge

#10799 Align WinAppSDK template to not hardcode package versions
  change/@react-native-windows-cli-bb3dec8a-9e52-4cac-9001-e6d08adc2e33.json
  change/react-native-windows-00869e87-88ae-481d-ba9b-d6bd01cae748.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  vnext/PropertySheets/External/Microsoft.ReactNative.WinAppSDK.CSharp.PackageReferences.props
  vnext/PropertySheets/External/Microsoft.ReactNative.WinAppSDK.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props
  vnext/template/cpp-app/proj/MyApp.vcxproj
  vnext/template/cpp-lib/proj/MyLib.vcxproj
  vnext/template/cs-app-WinAppSDK/proj/MyApp.csproj
  vnext/template/cs-app/proj/MyApp.csproj
  vnext/template/cs-lib/proj/MyLib.csproj
Labels: Breaking Change, Area: Developer Experience, Area: Dependencies, Platform: WinAppSDK, Area: App Template

#10673 Prevent onKeyUp on Pressability.windows.js from firing onPress without preceding onKeyDown
  change/react-native-windows-8636e386-ed31-4e68-9121-348b6a5fe8ab.json
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
  vnext/src/Libraries/Pressability/Pressability.windows.js
Labels: Area: Keyboard, Area: Focus

#10691 Workaround for blur on XAML Islands
  change/react-native-windows-5069a4c1-e7cf-4629-ad97-03c11d35fe8a.json
  packages/playground/Samples/textinput.tsx
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
Labels: Area: View Managers, Area: Focus, Area: Islands

#10671 Adds LayoutService interface to allow native layout updates
  change/react-native-windows-701f2200-7c68-46ab-9af5-099e1ca8ba0f.json
  vnext/Microsoft.ReactNative/INativeUIManager.h
  vnext/Microsoft.ReactNative/LayoutService.cpp
  vnext/Microsoft.ReactNative/LayoutService.h
  vnext/Microsoft.ReactNative/LayoutService.idl
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
Labels: Area: Layout

#10797 Implement Form Data requests
  change/react-native-windows-002cdf98-9f28-4a37-ac6c-33789f8b36b1.json
  packages/@react-native-windows/tester/overrides.json
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExample.js
  packages/@react-native-windows/tester/src/js/examples/HTTP/HTTPExampleMultiPartFormData.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
  vnext/Microsoft.ReactNative/INativeUIManager.h
  vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp
  vnext/Microsoft.ReactNative/Modules/PaperUIManagerModule.cpp
  vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.cpp
  vnext/Microsoft.ReactNative/Views/ShadowNodeRegistry.h
  vnext/Shared/Networking/WinRTHttpResource.cpp
Labels: Area: Networking

#10844 [0.69] CG 11/7/22: Update `@xmldom/xmldom`
  change/@react-native-windows-cli-690eac2a-adb7-4a70-961a-8cf4e6930446.json
  change/@react-native-windows-telemetry-52e61840-c7f5-4b0e-9160-0fabee406aa4.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/telemetry/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10843 [0.70] CG 11/7/22: Update `@xmldom/xmldom`
  change/@react-native-windows-cli-8a99690d-57f4-46af-9e61-4f6c4bb95384.json
  change/@react-native-windows-telemetry-45cb351d-b880-40ef-8838-c884f8f6162b.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/telemetry/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10841 CG 11/7/22: Update `@xmldom/xmldom`
  change/@react-native-windows-cli-30efcfa1-a7c7-45e7-b9c2-186edfadad49.json
  change/@react-native-windows-telemetry-9dcd5adb-bcbf-4696-b9ab-aac6ed63515d.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/telemetry/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10845 [0.68] CG 11/7/22: Update `@xmldom/xmldom`
  change/@react-native-windows-cli-b0c55029-d039-44de-9750-a585afade9e5.json
  change/@react-native-windows-telemetry-81f9cac6-be82-4e0c-b7f6-5dd8c79a4f9f.json
  package.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/telemetry/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10847 [0.67] CG 11/7/22: Update `@xmldom/xmldom`
  change/@react-native-windows-cli-daf01106-67fe-4d28-8f61-17d4e4f6fd8d.json
  package.json
  packages/@react-native-windows/cli/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#10858 Suppress warning in test code when discarding a std::async object
  change/react-native-windows-374819da-ddb8-4457-9ef5-f136eb4f3829.json
  vnext/Mso.UnitTests/object/refCountedObjectTest.cpp
  vnext/Mso.UnitTests/object/unknownObjectTest.cpp
Labels: AutoMerge

#10856 Add Anti-Malware Scan to CI
  .ado/compliance.yml
  .ado/templates/run-compliance-prebuild.yml
Labels: AutoMerge, Area: Compliance

#9249 Adds Rendering driver option to NativeAnimated
  change/react-native-windows-bf20335c-eccd-487b-bbcf-9fcc46a3b849.json
  packages/@react-native-windows/tester/src/js/examples-win/NativeAnimation/CompositionBugsExample.js
  packages/@react-native-windows/tester/src/js/utils/RNTesterList.windows.js
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/Animated/AdditionAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/AdditionAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/AnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/AnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/AnimatedPlatformConfig.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/AnimatedPlatformConfig.h
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationDriver.h
  vnext/Microsoft.ReactNative/Modules/Animated/AnimationUtils.h
  vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/CalculatedAnimationDriver.h
  vnext/Microsoft.ReactNative/Modules/Animated/DecayAnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/DecayAnimationDriver.h
  vnext/Microsoft.ReactNative/Modules/Animated/DiffClampAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/DiffClampAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/DivisionAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/DivisionAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/FrameAnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/FrameAnimationDriver.h
  vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/InterpolationAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/ModulusAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/ModulusAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/MultiplicationAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/MultiplicationAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedModule.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/NativeAnimatedNodeManager.h
  vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/PropsAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/SpringAnimationDriver.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/SpringAnimationDriver.h
  vnext/Microsoft.ReactNative/Modules/Animated/StyleAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/StyleAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/SubtractionAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/SubtractionAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/TrackingAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/TrackingAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/TransformAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/TransformAnimatedNode.h
  vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.cpp
  vnext/Microsoft.ReactNative/Modules/Animated/ValueAnimatedNode.h
Labels: AutoMerge, Area: Animation

#10868 Update `rnw-dependencies.ps1` to improve messaging
  change/react-native-windows-bc1ccb33-c9d8-427a-9fe4-af8cbcd246a0.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Developer Experience, Area: Dependencies

#10848 Always instantiate Blob module in UWP
  change/react-native-windows-3ee0cf72-a448-421f-a738-e2aac37a7883.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp
  vnext/Shared/OInstance.cpp
  vnext/Shared/Shared.vcxitems
Labels: Area: Networking

#10830 Move remaining PackageReferences out of new project templates
  change/@react-native-windows-automation-channel-8593d564-691b-4a8b-81d6-f975a400ebbd.json
  change/@react-native-windows-cli-7f238513-7e90-403c-aa7a-cb0ef1ceb45d.json
  change/react-native-windows-46f1f845-8831-4846-9af6-90fedeb09a49.json
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/integration-test-app/windows/InteropTestModuleCS/InteropTestModuleCS.csproj
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
  packages/playground/CoreApp/CoreApp.vcxproj
  packages/playground/windows/playground-composition/Playground-Composition.vcxproj
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground/Playground.vcxproj
  packages/sample-apps/windows/SampleAppCPP/SampleAppCpp.vcxproj
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  packages/sample-apps/windows/SampleLibraryCPP/SampleLibraryCPP.vcxproj
  packages/sample-apps/windows/SampleLibraryCS/SampleLibraryCS.csproj
  vnext/Microsoft.ReactNative.Managed.IntegrationTests/Microsoft.ReactNative.Managed.IntegrationTests.csproj
  vnext/Microsoft.ReactNative.Managed.UnitTests/Microsoft.ReactNative.Managed.UnitTests.csproj
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
  vnext/PropertySheets/External/Microsoft.ReactNative.CSharp.Dependencies.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Common.props
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CSharpLib.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppApp.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.targets
Labels: Breaking Change, Area: App Template

#10881 Update to folly 2022.11.07
  change/@react-native-windows-virtualized-list-ee65ac06-b7a0-4d3f-ab30-125692090e9d.json
  change/react-native-windows-7dddf547-aeee-49ee-8b09-ad91a21dbaec.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Directory.Build.props
  vnext/Folly/Folly.vcxproj
  vnext/Folly/Folly.vcxproj.filters
  vnext/Folly/TEMP_UntilFollyUpdate/dynamic-inl.h
  vnext/Folly/TEMP_UntilFollyUpdate/lang/SafeAssert.h
  vnext/Folly/TEMP_UntilFollyUpdate/lang/ToAscii.cpp
Labels: AutoMerge

#10891 Align folly commit hash with folly version
  change/react-native-windows-d6678bf6-0866-4c10-95bb-05c3f23042b9.json
  vnext/Directory.Build.props
  vnext/Folly/cgmanifest.json
Labels: AutoMerge

#10885 Allow >10MB content for blob responses
  change/react-native-windows-cc7e46ad-44db-4623-937f-d2899c415dfa.json
  vnext/Shared/Networking/WinRTHttpResource.cpp
Labels: AutoMerge, Area: Networking

#10898 Fixes for Office usage of latest canary
  change/react-native-windows-810f7970-4604-4fe4-8b17-3bf02d9c14bb.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
  vnext/Scripts/OfficeReact.Win32.nuspec
  vnext/Scripts/Tfs/Layout-Desktop-Headers.ps1
Labels: Partner: Office

#10910 Fix copying patch files in Folly and Fmt projects
  change/react-native-windows-e435a388-efe0-4ff8-ade9-5ac10965c163.json
  vnext/Folly/Folly.vcxproj
  vnext/Folly/Folly.vcxproj.filters
  vnext/fmt/fmt.vcxproj
Labels: AutoMerge

#10922 Fix CLI to search for correct VS version range
  change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: Backport: Requested

#10923 [0.70] Fix CLI to search for correct VS version range
  change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: AutoMerge

#10924 [0.69] Fix CLI to search for correct VS version range
  change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: AutoMerge

#10926 [0.67] Fix CLI to search for correct VS version range
  change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: AutoMerge

#10921 Avoid template type shadowing for CntPtr
  change/react-native-windows-8b277652-e95c-43b7-9c81-00a11493947d.json
  vnext/Mso/smartPtr/cntPtr.h
Labels: AutoMerge

#10925 [0.68] Fix CLI to search for correct VS version range
  change/@react-native-windows-cli-8fb1e274-a5a2-4a7c-9dae-2ed655b8f87e.json
  packages/@react-native-windows/cli/src/runWindows/utils/vsInstalls.ts
Labels: AutoMerge

#10949 Use a ReactViewHost to specify view options on CompositionRootView
  change/react-native-windows-e1f270c5-39a5-4d8a-8f95-8a311727dca2.json
  packages/playground/windows/playground-composition/Playground-Composition.cpp
  vnext/Microsoft.ReactNative/CompositionHwndHost.idl
  vnext/Microsoft.ReactNative/CompositionRootView.idl
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
  vnext/Microsoft.ReactNative/Modules/LogBoxModule.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.h
  vnext/Microsoft.ReactNative/ReactCoreInjection.idl
Labels: Area: Fabric
