Repository microsoft/react-native-windows, pull requests merged in 2023-07, with the labels that each got.

#11855 CG: Move to single nuget source
  NuGet.Config
  change/react-native-windows-bfb79e47-04d8-4f4e-a72f-26b1621873d2.json
  vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
Labels: Area: Infrastructure, Area: Compliance

#11849 Add REACT_MODULE_NOREG which is REACT_MODULE but without auto registration
  change/react-native-windows-ccec3086-548e-40b6-a95d-41c1ca26caff.json
  vnext/Microsoft.ReactNative.Cxx.UnitTests/NativeModuleTest.cpp
  vnext/Microsoft.ReactNative.Cxx/ModuleRegistration.h
  vnext/Microsoft.ReactNative.Cxx/NativeModules.h
  vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp
Labels: Needs: Author Feedback

#11873 [0.71] Update policheck database
  .ado/config/PoliCheckExclusions.xml
  .ado/config/PoliCheckRules.mdb
Labels: Area: Compliance

#11884 [0.69] Component Governance for 7/11/23
  package.json
  yarn.lock
Labels: security, Area: Compliance

#11902 Use correct data types in FileReaderTurboModule::ReadAs*
  change/react-native-windows-ea809b99-bf6d-4902-9c4f-5b35c6a7996f.json
  vnext/Shared/Modules/FileReaderModule.cpp
Labels: Area: Networking

#11883 [0.70] Component Governance for 7/11/23
  package.json
  yarn.lock
Labels: security, Area: Compliance

#11875 [0.72] Component Governance for 7/11/23
  yarn.lock
Labels: security, Area: Compliance

#11877 [0.71] Component Governance for 7/11/23
  package.json
  yarn.lock
Labels: security, Area: Compliance

#11906 [Fabric] Add colored emojis to TextInput and Text
  change/react-native-windows-94dfd5a6-f3d9-472b-b3f9-a1d25de3296b.json
  vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
Labels: Area: Text, Area: Fabric

#11926 Attempt AddNetworkingHandler if HTTP module was not ready
  change/react-native-windows-1c549950-1146-4bb2-b48f-ed2c578f8237.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Microsoft.ReactNative.Managed.IntegrationTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed.UnitTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Shared/Modules/HttpModule.cpp
  vnext/Shared/Modules/HttpModule.h
  vnext/Shared/Networking/DefaultBlobResource.cpp
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/OInstance.cpp
Labels: Area: Networking

#11933 Remove upstream react-native flow typings from repo
  change/@office-iss-react-native-win32-ca94c499-0aa3-4bc9-b3da-2fb57957ce91.json
  change/@rnw-scripts-just-task-bbb6b96a-e60b-4f64-9321-59ddd61d874f.json
  change/react-native-platform-override-969e76a0-7cbf-42e7-a8b3-4bd1b8edc8a8.json
  change/react-native-windows-0f8884ee-fe5b-4a6c-a5f3-87fae008c534.json
  packages/@office-iss/react-native-win32/.flowconfig
  packages/@office-iss/react-native-win32/flow-typed/npm/ansi-regex_v5.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/base64-js_v1.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/glob_v7.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/pretty-format_v26.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/promise_v8.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/react-dom_v17.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/react-test-renderer_v16.x.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/stacktrace-parser_v0.1.x.js
  packages/@office-iss/react-native-win32/flow-typed/npm/yargs_v17.x.x.js
  packages/@office-iss/react-native-win32/just-task.js
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/package.json
  packages/@rnw-scripts/just-task/.eslintrc.js
  packages/@rnw-scripts/just-task/cli.js
  packages/@rnw-scripts/just-task/copyRNLibraries.js
  packages/@rnw-scripts/just-task/flow-tasks.js
  packages/@rnw-scripts/just-task/just-task.js
  packages/@rnw-scripts/just-task/package.json
  packages/@rnw-scripts/just-task/react-native-tasks.js
  packages/react-native-platform-override/src/refFromVersion.ts
  vnext/.flowconfig
  vnext/flow-typed/npm/ansi-regex_v5.x.x.js
  vnext/flow-typed/npm/base64-js_v1.x.x.js
  vnext/flow-typed/npm/glob_v7.x.x.js
  vnext/flow-typed/npm/pretty-format_v26.x.x.js
  vnext/flow-typed/npm/promise_v8.x.x.js
  vnext/flow-typed/npm/react-dom_v17.x.x.js
  vnext/flow-typed/npm/react-test-renderer_v16.x.x.js
  vnext/flow-typed/npm/stacktrace-parser_v0.1.x.js
  vnext/flow-typed/npm/yargs_v17.x.x.js
  vnext/just-task.js
  vnext/overrides.json
  vnext/package.json
Labels: Area: Build Infrastructure, Area: Compliance

#11940 fix AT crash on boot/load of Playground
  change/react-native-windows-f44ed64d-339c-49ab-92ae-1bd6d81fe2d3.json
  packages/playground/windows/playground-composition/Playground-Composition.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
Labels: Area: Accessibility, Area: Fabric

#11792 Fix accessibilityState to support states not being set
  change/@react-native-windows-automation-commands-bd4c0b18-0390-4f53-b491-1c7671344cd2.json
  change/react-native-windows-d269038a-a1db-4d00-a62c-ff552f06c42f.json
  package.json
  packages/@react-native-windows/automation-commands/src/dumpVisualTree.ts
  packages/e2e-test-app/test/__snapshots__/ButtonComponentTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/FlyoutComponentTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/LegacyControlStyleTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/LegacyImageTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/PopupComponentTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/PressableComponentTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/ScrollViewComponentTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/SwitchComponentTest.test.ts.snap
  packages/e2e-test-app/test/__snapshots__/ViewComponentTest.test.ts.snap
  packages/e2e-test-app/windows/RNTesterApp/MainPage.xaml.cs
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.cpp
  vnext/Microsoft.ReactNative/Views/DynamicAutomationPeer.h
  vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.cpp
  vnext/Microsoft.ReactNative/Views/DynamicAutomationProperties.h
  vnext/Microsoft.ReactNative/Views/FrameworkElementTransferProperties.cpp
  vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp
  vnext/Microsoft.ReactNative/Views/cppwinrt/DynamicAutomationPeer.idl
  yarn.lock
Labels: Area: Accessibility, Breaking Change

#11953 Enable using newer CppWinRT versions that use WINRT_IMPL_LoadLibraryExW
  change/react-native-windows-a293bfbd-cd92-48c4-8758-bcff78656d4a.json
  vnext/Microsoft.ReactNative.Cxx/CppWinRTIncludes.h
  vnext/PropertySheets/External/Microsoft.ReactNative.Cpp.Dependencies.props
Labels: Area: Build Infrastructure
