Repository microsoft/react-native-windows, pull requests merged in 2023-02, with the labels that each got.

#11033 Fix Hermes sampling profiler
  change/@react-native-windows-telemetry-778ea18a-3b80-476b-92e7-d46058128073.json
  change/react-native-windows-af5ee70c-4767-4145-82a9-61331fa11ab8.json
  packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/packages.config
  packages/playground/windows/playground-composition/packages.config
  packages/playground/windows/playground-win32/packages.config
  packages/playground/windows/playground/packages.config
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/HermesRuntimeHolder.cpp
  vnext/Shared/HermesRuntimeHolder.h
  vnext/Shared/HermesSamplingProfiler.cpp
  vnext/Shared/HermesSamplingProfiler.h
  vnext/Shared/HermesShim.cpp
  vnext/Shared/HermesShim.h
  vnext/Shared/JSI/RuntimeHolder.h
Labels: AutoMerge

#11186 Allow disabling static graph restore under VS
  change/react-native-windows-48ba39dc-ea15-4e83-b76e-80afc2f808ef.json
  vnext/Directory.Build.props
  vnext/PropertySheets/NuGet.Cpp.props
Labels: PackageReference

#11204 [Fabric] Add initial implementation for Switch
  change/react-native-windows-30c9bb46-8ce0-4b9d-a42f-64a7b138a63b.json
  vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/Color.cpp
  vnext/Microsoft.ReactNative/Fabric/platform/react/renderer/graphics/platform/cxx/react/renderer/graphics/Color.h
  vnext/Shared/Shared.vcxitems
Labels: AutoMerge

#11199 [0.71] Allow disabling static graph restore under VS
  change/react-native-windows-566e71d3-0d9f-403d-9817-c2c8f9e4cab7.json
  vnext/Directory.Build.props
  vnext/PropertySheets/NuGet.Cpp.props
Labels: Backport: Requested

#11200 [0.70] Allow disabling static graph restore under VS
  change/react-native-windows-4c5246df-32eb-43c7-98bb-cb5f656b671c.json
  vnext/Directory.Build.props
  vnext/PropertySheets/NuGet.Cpp.props
Labels: Backport: Requested

#11201 [0.69] Allow disabling static graph restore under VS
  change/react-native-windows-c6a14e9f-726b-48c7-b6a0-9962e8f8a8fa.json
  vnext/Directory.Build.props
  vnext/PropertySheets/NuGet.Cpp.props
Labels: Backport: Requested

#11202 [0.68] Allow disabling static graph restore under VS
  change/react-native-windows-8103806d-4bb2-410b-8069-41763615cb43.json
  vnext/Directory.Build.props
  vnext/PropertySheets/NuGet.Cpp.props
Labels: Backport: Requested

#11203 [0.69] Fix Hermes sampling profiler (#11033)
  change/@react-native-windows-telemetry-a883e2fb-184e-4a5c-8e6a-c893f19aab47.json
  change/react-native-windows-161cd4d0-000f-40c3-8a37-f0260ef756d7.json
  packages/@react-native-windows/telemetry/src/test/projects/UsesPackagesConfig/packages.config
  packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityInfoExample.js
  packages/e2e-test-app/windows/RNTesterApp/RNTesterApp.csproj
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/playground/windows/playground-win32/Playground-win32.vcxproj
  packages/playground/windows/playground/packages.config
  packages/sample-apps/windows/SampleAppCS/SampleAppCS.csproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/IReactDispatcher.cpp
  vnext/Microsoft.ReactNative/IReactDispatcher.h
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/Utils/Helpers.h
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
  vnext/PropertySheets/JSEngine.props
  vnext/Shared/HermesRuntimeHolder.cpp
  vnext/Shared/HermesRuntimeHolder.h
  vnext/Shared/HermesSamplingProfiler.cpp
  vnext/Shared/HermesSamplingProfiler.h
  vnext/Shared/HermesShim.cpp
  vnext/Shared/HermesShim.h
  vnext/Shared/JSI/RuntimeHolder.h
  vnext/Shared/Networking/IWebSocketResource.h
Labels: AutoMerge

#11236 [Fabric] Fix debug menu crash when not using Xaml
  change/react-native-windows-3e9d5740-8654-448c-9431-3b681c4de19d.json
  packages/playground/windows/playground-composition/Playground-Composition.cpp
  vnext/Microsoft.ReactNative/CompositionUIService.idl
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionUIService.h
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj.filters
  vnext/Microsoft.ReactNative/Modules/AlertModule.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.cpp
  vnext/Microsoft.ReactNative/ReactCoreInjection.h
  vnext/Microsoft.ReactNative/ReactCoreInjection.idl
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/Microsoft.ReactNative/RedBox.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.cpp
  vnext/Microsoft.ReactNative/Views/DevMenu.h
  vnext/Shared/HermesSamplingProfiler.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: Area: Fabric

#11241 Fix PR builds failing due to new version of @react-native/codegen
  change/@react-native-windows-codegen-58b6b062-ece9-4cb5-8396-f7a20afe1286.json
  change/react-native-windows-02af65fd-d5ef-4372-9efe-fa056afd4070.json
  packages/@react-native-windows/codegen/package.json
  packages/@react-native-windows/codegen/src/generators/AliasGen.ts
  packages/@react-native-windows/codegen/src/generators/AliasManaging.ts
  packages/@react-native-windows/codegen/src/generators/GenerateNM2.ts
  packages/@react-native-windows/codegen/src/generators/GenerateTypeScript.ts
  packages/@react-native-windows/codegen/src/generators/ObjectTypes.ts
  packages/@react-native-windows/codegen/src/generators/ParamTypes.ts
  packages/@react-native-windows/codegen/src/generators/ReturnTypes.ts
  packages/@react-native-windows/codegen/src/generators/ValidateConstants.ts
  packages/@react-native-windows/codegen/src/generators/ValidateMethods.ts
  packages/@react-native-windows/codegen/src/index.ts
  vnext/.gitignore
  vnext/Microsoft.ReactNative.IntegrationTests/codegen/msrnIntegrationTestsJSI.h
  vnext/codegen/NativePermissionsAndroidSpec.g.h
  vnext/codegen/react/components/rnwcore/EventEmitters.cpp
  vnext/codegen/rnwcoreJSI.h
  vnext/overrides.json
  vnext/src/babel-plugin-codegen/GenerateViewConfigJs.js
  vnext/src/babel-plugin-codegen/index.js
  vnext/src/babel-plugin-codegen/package.json
  yarn.lock
Labels: AutoMerge

#11233 [Fabric] Keyboard focus loop
  change/react-native-windows-6e424ae1-f721-4aea-ab51-faba2ae3a2d6.json
  vnext/Microsoft.ReactNative/CompositionHwndHost.idl
  vnext/Microsoft.ReactNative/CompositionRootView.idl
  vnext/Microsoft.ReactNative/Fabric/ComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/ImageComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/ParagraphComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/RootComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/TextInput/WindowsTextInputComponentView.h
  vnext/Microsoft.ReactNative/Fabric/platform/react/components/view/ViewProps.h
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.cpp
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewProps.h
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/components/view/ViewShadowNode.cpp
  vnext/Shared/Shared.vcxitems
  vnext/overrides.json
Labels: Area: Fabric

#11292 Update Sign phase to do prepare-js-env instead of only yarn install
  .ado/publish.yml
Labels: AutoMerge

#11269 fix: move typescript-eslint to devDependencies
  change/@react-native-windows-cli-d15e4dfa-8637-4d54-b010-64d28d610515.json
  change/@react-native-windows-codegen-5753d909-a4f1-4a72-a2e0-9409293bfab6.json
  change/@react-native-windows-find-repo-root-149e990d-a5af-41fa-89fa-190c85890f02.json
  change/@react-native-windows-fs-7dd519e2-cbc4-462f-b4bd-c983bfb0b12f.json
  change/@react-native-windows-package-utils-81b0a826-9067-45d7-b018-3a4d42a55a86.json
  change/@react-native-windows-telemetry-f77d118a-38f8-4064-a2d9-4c51a378ed42.json
  packages/@react-native-windows/cli/package.json
  packages/@react-native-windows/codegen/package.json
  packages/@react-native-windows/find-repo-root/package.json
  packages/@react-native-windows/fs/package.json
  packages/@react-native-windows/package-utils/package.json
  packages/@react-native-windows/telemetry/package.json
Labels: AutoMerge, Backport: Requested

#11308 Remove an unneeded force include from yoga/utils.cpp
  change/react-native-windows-6c7cee5f-4e4d-4054-8e32-718e45346198.json
  vnext/ReactCommon/ReactCommon.vcxproj
Labels: AutoMerge
