Repository microsoft/react-native-windows, pull requests merged in 2023-11, with the labels that each got.

#12324 C++ 20: Preprocessor definitions
  change/react-native-windows-c64047dc-de68-4470-93bb-27e900f3696c.json
  vnext/Desktop.DLL/React.Windows.Desktop.DLL.vcxproj
  vnext/Desktop.IntegrationTests/React.Windows.Desktop.IntegrationTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Folly/Folly.vcxproj
  vnext/FollyWin32/FollyWin32.vcxproj
  vnext/IntegrationTests/React.Windows.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative.ComponentTests/Microsoft.ReactNative.ComponentTests.vcxproj
  vnext/Microsoft.ReactNative.IntegrationTests/Microsoft.ReactNative.IntegrationTests.vcxproj
  vnext/Microsoft.ReactNative/Microsoft.ReactNative.vcxproj
  vnext/PropertySheets/ReactCommunity.cpp.props
  vnext/ReactCommon/ReactCommon.vcxproj
Labels: AutoMerge

#12325 C++ 20: Switch AutomationChannel and IntegrationTest to /std:C++20
  change/@react-native-windows-automation-channel-b40845ff-ac08-4250-bba7-6f0d4378f435.json
  change/react-native-windows-d93b5adf-a8b2-4ceb-89f1-aeedd9546d76.json
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/AutomationChannel.vcxproj
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/CppWinrtLessExceptions.h
  packages/integration-test-app/windows/integrationtest/TestHostHarness.h
  packages/integration-test-app/windows/integrationtest/integrationtest.vcxproj
Labels: AutoMerge

#12355 Cherry pick PRs #12143 #12211
  change/react-native-windows-5d484961-48b1-4a0c-b38f-813f9587a87c.json
  vnext/Desktop.ABITests/packages.lock.json
  vnext/Desktop.DLL/packages.lock.json
  vnext/Desktop.IntegrationTests/packages.lock.json
  vnext/Desktop.UnitTests/packages.lock.json
  vnext/Desktop/packages.lock.json
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/PropertySheets/JSEngine.props
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/packages.lock.json
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/uimanager/UIManagerBinding.cpp
  vnext/Shared/HermesRuntimeHolder.cpp
  vnext/Shared/JSI/V8RuntimeHolder.cpp
  vnext/Shared/OInstance.cpp
  vnext/Shared/SafeLoadLibrary.cpp
  vnext/Shared/SafeLoadLibrary.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#12354 [0.73] Cherry pick PRs #12143 #12211
  .ado/jobs/linting.yml
  change/react-native-windows-948c4c23-83ed-474f-9940-28edf5a5c120.json
  vnext/Desktop.ABITests/packages.lock.json
  vnext/Desktop.DLL/packages.lock.json
  vnext/Desktop.IntegrationTests/packages.lock.json
  vnext/Desktop.UnitTests/packages.lock.json
  vnext/Desktop/packages.lock.json
  vnext/Microsoft.ReactNative.Cxx/Microsoft.ReactNative.Cxx.vcxitems
  vnext/Microsoft.ReactNative/ReactHost/React.h
  vnext/Microsoft.ReactNative/ReactHost/ReactHost.cpp
  vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp
  vnext/PropertySheets/JSEngine.props
  vnext/PropertySheets/React.Cpp.props
  vnext/ReactCommon.UnitTests/packages.lock.json
  vnext/ReactCommon/ReactCommon.vcxproj
  vnext/ReactCommon/TEMP_UntilReactCommonUpdate/react/renderer/uimanager/UIManagerBinding.cpp
  vnext/Shared/HermesRuntimeHolder.cpp
  vnext/Shared/JSI/V8RuntimeHolder.cpp
  vnext/Shared/OInstance.cpp
  vnext/Shared/SafeLoadLibrary.cpp
  vnext/Shared/SafeLoadLibrary.h
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
  vnext/Shared/V8JSIRuntimeHolder.cpp
  vnext/Shared/V8JSIRuntimeHolder.h
Labels: AutoMerge

#12070 Switch from using choco to winget in rnw-dep script
  change/react-native-windows-2cdbaeab-1256-4249-8524-7e705d8ef750.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Dependencies

#8969 Adds option to allow ViewManagers to capture pointer
  change/react-native-windows-1fca69d4-5eb2-4787-91ff-91a19b4fbad9.json
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.cpp
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.h
  vnext/Microsoft.ReactNative/ReactPointerEventArgs.idl
  vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp
Labels: Area: Pointer

#12321 Make Hermes the default JS engine
  .ado/jobs/cli-init.yml
  .ado/jobs/e2e-test.yml
  .ado/jobs/integration-test.yml
  .ado/templates/react-native-init.yml
  change/@react-native-windows-cli-b478dee5-f5a0-4257-96b1-c3cd1ce241f0.json
  change/react-native-windows-199ec877-3e4a-4205-bdf0-60a698957050.json
  packages/@react-native-windows/cli/src/commands/config/configUtils.ts
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/e2e-test-app/windows/ExperimentalFeatures.props
  packages/integration-test-app/windows/ExperimentalFeatures.props
  vnext/Microsoft.ReactNative.IntegrationTests/JsiSimpleTurboModuleTests.js
  vnext/Microsoft.ReactNative.IntegrationTests/JsiTurboModuleTests.js
  vnext/Microsoft.ReactNative.IntegrationTests/TestBundle.targets
  vnext/PropertySheets/External/Microsoft.ReactNative.Composition.Common.props
  vnext/PropertySheets/JSEngine.props
  vnext/metro.config.js
  vnext/templates/cpp-app/windows/ExperimentalFeatures.props
  vnext/templates/old/generateWrapper.js
  vnext/templates/old/uwp-cpp-lib/template.config.js
Labels: Area: JavaScript Engine

#12374 Fabric: Add windows script to new cpp-app template
  change/react-native-windows-aeaa392d-12c1-43af-8980-02dfd8e6d4f3.json
  vnext/templates/cpp-app/template.config.js
  vnext/templates/templateUtils.js
Labels: Area: Fabric

#12378 Untrack HTTP responses when processed by IResponseHandler
  change/react-native-windows-766f6cc5-f66b-4147-9bd6-bcf8c9897469.json
  vnext/Shared/Networking/WinRTHttpResource.cpp
  vnext/Shared/Shared.vcxitems.filters
Labels: Area: Networking, Backport: Requested

#12388 [0.72] Release long lived JSI objects ASAP
  change/react-native-windows-86ce2be3-b89f-4ddb-9476-45f3d6c9cd21.json
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#12396 A couple of fixes for running Fabric applications without using ContentIslands
  change/react-native-windows-c11014d1-49bc-4bcd-9535-3f0e07fde677.json
  packages/e2e-test-app-fabric/test/ButtonComponentTest.test.ts
  packages/e2e-test-app-fabric/test/__snapshots__/ButtonComponentTest.test.ts.snap
  packages/playground/windows/playground-composition/Playground-Composition.cpp
  vnext/Microsoft.ReactNative/CompositionRootView.idl
  vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/Composition.Input.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionEventHandler.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionHwndHost.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionRootView_emptyimpl.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/Theme.cpp
Labels: Area: Tests, Area: Fabric

#12387 [0.73] Release long lived JSI objects ASAP
  change/react-native-windows-c2347d19-8010-4196-9179-d7b615481b93.json
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#12405 Change Hermes package version to 0.1.18
  change/@react-native-windows-automation-channel-bae850aa-ef41-4bd0-840b-314b20a2b40a.json
  change/react-native-windows-2fcbda0d-58f8-4b42-af03-b5226ab939d2.json
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
  packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/packages.lock.json
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
  packages/integration-test-app/windows/integrationtest/packages.lock.json
  packages/playground/CoreApp/packages.lock.json
  packages/playground/windows/PlaygroundNativeModules/packages.lock.json
  packages/playground/windows/playground-composition/packages.lock.json
  packages/playground/windows/playground-win32/packages.lock.json
  packages/playground/windows/playground/packages.lock.json
  packages/sample-apps/windows/SampleAppCPP/packages.lock.json
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  packages/sample-apps/windows/SampleLibraryCPP/packages.lock.json
  packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
  vnext/Desktop.ABITests/packages.lock.json
  vnext/Desktop.DLL/packages.lock.json
  vnext/Desktop.IntegrationTests/packages.lock.json
  vnext/Desktop.UnitTests/packages.lock.json
  vnext/Desktop/packages.lock.json
  vnext/Microsoft.ReactNative.IntegrationTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/packages.lock.json
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.lock.json
Labels: AutoMerge

#12412 [0.72] Update fmt to 10.1.0
  change/react-native-windows-f6ce9779-80b8-4939-b78b-f28dfa7b0e8c.json
  vnext/Directory.Build.props
  vnext/fmt/cgmanifest.json
Labels: AutoMerge

#12416 [0.72] Change Hermes package version to 0.1.18
  change/react-native-windows-0d50f26a-8d3c-41c4-9796-c73e077e35f4.json
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  vnext/PropertySheets/JSEngine.props
Labels: AutoMerge

#12386 [0.68] Fix Secure Supply Chain compliance issues
  .gitignore
  GuardianCustomConfiguration.json
  NuGet.Config
  change/@react-native-windows-cli-81517eff-3586-4693-8d07-0ff6bd9710b0.json
  change/react-native-windows-14a87dda-f285-4cd4-8a0f-b5aa9543cb9f.json
  change/react-native-windows-74880bf0-e7b0-4668-9148-3c7fbf28d4a9.json
  packages/@react-native-windows/cli/src/generator-windows/index.ts
  packages/e2e-test-app/.npmrc
  packages/e2e-test-app/windows/NuGet.Config
  packages/integration-test-app/windows/NuGet.Config
  packages/playground/windows/NuGet.Config
  packages/sample-apps/.npmrc
  packages/sample-apps/windows/NuGet.Config
  vnext/.npmrc
  vnext/NuGet.Config
  vnext/template/shared-app/proj/NuGet_Config
  vnext/template/shared-lib/proj/NuGet_Config
Labels: Area: Compliance

#12376 Fabric: Enable react-test-renderer tests in the new cpp-app template
  .ado/templates/react-native-init-windows.yml
  change/react-native-windows-20088f72-5201-4d7b-96c9-2b522fed786b.json
  vnext/templates/cpp-app/jest.config.windows.js
  vnext/templates/cpp-app/template.config.js
  vnext/templates/templateUtils.js
Labels: Area: Developer Experience, Area: App Template

#12417 Ensure both property and value exist for Blob's HTTP proxy
  change/react-native-windows-e6a650eb-7ab8-4cf5-b094-4b685648e01a.json
  vnext/Shared/Networking/DefaultBlobResource.cpp
Labels: Area: Networking, Backport: Requested

#12415 [0.73] Change Hermes package version to 0.1.18
  change/react-native-windows-e9e06367-1f4f-4220-883d-fe87a724ef13.json
  packages/@react-native-windows/automation-channel/windows/AutomationChannel/packages.lock.json
  packages/e2e-test-app-fabric/windows/RNTesterApp-Fabric/packages.lock.json
  packages/e2e-test-app/windows/RNTesterApp/packages.lock.json
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
  packages/integration-test-app/windows/integrationtest/packages.lock.json
  packages/playground/CoreApp/packages.lock.json
  packages/playground/windows/PlaygroundNativeModules/packages.lock.json
  packages/playground/windows/playground-composition/packages.lock.json
  packages/playground/windows/playground-win32/packages.lock.json
  packages/playground/windows/playground/packages.lock.json
  packages/sample-apps/windows/SampleAppCPP/packages.lock.json
  packages/sample-apps/windows/SampleAppCS/packages.lock.json
  packages/sample-apps/windows/SampleLibraryCPP/packages.lock.json
  packages/sample-apps/windows/SampleLibraryCS/packages.lock.json
  vnext/Desktop.ABITests/packages.lock.json
  vnext/Desktop.DLL/packages.lock.json
  vnext/Desktop.IntegrationTests/packages.lock.json
  vnext/Desktop.UnitTests/packages.lock.json
  vnext/Desktop/packages.lock.json
  vnext/Microsoft.ReactNative.IntegrationTests/packages.lock.json
  vnext/Microsoft.ReactNative.Managed/packages.lock.json
  vnext/Microsoft.ReactNative/packages.lock.json
  vnext/PropertySheets/JSEngine.props
  vnext/ReactCommon.UnitTests/packages.lock.json
Labels: AutoMerge

#12385 Release long lived JSI objects ASAP
  change/react-native-windows-a2b5faff-fe2c-41f9-b341-3c02d3b4c12b.json
  vnext/Microsoft.ReactNative/JSDispatcherWriter.cpp
  vnext/Microsoft.ReactNative/JSDispatcherWriter.h
  vnext/Microsoft.ReactNative/TurboModulesProvider.cpp
Labels: AutoMerge

#12342 [0.72] Call exceptions manager even in DEV bundles
  change/@office-iss-react-native-win32-108790fb-da57-49ce-a33a-cdd1c01607c8.json
  packages/@office-iss/react-native-win32/overrides.json
  packages/@office-iss/react-native-win32/src/Libraries/Core/ExceptionsManager.win32.js
Labels: Platform: NetUI
