Repository microsoft/react-native-windows, pull requests merged in 2023-05, with the labels that each got.

#11537 Adds simple animated fabric activityIndicator
  change/react-native-windows-3e148754-c37f-47ca-ba18-1dc6bbbd3865.json
  vnext/Microsoft.ReactNative/CompositionSwitcher.idl
  vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/ActivityIndicatorComponentView.h
  vnext/Microsoft.ReactNative/Fabric/Composition/ComponentViewRegistry.cpp
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionContextHelper.cpp
  vnext/Microsoft.ReactNative/Fabric/WindowsComponentDescriptorRegistry.cpp
  vnext/Shared/Shared.vcxitems
  vnext/Shared/Shared.vcxitems.filters
Labels: Area: Fabric

#11548 Fix Secure Supply Chain compliance issues
  .gitignore
  NuGet.Config
  change/react-native-windows-14a87dda-f285-4cd4-8a0f-b5aa9543cb9f.json
  packages/e2e-test-app-fabric/.npmrc
  packages/e2e-test-app/.npmrc
  packages/e2e-test-app/windows/NuGet.Config
  packages/integration-test-app/windows/NuGet.Config
  packages/playground/windows/NuGet.Config
  packages/sample-apps/.npmrc
  packages/sample-apps/windows/NuGet.Config
  vnext/.npmrc
  vnext/Desktop.ABITests/NuGet.Config
  vnext/Desktop.DLL/NuGet.Config
  vnext/Desktop.IntegrationTests/NuGet.Config
  vnext/Desktop.UnitTests/NuGet.Config
  vnext/Desktop/NuGet.Config
  vnext/NuGet.Config
  vnext/ReactCommon.UnitTests/NuGet.Config
Labels: Area: Compliance

#11561 Fix issue with mixed border widths on Fabric
  change/react-native-windows-1d22a163-fe34-4bb8-84cd-16ca4ee138cb.json
  vnext/Microsoft.ReactNative/Fabric/Composition/CompositionViewComponentView.cpp
Labels: AutoMerge, Area: Borders and Brushes, Area: Fabric

#11567 Improve Chocolatey detection in rnw-dependencies.ps1
  change/react-native-windows-0d31a01f-9831-4a2f-9b72-e5eeec31c183.json
  vnext/Scripts/rnw-dependencies.ps1
Labels: Area: Dependencies

#11575 Component Governance Updates 5/8/23
  change/@rnw-scripts-doxysaurus-7a64cc60-7a5b-4c0b-8b9e-53447f0f76e8.json
  package.json
  packages/@rnw-scripts/doxysaurus/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11581 [0.72] Component Governance 5/8/23
  package.json
  packages/@rnw-scripts/doxysaurus/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11582 [0.71] Component Governance 5/8/23
  package.json
  packages/@rnw-scripts/doxysaurus/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11583 [0.70] Component Governance 5/8/23
  package.json
  packages/@rnw-scripts/doxysaurus/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11584 [0.69] Component Governance 5/8/23
  package.json
  packages/@rnw-scripts/doxysaurus/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11585 [0.68] Component Governance 5/8/23
  package.json
  packages/@rnw-scripts/doxysaurus/package.json
  yarn.lock
Labels: AutoMerge, security, Area: Compliance

#11586 Fix flaky DoubleClickWhenSelectable E2E test
  packages/e2e-test-app/test/LegacySelectableTextTest.test.ts
Labels: Area: Tests

#11596 Fix integration test failures in Debug
  packages/integration-test-app/tests/MountComponentTests.tsx
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
Labels: AutoMerge, Area: Test Infrastructure, Area: Build Infrastructure, Area: Slider, Backport: Requested

#11602 [0.71] Fix flaky DoubleClickWhenSelectable E2E test
  packages/e2e-test-app/test/LegacySelectableTextTest.test.ts
Labels: AutoMerge

#11600 [0.72] Fix flaky DoubleClickWhenSelectable E2E test
  packages/e2e-test-app/test/LegacySelectableTextTest.test.ts
Labels: AutoMerge

#11608 Implement ScrollView props() Function on Fabric
  change/react-native-windows-1187ae94-06f0-4d36-bb52-87f96b11cdd7.json
  vnext/Microsoft.ReactNative/Fabric/Composition/ScrollViewComponentView.cpp
Labels: Area: Accessibility, Area: ScrollView, Area: Fabric

#11597 [0.72] Fix integration test failures in Debug
  packages/integration-test-app/windows/InteropTestModuleCS/packages.lock.json
Labels: AutoMerge, Area: Tests, Area: Test Infrastructure, Area: Build Infrastructure, Area: Slider

#11643 Allow apps to provide accessiblity information on non-focusable components
  change/react-native-windows-3ef19692-9e5c-436c-8efe-c0555e8cfd84.json
  vnext/Microsoft.ReactNative/Views/ControlViewManager.cpp
  vnext/Microsoft.ReactNative/Views/ViewViewManager.cpp
  vnext/src/Libraries/Components/TextInput/TextInput.windows.js
  vnext/src/Libraries/Components/View/View.windows.js
Labels: Backport: Requested

#11653 [Win32] Export yoga gap function
  change/react-native-windows-73fc6145-5b3c-4a35-af6f-c4efb5e8dcf0.json
  vnext/Desktop.DLL/react-native-win32.x64.def
  vnext/Desktop.DLL/react-native-win32.x86.def
Labels: Platform: NetUI

#11658 Update Guardian tasks to v2
  .ado/templates/run-compliance-prebuild.yml
Labels: Area: Compliance

#11517 Remove unused Beast-dependent code
  change/react-native-windows-a4cce52c-4f2a-4843-9e24-c6b6917f8b44.json
  vnext/Desktop.IntegrationTests/RNTesterIntegrationTests.cpp
  vnext/Desktop.UnitTests/BaseWebSocketTests.cpp
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj
  vnext/Desktop.UnitTests/React.Windows.Desktop.UnitTests.vcxproj.filters
  vnext/Desktop/BeastWebSocketResource.cpp
  vnext/Desktop/BeastWebSocketResource.h
  vnext/Desktop/React.Windows.Desktop.vcxproj
  vnext/Desktop/React.Windows.Desktop.vcxproj.filters
  vnext/Desktop/WebSocketResourceFactory.cpp
  vnext/PropertySheets/React.Cpp.props
Labels: AutoMerge

#11659 Fix os.arch for x86/arm64
  change/@react-native-windows-cli-e0d0ac4b-9d62-43e2-bcd9-1169b0c8c681.json
  packages/@react-native-windows/cli/src/runWindows/runWindowsOptions.ts
Labels: Area: CLI, Area: Dependencies
