Repository microsoft/react-native-windows, pull requests merged in 2024-04, with the labels that each got.

#12900 Add builds and nugets for MS.RN Fabric
  .ado/jobs/desktop.yml
  .ado/jobs/universal.yml
  .ado/publish.yml
  change/react-native-windows-2054f9f3-4bfb-45c2-8c07-b7ac052b1922.json
  vnext/Microsoft.ReactNative.CppOnly.slnf
  vnext/Microsoft.ReactNative.Managed/Microsoft.ReactNative.Managed.csproj
Labels: Area: Fabric, Area: Build Infrastructure, New Architecture

#12902 Package Playground Composition
  change/react-native-windows-2bd0d917-fc69-41b9-bf3f-ba32bb117fc6.json
  packages/playground/README_composition.md
  packages/playground/windows/.gitignore
  packages/playground/windows/playground-composition.Package/Images/LockScreenLogo.scale-200.png
  packages/playground/windows/playground-composition.Package/Images/SplashScreen.scale-200.png
  packages/playground/windows/playground-composition.Package/Images/Square150x150Logo.scale-200.png
  packages/playground/windows/playground-composition.Package/Images/Square44x44Logo.scale-200.png
  packages/playground/windows/playground-composition.Package/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  packages/playground/windows/playground-composition.Package/Images/StoreLogo.png
  packages/playground/windows/playground-composition.Package/Images/Wide310x150Logo.scale-200.png
  packages/playground/windows/playground-composition.Package/Package.appxmanifest
  packages/playground/windows/playground-composition.Package/packages.lock.json
  packages/playground/windows/playground-composition.Package/playground-composition.Package.wapproj
  packages/playground/windows/playground-composition.sln
  packages/playground/windows/playground-composition/.gitignore
  packages/playground/windows/playground-composition/Playground-Composition.vcxproj
  packages/playground/windows/playground-composition/packages.lock.json
  vnext/Microsoft.ReactNative.Cxx/DesktopWindowBridge.h
  vnext/Microsoft.ReactNative/packages.lock.json
  vnext/PropertySheets/External/Microsoft.ReactNative.Composition.CppApp.props
  vnext/PropertySheets/External/Microsoft.ReactNative.WindowsSdk.Default.props
Labels: Area: Playground, Backport: Requested, New Architecture

#12969 [0.74] Component Governance Fixes 4/22/24
  yarn.lock
Labels: security, Area: Compliance

#12984 Change Fabric e2etest timeout from 60 to 35m
  .ado/jobs/e2e-test.yml
Labels: AutoMerge

#13002 [0.74] Fix changefiles
  change/@office-iss-react-native-win32-6b1b9c92-50ad-4985-89ba-4f2505aa825c.json
  change/react-native-windows-3701d914-c1cc-48f7-b2ad-e84229318968.json
  change/react-native-windows-91e4571c-cdb6-4c4e-b7f6-d720a005abd1.json
Labels: AutoMerge

#13001 [CodeQL] Unsafe shell command constructed from library input
  packages/@rnw-scripts/beachball-config/package.json
  packages/@rnw-scripts/beachball-config/src/beachball.config.ts
  yarn.lock
Labels: Area: Compliance

#13009 [0.73] [NetUI] Fix issue using Paper UI manager with newer turbomodule
  change/@office-iss-react-native-win32-3df907f2-8166-40fe-840d-a260eed0fd3e.json
  packages/@office-iss/react-native-win32/src/Libraries/ReactNative/PaperUIManager.win32.js
Labels: Platform: NetUI

#13161 [CodeQL] Resolve "Weak hashes" alert
  change/react-native-platform-override-aa0ae023-d4d6-436c-bb36-9fa78bbed9af.json
  packages/react-native-platform-override/src/Hash.ts
Labels: AutoMerge
